import { EXERCISES, FORM_REMINDERS, MILESTONES, NUTRITION_NUDGES, PERIOD_LABELS } from './content.js';
import { calculateStats, createInitialState, encouragement, ensurePlanForDate, findExercise, isoDate, logDuty, nagMessage, nextPendingDuty, readinessScore, serialiseState, setLowEnergyMode, switchLocationMode, validateImportData } from './engine.js';
import { createBrowserStorage } from './storage.js';

const root = document.querySelector('#app');
const nowDate = () => isoDate(new Date());
let storage, state = createInitialState(), view = 'bridge', tick;
const NAV = [['bridge','Bridge'],['engine','Engine Room'],['log','Ship\'s Log'],['chart','Chart Room'],['settings','Settings']];
const esc = (s='') => String(s).replace(/[&<>\u0022']/g, c => c==='&'?'&amp;':c==='<'?'&lt;':c==='>'?'&gt;':c===String.fromCharCode(34)?'&quot;':'&#39;');
const niceDate = d => new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(`${d}T12:00:00`));

boot();
async function boot(){ if('serviceWorker' in navigator) navigator.serviceWorker.register("./sw.js").catch(()=>{}); storage=await createBrowserStorage(); state=ensurePlanForDate(await storage.load(),nowDate()); theme(); loopNag(); render(); }
async function save(next=state){ state=await storage.save(next); theme(); loopNag(); render(); }
function theme(){ document.documentElement.dataset.theme=state.settings?.theme||'system'; }
function render(){ state=ensurePlanForDate(state,nowDate()); root.innerHTML=state.initialized?shell():welcome(); bind(); if(view==='chart') requestAnimationFrame(drawCharts); }

function shell(){ return `<div class='app-shell'><header class='topbar'><a href='../' class='back'>← almanac</a><div><p class='kicker'>SHIPSHAPE :: MAINTENANCE LOG</p><h1>A maintenance log for the long voyage</h1></div></header><nav class='tabs' aria-label='Shipshape sections'>${NAV.map(([id,l])=>`<button class='tab ${view===id?'active':''}' data-view='${id}' type='button'>${l}</button>`).join('')}</nav><main class='main'>${view==='engine'?engineRoom():view==='log'?shipsLog():view==='chart'?chartRoom():view==='settings'?settings():bridge()}</main><dialog id='dutyDialog' class='dialog'></dialog></div>`; }
function welcome(){ return `<main class='welcome'><section class='welcome-card'>${gauge(72,'Ready')}<p class='kicker'>SHIP'S ENGINEER REPORT</p><h1>Shipshape</h1><p class='lede'>A calm, private exercise companion for Martin: tiny upper-body and core maintenance duties spread across the day. Anything is better than nothing. One completed duty keeps the voyage going.</p><div class='assurance-grid'><span>Private local logbook</span><span>Offline after first load</span><span>No accounts</span><span>No weight, calories or body measurements</span></div><form id='onboardForm'><fieldset><legend>Home equipment</legend><label><input type='checkbox' name='rings' checked> Ceiling rings are available</label><label><input type='checkbox' name='bands'> Resistance bands may be available</label></fieldset><fieldset><legend>Default watch station</legend><label><input type='radio' name='mode' value='home' checked> Home: rings and 2/4/5 kg weights</label><label><input type='radio' name='mode' value='hotel_gym'> Hotel gym when travelling</label></fieldset><fieldset><legend>Nag mode</legend><label><input type='checkbox' name='nag'> Gentle reminders; browser notifications can be enabled after this explanation.</label><p class='muted'>Browsers do not reliably schedule notifications while every tab is closed. Shipshape uses the best local behaviour available and always shows in-app overdue prompts.</p></fieldset><button class='primary wide'>Open the Bridge</button></form></section></main>`; }

function bridge(){ const d=nowDate(), p=state.plans[d], c=readinessScore(state,d), s=calculateStats(state,d), n=nextPendingDuty(p), done=p.duties.filter(x=>x.status==='done'||x.status==='partial').length; return `<section class='bridge-grid'><article class='status-panel hero-panel'><div><p class='kicker'>Bridge · ${esc(niceDate(d))}</p><h2>${esc(c.label)}</h2><p>${esc(c.detail)}</p></div>${gauge(c.score,c.label)}<p class='mentor'>${esc(p.maintained?encouragement(state,d):nagMessage(state,d))}</p></article><article class='next-duty'><p class='kicker'>NEXT DUTY</p>${n?dutySummary(n,true):'<h2>Watch complete</h2><p>All duties are logged. Extra maintenance is welcome, never required.</p>'}<div class='bridge-actions'><button class='secondary' data-low='${!p.lowEnergyMode}'>${p.lowEnergyMode?'Resume normal day':'Low-energy day'}</button><button class='secondary' data-loc='${p.locationMode==='home'?'hotel_gym':'home'}'>${p.locationMode==='home'?'I\'m travelling / hotel gym today':'Back to home equipment'}</button><button class='primary' data-anything>Do anything: 20-second brace</button></div></article><article class='log-strip'><span><b>${done}</b> duties touched today</span><span><b>${p.lowEnergyMode?'1–3':'about 10'}</b> minutes target</span><span><b>${s.currentStreak}</b> day streak</span><span>${esc(p.nutritionNudge)}</span></article><section class='duty-list'>${p.duties.map(dutyCard).join('')}</section><aside class='nag-box'><h3>Nag mode</h3><p>${state.settings.nagModeEnabled?'Enabled. In-app overdue prompts are active; browser notifications appear where the platform allows.':'Off. The Bridge still shows overdue maintenance without shame.'}</p><p class='muted'>${esc(FORM_REMINDERS[(state.logs.length+d.length)%FORM_REMINDERS.length])}</p></aside></section>`; }
function dutyCard(d){ return `<article class='duty-card ${d.status}'><div class='period'>${PERIOD_LABELS[d.period]||d.period}</div>${dutySummary(d,false)}<div class='duty-controls'><button class='primary' data-open='${d.id}'>Do it now</button><button data-fast='done' data-duty='${d.id}'>Done</button><button data-fast='partial' data-duty='${d.id}'>Part done</button><button data-fast='skipped' data-duty='${d.id}'>Skip</button></div></article>`; }
function dutySummary(d,big){ const e=findExercise(d.exerciseId); return `<div class='duty-summary'><div class='mini-diagram'>${diagram(e.diagramType)}</div><div><h${big?'2':'3'}>${esc(d.title)}</h${big?'2':'3'}><p>${esc(d.targetDescription)}</p><p class='muted'>${esc(e.purpose)}</p><span class='stamp ${d.status}'>${d.status}</span></div></div>`; }

function engineRoom(){ return `<section class='section-stack'><div class='section-head'><p class='kicker'>Engine Room</p><h2>Small vocabulary, high leverage</h2><p>Every exercise has a purpose, beginner version, progression, mistakes and safety notes.</p></div>${['home','hotel_gym'].map(m=>`<section><h3>${m==='home'?'Home watch':'Hotel gym watch'}</h3><div class='exercise-grid'>${EXERCISES.filter(e=>e.locationModes.includes(m)&&e.category!=='nutrition').map(exerciseCard).join('')}</div></section>`).join('')}</section>`; }
function exerciseCard(e){ return `<article class='exercise-card'><div class='exercise-art'>${diagram(e.diagramType)}</div><div><p class='kicker'>${e.category} · ${esc(e.equipment.join(', '))}</p><h3>${esc(e.name)}</h3><p>${esc(e.longevityWhy)}</p><details><summary>Instructions and form</summary>${details(e)}</details></div></article>`; }
function details(e){ return `<h4>Steps</h4><ol>${e.instructions.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><h4>Beginner version</h4><p>${esc(e.beginnerVersion)}</p><h4>Progression</h4><p>${esc(e.progression)}</p><h4>Common mistakes</h4><ul>${e.commonMistakes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>Safety notes</h4><ul>${e.safetyNotes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`; }

function shipsLog(){ const s=calculateStats(state,nowDate()), recent=[...state.logs].sort((a,b)=>b.completedAt.localeCompare(a.completedAt)).slice(0,12), seen=new Set(state.milestonesSeen||[]); return `<section class='section-stack'><div class='section-head'><p class='kicker'>Ship's Log</p><h2>Exercise maintenance only</h2><p>No weight, waist, calories, sleep, mood, heart-rate or medical tracking.</p></div><div class='stat-grid'><span><b>${s.maintainedDays}</b> days maintained</span><span><b>${s.currentStreak}</b> current streak</span><span><b>${s.longestStreak}</b> longest streak</span><span><b>${s.totalDuties}</b> duties completed</span><span><b>${s.totalMinutes}</b> estimated minutes</span><span><b>${s.partialDuties}</b> partials</span></div><div class='calendar'>${lastDays(28).map(day=>`<span class='day ${state.plans[day]?.maintained?'kept':''}' title='${day}'>${day.slice(8)}</span>`).join('')}</div><section><h3>Milestone plates</h3><div class='plates'>${MILESTONES.map(m=>`<span class='plate ${seen.has(m.id)?'earned':''}'>${esc(m.text)}</span>`).join('')}</div></section><section><h3>Recent log entries</h3>${recent.length?recent.map(l=>`<article class='entry'><b>${esc(findExercise(l.exerciseId)?.name||l.exerciseId)}</b><span>${l.date} · ${l.status}${l.feedback?' · '+l.feedback.replaceAll('_',' '):''}</span></article>`).join(''):`<p class='empty'>No entries yet. One tiny duty will start the logbook.</p>`}</section></section>`; }
function chartRoom(){ const c=readinessScore(state,nowDate()), ps=Object.values(state.progression).filter(p=>p.currentLevel||p.bestSeconds||p.bestReps||p.bestWeightKg); return `<section class='section-stack'><div class='section-head'><p class='kicker'>Chart Room</p><h2>Trends without judgement</h2><p>Condition reflects recent consistency and coverage, not moral worth.</p></div><div class='chart-grid'><article class='chart-card'><h3>Maintenance minutes</h3><canvas id='minutesChart' width='720' height='260'></canvas></article><article class='chart-card'><h3>Duties completed</h3><canvas id='dutiesChart' width='720' height='260'></canvas></article></div><article class='status-panel'><div>${gauge(c.score,c.label)}</div><div><h3>${esc(c.label)}</h3><p>${esc(c.detail)}</p><p>Seaworthy · Needs light maintenance · Back on watch · Voyage resumed.</p></div></article><section><h3>Exercise progression</h3><div class='progression-grid'>${ps.length?ps.map(p=>`<article class='progress-card'><b>${esc(findExercise(p.exerciseId)?.name||p.exerciseId)}</b><span>Level ${p.currentLevel||0}</span><small>${p.bestSeconds?`Best ${p.bestSeconds}s`:''} ${p.bestReps?`Best ${p.bestReps} reps`:''} ${p.bestWeightKg?`Best ${p.bestWeightKg} kg`:''}</small></article>`).join(''):`<p class='empty'>Progression calibrates after a few logged duties. No formal fitness test required.</p>`}</div></section></section>`; }
function settings(){ const perm=typeof Notification==='undefined'?'not supported':Notification.permission; return `<section class='section-stack'><div class='section-head'><p class='kicker'>Settings</p><h2>Local engine-room controls</h2><p>All runtime data stays in this browser. Storage: ${esc(storage.kind)}.</p></div><form id='settingsForm' class='settings-grid'><label>Theme <select name='theme'><option value='system' ${state.settings.theme==='system'?'selected':''}>System</option><option value='dark' ${state.settings.theme==='dark'?'selected':''}>Dark</option><option value='light' ${state.settings.theme==='light'?'selected':''}>Light</option></select></label><label><input type='checkbox' name='rings' ${state.settings.equipment.rings?'checked':''}> Rings available at home</label><label><input type='checkbox' name='bands' ${state.settings.equipment.resistanceBandsMaybe?'checked':''}> Resistance bands may exist</label><label><input type='checkbox' name='nag' ${state.settings.nagModeEnabled?'checked':''}> Nag mode enabled</label><button class='primary'>Save settings</button></form><article class='notice'><h3>Install and offline</h3><p>The manifest and service worker make Shipshape installable and cache the app shell after first load. Browser notification permission is currently: <b>${perm}</b>.</p><button data-notify>Enable browser notifications</button></article><article class='notice'><h3>Backup and transfer</h3><p>Export/import is readable JSON with storage version and validation before replacement.</p><div class='bridge-actions'><button class='primary' data-export>Export JSON backup</button><label class='file-button'>Import JSON backup<input type='file' accept='application/json,.json' data-import hidden></label><button class='danger' data-reset>Reset local data</button></div></article><article class='notice'><h3>Nutrition nudges included</h3><p>${NUTRITION_NUDGES.slice(0,4).map(esc).join(' · ')}.</p></article></section>`; }

function bind(){ root.querySelector('#onboardForm')?.addEventListener('submit',onboard); root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();}); root.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDuty(b.dataset.open)); root.querySelectorAll('[data-fast]').forEach(b=>b.onclick=()=>quick(b.dataset.duty,b.dataset.fast)); root.querySelector('[data-low]')?.addEventListener('click',e=>save(setLowEnergyMode(state,nowDate(),e.currentTarget.dataset.low==='true'))); root.querySelector('[data-loc]')?.addEventListener('click',e=>save(switchLocationMode(state,nowDate(),e.currentTarget.dataset.loc))); root.querySelector('[data-anything]')?.addEventListener('click',openAnything); root.querySelector('#settingsForm')?.addEventListener('submit',saveSettings); root.querySelector('[data-notify]')?.addEventListener('click',requestNotifications); root.querySelector('[data-export]')?.addEventListener('click',exportBackup); root.querySelector('[data-import]')?.addEventListener('change',importBackup); root.querySelector('[data-reset]')?.addEventListener('click',resetAll); }
async function onboard(e){ e.preventDefault(); const f=new FormData(e.currentTarget); const next={...state,initialized:true,settings:{...state.settings,locationModeDefault:f.get('mode'),nagModeEnabled:f.has('nag'),equipment:{...state.settings.equipment,rings:f.has('rings'),resistanceBandsMaybe:f.has('bands')}}}; await save(ensurePlanForDate(next,nowDate())); if(f.has('nag')) requestNotifications(); }
async function saveSettings(e){ e.preventDefault(); const f=new FormData(e.currentTarget); await save({...state,settings:{...state.settings,theme:f.get('theme'),nagModeEnabled:f.has('nag'),equipment:{...state.settings.equipment,rings:f.has('rings'),resistanceBandsMaybe:f.has('bands')}}}); }
function dutyById(id){ return state.plans[nowDate()].duties.find(d=>d.id===id); }
function openAnything(){ const p=state.plans[nowDate()]; const d={id:`${nowDate()}-emergency-brace`,date:nowDate(),exerciseId:'standing-core-brace',title:'Emergency standing core brace',period:'anytime',targetDescription:'20 seconds · enough to maintain the voyage',targetSeconds:20,targetSets:1,status:'pending'}; if(!p.duties.some(x=>x.id===d.id)) p.duties.unshift(d); openDialog(d); }
function openDuty(id){ openDialog(dutyById(id)); }
function openDialog(d){ const e=findExercise(d.exerciseId), dlg=root.querySelector('#dutyDialog'); dlg.innerHTML=`<form method='dialog' id='dutyForm'><button class='close' value='cancel' aria-label='Close'>×</button><div class='dialog-grid'><div class='large-diagram'>${diagram(e.diagramType)}</div><div><p class='kicker'>${PERIOD_LABELS[d.period]||d.period}</p><h2>${esc(d.title)}</h2><p>${esc(d.targetDescription)}</p><p>${esc(e.purpose)}</p></div></div>${details(e)}<div class='timer-box'><button type='button' data-timer>Start timer</button><output id='timerOutput'>${d.targetSeconds||30}s</output></div><fieldset class='log-fields'><legend>What actually happened?</legend><label>Seconds <input name='seconds' type='number' min='0' value='${d.targetSeconds||''}'></label><label>Sets <input name='sets' type='number' min='0' value='${d.targetSets||1}'></label><label>Reps <input name='reps' type='number' min='0' value='${d.targetReps||''}'></label><label>Weight kg <input name='weight' type='number' min='0' step='0.5' value='${d.targetWeightKg||''}'></label></fieldset><fieldset><legend>How did it feel?</legend><label><input type='radio' name='feedback' value='too_easy'> Too easy</label><label><input type='radio' name='feedback' value='about_right' checked> About right</label><label><input type='radio' name='feedback' value='too_hard'> Too hard</label><label><input type='radio' name='feedback' value='pain_or_discomfort'> Pain/discomfort</label></fieldset><menu><button data-status='skipped'>Skipped</button><button data-status='partial'>Part done</button><button class='primary' data-status='done'>Done</button></menu></form>`; dlg.querySelector('[data-timer]').onclick=()=>startTimer(d.targetSeconds||30); dlg.querySelectorAll('[data-status]').forEach(b=>b.onclick=ev=>{ev.preventDefault(); submit(d,b.dataset.status,dlg);}); dlg.showModal(); }
function n(v){ const x=Number(v); return Number.isFinite(x)&&x>0?x:undefined; }
async function submit(d,status,dlg){ const f=new FormData(dlg.querySelector('#dutyForm')); dlg.close(); await save(logDuty(state,nowDate(),d.id,{status,actualSeconds:n(f.get('seconds')),actualSets:n(f.get('sets')),actualReps:n(f.get('reps')),actualWeightKg:n(f.get('weight')),feedback:f.get('feedback')},new Date())); }
async function quick(id,status){ const d=dutyById(id); await save(logDuty(state,nowDate(),id,{status,actualSeconds:d.targetSeconds,actualSets:d.targetSets,actualReps:d.targetReps,actualWeightKg:d.targetWeightKg,feedback:status==='skipped'?'too_hard':'about_right'},new Date())); }
function startTimer(sec){ clearInterval(tick); let left=sec, out=root.querySelector('#timerOutput'); out.textContent=`${left}s`; tick=setInterval(()=>{left--; out.textContent=left>0?`${left}s`:'Complete'; if(left<=0) clearInterval(tick);},1000); }
async function requestNotifications(){ const settings={...state.settings,nagModeEnabled:true,notificationPermissionAsked:true}; if('Notification' in window&&Notification.permission==='default') await Notification.requestPermission(); await save({...state,settings}); }
function loopNag(){ clearInterval(tick); if(!state.settings?.nagModeEnabled) return; tick=setInterval(()=>{const d=nowDate(),p=ensurePlanForDate(state,d).plans[d]; if(!p.maintained&&document.hidden&&'Notification' in window&&Notification.permission==='granted') new Notification('Shipshape',{body:nagMessage(state,d),tag:'shipshape-duty'});},2700000); }
function exportBackup(){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([serialiseState(state)],{type:'application/json'})); a.download=`shipshape-backup-${nowDate()}.json`; a.click(); URL.revokeObjectURL(a.href); }
async function importBackup(e){ const file=e.target.files?.[0]; if(!file) return; const text=await file.text(), result=validateImportData(text); if(!result.ok) return alert(result.error); if(!confirm('Replace this browser’s Shipshape logbook with the selected backup?')) return; const imported=await storage.importJson(text); if(!imported.ok) return alert(imported.error); state=imported.value; render(); }
async function resetAll(){ if(confirm('Reset all local Shipshape data in this browser? This cannot be undone unless you exported a backup.')){state=await storage.reset();render();} }
function lastDays(c){ const out=[], d=new Date(`${nowDate()}T12:00:00`); for(let i=c-1;i>=0;i--){const x=new Date(d); x.setDate(d.getDate()-i); out.push(isoDate(x));} return out; }
function drawCharts(){ drawBar('minutesChart',lastDays(14).map(day=>state.logs.filter(l=>l.date===day&&l.status!=='skipped').reduce((s,l)=>s+(l.actualSeconds?l.actualSeconds/60:.5),0))); drawBar('dutiesChart',lastDays(14).map(day=>state.logs.filter(l=>l.date===day&&(l.status==='done'||l.status==='partial')).length)); }
function drawBar(id,vals){ const c=document.getElementById(id); if(!c) return; const ctx=c.getContext('2d'), w=c.width,h=c.height,p=28,max=Math.max(1,...vals),bw=(w-p*2)/vals.length*.7,css=getComputedStyle(document.documentElement); ctx.clearRect(0,0,w,h); ctx.strokeStyle=css.getPropertyValue('--line'); ctx.fillStyle=css.getPropertyValue('--brass'); ctx.beginPath(); ctx.moveTo(p,p); ctx.lineTo(p,h-p); ctx.lineTo(w-p,h-p); ctx.stroke(); vals.forEach((v,i)=>{const x=p+i*((w-p*2)/vals.length)+bw*.15,bh=(h-p*2)*(v/max); ctx.fillRect(x,h-p-bh,bw,bh);}); }
function gauge(score,label){ const a=-110+(Math.max(0,Math.min(100,score))/100)*220; return `<svg class='gauge' viewBox='0 0 220 150' role='img' aria-label='Ship condition ${esc(label)}'><path class='gauge-arc' d='M35 120 A75 75 0 0 1 185 120'/><path class='gauge-good' d='M67 120 A43 43 0 0 1 153 120'/><line class='needle' x1='110' y1='120' x2='110' y2='48' style='transform:rotate(${a}deg);transform-origin:110px 120px'/><circle cx='110' cy='120' r='8'/><text x='110' y='142' text-anchor='middle'>${Math.round(score)}</text></svg>`; }
function diagram(type){ const common=`<rect class='floor' x='18' y='132' width='164' height='5'/>`, m={hang:`<circle cx='50' cy='68' r='14'/><circle cx='150' cy='68' r='14'/><path class='human sway' d='M100 65 v42 m0-28 l-30-8 m30 8 l30-8 m0 72 l-22-36 m-8 36 l8-36'/>`,row:`<path class='human rowAnim' d='M58 118 L110 88 L150 118 M110 88 l-22-24 m22 24 l34-8'/>`,support:`<circle cx='70' cy='74' r='12'/><circle cx='130' cy='74' r='12'/><path class='human pulse' d='M100 60 v48 m-30-34 h60 m-30 34 l-24 34 m24-34 l24 34'/>`,press:`<path class='weight lift' d='M70 38 h60 M76 30 v16 M124 30 v16'/><path class='human' d='M100 58 v54 m-28-30 l28-18 l28 18 m-28 30 l-24 30 m24-30 l24 30'/>`,carry:`<path class='human pulse' d='M100 50 v54 m-25-26 h50 m-25 26 l-24 34 m24-34 l24 34'/><rect class='weight' x='132' y='92' width='22' height='36' rx='4'/>`,brace:`<path class='human pulse' d='M100 48 v62 m-28-30 h56 m-28 30 l-24 34 m24-34 l24 34'/><circle cx='100' cy='36' r='12'/><path class='breath' d='M70 70 q30 20 60 0'/>`,pushup:`<path class='wall' d='M170 28 v110'/><path class='human rowAnim' d='M60 118 L112 86 L165 86 M112 86 l-14-28 m14 28 l-16 34'/>`,pallof:`<path class='wall' d='M28 40 v90'/><line class='band' x1='28' y1='80' x2='100' y2='80'/><path class='human pulse' d='M112 52 v56 m-34-28 h56 m-22 28 l-22 34 m22-34 l22 34'/>`,pulldown:`<path class='machine' d='M45 25 h110 v18 M100 25 v45'/><path class='band lift' d='M67 70 h66'/><path class='human' d='M100 82 v46 m-34-42 l34-10 l34 10'/>`,facepull:`<path class='machine' d='M35 32 v100'/><line class='band rowAnim' x1='35' y1='62' x2='113' y2='76'/><path class='human' d='M120 54 v56 m-38-32 l38-2 l32 10'/>`,nutrition:`<circle class='plate' cx='100' cy='84' r='44'/><path class='leaf' d='M88 82 q22-36 48-8 q-26 4-48 8'/>`}; return `<svg class='diagram' viewBox='0 0 200 150' aria-hidden='true'>${common}${m[type]||m.brace}</svg>`; }
