export const EXERCISES = [
  { id:'ring-dead-hang', name:'Ring dead hang / assisted hang', category:'grip', equipment:['ceiling rings'], locationModes:['home'], purpose:'Build grip, shoulder trust and upper-back tolerance with almost no setup.', longevityWhy:'Strong hands and shoulders make falls, bags, doors, hills and ageing joints easier to handle.', beginnerVersion:'Keep toes on the floor and unload only a little body weight.', progression:'Add five seconds when three hangs feel calm, then reduce foot help before chasing long hangs.', loggingType:'seconds', diagramType:'hang', instructions:['Set the rings just above head height and stand tall beneath them.','Take a full grip, ribs down, and let the shoulders rise without shrugging hard.','Keep toes lightly on the floor if needed; breathe slowly until the timer ends.','Step down before form turns into a fight.'], commonMistakes:['Jumping into the hang cold.','Holding the breath.','Letting sharp shoulder pain become a test of courage.'], safetyNotes:['Use secure rings only. Stop for sharp pain, tingling or a slipping grip.'], starting:{sets:3,seconds:20} },
  { id:'ring-row', name:'Easy ring row', category:'pull', equipment:['ceiling rings'], locationModes:['home'], purpose:'Teach the back and arms to pull while the angle stays adjustable.', longevityWhy:'Pulling strength supports posture, shoulder balance and the ability to handle loads in real life.', beginnerVersion:'Stand almost upright and pull only as far as the shoulder blades stay organised.', progression:'Walk feet slightly forward or add one clean rep after several easy sessions.', loggingType:'sets_reps', diagramType:'row', instructions:['Hold the rings with arms straight and body in one long plank.','Start easy: feet close under you, not far forward.','Pull the rings towards the lower ribs, pause, then lower with control.','Stop each set while every rep still looks tidy.'], commonMistakes:['Making the angle too hard too soon.','Chin poking forward.','Letting the elbows flare wildly.'], safetyNotes:['Move feet back to make it easier if the shoulders complain.'], starting:{sets:2,reps:5} },
  { id:'ring-support', name:'Feet-assisted ring support hold', category:'push', equipment:['ceiling rings'], locationModes:['home'], purpose:'Build shoulder stability and straight-arm confidence without dips.', longevityWhy:'Stable shoulders make pushing, bracing and catching yourself safer over the long voyage.', beginnerVersion:'Keep both feet on the floor and press down into the rings for a few seconds.', progression:'Use less foot help, then add five seconds; dips are not required.', loggingType:'seconds', diagramType:'support', instructions:['Set rings near hip height and stand between them.','Press the rings down with straight arms while feet stay grounded.','Keep ribs quiet, neck long and rings close to the body.','Release before the shoulders wobble aggressively.'], commonMistakes:['Locking the neck and jaw.','Trying full bodyweight too early.','Letting rings drift far away from the ribs.'], safetyNotes:['Avoid if it creates front-shoulder pinching; swap to wall push-up.'], starting:{sets:3,seconds:10} },
  { id:'standing-press', name:'Standing overhead press', category:'push', equipment:['2 kg, 4 kg or 5 kg bar weight'], locationModes:['home'], purpose:'A simple shoulder and trunk strength duty with the equipment already available.', longevityWhy:'Overhead strength helps keep shoulders capable and the trunk braced during everyday lifting.', beginnerVersion:'Use 2 kg and press one slow rep at a time.', progression:'Add reps first, then move from 2 kg to 4 kg or 5 kg only when it feels ordinary.', loggingType:'weight_reps', diagramType:'press', instructions:['Stand tall with the weight at collarbone height.','Brace gently as though preparing for a nudge.','Press overhead without leaning back, then lower slowly.','Keep every rep smooth and stop well before grinding.'], commonMistakes:['Turning it into a back bend.','Rushing the lowering phase.','Choosing the heavier weight for pride.'], safetyNotes:['No sharp shoulder or back pain; use a lighter weight or fewer reps.'], starting:{sets:2,reps:8,weightKg:4} },
  { id:'bent-over-row', name:'Bent-over weight row', category:'pull', equipment:['2 kg, 4 kg or 5 kg bar weight'], locationModes:['home'], purpose:'A low-friction pull for the upper back when the rings are not inviting.', longevityWhy:'Rows counter the forward slump that accumulates from desks, phones and long years.', beginnerVersion:'Use the lightest weight and a small hinge, one arm supported on a wall if needed.', progression:'Add reps before weight and keep the back position quiet.', loggingType:'weight_reps', diagramType:'row', instructions:['Hinge slightly at the hips with a long spine.','Let the weight hang below the shoulder.','Pull elbow towards the back pocket, pause, and lower slowly.','Stand up between sets and reset.'], commonMistakes:['Rounding into a tired slump.','Yanking with momentum.','Shrugging the shoulder to the ear.'], safetyNotes:['If the back feels vulnerable, choose ring rows or seated gym rows.'], starting:{sets:2,reps:8,weightKg:5} },
  { id:'suitcase-hold', name:'Suitcase hold', category:'carry', equipment:['bar weights'], locationModes:['home','hotel_gym'], purpose:'Grip, obliques and posture in one tiny standing duty.', longevityWhy:'Carrying uneven loads trains the trunk to resist tipping, useful for bags, shopping and rough ground.', beginnerVersion:'Hold one light weight by the side for 15 seconds each side.', progression:'Add time before load; stay tall rather than leaning away.', loggingType:'seconds', diagramType:'carry', instructions:['Stand tall with one weight held like a suitcase.','Zip the ribs down and keep both shoulders level.','Breathe calmly for the target time, then switch sides.','Put the weight down before grip collapses.'], commonMistakes:['Leaning away from the weight.','Holding the breath.','Letting the shoulder hang painfully low.'], safetyNotes:['Keep the path clear and do not walk if balance feels poor.'], starting:{sets:2,seconds:30,weightKg:5} },
  { id:'wall-push-up', name:'Wall or incline push-up', category:'push', equipment:['wall or stable surface'], locationModes:['home','hotel_gym'], purpose:'A frictionless push pattern that can start at almost any strength level.', longevityWhy:'Pushing strength supports shoulders, elbows and getting up from awkward positions.', beginnerVersion:'Use a wall and a short range of motion.', progression:'Move hands lower or feet farther away when clean reps feel easy.', loggingType:'sets_reps', diagramType:'pushup', instructions:['Place hands on a wall or stable surface at chest height.','Make the body a straight line from ears to heels.','Lower slowly, touch lightly, and press back without shrugging.','Finish the set while the last rep is still neat.'], commonMistakes:['Sagging through the ribs.','Nose diving while hips stay behind.','Flaring elbows to ninety degrees.'], safetyNotes:['Use a stable surface only. Stop for wrist or shoulder pain.'], starting:{sets:2,reps:8} },
  { id:'standing-core-brace', name:'Standing core brace', category:'core', equipment:['none'], locationModes:['home','hotel_gym'], purpose:'Teach the trunk to brace without needing a mat or floor setup.', longevityWhy:'A reliable brace protects the back during lifting, stumbling and long days on foot.', beginnerVersion:'Brace for five easy breaths with hands on lower ribs.', progression:'Add suitcase hold, suitcase march or Pallof press once bracing feels natural.', loggingType:'seconds', diagramType:'brace', instructions:['Stand tall with feet planted and knees soft.','Breathe out gently and feel the ribs settle.','Brace as though someone may nudge you, without holding the breath.','Keep the brace through five calm breaths.'], commonMistakes:['Sucking the belly in hard.','Holding the breath.','Clenching the shoulders and face.'], safetyNotes:['This should feel like control, not strain or dizziness.'], starting:{sets:2,seconds:25} },
  { id:'band-pallof', name:'Standing anti-rotation press', category:'core', equipment:['resistance band or cable'], locationModes:['home','hotel_gym'], purpose:'A tiny anti-twist drill for trunk resilience.', longevityWhy:'Resisting rotation helps the spine and hips share load during carries and uneven terrain.', beginnerVersion:'Use a very light band and stand close to the anchor.', progression:'Step farther from the anchor or pause longer with straight arms.', loggingType:'sets_reps', diagramType:'pallof', instructions:['Anchor a band at chest height or use a cable stack.','Stand side-on, hold the handle at the chest, and brace.','Press arms forward without letting the torso twist.','Pause, return, and repeat both sides.'], commonMistakes:['Using too much resistance.','Letting hips rotate.','Holding the breath.'], safetyNotes:['Skip if no safe anchor is available.'], starting:{sets:2,reps:6} },
  { id:'lat-pulldown', name:'Lat pulldown', category:'pull', equipment:['lat pulldown machine'], locationModes:['hotel_gym'], purpose:'A clear gym pull that builds the same vocabulary as rings.', longevityWhy:'Vertical pulling supports shoulder capacity, grip and upper-back strength.', beginnerVersion:'Use a light weight and stop with the bar around chin or upper chest height.', progression:'Add reps or a small weight increase only when the shoulders stay down and back.', loggingType:'weight_reps', diagramType:'pulldown', instructions:['Sit tall with thighs secured and hands just wider than shoulders.','Start by drawing shoulder blades gently down.','Pull the bar towards the upper chest, then return slowly.','Keep the ribs quiet; do not turn it into a lean-back row.'], commonMistakes:['Yanking behind the neck.','Leaning far back.','Letting the stack slam.'], safetyNotes:['Use the front-of-body version only; skip if the machine feels awkward.'], starting:{sets:2,reps:8,weightKg:20} },
  { id:'seated-row', name:'Seated row machine', category:'pull', equipment:['seated row machine'], locationModes:['hotel_gym'], purpose:'A stable, easy-to-learn upper-back builder.', longevityWhy:'Rows maintain posture and shoulder balance without needing heavy loads.', beginnerVersion:'Light weight, chest tall, stop before the lower back joins in.', progression:'Add one clean rep per set or the smallest plate increase.', loggingType:'weight_reps', diagramType:'row', instructions:['Sit tall and take the handles with arms straight.','Pull elbows back towards the ribs.','Pause briefly, then let the arms return under control.','Keep shoulders away from ears.'], commonMistakes:['Rocking the torso.','Shrugging.','Rushing the return.'], safetyNotes:['Choose a chest-supported row if available and the lower back is tired.'], starting:{sets:2,reps:8,weightKg:20} },
  { id:'chest-press', name:'Chest press machine', category:'push', equipment:['chest press machine'], locationModes:['hotel_gym'], purpose:'A safe gym push pattern with adjustable load.', longevityWhy:'Push strength supports shoulders, elbows and day-to-day bracing.', beginnerVersion:'Set handles around chest height and use a weight that feels almost too easy.', progression:'Add reps before load; leave two or three good reps in reserve.', loggingType:'weight_reps', diagramType:'press', instructions:['Set the seat so handles start near mid-chest.','Press smoothly without locking shoulders forward.','Return slowly until elbows are comfortable, not overstretched.','Keep feet planted and neck quiet.'], commonMistakes:['Seat too low or too high.','Bouncing at the bottom.','Grinding heavy reps.'], safetyNotes:['Stop for shoulder pinching and switch to wall push-ups if needed.'], starting:{sets:2,reps:8,weightKg:15} },
  { id:'shoulder-press-machine', name:'Shoulder press machine', category:'push', equipment:['shoulder press machine or dumbbells'], locationModes:['hotel_gym'], purpose:'Overhead strength with a predictable path.', longevityWhy:'Maintaining overhead ability keeps shoulders useful for decades.', beginnerVersion:'Use the machine lightly; dumbbells only if they feel steadier.', progression:'Add reps slowly and never chase maximal load.', loggingType:'weight_reps', diagramType:'press', instructions:['Set the seat so handles begin near shoulder height.','Brace gently and press overhead without shrugging.','Lower under control to the start position.','Stop before the last rep becomes a grind.'], commonMistakes:['Arching hard through the back.','Starting too heavy.','Letting elbows drift painfully behind the body.'], safetyNotes:['Skip if shoulder range does not feel friendly today.'], starting:{sets:2,reps:8,weightKg:10} },
  { id:'assisted-pullup', name:'Assisted pull-up or assisted dip station', category:'pull', equipment:['assisted pull-up/dip machine'], locationModes:['hotel_gym'], purpose:'A gentle introduction to bodyweight pulling or support with the machine carrying the excess.', longevityWhy:'Assisted bodyweight work builds robust shoulders and grip without heroic strain.', beginnerVersion:'Set assistance high and perform small clean reps.', progression:'Reduce assistance only after several calm sessions.', loggingType:'sets_reps', diagramType:'hang', instructions:['Set plenty of assistance and move deliberately.','Grip, brace, and pull or support through a comfortable range.','Pause at control points rather than bouncing.','Stop at the first sign of shoulder irritation.'], commonMistakes:['Too little assistance.','Swinging.','Treating it as a test.'], safetyNotes:['Use the machine instructions; skip if setup is confusing.'], starting:{sets:2,reps:5} },
  { id:'cable-face-pull', name:'Cable face pull', category:'mobility', equipment:['cable machine with rope'], locationModes:['hotel_gym'], purpose:'A light shoulder-posture tune-up.', longevityWhy:'Rear-shoulder and upper-back control helps keep pressing and carrying balanced.', beginnerVersion:'Very light cable, slow reps, elbows below shoulder irritation range.', progression:'Add reps before load; this stays a tune-up, not a max lift.', loggingType:'sets_reps', diagramType:'facepull', instructions:['Set cable around face height with a rope handle.','Step back, brace, and pull the rope towards the face.','Finish with hands beside the temples and shoulder blades gently together.','Return slowly and keep the weight light.'], commonMistakes:['Going heavy.','Cranking the neck forward.','Flaring into shoulder pain.'], safetyNotes:['Skip if it pinches; choose seated row instead.'], starting:{sets:2,reps:10} },
  { id:'farmer-carry-gym', name:'Dumbbell farmer hold', category:'carry', equipment:['dumbbells'], locationModes:['hotel_gym'], purpose:'Grip and trunk maintenance with common gym equipment.', longevityWhy:'Loaded carries are simple insurance for hands, posture and useful strength.', beginnerVersion:'Hold two light dumbbells at the sides for 20 seconds.', progression:'Add time before load and keep the walk optional.', loggingType:'seconds', diagramType:'carry', instructions:['Choose dumbbells that feel controlled.','Stand tall with shoulders level and ribs quiet.','Hold or walk a short clear line for the target time.','Set the weights down with control.'], commonMistakes:['Choosing heroic dumbbells.','Leaning or waddling.','Dropping weights loudly.'], safetyNotes:['Keep the floor clear and skip walking if the gym is crowded.'], starting:{sets:2,seconds:30,weightKg:10} },
  { id:'nutrition-nudge', name:'Tiny nutrition nudge', category:'nutrition', equipment:['none'], locationModes:['home','hotel_gym'], purpose:'One small food default that supports the vessel without logging meals.', longevityWhy:'Repeated boring improvements beat dramatic diet campaigns.', beginnerVersion:'Pick one nudge for the next meal or snack.', progression:'Keep the easiest useful default until it feels automatic.', loggingType:'boolean', diagramType:'nutrition', instructions:['Read the day’s nudge.','Apply it to the next meal, drink or snack if convenient.','Do not count calories, macros or points.','Log it only as noticed or done.'], commonMistakes:['Turning a nudge into a diet project.','Using food language as a moral judgement.','Trying to fix the entire day at once.'], safetyNotes:['This is not medical advice; keep it small and sensible.'], starting:{sets:1} }
];

export const NUTRITION_NUDGES = [
  'Add a clear protein source to the next meal.', 'Put vegetables or beans on the plate before extras.', 'Drink water before deciding about a snack.', 'Make the next snack boring and useful.', 'Eat the first half slowly enough to notice it.', 'Keep liquid calories and alcohol unexciting today.', 'Add fibre: oats, beans, fruit, vegetables or wholegrain bread.', 'Stop at enough; leave heroics for sea stories.', 'Make the next default five percent better.', 'Put the tempting snack out of sight and the useful one in reach.', 'Choose a meal that would still make sense tomorrow.', 'Have protein after the next walk if a meal is due.'
];

export const NAG_MESSAGES = [
  'Minor maintenance due.', 'The vessel would benefit from a 30-second check.', 'One small duty keeps the voyage moving.', 'Do the smallest useful thing.', 'No heroics required; touch the duty and log the truth.', 'A short inspection now prevents a bigger repair later.', 'The engine room is quiet, but not abandoned.', 'Even one clean rep counts as watch kept.', 'Lower the target, not the standard of kindness.', 'The shoulders are waiting for a polite signal.', 'A tiny brace is still maintenance.', 'The voyage resumes with the next small act.', 'The logbook likes honest partials.', 'Grease the hinge before it complains.', 'The next useful step is not dramatic.', 'Thirty seconds is a perfectly respectable repair.', 'Keep the vessel seaworthy, not perfect.', 'A skipped duty is information; a tiny duty is momentum.', 'The day can still be maintained.', 'One completed duty keeps the voyage going.', 'No shame in a lighter setting.', 'The brass plate is earned by showing up.'
];

export const ENCOURAGEMENTS = [
  'Anything is better than nothing.', 'A short duty completed is a win.', 'The vessel remains under care.', 'That was enough to keep the habit alive.', 'Small maintenance now prevents major repairs later.', 'The shoulders are earning more trust.', 'The logbook records useful work, not perfection.', 'Steady hands, steady voyage.', 'You chose continuity over drama.'
];

export const MILESTONES = [
  { id:'first-duty', at:1, text:'First duty logged. The vessel is officially under maintenance.' },
  { id:'five-duties', at:5, text:'Five duties completed. The engine room has a rhythm.' },
  { id:'ten-duties', at:10, text:'Ten duties. Small rivets, real structure.' },
  { id:'twenty-five-duties', at:25, text:'Twenty-five duties. The habit has left the harbour.' },
  { id:'fifty-duties', at:50, text:'Fifty duties. A quiet certificate of consistency.' },
  { id:'hundred-duties', at:100, text:'One hundred duties. The vessel knows this route.' },
  { id:'first-week', maintainedDays:7, text:'Seven maintained days. A week of watchkeeping.' },
  { id:'two-weeks', maintainedDays:14, text:'Fourteen maintained days. The long voyage likes this.' },
  { id:'streak-three', streak:3, text:'Three-day streak. No fireworks; just seamanship.' },
  { id:'streak-seven', streak:7, text:'Seven-day streak. Brass plate earned.' },
  { id:'minutes-thirty', minutes:30, text:'Thirty maintenance minutes logged. Useful work accumulates.' },
  { id:'minutes-hundred', minutes:100, text:'One hundred maintenance minutes. The vessel is better cared for.' },
  { id:'coverage', coverage:4, text:'Push, pull, grip and core all touched. Balanced maintenance.' },
  { id:'travel-watch', travel:1, text:'Travel watch kept. A strange engine room still counts.' }
];

export const FORM_REMINDERS = [
  'Breathe. Bracing is not breath-holding.', 'Stop before form becomes a negotiation.', 'No sharp pain is part of the plan.', 'Make the setup easier before quitting the habit.', 'Slow lowering is useful strength.', 'Ribs quiet, neck long, shoulders unhurried.', 'A clean partial beats a messy full target.'
];

export const PERIOD_LABELS = { morning:'Morning inspection', midday:'Midday maintenance', afternoon:'Afternoon check', evening:'Evening log', anytime:'Anytime repair' };
