/* BOOT TO DESKTOP — recorded data, transcribed from the mddosem bug
   ledger (MDD-BUG-KILN-00004), the engineering journals, and the
   preserved run artifacts. Dates are 2026. Do not hand-edit numbers:
   every figure below traces to a ledger entry, journal line, commit,
   or artifact hash. */
window.W2K_DATA = {

  /* ---- the whole campaign, one event per story beat ----
     kind: "milestone" | "fix" | "herring" | "event" */
  timeline: [
    { d: "Apr 22", iso: "2026-04-22", kind: "milestone", h: "--real-boot ships",
      b: "SeaBIOS + SeaVGABIOS boot real firmware on the emulated hardware; PIIX3 IDE follows so the BIOS can see a hard disk. The road to NT starts here." },
    { d: "May 28", iso: "2026-05-28", kind: "milestone", h: "First Win2K checkpoint",
      b: "First journal of the Windows 2000 investigation lands in git — a ~30-run boot log. By 31 May one install has accumulated 47 reboots." },
    { d: "Jun 04", iso: "2026-06-04", kind: "event", h: "The QEMU oracle is established",
      b: "A reference install on QEMU (same ISO, same key, Standard PC HAL, acpi=off) completes. Divergence marker: its setuperr.log is 0 bytes." },
    { d: "Jun 23", iso: "2026-06-23", kind: "milestone", h: "The goal prompt",
      b: "“Fix underlying emulation behavior only. Do not patch, bypass, preseed, or fake” — boot to a usable desktop, FreeCell running, reproduced twice." },
    { d: "Jun 30", iso: "2026-06-30", kind: "event", h: "KILN-00004 raised",
      b: "GUI setup fails at “set system security”, reboots via the 8042 line, and re-runs the wizard forever. Reproduces on the pure interpreter: shared emulation bug." },
    { d: "Jun 30", iso: "2026-06-30", kind: "herring", h: "The red-herring massacre",
      b: "In one marathon day: ESE “never flushes”, the 1601/2113 clocks, disk corruption, turbo time-starvation and memory pressure are all refuted by controlled experiments." },
    { d: "Jun 30", iso: "2026-06-30", kind: "fix", h: "V86 #GP storm fixed",
      b: "182 identical faults at ntoskrnl 0x80467EC1: V86→ring-0 entry left auto-nulled segments unusable. SegmentCache::null_flat_usable() per SDM §20.3.1.2. 182 → 2." },
    { d: "Jul 04", iso: "2026-07-04", kind: "event", h: "Routed: blocked on a deep fix",
      b: "The livelock is localized to WDM-audio software-device setup — an “architecturally significant” fix flagged for Arthur’s steer. The bug waits." },
    { d: "Jul 10", iso: "2026-07-10", kind: "event", h: "The repro had vanished",
      b: "No surviving Win2K disk anywhere. The repro is rebuilt from the retail SP4 ISO with an unattended answer floppy: text mode ~16 min, GUI ~22 min, wall re-confirmed." },
    { d: "Jul 11", iso: "2026-07-11", kind: "fix", h: "ATA edge destruction fixed",
      b: "A Status-port read was erasing the latched interrupt edge the 8259 had already captured. Fix moves the install from 2.03M disk write-commits to 3.64M — into a new wall." },
    { d: "Jul 13", iso: "2026-07-13", kind: "event", h: "Nine commits in sixteen hours",
      b: "HAL-swap reaches the “Starting up…” splash for the first time; PIIX3 gets a real bus-master engine; the transplant end-run is rejected as doctrine-violating; the WDMAUD theory is found stale." },
    { d: "Jul 14", iso: "2026-07-14", kind: "event", h: "Kernel debugger over serial",
      b: "W2K’s own KDCOM speaks through the emulated 16550 — 161 valid KD packets — but Microsoft’s symbol server has dropped Win2K. A symbol-free RAM walker it is. hang.bin (128 MiB) preserved, 23:12." },
    { d: "Jul 15", iso: "2026-07-15", kind: "event", h: "The census",
      b: "w2kcensus walks the RAM dump: 8 processes, 71 threads, every one Waiting. setup.exe blocks on three anonymous unsignaled events. A whole-system lost wakeup — apparently." },
    { d: "Jul 15", iso: "2026-07-15", kind: "fix", h: "Fix 1 + Fix 2 land",
      b: "23:04: interrupt-recognition boundaries after STI/POPFD. 23:30: the PIT channel-0 track un-parked under real boot. Each proven real; neither sufficient." },
    { d: "Jul 16", iso: "2026-07-16", kind: "fix", h: "Fix 3 lands; the twist",
      b: "01:09: PIIX3 latches channel interrupts at assertion. Then capture 15 injects one Enter key — and “deadlocked” setup wakes instantly. The wall was a modal dialog nobody could see." },
    { d: "Jul 16", iso: "2026-07-16", kind: "event", h: "“Please insert the disk labeled Service Pack 4 CD”",
      b: "Capture 19 decodes the live call frame: SetupPromptForDiskW asking for NT5INF.CAT from D:\\I386. The harness had stopped attaching the ISO at capture 03. Windows was right." },
    { d: "Jul 16", iso: "2026-07-16", kind: "event", h: "The product key, entered blind",
      b: "Past the media prompt, a second invisible page: “The CD Key you entered is not valid.” A secure stdin path is built; Arthur types the key. No key ever touches a log." },
    { d: "Jul 18", iso: "2026-07-18", kind: "event", h: "The key experiment, corrected",
      b: "Instrument honesty: decimal-parsed scancodes and a stray Tab had garbled entry into the five auto-advancing fields. The earlier “accepted key” claim is formally withdrawn." },
    { d: "Jul 19", iso: "2026-07-19", kind: "fix", h: "Fix 4: PSE in the IOPM walk",
      b: "03:05: W2K maps its TSS through a CR4.PSE 4 MiB page during V86 VGA BIOS calls; the I/O-bitmap walker had treated the huge-page PDE as a page-table pointer. One masked OR fixes it." },
    { d: "Jul 19", iso: "2026-07-19", kind: "milestone", h: "Boot to desktop",
      b: "Captures 46 and 47: two independent fresh-copy boots to Winlogon, Administrator login, responsive Explorer, FreeCell rendering, clean restart. 03:02: desktop-settled.png. 03:27: acceptance recorded." },
  ],

  /* ---- the hang.bin census (2026-07-15, CR3 0x00030000) ---- */
  census: {
    dump: { file: "hang.bin", bytes: 134217728,
      sha256: "729AE8FEA5CDB4CFC4BF4B6CAEDC28A2CFF300CEC162F4A15F77B8FD9EAC4825",
      taken: "2026-07-14 23:12" },
    processes: [
      { name: "System",   threads: 21, note: "kernel worker pool — all Waiting" },
      { name: "smss.exe", threads: 6,  note: "session manager" },
      { name: "csrss.exe", threads: 8, note: "Win32 subsystem" },
      { name: "winlogon.exe", threads: 7, note: "logon — owns GUI setup’s session" },
      { name: "services.exe", threads: 12, note: "service control manager" },
      { name: "lsass.exe", threads: 10, note: "local security authority" },
      { name: "svchost.exe", threads: 4, note: "shared service host" },
      { name: "setup.exe", threads: 3, pid: 352, eprocess: "0x813E2020",
        note: "GUI setup — the three terminal waits", highlight: true },
    ],
    setupWaits: [
      { kthread: "0x813E2560", event: "0x813E1520" },
      { kthread: "0x813DFDA0", event: "0x813DF140" },
      { kthread: "0x813E3DA0", event: "0x813E3660" },
    ],
    totals: { processes: 8, threads: 71, runnable: 0 },
    offsets: [
      { name: "KTHREAD.WaitBlockList", value: "0x58", note: "not the 0x5C in the published 3.51–5.1 table — why earlier reads were garbage" },
      { name: "KTHREAD.ThreadListEntry", value: "0x1A4", note: "not the published 0x110" },
      { name: "EPROCESS.UniqueProcessId", value: "0x9C", note: "" },
      { name: "KWAIT_BLOCK.Object", value: "0x0C", note: "cross-validated by Thread backpointers + list reciprocity" },
    ],
  },

  /* ---- the hypothesis board ---- */
  hypotheses: [
    { h: "ESE never flushes; checkpoint frozen", verdict: "refuted",
      ev: "secedit.sdb: checkpoint stuck at log gen 799 with 1,470 log files (~1.47 GB). Killed: a clean-disk install advances the checkpoint normally — an old-disk artifact." },
    { h: "Async write completion lost", verdict: "refuted",
      ev: "Syscall trace over the whole failing phase: NtWriteFile × 0 to secedit.sdb. There were no writes to lose." },
    { h: "Turbo time-compression starves ESE", verdict: "refuted",
      ev: "33× more guest time per unit work (60,000 vs 2,000,000 cycles/ms): failure byte-identical." },
    { h: "Clock anomaly (1601 / 2113)", verdict: "refuted",
      ev: "A clean run with a correct 06/30/2026 clock fails identically. Co-symptom, not cause." },
    { h: "Accumulated disk corruption", verdict: "refuted",
      ev: "Fresh from-blank install fails byte-identically at the same phase." },
    { h: "MMU bug (repeated page faults)", verdict: "refuted",
      ev: "23% of samples at 64 MiB → 0.7% at 128 MiB: working-set thrashing under low RAM, not a paging bug — and the failure is RAM-independent." },
    { h: "“LSA Policy Open DB Error=2”", verdict: "herring",
      ev: "The successful QEMU reference contains 18 of the same errors — and recovers. Benign-transient." },
    { h: "desk.cpl returns 0xe000020e", verdict: "herring",
      ev: "DIF_DESTROYPRIVATEDATA answering ERROR_DI_DO_DEFAULT = “not handled, do the default.” Completely normal." },
    { h: "V86 #GP storm at KiTrap0D", verdict: "fixed",
      ev: "Real: auto-nulled segments left unusable on V86→ring-0 entry. 182 faults → 2 after SegmentCache::null_flat_usable()." },
    { h: "WDMAUD/SWENUM interface never publishes", verdict: "stale",
      ev: "Painstakingly localized — then found stale on v0.151.0: the stall had moved earlier and the WDMAUD installer never even ran. Diagnosis ≠ the current binary’s bug." },
    { h: "ATA/ATAPI completion-edge destruction", verdict: "fixed",
      ev: "Status reads and nIEN writes were erasing latched 8259 edges. Real: fix moved the install 2.03M → 3.64M write-commits." },
    { h: "Whole-system lost-wakeup deadlock", verdict: "reframed",
      ev: "The census was correct — and misread. Capture 15: one injected Enter key wakes setup instantly. It was a modal dialog on a black screen." },
    { h: "Missing media + product key prompts", verdict: "confirmed",
      ev: "SetupPromptForDiskW: “Service Pack 4 CD”, NT5INF.CAT — the harness had omitted --cdrom since capture 03. Then the key page, entered securely by hand." },
    { h: "Four shared-emulation defects", verdict: "fixed",
      ev: "STI/POPFD shadow, PIT ch0 under real boot, BMISTA latch-at-assert, PSE in the IOPM walk. All four needed; the last landed 22 minutes before acceptance." },
  ],

  /* ---- the four unlocking fixes (flag panes) ---- */
  fixes: [
    { n: 1, color: "#d64b3a", pane: "red", name: "The interrupt shadow",
      what: "STI; DEC ECX; CLI retired three instructions, not two — and POPFD; CLI retired sixteen. A following CLI could close the only legal window in which a pending interrupt may be recognized. NT’s PUSHFD/CLI…POPFD critical sections lost completion interrupts.",
      fix: "An explicit InterruptPollBoundary result: the scheduler owns exactly one shadow-protected successor instruction, and inner/outer scheduling share one readiness predicate (including visible 8042 output).",
      sha: "399d34b3b", when: "Jul 15, 23:04", tests: "2,511 → 2,512 interpreter tests" },
    { n: 2, color: "#2f9d85", pane: "green", name: "The parked timer",
      what: "Under --real-boot, timer interrupts enter the guest’s own IDT — the emulator’s HLE timer path never runs. But the PIT channel-0 counter track was still deferred for an HLE commit that never came: the 8254 froze between IRQs.",
      fix: "can_defer_pit_channel0_track() answers no under native boot; DOS/DPMI HLE paths keep their deferral.",
      sha: "26915729b", when: "Jul 15, 23:30", tests: "9 focused channel-0 regressions" },
    { n: 3, color: "#3489d6", pane: "blue", name: "The silent status bit",
      what: "Real PIIX3 IDE latches its per-channel BMISTA Interrupt bit the moment the drive asserts INTRQ — DMA or not. Ours raised IRQ14 with BMISTA reading zero (the secondary register was hardwired zero), so a PCI IDE ISR could dismiss its own interrupt as not-mine.",
      fix: "Assertion-time latching on every routed I/O before it returns, independent banks per channel, write-one-to-clear semantics, Start/Stop cancellation.",
      sha: "e0e9fe9a5", when: "Jul 16, 01:09", tests: "5,544 mddosem-hw tests" },
    { n: 4, color: "#bd8b16", pane: "gold", name: "The four-megabyte page",
      what: "Windows 2000 maps its TSS — and with it the I/O-permission bitmap — through a CR4.PSE 4 MiB page. During V86 VGA BIOS calls the interpreter’s IOPM walker treated the huge-page PDE as a page-table pointer, read garbage PTEs, and denied legal port I/O.",
      fix: "One masked OR: physical = (pde & 0xFFC0_0000) | (linear & 0x003F_FFFF). Latent for years — DOS extenders use 4 KiB pages.",
      sha: "fe28f3aa0", when: "Jul 19, 03:05", tests: "fail-first PSE regression + full interp suite" },
  ],

  /* ---- the final night, 2026-07-19 ---- */
  finalNight: [
    { t: "00:07", h: "First boot of the installed disk", b: "Capture 29: the freshly-installed system boots. First FreeCell attempt renders a black frame (ipc-freecell-black.png, 5,757 bytes — the same size as four days of wall screenshots)." },
    { t: "00:45", h: "QEMU VGA trace pulled", b: "An 11 MB VGA-register trace from the oracle, to diff rendering behaviour." },
    { t: "01:49", h: "STOP 0x7B", b: "Capture 38 bugchecks: INACCESSIBLE_BOOT_DEVICE — later traced to the run’s own breakpoint instrumentation, not the emulator. Clean runs never reproduce it." },
    { t: "02:22", h: "Log On to Windows", b: "Capture 42: the logon dialog, Administrator, blank password. prelogon.png → post-login.png." },
    { t: "02:23", h: "First good FreeCell", b: "Capture 42: the first good FreeCell frame of the night renders. (The detailed felt-and-wizard portrait belongs to capture 45’s 02:46 frame.)" },
    { t: "02:36 + 02:54", h: "Release binary rebuilt twice", b: "mddosem v0.156.3 (669806963), interpreter-only. The ATAPI probe was still chattering in capture 45’s stderr before the diagnostics came out for the acceptance runs." },
    { t: "02:43–02:46", h: "Capture 45: the instrumented full sequence", b: "Splash at 02:43, first desktop at 02:45, FreeCell at 02:46 — splash → login → FreeCell in one run, ATAPI probe still attached." },
    { t: "before 03:00", h: "Capture 46: acceptance run one", b: "Fresh copy, ISO attached, fixed diagnostic epoch, uninstrumented release binary: Winlogon, Administrator login, Explorer, FreeCell, clean guest restart. Duration unrecorded." },
    { t: "03:00–03:02", h: "Capture 47: acceptance run two", b: "Second fresh copy, no fixed epoch: Winlogon, responsive desktop, clean restart. desktop-settled.png — taskbar clock 2:04 AM." },
    { t: "03:27", h: "Acceptance recorded", b: "MDD-BUG-KILN-00004 → Fixed. Not Closed: the two-eyes rule holds — the author of the flip may not close it." },
  ],

  /* ---- evidence anchors ---- */
  evidence: [
    { k: "RAM dump", v: "hang.bin — 134,217,728 bytes, SHA-256 729AE8FE…EAC4825, 2026-07-14 23:12" },
    { k: "Pristine continuation disk", v: "SHA-256 DB4B3E02…5FACB57 — every capture booted a hash-verified fresh copy" },
    { k: "Capture campaign", v: "47 numbered captures, Jul 15 16:08 → Jul 19 03:02; 42 two-GiB run disks (~85 GiB)" },
    { k: "Earlier campaign", v: "19 further 2 GiB disks + 6,763 PNG frames + a 654 MB syscall trace and a 602 MB storage trace (Jul 10–15)" },
    { k: "The wall", v: "one byte-identical 5,757-byte black 640×480 PNG, recurring across four days of runs" },
    { k: "Victory binary", v: "mddosem v0.156.3, built 2026-07-19 02:54 (669806963), interpreter-only" },
    { k: "Final validation", v: "2,512 mddosem-interp tests, 0 failed; fmt, clippy −D warnings, release build green; full gate owned by integration" },
    { k: "Ledger state", v: "MDD-BUG-KILN-00004 Fixed 2026-07-19 (two-eyes closure pending); MDD-BUG-KILN-00005 (dynrec on W2K) still open" },
  ],
};
