(function(){
  'use strict';
  const $=(s)=>document.querySelector(s);
  const xLabels={'-3':'strong dislike','-2':'dislike','-1':'slight dislike','0':'neutral','1':'slight liking','2':'like','3':'strong liking'};
  const yLabels=['co-presence','recognition','functional','casual social','personal','intimate'];
  const zLabels=['ambiguous','open','semi-structured','structured','scripted','rehearsed'];
  const presets={lecture:{x:0,y:0,z:4},bus:{x:0,y:0,z:4},lab:{x:0,y:2,z:2},group:{x:0,y:2,z:1},social:{x:0,y:3,z:0}};
  function readout(x,y,z){
    if(y<=1&&z>=3)return['Low social demand, high structure','You can mostly coexist. The useful preparation is logistical rather than interpersonal: where to go, what to bring, when it ends.','Turn up, occupy a place, complete the task, leave.'];
    if(y<=1&&z<=2)return['Little interaction, but few cues','Almost nothing interpersonal is required; the difficulty is orientation rather than conversation. Finding out the practical details in advance moves this up Z without changing Y.','Settle the logistics first: where to go, where to wait, how long it lasts.'];
    if(y===2&&z>=3)return['Functional interaction with clear rules','The interaction is real, but it is bounded by a task. You do not need friendship or personal disclosure.','Use task language: ask, answer, clarify, record, finish.'];
    if(y===2&&z<=2)return['The task is clear; the social process is not','Most of the load comes from uncertainty: who begins, who decides, what happens on disagreement. A protocol can move this upward on Z without changing Y.','Prepare the common states and one default response for each.'];
    if(y>=3&&z<=1)return['High improvisation','This setting asks for open-ended reciprocal interaction. It may be optional. If it is not, reduce duration, add a purpose, or add structure.','Give the encounter a boundary: a purpose, a time limit, a known person or an exit.'];
    if(y>=4)return['Deep interaction','This level normally depends on trust and cannot be reduced to a script. Predictability can still help with timing and boundaries.','Do not force depth. Decide what you genuinely want to share.'];
    return['Mixed demand','There is some interaction, but it can be decomposed. Identify which parts are required and which are optional.','Keep the required path small and make each uncertain transition explicit.'];
  }
  function updateExplorer(){
    const x=Number($('#x').value),y=Number($('#y').value),z=Number($('#z').value);
    $('#x-out').textContent=`${x} · ${xLabels[x]}`;
    $('#y-out').textContent=`${y} · ${yLabels[y]}`;
    $('#z-out').textContent=`${z} · ${zLabels[z]}`;
    $('#coordinate').textContent=`X ${x} · Y ${y} · Z ${z}`;
    const r=readout(x,y,z);$('#readout-title').textContent=r[0];$('#readout-copy').textContent=r[1];$('#minimum').textContent=r[2];
  }
  ['#x','#y','#z'].forEach(id=>$(id).addEventListener('input',updateExplorer));
  document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{const p=presets[b.dataset.preset];$('#x').value=p.x;$('#y').value=p.y;$('#z').value=p.z;updateExplorer();}));

  const maps=[
    {id:'lecture',name:'Lecture',xyz:'X 0 · Y 0 · Z 4',x:'neutral',y:'co-presence',z:'scripted',required:'Arrive, find a seat, listen, take notes, leave. Talking to peers is optional unless the lecturer explicitly introduces an activity.',states:[['The room is busy','Choose any workable seat. No introduction is required.'],['Someone sits beside you','Nothing is required. A nod or “hi” is enough if they greet you.'],['Lecturer asks the room a question','Answering is optional unless participation is specified.'],['Break starts','Stay, leave, get water, look at notes — all are valid.'],['Lecture ends','Pack up and leave. There is no closing social ritual.']]},
    {id:'transport',name:'Bus / taxi',xyz:'X 0 · Y 0–1 · Z 4',x:'neutral',y:'co-presence',z:'scripted',required:'Use the service. Most interaction has fixed roles and a tiny vocabulary.',states:[['Boarding a bus','Tap/pay, move inside, sit or stand.'],['Driver asks a question','Answer the literal question. No extension is required.'],['Taxi begins','Confirm destination if needed. Silence is acceptable.'],['Driver makes small talk','A short answer is enough; you can return to silence.'],['Arrival','Thank them if you want, pay/exit, done.']]},
    {id:'lab',name:'Laboratory',xyz:'X 0 · Y 2 · Z 2 → 4',x:'neutral',y:'functional',z:'make predictable',required:'Cooperate enough to complete the experiment safely and accurately. Friendship, banter and personal disclosure are not requirements.',states:[['Arriving','Go to the assigned station or ask “Is this our bench?”'],['Nobody starts','“Shall we start with step one?”'],['Not sure what to do','“Which bit are we doing next?”'],['Need clarification','“Can you show me what you mean?”'],['Result looks wrong','“I think we may have missed this step.”'],['Asked for an opinion','“I think X, because Y.”'],['You do not know','“I’m not sure. Let’s check.”'],['Need a brief break','“I’m just going to step out for a minute.”'],['Task is complete','“Is there anything else we need to record?”']]},
    {id:'tutorial',name:'Tutorial',xyz:'X 0 · Y 1–2 · Z 3',x:'neutral',y:'recognition / functional',z:'structured',required:'Follow the discussion and contribute only to the extent the course requires. A contribution can be technical rather than social.',states:[['Asked directly','Answer the question you were asked, then stop.'],['Do not understand','“Could you say that another way?”'],['Have a point to add','“I think there’s another way to look at that…”'],['Disagree','“I read that differently because…”'],['Long silence','The tutor owns the silence; you do not have to repair it.']]},
    {id:'group',name:'Group work',xyz:'X 0 · Y 2 · Z 1 → 3',x:'neutral',y:'functional',z:'add roles',required:'Exchange enough information to divide the task, make decisions and combine the result. Social bonding is optional.',states:[['Group forms','Ask “What are we splitting up?”'],['Roles unclear','“I can take X. Who wants Y?”'],['Two people disagree','Return to criteria: “What does the brief actually ask for?”'],['Someone dominates','Use a task question to create a turn: “Can we decide X before we move on?”'],['Your part is done','“I’ve finished X. Where should I put it?”']]},
    {id:'staff',name:'Ask staff for help',xyz:'X 0 · Y 2 · Z 4',x:'neutral',y:'functional',z:'role-based',required:'State the problem, give the relevant facts, ask for a concrete next step.',states:[['Opening','“Hi — could I ask about X?”'],['Explaining','Use: what I expected → what happened → what I tried.'],['Asked something unknown','“I don’t know.” / “I haven’t tried that yet.”'],['Need it written down','“Could you put that in an email / show me where that is?”'],['Closing','“Okay, I’ll do that. Thanks.”']]},
    {id:'social',name:'Open social event',xyz:'X ? · Y 3 · Z 0–1',x:'unknown',y:'casual social',z:'open',required:'Often very little is truly required. Decide in advance whether attendance itself is the goal, and give it a boundary.',states:[['Arriving','Know where to stand/go first; identify one anchor person or place.'],['No obvious conversation','You do not have to manufacture one immediately.'],['Conversation starts','Use one question or one shared-context comment.'],['Energy drops','Use the planned time boundary or exit.'],['Leaving','A simple “I’m heading off — see you” is enough.']]}
  ];
  const tabs=$('#map-tabs'),card=$('#map-card');
  maps.forEach((m,i)=>{const b=document.createElement('button');b.textContent=m.name;b.dataset.map=m.id;b.setAttribute('role','tab');b.setAttribute('type','button');b.setAttribute('aria-controls','map-card');b.setAttribute('aria-selected',i===0?'true':'false');b.addEventListener('click',()=>showMap(m.id));tabs.appendChild(b)});
  function showMap(id){const m=maps.find(x=>x.id===id);document.querySelectorAll('[data-map]').forEach(b=>b.setAttribute('aria-selected',b.dataset.map===id?'true':'false'));card.innerHTML=`<div class="map-top"><div><div class="coordinate">${m.xyz}</div><h3>${m.name}</h3><div class="badge-row"><span class="badge x">X · ${m.x}</span><span class="badge y">Y · ${m.y}</span><span class="badge z">Z · ${m.z}</span></div></div><div class="map-requirements"><b>What is actually required?</b><p>${m.required}</p></div></div><div class="state-list">${m.states.map(s=>`<div class="state-row"><b>${s[0]}</b><p>${s[1]}</p></div>`).join('')}</div>`}
  showMap('lecture');
  const phrases=[['Starting','Shall we start with step one?'],['Clarifying','Can you show me what you mean?'],['Not knowing','I’m not sure. Let’s check.'],['Checking','Does that result look right to you?'],['Disagreeing','I think it might be X because Y.'],['Taking a role','I can do this part.'],['Finding the next step','Which bit are we doing next?'],['Creating a pause','Give me a second to think.'],['Leaving briefly','I’m just going to step out for a minute.'],['Finishing','Is there anything else we need to record?'],['Asking staff','Could I ask about X?'],['Closing','Okay, I’ll do that. Thanks.']];
  $('#phrase-grid').innerHTML=phrases.map(p=>`<div class="phrase"><span>${p[0]}</span><q>${p[1]}</q></div>`).join('');
  const cloud=$('#cloud');for(let i=0;i<90;i++){const d=document.createElement('i'),a=i*2.3999632297,r=Math.pow((i+1)/90,1.8)*45;d.style.left=`${50+Math.cos(a)*r}%`;d.style.top=`${50+Math.sin(a)*r*.72}%`;cloud.appendChild(d)}
  updateExplorer();
})();
