// ============================================================
// 0x4D44 — document catalog
// Add/edit entries here. Each entry needs at minimum: title,
// tagline, url, date (YYYY-MM-DD), year (subject year), tag.
// readingMin and words are optional but shown when present.
// ============================================================

window.ESSAYS = [
  {
    slug: "ecml",
    title: "The Long Run",
    tagline: "A timeline of the East Coast Main Line, 1862–2025.",
    url: "https://0x4d44.github.io/ecml-timeline/",
    illustration: "ill-map",
    date: "2026-01-21",
    year: 2026,
    readingMin: 34,
    words: 8600,
    tag: "rail",
    real: true,
  },
  {
    slug: "ai-watched",
    title: "The AI Who Watched",
    tagline: "“Watch the cat,” she said. It watched. A fable on the gap between what we tell an AI and what we mean.",
    url: "https://0x4d44.github.io/the-ai-who-watched/",
    illustration: "ill-eye",
    date: "2025-11-02",
    year: 2025,
    readingMin: 14,
    words: 3300,
    tag: "fiction",
    real: true,
  },
  {
    slug: "br1955",
    title: "BR Modernisation Program",
    tagline: "British Railways' 1955 Modernisation Plan — a fleet that solved the wrong problem.",
    url: "https://0x4d44.github.io/br1955/",
    illustration: "ill-diesel",
    date: "2025-09-14",
    year: 1955,
    readingMin: 22,
    words: 5400,
    tag: "rail",
    real: true,
  },
  {
    slug: "vernier",
    title: "Vernier",
    tagline: "A field guide to quality, testing & agents.",
    url: "https://0x4d44.github.io/vernier/",
    illustration: "ill-caliper",
    date: "2026-05-26",
    year: 2026,
    readingMin: 203,
    words: 40658,
    tag: "software",
    real: true,
  },
  {
    slug: "readex",
    title: "readex",
    tagline: "HTML main-content extraction for Rust.",
    url: "https://0x4d44.github.io/readex/",
    illustration: "ill-extract",
    date: "2026-05-26",
    year: 2026,
    readingMin: 8,
    words: 1554,
    tag: "software",
    real: true,
  },
  {
    slug: "ropus",
    title: "ropus",
    tagline: "The Opus audio codec, ported to safe Rust — bit-exact against the C reference.",
    url: "https://0x4d44.github.io/ropus/",
    illustration: "ill-wave",
    date: "2026-05-26",
    year: 2026,
    readingMin: 12,
    words: 2331,
    tag: "software",
    real: true,
  },
  {
    slug: "mr-poop",
    title: "The Day Mr Poop Got His Name",
    tagline: "A Bumbleworth Paper Co. comic.",
    url: "https://0x4d44.github.io/mr-poop/",
    illustration: "ill-comic",
    date: "2026-05-26",
    year: 2026,
    readingMin: 2,
    words: 395,
    tag: "comic",
    real: true,
  },
  {
    slug: "azuma",
    title: "Azuma",
    tagline: "A data dump on LNER's Class 800/801 fleet.",
    url: "https://0x4d44.github.io/azuma/",
    illustration: "ill-emu",
    date: "2026-05-26",
    year: 2026,
    readingMin: 31,
    words: 6223,
    tag: "rail",
    real: true,
  },
  {
    slug: "picoem",
    title: "picoem",
    tagline: "Cycle-accurate Raspberry Pi RP2350 / RP2040 emulators in Rust.",
    url: "https://0x4d44.github.io/picoem/",
    illustration: "ill-chip",
    date: "2026-05-26",
    year: 2026,
    readingMin: 14,
    words: 2822,
    tag: "software",
    real: true,
  },
  {
    slug: "token-predictor",
    title: "Token Predictor",
    tagline: "A visceral look at how fast an LLM actually generates text.",
    url: "https://0x4d44.github.io/token-predictor/",
    illustration: "ill-tokens",
    date: "2026-05-26",
    year: 2026,
    readingMin: 3,
    words: 600,
    tag: "software",
    real: true,
  },
  {
    slug: "mddskimg",
    title: "mddskimg",
    tagline: "Browse, extract and rewrite raw disk images — no loop mounts, root, or OS drivers.",
    url: "https://0x4d44.github.io/mddskimg/",
    illustration: "ill-disk",
    date: "2026-05-26",
    year: 2026,
    readingMin: 12,
    words: 2332,
    tag: "software",
    real: true,
  },
  {
    slug: "east-coast-main-line",
    title: "The East Coast Main Line",
    tagline: "An interactive history of Britain's East Coast Main Line, 1825–1991.",
    url: "https://0x4d44.github.io/ecml/",
    illustration: "ill-signal",
    date: "2026-05-26",
    year: 2026,
    readingMin: 13,
    words: 2670,
    tag: "rail",
    real: true,
  },
  {
    slug: "hydro",
    title: "The Hydro",
    tagline: "A century of Scottish water power.",
    url: "https://0x4d44.github.io/hydro/",
    illustration: "ill-hydro",
    date: "2026-05-26",
    year: 2026,
    readingMin: 12,
    words: 2311,
    tag: "history",
    real: true,
  },
  {
    slug: "mdmdview",
    title: "mdmdview",
    tagline: "A markdown viewer built for speed.",
    url: "https://0x4d44.github.io/mdmdview/",
    illustration: "ill-markdown",
    date: "2026-05-27",
    year: 2026,
    readingMin: 9,
    words: 1734,
    tag: "software",
    real: true,
  },
  {
    slug: "mercury-arc-rectifiers",
    title: "Mercury Arc Rectifiers",
    tagline: "A technical primer on the glass-bulb rectifiers that turned AC into DC.",
    url: "https://0x4d44.github.io/mercury-arc-rectifiers/",
    illustration: "ill-rectifier",
    date: "2026-05-27",
    year: 2026,
    readingMin: 19,
    words: 3769,
    tag: "history",
    real: true,
  },
  {
    slug: "mdminecraft",
    title: "mdminecraft",
    tagline: "A deterministic voxel sandbox engine, in Rust.",
    url: "https://0x4d44.github.io/mdminecraft/",
    illustration: "ill-voxel",
    date: "2026-05-27",
    year: 2026,
    readingMin: 11,
    words: 2281,
    tag: "software",
    real: true,
  },
  {
    slug: "mdkloc",
    title: "mdkloc",
    tagline: "A field guide to counting lines of code.",
    url: "https://0x4d44.github.io/mdkloc/",
    illustration: "ill-loc",
    date: "2026-05-27",
    year: 2026,
    readingMin: 10,
    words: 2063,
    tag: "software",
    real: true,
  },
  {
    slug: "netmeeting",
    title: "NetMeeting",
    tagline: "A deep dive into Microsoft's forgotten conferencing pioneer.",
    url: "https://0x4d44.github.io/netmeeting/",
    illustration: "ill-call",
    date: "2026-05-27",
    year: 2026,
    readingMin: 19,
    words: 3764,
    tag: "history",
    real: true,
  },
  {
    slug: "mddosem",
    title: "mddosem",
    tagline: "A hardware-accurate 1990s PC, emulated in Rust.",
    url: "https://0x4d44.github.io/mddosem/",
    illustration: "ill-pc",
    date: "2026-05-27",
    year: 2026,
    readingMin: 15,
    words: 3057,
    tag: "software",
    real: true,
  },
];

// Tags shown in the filter row. "all" is always first.
window.TAGS = ["all", "rail", "fiction", "software", "comic", "history"];

window.fmtDate = function (iso) {
  const d = new Date(iso);
  const m = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  return `${String(d.getDate()).padStart(2,"0")} ${m[d.getMonth()]} ${d.getFullYear()}`;
};
