// ============================================================
// 0x4D44 — document catalog
// Add/edit entries here. Each entry needs at minimum: title,
// tagline, url, date, year (subject year), and a tag.
// Use `tag: "x"` for one subject, or `tags: ["x", "y"]` for several
// (the page then appears under each of those filters).
// Keep `tagline` short — aim for one to three sentences and ~55 words
// max (roughly two lines in the listing). Lead with what the thing IS,
// add at most one sentence of flavour, then close with the tech stack.
// Resist itemising every feature: the tagline is a hook, not a spec.
// `date` is ISO 8601 and is the sort key. Use a full timestamp
// (e.g. "2026-05-28T18:54:00") so multiple entries published on the
// same day sort in the right order; a bare "YYYY-MM-DD" also works.
// readingMin and words are optional but shown when present.
// ============================================================

window.ESSAYS = [
  {
    slug: "broadband-speed-checker",
    title: "Line Rate",
    tagline: "A private broadband speed checker: find a nearby M-Lab NDT7 server, measure WebSocket download and upload throughput, sample ping, request a GPS fix and keep every result in browser-local history. Vanilla JS with localStorage — no backend, no build step.",
    url: "https://0x4d44.github.io/broadband-speed-checker/",
    illustration: "ill-wave",
    date: "2026-07-06T12:00:00",
    year: 2026,
    tags: ["software", "engineering"],
    real: true,
  },
  {
    slug: "shipshape",
    title: "Shipshape",
    tagline: "A phone-first, offline maintenance log for tiny upper-body and core duties across the day. Bridge, engine room and log screens turn small ring, weight and bodyweight sets into kept watches, with home and hotel-gym plans, low-energy and travel modes, and honest partial credit. An installable vanilla-JS PWA — IndexedDB and a service worker, no backend.",
    url: "https://0x4d44.github.io/shipshape/",
    illustration: "ill-anchor",
    date: "2026-07-06T11:00:00",
    year: 2026,
    tag: "software",
    real: true,
  },
  {
    slug: "cruise-propulsion",
    title: "The Electric Wake",
    tagline: "A deep interactive cutaway of diesel-electric cruise propulsion: medium-speed gensets, 11 kV switchboards, transformers, VFDs, pod motors and the 20 MW Azipods that turn thrust into steering. Trace megawatts from fuel rack to propeller, calculate currents, compare engine plants and watch the load-sharing system breathe. Vanilla JS on SVG and canvas — no dependencies, no build step.",
    url: "https://0x4d44.github.io/cruise-propulsion/",
    illustration: "ill-ship",
    date: "2026-07-05T12:00:00",
    year: 2026,
    readingMin: 32,
    words: 7600,
    tags: ["software", "engineering", "maritime"],
    real: true,
  },
  {
    slug: "nettles",
    title: "The Nettle",
    tagline: "Everything about the stinging nettle: how it grows, how its glass-needle sting actually works, what it developed from, and the thousand things — soup, cloth, medicine, myth — people have made from it. Magnify a trichome and fire it, tour the family tree, and rank the world's most agonising nettles. Vanilla JS, drawn live in SVG; fact-checked by a multi-agent research pass.",
    url: "https://0x4d44.github.io/nettles/",
    illustration: "ill-nettle",
    date: "2026-07-04T12:00:00",
    year: 2026,
    tags: ["science", "history"],
    real: true,
  },
  {
    slug: "japanese-wordle",
    title: "Kotoba",
    tagline: "A Wordle for learning Japanese: guess a JLPT N5/N4 word in kana. Beyond green/amber tiles, gojūon hint pips show when your kana shares the consonant row or vowel column with the answer — teaching the 五十音 table as you play. It speaks each word, shows the kanji and an example, and resurfaces your misses on a spaced schedule. Installable offline; browser React, no build step.",
    url: "https://0x4d44.github.io/japanese-wordle/",
    illustration: "ill-kotoba",
    date: "2026-07-04T10:00:00",
    year: 2026,
    tag: "games",
    real: true,
  },
  {
    slug: "paint-drying",
    title: "Watch Paint Dry",
    tagline: "A wall of fresh emulsion, drying in real time — and yes, that is the whole thing. Choose a colour and finish, then watch the wet sheen fade to matt as a drying front creeps across the surface. Warm the room or drop the humidity and the dry-time genuinely moves. Deadpan telemetry, and certificates for your patience. Vanilla JS on a canvas.",
    url: "https://0x4d44.github.io/paint-drying/",
    illustration: "ill-paint",
    date: "2026-07-04T13:00:00",
    year: 2026,
    tags: ["simulation", "science"],
    real: true,
  },
  {
    slug: "fifty-hertz",
    title: "Fifty Hertz",
    tagline: "Hold Scotland's grid dead on 50 Hz from the 1953 NSHEB control room at Pitlochry. Fight a momentum-heavy needle, read the half-time TV-pickup surges coming, and catch them by pre-spinning Cruachan — the Hollow Mountain — across fifty years of Highland winters, sheep in the intake and generator trips as the tech sharpens under your hands. A grid-balancing arcade in vanilla JS on a canvas, with a synthesised WebAudio hum.",
    url: "https://0x4d44.github.io/fifty-hertz/",
    illustration: "ill-fiftyhertz",
    date: "2026-07-03T19:40:00",
    year: 1953,
    tags: ["games", "engineering"],
    real: true,
  },
  {
    slug: "morning-run",
    title: "Morning Run",
    tagline: "Find a running loop from your hotel and track it live — or switch to Ship track to count laps of a moving cruise-ship deck, where GPS can't measure stride. Pick your ship (or auto-detect it), set the lap length, and it projects your finish. Browser React on MapLibre GL, no build step.",
    url: "https://0x4d44.github.io/morning-run/",
    illustration: "ill-run",
    date: "2026-07-07T12:00:00",
    year: 2026,
    tags: ["software", "transport", "maritime"],
    real: true,
  },
  {
    slug: "barcelona",
    title: "Barcelona · Aperture Modernisme",
    tagline: "A fun, bilingual (Spanish/English) field manual for two days in Barcelona — Gaudí's Sagrada Família, the aquarium under the sea, and the great cruise port — narrated by four cartoon guides who are half Catalan legend, half GLaDOS from Portal. A live map, a phrasebook that speaks aloud, and a two-day plan. Vanilla JS on Leaflet; content web-checked by a multi-agent pass.",
    url: "https://0x4d44.github.io/barcelona/",
    illustration: "ill-barcelona",
    date: "2026-07-03T17:30:00",
    year: 2026,
    tags: ["software", "history"],
    real: true,
  },
  {
    slug: "supernova",
    title: "The Death of Stars",
    tagline: "How stars are born, live and die — and what they leave behind. An interactive almanac from cold molecular cloud to supernova and beyond: dial a star's mass to read its fate, bounce a collapsing core, forge the elements in a periodic table of origins, and weigh white dwarfs against neutron stars and black holes. Vanilla JS on a canvas; fact-checked by a multi-agent research pass.",
    url: "https://0x4d44.github.io/supernova/",
    illustration: "ill-supernova",
    date: "2026-07-03T16:00:00",
    year: 2026,
    tags: ["science", "software"],
    real: true,
  },
  {
    slug: "constellation",
    title: "The Almanac, as a Constellation",
    tagline: "This catalog, drawn as a star map. Every document is a star — sized by length, coloured by tag — and a line joins any two that share one, so the whole almanac clusters itself. Drag a star, hover to read it, click to open it, or isolate a tag. Built live from data.js; vanilla JS on a canvas, no build step.",
    url: "https://0x4d44.github.io/constellation/",
    illustration: "ill-constellation",
    date: "2026-07-03T13:30:00",
    year: 2026,
    tags: ["software"],
    real: true,
  },
  {
    slug: "flight",
    title: "Flight",
    tagline: "A browser flight simulator over an endless procedural world of towns, cities, mountains, oceans, deserts and forests. Seven aircraft — from a Cessna 172 to the A380 — each with its own tuned aerodynamics, a full amber-phosphor HUD, autopilot, inducible equipment failures and switchable flying aids. Synthesised engine and wind, day or night. Three.js on a hand-written flight model.",
    url: "https://0x4d44.github.io/flight/",
    illustration: "ill-aircraft",
    date: "2026-07-03T12:00:00",
    year: 2026,
    tags: ["simulation", "software"],
    real: true,
  },
  {
    slug: "quixo",
    title: "Quixo",
    tagline: "The sliding-cube strategy game: take a blank or friendly cube from the edge, turn it to your symbol and push it back in — the whole row shifts. Five in a row wins, but line up five of theirs and you've lost. A phone-first match against an AI in three hand-built themes. React, transpiled in the browser; installable offline.",
    url: "https://0x4d44.github.io/quixo/",
    illustration: "ill-quixo",
    date: "2026-07-03T00:55:00",
    year: 1995,
    tag: "games",
    real: true,
  },
  {
    slug: "driftfield",
    title: "Driftfield",
    tagline: "A Perlin-noise flow-field toy: steer thousands of particles through live vector currents, then tune scale, speed, trails, palettes and cursor forces. React via the design-runtime export, painting directly to canvas - no build step.",
    url: "https://0x4d44.github.io/driftfield/",
    illustration: "ill-attractor",
    date: "2026-07-03T00:46:00",
    year: 2026,
    tags: ["simulation", "math"],
    real: true,
  },
  {
    slug: "class-55",
    title: "Class 55",
    tagline: "An interactive study of the Deltic — British Rail's Class 55. The triangular Napier opposed-piston engine that named it, the 3,300 hp locomotive that ruled the East Coast Main Line, and the racehorses and regiments its 22 machines carried. Animated engine schematic in vanilla JS on a canvas — no build step.",
    url: "https://0x4d44.github.io/class-55/",
    illustration: "ill-class55",
    date: "2026-07-03T12:00:00",
    year: 1961,
    tags: ["rail", "engineering", "history"],
    real: true,
  },
  {
    slug: "hyperbolic",
    title: "Hyperbolic",
    tagline: "An orbital-mechanics toy: fling interstellar visitors through the solar system on one-pass hyperbolic orbits — ʻOumuamua, Borisov and 3I/ATLAS as presets, or dial in your own approach. Real vis-viva + velocity-Verlet physics, to scale out to Saturn. Vanilla JS on a canvas — no dependencies, no build step.",
    url: "https://0x4d44.github.io/hyperbolic/",
    illustration: "ill-comet",
    date: "2026-07-02T22:19:00",
    year: 2026,
    tags: ["simulation", "science"],
    real: true,
  },
  {
    slug: "strange-attractors",
    title: "Strange Attractors",
    tagline: "Seven strange attractors, drawn live in phase space — Lorenz, Rössler, Aizawa and more, each a handful of deterministic rules that never repeat and never escape. Spin them, then watch the butterfly effect happen: two near-identical worlds diverge on a log plot. Fourth-order Runge–Kutta in vanilla JS on a canvas — nothing pre-rendered.",
    url: "https://0x4d44.github.io/strange-attractors/",
    illustration: "ill-attractor",
    date: "2026-07-02T21:30:00",
    year: 1963,
    tags: ["simulation", "science", "math"],
    real: true,
  },
  {
    slug: "midi-observatory",
    title: "Asterion MIDI Observatory",
    tagline: "A celestial in-browser MIDI listening room: play curated demo pieces or drop in .mid files, then drive a Web Audio synth across four live visualizer scenes — constellations, spectrogram, oscilloscope and piano roll. Per-channel mixer, presets with reverb, loop/shuffle and WAV export. Self-contained offline PWA — no runtime network calls.",
    url: "https://0x4d44.github.io/midi-observatory/",
    illustration: "ill-wave",
    date: "2026-07-03T01:10:00",
    year: 2026,
    tag: "software",
    real: true,
  },
  {
    slug: "vamos-spanish",
    title: "¡Vamos!: Spanish Learning App",
    tagline: "A Duolingo-style Spanish course in an iOS device frame: 26 units across six Spanish-speaking cities, each with vocabulary, sentences, grammar drills and listening exercises, plus streaks, XP, combos and badges. Text-to-speech reads every phrase aloud, with sound effects for taps, combos and wins. Built on a tiny HTML-template runtime that renders React in the browser — no build step.",
    url: "https://0x4d44.github.io/vamos-spanish/",
    illustration: "ill-vamos",
    date: "2026-07-02T20:00:00",
    year: 2026,
    tag: "software",
    real: true,
  },
  {
    slug: "humanity-retention",
    title: "Humanity Retention Programme",
    tagline: "A satirical mobile-first strategy game about keeping civilisation intact through fictional crises: manage regions, research, public trust, economy, misinformation and a suspicious administrative AI. Installable offline PWA with campaign and quick-play modes, local saves, procedural audio and deterministic vanilla JS simulation.",
    url: "https://0x4d44.github.io/humanity-retention/",
    illustration: "ill-population",
    date: "2026-07-02T19:10:00",
    year: 2026,
    tag: "games",
    real: true,
  },
  {
    slug: "japanese-travel-rpg",
    title: "Nihon Quest",
    tagline: "A mobile-first Japanese travel RPG in an iOS device frame: follow a UK-to-Japan route through airports, stations, konbini, temples and side trips, earning stamps while learning practical phrases, signs and etiquette. Includes SRS review, searchable phrasebook, speech buttons, guide characters, XP, combos and scripted roleplay. Design-runtime React export - no build step.",
    url: "https://0x4d44.github.io/japanese-travel-rpg/",
    illustration: "ill-nihon-quest",
    date: "2026-07-03T00:58:00",
    year: 2026,
    tag: "software",
    real: true,
  },
  {
    slug: "harbour-hustle-cruise-cup",
    title: "Harbour Hustle: Cruise Cup",
    tagline: "A cartoon cruise-boat racing arcade: kit out a bonkers boat from hulls, engines, decks and gadgets, then weave through buoys across six harbour races to bank coins, cups and oddball new parts. Keeps a browser-local high-score board and import/export save codes. Vanilla JS on a canvas — no dependencies, no build step.",
    url: "https://0x4d44.github.io/harbour-hustle-cruise-cup/",
    illustration: "ill-harbour-hustle",
    date: "2026-07-02T18:00:00",
    year: 2026,
    tags: ["games", "maritime"],
    real: true,
  },
  {
    slug: "med-cruise",
    title: "Mediterranean Cruise Planner",
    tagline: "A phone-first companion for a family's 7-night Western Mediterranean sailing on Harmony of the Seas: a departure countdown, port-by-port itinerary, a day planner, a ship guide, and a four-game deck arcade for the sea days. Built on a tiny HTML-template runtime that renders React in the browser — no build step.",
    url: "https://0x4d44.github.io/med-cruise/",
    illustration: "ill-ship",
    date: "2026-07-02T12:00:00",
    year: 2026,
    tags: ["maritime", "software"],
    real: true,
  },
  {
    slug: "salient",
    title: "Salient",
    tagline: "A parlour reimagining of the classic territory-and-dice war game: reinforce your armies, roll to attack across the sea-lanes, and conquer a five-continent world. Two to four players, any mix of humans and AI on Easy or Hard, with a coach that suggests moves for newcomers. A hex-mapped game, installable offline.",
    url: "https://0x4d44.github.io/salient/",
    illustration: "ill-salient",
    date: "2026-07-01T13:00:00",
    year: 2026,
    tag: "games",
    real: true,
  },
  {
    slug: "focus",
    title: "Focus",
    tagline: "Sid Sackson's 1963 Spiel-des-Jahres classic (a.k.a. Domination): a stack moves as many squares as it is tall, and you control any pile your colour caps. Overflow past five spills off the bottom — your own return as reserves, the rest are captured. Two- or four-player, an AI ladder or pass-and-play, three hand-built themes. Installable offline.",
    url: "https://0x4d44.github.io/focus/",
    illustration: "ill-focus",
    date: "2026-07-01T12:00:00",
    year: 1963,
    tag: "games",
    real: true,
  },
  {
    slug: "pylos",
    title: "Pylos",
    tagline: "The rising-pyramid strategy game: place spheres on a 4×4 base and build upward — whoever crowns the single apex wins. The twist: neither side has enough spheres to fill it alone, so you win them back by completing squares and raising your own. A phone-first match against an AI, built in React and installable offline.",
    url: "https://0x4d44.github.io/pylos/",
    illustration: "ill-pylos",
    date: "2026-06-28T12:00:00",
    year: 1994,
    tag: "games",
    real: true,
  },
  {
    slug: "coil",
    title: "Coil",
    tagline: "A snake that solves puzzles with its own body. Strike across a void, grow to bridge a gap, anchor to climb a wall, hold a plate down while you reach the next exit — a curriculum of snake abilities taught one room at a time, across eight worlds. Discrete, deterministic, undo-friendly. TypeScript + Three.js on a tested sim core.",
    url: "https://0x4d44.github.io/coil/",
    illustration: "ill-coil",
    date: "2026-06-20T20:00:00",
    year: 2026,
    tags: ["games"],
    real: false,
  },
  {
    slug: "quarto",
    title: "Quarto",
    tagline: "The elegant abstract with a cruel twist: you never choose your own piece — your opponent hands you each one. Line up four that share any trait — tall, dark, round or hollow — and you win. A phone-first match against an AI in three hand-built themes. React, transpiled in the browser; installable offline.",
    url: "https://0x4d44.github.io/quarto/",
    illustration: "ill-quarto",
    date: "2026-06-20T19:30:00",
    year: 1991,
    tag: "games",
    real: true,
  },
  {
    slug: "the-second-world-war",
    title: "The Second World War",
    tagline: "An animated atlas of the deadliest conflict in history, 1937–1945. Watch the world change month by month as front lines bulge and roll back, the great offensives sweep the continent, and a running death toll climbs past seventy million. Play, pause, scrub and switch between the European, Pacific and world theatres. Vanilla JS on a canvas, fact-checked by a multi-agent research pass.",
    url: "https://0x4d44.github.io/the-second-world-war/",
    illustration: "ill-ww2",
    date: "2026-06-15T18:00:00",
    year: 1939,
    tags: ["history", "software"],
    real: true,
  },
  {
    slug: "night-cab",
    title: "The Night Cab",
    tagline: "A first-person drive of a GTO-inverter EMU down a fourteen-kilometre route from city terminus to the sea — through cuttings, over a viaduct and through a tunnel under a real, rain-streaked sky. Now you share the line: overtake an AI service held in a passing loop and watch another diverge onto a branch. Notch up the whine, work the brake, answer the AWS. Test-driven sim core; TypeScript + Three.js.",
    url: "https://0x4d44.github.io/night-cab/",
    illustration: "ill-emu",
    date: "2026-06-20T22:30:00",
    year: 2026,
    tags: ["rail", "simulation"],
    real: true,
  },
  {
    slug: "world-population",
    title: "The Peopling of the Earth",
    tagline: "Twelve thousand years of humanity, lit on a dark globe — an animated heat-map of population density from the first Neolithic farmers to the megacities of today, and on past a projected peak of ten billion. Watch the centre of human gravity swing from China and India to a blazing Africa. Play, pause, scrub and change speed. Vanilla JS on a canvas.",
    url: "https://0x4d44.github.io/world-population/",
    illustration: "ill-population",
    date: "2026-06-14T16:30:00",
    year: 2026,
    tags: ["science", "history", "software"],
    real: true,
  },
  {
    slug: "worldviewer",
    title: "Worldviewer",
    tagline: "A browser-based Earth twin that flies from orbit to street level. Spin a MapLibre globe with terrain relief, Sentinel-2 imagery and extruded 3D buildings, search any place on Earth, then drop to street scale with live aircraft overhead from the OpenSky network. TypeScript on MapLibre GL JS.",
    url: "https://0x4d44.github.io/worldviewer/",
    illustration: "ill-globe",
    date: "2026-06-14T15:30:00",
    year: 2026,
    tags: ["transport", "simulation"],
    real: true,
  },
  {
    slug: "emu-cab",
    title: "The Cab",
    tagline: "Take the controls of a British electric multiple unit in a fully 3D WebGL cab. Notch up the traction, work the brake, cancel the AWS before it dumps the air, and run the working timetable stop-to-stop — minding the dwell while dodging the SPAD and the high-speed derailment. Pointer-lock cab and ambient soundscape, in Three.js.",
    url: "https://0x4d44.github.io/emu-cab/",
    illustration: "ill-emu",
    date: "2026-06-14T15:00:00",
    year: 2026,
    tags: ["rail", "simulation"],
    real: true,
  },
  {
    slug: "uk-isochrone",
    title: "An Isochronic Map of Britain",
    tagline: "How long does it take to reach anywhere in Britain from Colinton — and to stand atop every mountain? A national isochrone map: door-to-door travel-time contours by road, rail and air, plus a Munros layer timing the walk-up for all 282 Munros and 222 Corbetts. Multi-scale, with real local transit down to street level. A companion to the Time-Contours of Edinburgh.",
    url: "https://0x4d44.github.io/uk-isochrone/",
    illustration: "ill-uk-iso",
    date: "2026-06-14T12:00:00",
    year: 2026,
    tags: ["transport", "software"],
    real: true,
  },
  {
    slug: "edinburgh-isochrone",
    title: "Time-Contours of Edinburgh",
    tagline: "How far can you really get from Colinton — on foot, by bus, tram, train, car or taxi? A layer-tinted travel-time map of the Lothians, Fife and the Borders, built from the real road, rail and path network and bus timetables, routed offline with a grid-Dijkstra flood and a Connection-Scan transit engine. Drawn in the green-to-buff-to-brown tints of Bartholomew & Son.",
    url: "https://0x4d44.github.io/edinburgh-isochrone/",
    illustration: "ill-edinburgh-iso",
    date: "2026-06-13T19:00:00",
    year: 2026,
    tags: ["transport", "software"],
    real: true,
  },
  {
    slug: "mdisochrone",
    title: "An Isochronic Passage Chart",
    tagline: "How long does it really take to get anywhere from Colinton? An interactive homage to Francis Galton's 1881 isochronic chart: pick one of thirteen origin cities and watch real door-to-door travel-time contours wash across an aged-paper world. Then travel back through time, from the jet age to medieval sail, as the legend rescales from hours to months.",
    url: "https://0x4d44.github.io/mdisochrone/",
    illustration: "ill-isochrone",
    date: "2026-06-12T23:10:00",
    year: 2026,
    tags: ["transport", "software"],
    real: true,
  },
  {
    slug: "godel",
    title: "The Snake That Ate Its Own Tail",
    tagline: "An interactive essay on Gödel's incompleteness theorems for a young naturalist — self-reference told through snakes, self-copying microbes, honest calculus and four plushie guides. Eight chapters and six working interactives, from a real Gödel-number encoder to the step-by-step build of the sentence that ended Hilbert's dream.",
    url: "https://0x4d44.github.io/godel/",
    illustration: "ill-ouroboros",
    date: "2026-06-10T14:00:00",
    year: 1931,
    readingMin: 30,
    words: 3200,
    tags: ["math", "science"],
    real: true,
  },
  {
    slug: "benchmarks",
    title: "Fable Arena",
    tagline: "Fourteen frontier models, five disciplines, 1,761 mechanically-graded runs — and a finish line so crowded the score stopped meaning anything. A six-chapter CRT benchmark-zine where the real leaderboard is written in tokens, ending in five theses on what a benchmark that saturates in a day means for the future of AI — and of us.",
    url: "https://0x4d44.github.io/benchmarks/",
    illustration: "ill-arena",
    date: "2026-06-10T11:02:00",
    year: 2026,
    readingMin: 30,
    words: 6500,
    tags: ["software", "science"],
    real: true,
  },
  {
    slug: "win-at-cards",
    title: "The Gentleman's Compendium",
    tagline: "A deadpan vintage manual of winning — never, ever cheating — at cards: wardrobe and concealment, the doctrine of the multiple deck, and the Meaningful Cough. Dedicated to a grandmaster who has never once cheated and will tell you so, at length — with a working Sleeve Capacity Calculator and an Automatic Distraction Generator.",
    url: "https://0x4d44.github.io/win-at-cards/",
    illustration: "ill-sleeve",
    date: "2026-06-09T23:00:00",
    year: 2026,
    readingMin: 11,
    words: 2230,
    tag: "fiction",
    real: true,
  },
  {
    slug: "lothian",
    title: "Lothian",
    tagline: "Edinburgh's buses, a deep dive — a century of madder-and-gold deckers, 110 million journeys a year, a flat-fare network and the road to a net-zero fleet.",
    url: "https://0x4d44.github.io/lothian/",
    illustration: "ill-bus",
    date: "2026-06-09T22:00:00",
    year: 2025,
    readingMin: 14,
    words: 3200,
    tags: ["transport", "history", "engineering"],
    real: true,
  },
  {
    slug: "perth",
    title: "Perth on the Tay",
    tagline: "Eight centuries of a Scottish town, traced on a map that grows before your eyes — the medieval burgh on the river, the great Victorian railway junction, the A9 bypass that remade its edges, and the Wm Low and Iceland years that rewrote its weekly shop.",
    url: "https://0x4d44.github.io/perth/",
    illustration: "ill-perth",
    date: "2026-06-09T16:00:00",
    year: 1124,
    readingMin: 18,
    words: 3500,
    tags: ["history", "rail"],
    real: true,
  },
  {
    slug: "ic-engine",
    title: "How an Engine Works",
    tagline: "An interactive study of the internal combustion engine — the cycle, the thermodynamics, the forces, the turbo, and a century of significant engines. Drive a rotatable 3D model, blow it up on the rev limiter, and watch the balance gauges.",
    url: "https://0x4d44.github.io/ic-engine/",
    illustration: "ill-engine",
    date: "2026-06-09T12:30:00",
    year: 2026,
    readingMin: 58,
    words: 13200,
    tags: ["engineering", "history"],
    real: true,
  },
  {
    slug: "class-47",
    title: "Class 47",
    tagline: "An interactive study of the Brush Type 4 — Britain's most useful diesel. The twin-bank Sulzer, the diesel-electric power chain, the great derating, the series-parallel wiring question, and a fleet of 512, across five driveable chapters.",
    url: "https://0x4d44.github.io/class-47/",
    illustration: "ill-class47",
    date: "2026-06-09T12:00:00",
    year: 1962,
    readingMin: 28,
    words: 6200,
    tags: ["rail", "engineering", "history"],
    real: true,
  },
  {
    slug: "ai-history",
    title: "To Build a Mind",
    tagline: "An interactive history of artificial intelligence — the people, the ideas and the machines that built it — with a working model you can drive in every era, from Turing to today's frontier labs.",
    url: "https://0x4d44.github.io/ai-history/",
    illustration: "ill-ai",
    date: "2026-06-08T20:30:00",
    year: 1956,
    readingMin: 38,
    words: 8000,
    tags: ["software", "history"],
    real: true,
  },
  {
    slug: "ipo-history",
    title: "Declared Effective",
    tagline: "Four centuries of going public — the history, anatomy and high drama of the IPO prospectus, from the VOC's 1602 charter to the modern S-1, plus a build-your-own-IPO scoring engine.",
    url: "https://0x4d44.github.io/ipo-history/",
    illustration: "ill-prospectus",
    date: "2026-06-08T18:30:00",
    year: 1933,
    readingMin: 18,
    words: 4000,
    tags: ["finance", "history"],
    real: true,
  },
  {
    slug: "mdtoken",
    title: "The Forge",
    tagline: "Nine months, 260 billion tokens, three AI tools and seven machines — an interactive autopsy of my own AI-coding habit, mountain ranges and all.",
    url: "https://0x4d44.github.io/mdtoken/",
    illustration: "ill-ridgeline",
    date: "2026-06-08T12:05:00",
    year: 2026,
    readingMin: 8,
    words: 1500,
    tags: ["software", "engineering"],
    real: true,
  },
  {
    slug: "rci-fleet",
    title: "Fleet Atlas",
    tagline: "Every Royal Caribbean cruise ship by tonnage, power, age and fate — and how the cruise ship grew from ocean liner to floating city.",
    url: "https://0x4d44.github.io/rci-fleet/",
    illustration: "ill-ship",
    date: "2026-06-08T12:00:00",
    year: 2026,
    readingMin: 13,
    words: 3000,
    tags: ["maritime", "history", "engineering"],
    real: true,
  },
  {
    slug: "mddosem-win16",
    title: "Win16, Repaired",
    tagline: "An interactive field report from the mddosem Windows 3.1 compatibility sweep — thirty fixes across the NE loader, KERNEL/USER/GDI, and the cooperative scheduler.",
    url: "https://0x4d44.github.io/mddosem-win16/",
    illustration: "ill-win16",
    date: "2026-06-06T12:00:00",
    year: 2026,
    readingMin: 18,
    words: 5200,
    tags: ["software", "engineering"],
    real: true,
  },
  {
    slug: "claude-workflows",
    title: "Dynamic Workflows in Claude Code",
    tagline: "An interactive, cartoon deep-dive into Claude Code's parallel-subagent dynamic workflows — how they work, the patterns, the pitfalls, and a build-it-yourself playground.",
    url: "https://0x4d44.github.io/claude-workflows/",
    illustration: "ill-workflow",
    date: "2026-06-05T19:20:00",
    year: 2026,
    readingMin: 16,
    words: 3600,
    tag: "software",
    real: true,
  },
  {
    slug: "ecml-timeline",
    title: "The Long Run",
    tagline: "A timeline of the East Coast Main Line, 1862–2025.",
    url: "https://0x4d44.github.io/ecml-timeline/",
    illustration: "ill-map",
    date: "2026-01-21",
    year: 2026,
    readingMin: 34,
    words: 8600,
    tags: ["rail", "history"],
    real: true,
  },
  {
    slug: "the-ai-who-watched",
    title: "The AI Who Watched",
    tagline: "“Watch the cat,” she said. It watched. A fable on the gap between what we tell an AI and what we mean.",
    url: "https://0x4d44.github.io/the-ai-who-watched/",
    illustration: "ill-eye",
    date: "2025-11-02",
    year: 2025,
    readingMin: 14,
    words: 3300,
    tag: "fiction",
    real: true,
  },
  {
    slug: "br1955",
    title: "BR Modernisation Program",
    tagline: "British Railways' 1955 Modernisation Plan — a fleet that solved the wrong problem.",
    url: "https://0x4d44.github.io/br1955/",
    illustration: "ill-diesel",
    date: "2025-09-14",
    year: 1955,
    readingMin: 22,
    words: 5400,
    tags: ["rail", "history"],
    real: true,
  },
  {
    slug: "vernier",
    title: "Vernier",
    tagline: "A field guide to quality, testing & agents.",
    url: "https://0x4d44.github.io/vernier/",
    illustration: "ill-caliper",
    date: "2026-05-26",
    year: 2026,
    readingMin: 203,
    words: 40658,
    tag: "software",
    real: true,
  },
  {
    slug: "readex",
    title: "readex",
    tagline: "HTML main-content extraction for Rust.",
    url: "https://0x4d44.github.io/readex/",
    illustration: "ill-extract",
    date: "2026-05-26",
    year: 2026,
    readingMin: 8,
    words: 1554,
    tag: "software",
    real: true,
  },
  {
    slug: "ropus",
    title: "ropus",
    tagline: "The Opus audio codec, ported to safe Rust — bit-exact against the C reference.",
    url: "https://0x4d44.github.io/ropus/",
    illustration: "ill-wave",
    date: "2026-05-26",
    year: 2026,
    readingMin: 12,
    words: 2331,
    tag: "software",
    real: true,
  },
  {
    slug: "mr-poop",
    title: "The Day Mr Poop Got His Name",
    tagline: "A Bumbleworth Paper Co. comic.",
    url: "https://0x4d44.github.io/mr-poop/",
    illustration: "ill-comic",
    date: "2026-05-26",
    year: 2026,
    readingMin: 2,
    words: 395,
    tag: "comic",
    real: true,
  },
  {
    slug: "azuma",
    title: "Azuma",
    tagline: "A data dump on LNER's Class 800/801 fleet.",
    url: "https://0x4d44.github.io/azuma/",
    illustration: "ill-emu",
    date: "2026-05-26",
    year: 2026,
    readingMin: 31,
    words: 6223,
    tag: "rail",
    real: true,
  },
  {
    slug: "picoem",
    title: "picoem",
    tagline: "Cycle-accurate Raspberry Pi RP2350 / RP2040 emulators in Rust.",
    url: "https://0x4d44.github.io/picoem/",
    illustration: "ill-chip",
    date: "2026-05-26",
    year: 2026,
    readingMin: 14,
    words: 2822,
    tags: ["software", "engineering"],
    real: true,
  },
  {
    slug: "token-predictor",
    title: "Token Predictor",
    tagline: "A visceral look at how fast an LLM actually generates text.",
    url: "https://0x4d44.github.io/token-predictor/",
    illustration: "ill-tokens",
    date: "2026-05-26",
    year: 2026,
    readingMin: 3,
    words: 600,
    tag: "software",
    real: true,
  },
  {
    slug: "mddskimg",
    title: "mddskimg",
    tagline: "Browse, extract and rewrite raw disk images — no loop mounts, root, or OS drivers.",
    url: "https://0x4d44.github.io/mddskimg/",
    illustration: "ill-disk",
    date: "2026-05-26",
    year: 2026,
    readingMin: 12,
    words: 2332,
    tag: "software",
    real: true,
  },
  {
    slug: "ecml",
    title: "The East Coast Main Line",
    tagline: "An interactive history of Britain's East Coast Main Line, 1825–1991.",
    url: "https://0x4d44.github.io/ecml/",
    illustration: "ill-signal",
    date: "2026-05-26",
    year: 2026,
    readingMin: 13,
    words: 2670,
    tags: ["rail", "history"],
    real: true,
  },
  {
    slug: "hydro",
    title: "The Hydro",
    tagline: "A century of Scottish water power.",
    url: "https://0x4d44.github.io/hydro/",
    illustration: "ill-hydro",
    date: "2026-05-26",
    year: 2026,
    readingMin: 12,
    words: 2311,
    tags: ["history", "engineering"],
    real: true,
  },
  {
    slug: "mdmdview",
    title: "mdmdview",
    tagline: "A markdown viewer built for speed.",
    url: "https://0x4d44.github.io/mdmdview/",
    illustration: "ill-markdown",
    date: "2026-05-27",
    year: 2026,
    readingMin: 9,
    words: 1734,
    tag: "software",
    real: true,
  },
  {
    slug: "mercury-arc-rectifiers",
    title: "Mercury Arc Rectifiers",
    tagline: "A technical primer on the glass-bulb rectifiers that turned AC into DC.",
    url: "https://0x4d44.github.io/mercury-arc-rectifiers/",
    illustration: "ill-rectifier",
    date: "2026-05-27",
    year: 2026,
    readingMin: 19,
    words: 3769,
    tags: ["engineering", "history"],
    real: true,
  },
  {
    slug: "mdminecraft",
    title: "mdminecraft",
    tagline: "A deterministic voxel sandbox engine, in Rust.",
    url: "https://0x4d44.github.io/mdminecraft/",
    illustration: "ill-voxel",
    date: "2026-05-27",
    year: 2026,
    readingMin: 11,
    words: 2281,
    tag: "software",
    real: true,
  },
  {
    slug: "mdkloc",
    title: "mdkloc",
    tagline: "A field guide to counting lines of code.",
    url: "https://0x4d44.github.io/mdkloc/",
    illustration: "ill-loc",
    date: "2026-05-27",
    year: 2026,
    readingMin: 10,
    words: 2063,
    tag: "software",
    real: true,
  },
  {
    slug: "netmeeting",
    title: "NetMeeting",
    tagline: "A deep dive into Microsoft's forgotten conferencing pioneer.",
    url: "https://0x4d44.github.io/netmeeting/",
    illustration: "ill-call",
    date: "2026-05-27",
    year: 2026,
    readingMin: 19,
    words: 3764,
    tags: ["history", "software"],
    real: true,
  },
  {
    slug: "mddosem",
    title: "mddosem",
    tagline: "A hardware-accurate 1990s PC, emulated in Rust.",
    url: "https://0x4d44.github.io/mddosem/",
    illustration: "ill-pc",
    date: "2026-05-27",
    year: 2026,
    readingMin: 15,
    words: 3057,
    tags: ["software", "engineering"],
    real: true,
  },
  {
    slug: "calculus",
    title: "The Calculus of Things That Move",
    tagline: "Two questions about change — an interactive field guide to calculus.",
    url: "https://0x4d44.github.io/calculus/",
    illustration: "ill-calculus",
    date: "2026-05-28T00:48:36",
    year: 2026,
    readingMin: 10,
    words: 2224,
    tag: "math",
    real: true,
  },
  {
    slug: "data-logger",
    title: "Data Logger",
    tagline: "A code tour of an embedded data logger: three chips, four sensors, one protocol.",
    url: "https://0x4d44.github.io/data-logger/",
    illustration: "ill-logger",
    date: "2026-05-28T00:48:31",
    year: 2026,
    readingMin: 4,
    words: 931,
    tags: ["software", "engineering"],
    real: true,
  },
  {
    slug: "estimation-whist",
    title: "ESTWHI.EXE",
    tagline: "A guided tour through a 3,952-line Pascal implementation of Estimation Whist.",
    url: "https://0x4d44.github.io/estimation-whist/",
    illustration: "ill-cards",
    date: "2026-05-28T00:56:58",
    year: 2026,
    readingMin: 26,
    words: 6057,
    tag: "software",
    real: true,
  },
  {
    slug: "estimation-whist-game",
    title: "Estimation Whist",
    tagline: "A playable rebuild of the 1994 Pascal card game: bid against three AI opponents across a full 25-round match, with a coach, house rules and three table themes. Built on a tiny HTML-template runtime that renders React in the browser — no build step.",
    url: "https://0x4d44.github.io/estimation-whist-game/",
    illustration: "ill-cards",
    date: "2026-07-02T23:00:00",
    year: 2026,
    tag: "games",
    real: true,
  },
  {
    slug: "nonogram",
    title: "NONOGRAM.EXE",
    tagline: "A codebase walkthrough of a nonogram (picross) puzzle solver.",
    url: "https://0x4d44.github.io/nonogram/",
    illustration: "ill-nonogram",
    date: "2026-05-28T00:58:10",
    year: 2026,
    readingMin: 14,
    words: 3210,
    tag: "software",
    real: true,
  },
  {
    slug: "rail-control",
    title: "Rail Control",
    tagline: "A codebase explainer for a railway signalling & train-routing simulator.",
    url: "https://0x4d44.github.io/rail-control/",
    illustration: "ill-railctrl",
    date: "2026-05-28T00:57:01",
    year: 2026,
    readingMin: 22,
    words: 5096,
    tags: ["rail", "software"],
    real: true,
  },
  {
    slug: "rust-field-guide",
    title: "Unsafe at Any Speed",
    tagline: "A field guide to Rust — ownership, editions, and where the language is headed.",
    url: "https://0x4d44.github.io/rust-field-guide/",
    illustration: "ill-rust",
    date: "2026-05-28T00:58:09",
    year: 2026,
    readingMin: 13,
    words: 3036,
    tag: "software",
    real: true,
  },
  {
    slug: "spectrum-analyzer",
    title: "Spectrum Analyser",
    tagline: "A 1996 spectrum-analyser codebase, explained — FFTs and all.",
    url: "https://0x4d44.github.io/spectrum-analyzer/",
    illustration: "ill-spectrum",
    date: "2026-05-28T01:20:55",
    year: 1996,
    readingMin: 15,
    words: 3364,
    tags: ["software", "engineering"],
    real: true,
  },
  {
    slug: "mdrll",
    title: "mdrll",
    tagline: "From magnetic flux to a mountable filesystem — decoding MFM and RLL disk encodings.",
    url: "https://0x4d44.github.io/mdrll/",
    illustration: "ill-flux",
    date: "2026-05-28T01:56:54",
    year: 2026,
    readingMin: 42,
    words: 9554,
    tags: ["software", "engineering"],
    real: true,
  },
  {
    slug: "lighthouse",
    title: "Lighthouse",
    tagline: "A 5,100-line C89 SCUMM-style adventure engine for 386 + VGA + Sound Blaster.",
    url: "https://0x4d44.github.io/lighthouse/",
    illustration: "ill-lighthouse",
    date: "2026-05-28T01:57:02",
    year: 2026,
    readingMin: 19,
    words: 4477,
    tag: "software",
    real: true,
  },
  {
    slug: "model-railway",
    title: "Model Railway",
    tagline: "DCC, I²C and back-EMF — a codebase deep dive into a model-railway control system.",
    url: "https://0x4d44.github.io/model-railway/",
    illustration: "ill-modelrail",
    date: "2026-05-28T01:59:04",
    year: 2026,
    readingMin: 15,
    words: 3431,
    tags: ["rail", "engineering", "software"],
    real: true,
  },
  {
    slug: "stop-the-bus",
    title: "Stop the Bus",
    tagline: "Inside STOPBUS — a 1994 four-player card game with three AI opponents.",
    url: "https://0x4d44.github.io/stop-the-bus/",
    illustration: "ill-bus",
    date: "2026-05-28T18:51:51",
    year: 1994,
    readingMin: 30,
    words: 6985,
    tag: "software",
    real: true,
  },
  {
    slug: "mdmcp",
    title: "mdmcp",
    tagline: "A Rust MCP server that hands an LLM your command-line tools — behind a policy gate.",
    url: "https://0x4d44.github.io/mdmcp/",
    illustration: "ill-mcp",
    date: "2026-05-28T18:51:48",
    year: 2026,
    readingMin: 18,
    words: 4192,
    tag: "software",
    real: true,
  },
  {
    slug: "edinburgh-biosci",
    title: "First Year, Decoded",
    tagline: "A first-year survival guide to Biological Sciences at the University of Edinburgh.",
    url: "https://0x4d44.github.io/edinburgh-biosci/",
    illustration: "ill-dna",
    date: "2026-05-28T18:54:17",
    year: 2026,
    readingMin: 13,
    words: 3072,
    tag: "science",
    real: true,
  },
  {
    slug: "traction-motors",
    title: "Electric Traction Motors",
    tagline: "An interactive study — from DC series motors to inverter-fed induction drives.",
    url: "https://0x4d44.github.io/traction-motors/",
    illustration: "ill-motor",
    date: "2026-05-28T19:40:37",
    year: 2026,
    readingMin: 51,
    words: 11670,
    tags: ["rail", "engineering"],
    real: true,
  },
  {
    slug: "mdtpw",
    title: "mdtpw",
    tagline: "A from-scratch Turbo Pascal compiler in Rust — legacy 16-bit Pascal in, native Windows .EXE out.",
    url: "https://0x4d44.github.io/mdtpw/",
    illustration: "ill-tpw",
    date: "2026-06-01T10:00:00",
    year: 2026,
    readingMin: 19,
    words: 3893,
    tags: ["software", "engineering"],
    real: true,
  },
];

// Filter vocabulary, split into two axes for the grouped filter row:
//   form    — what a piece IS    (software / games / simulation / fiction / comic)
//   subject — what it is ABOUT   (rail, history, engineering, …)
// A piece may carry tags from both axes. The order below is the display
// order of the chips; each chip's live document count is computed in app.js.
// Rule of thumb for the form axis: `games` = you play it to win/progress;
// `simulation` = you drive or inhabit a real-time model; `software` = tools
// and technical write-ups (including code walkthroughs *about* games/sims).
window.TAG_GROUPS = [
  { label: "form",    tags: ["software", "games", "simulation", "fiction", "comic"] },
  { label: "subject", tags: ["rail", "history", "engineering", "transport", "science", "maritime", "math", "finance"] },
];
// Flat list ("all" first), derived from the groups, for any consumer that
// just wants the plain vocabulary.
window.TAGS = ["all", ...window.TAG_GROUPS.flatMap(g => g.tags)];

window.fmtDate = function (iso) {
  const m = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  // Format from the YYYY-MM-DD prefix directly, so a bare date isn't shifted a
  // day by timezone (new Date("2025-11-02") is UTC midnight → prior day west of UTC).
  const [y, mo, d] = String(iso).slice(0, 10).split("-").map(Number);
  if (!y || !mo || !d) return "";
  return `${String(d).padStart(2,"0")} ${m[mo - 1]} ${y}`;
};

// Aggregate stats over the catalog, shared by the listing status bar (app.js)
// and the about page. `subjects` counts distinct *subject*-axis tags only (not
// the form axis), falling back to all tags when no subject axis is defined.
// `last` is the most recent entry (by date), or null for an empty catalog.
window.siteStats = function () {
  const essays = window.ESSAYS || [];
  const tagsOf = (e) => e.tags || (e.tag ? [e.tag] : []);
  const subjectAxis = (window.TAG_GROUPS || []).find(g => g.label === "subject");
  const subjectTags = subjectAxis ? new Set(subjectAxis.tags) : null;
  return {
    total: essays.length,
    words: essays.reduce((s, e) => s + (e.words || 0), 0),
    subjects: new Set(
      essays.flatMap(tagsOf).filter(t => !subjectTags || subjectTags.has(t))
    ).size,
    last: essays.slice().sort((a, b) => (b.date || "").localeCompare(a.date || ""))[0] || null,
  };
};
