// ============================================================
// 0x4D44 — document catalog
// Add/edit entries here. Each entry needs at minimum: title,
// tagline, url, date (YYYY-MM-DD), year (subject year), tag.
// readingMin and words are optional but shown when present.
// ============================================================

window.ESSAYS = [
  {
    slug: "ecml",
    title: "The Long Run",
    tagline: "A timeline of the East Coast Main Line, 1862–2025.",
    url: "https://0x4d44.github.io/ecml-timeline/",
    illustration: "ill-map",
    date: "2026-01-21",
    year: 2026,
    readingMin: 34,
    words: 8600,
    tag: "rail",
    real: true,
  },
  {
    slug: "ai-watched",
    title: "The AI Who Watched",
    tagline: "“Watch the cat,” she said. It watched. A fable on the gap between what we tell an AI and what we mean.",
    url: "https://0x4d44.github.io/the-ai-who-watched/",
    illustration: "ill-eye",
    date: "2025-11-02",
    year: 2025,
    readingMin: 14,
    words: 3300,
    tag: "fiction",
    real: true,
  },
  {
    slug: "br1955",
    title: "BR Modernisation Program",
    tagline: "British Railways' 1955 Modernisation Plan — a fleet that solved the wrong problem.",
    url: "https://0x4d44.github.io/br1955/",
    illustration: "ill-diesel",
    date: "2025-09-14",
    year: 1955,
    readingMin: 22,
    words: 5400,
    tag: "rail",
    real: true,
  },
  {
    slug: "vernier",
    title: "Vernier",
    tagline: "A field guide to quality, testing & agents.",
    url: "https://0x4d44.github.io/vernier/",
    illustration: "ill-caliper",
    date: "2026-05-26",
    year: 2026,
    readingMin: 203,
    words: 40658,
    tag: "software",
    real: true,
  },
  {
    slug: "readex",
    title: "readex",
    tagline: "HTML main-content extraction for Rust.",
    url: "https://0x4d44.github.io/readex/",
    illustration: "ill-extract",
    date: "2026-05-26",
    year: 2026,
    readingMin: 8,
    words: 1554,
    tag: "software",
    real: true,
  },
  {
    slug: "ropus",
    title: "ropus",
    tagline: "The Opus audio codec, ported to safe Rust — bit-exact against the C reference.",
    url: "https://0x4d44.github.io/ropus/",
    illustration: "ill-wave",
    date: "2026-05-26",
    year: 2026,
    readingMin: 12,
    words: 2331,
    tag: "software",
    real: true,
  },
  {
    slug: "mr-poop",
    title: "The Day Mr Poop Got His Name",
    tagline: "A Bumbleworth Paper Co. comic.",
    url: "https://0x4d44.github.io/mr-poop/",
    illustration: "ill-comic",
    date: "2026-05-26",
    year: 2026,
    readingMin: 2,
    words: 395,
    tag: "comic",
    real: true,
  },
  {
    slug: "azuma",
    title: "Azuma",
    tagline: "A data dump on LNER's Class 800/801 fleet.",
    url: "https://0x4d44.github.io/azuma/",
    illustration: "ill-emu",
    date: "2026-05-26",
    year: 2026,
    readingMin: 31,
    words: 6223,
    tag: "rail",
    real: true,
  },
  {
    slug: "picoem",
    title: "picoem",
    tagline: "Cycle-accurate Raspberry Pi RP2350 / RP2040 emulators in Rust.",
    url: "https://0x4d44.github.io/picoem/",
    illustration: "ill-chip",
    date: "2026-05-26",
    year: 2026,
    readingMin: 14,
    words: 2822,
    tag: "software",
    real: true,
  },
];

// Tags shown in the filter row. "all" is always first.
window.TAGS = ["all", "rail", "fiction", "software", "comic"];

window.fmtDate = function (iso) {
  const d = new Date(iso);
  const m = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  return `${String(d.getDate()).padStart(2,"0")} ${m[d.getMonth()]} ${d.getFullYear()}`;
};
