/* ============================================================
   BARCELONA · content.js — bilingual content (ES/EN).
   Generated by a multi-agent research + writing pass
   (web-verified venue facts, character bible, phrasebook),
   then hand-assembled. Edit here to change copy.
   ============================================================ */
window.CONTENT = {
  "venues": [
    {
      "slug": "sagrada",
      "name": {
        "en": "La Sagrada Família",
        "es": "La Sagrada Família"
      },
      "kicker": {
        "en": "Gaudí's unfinished masterpiece",
        "es": "La obra maestra inacabada de Gaudí"
      },
      "lat": 41.4036,
      "lng": 2.1744,
      "intro": [
        {
          "en": "Antoni Gaudí's colossal basilica has been rising over Barcelona since 1882, and in June 2026 its central Tower of Jesus Christ was finally crowned — making it, at 172.5 metres, the tallest church on Earth. Part cathedral, part forest, part fever dream in stone.",
          "es": "La colosal basílica de Antoni Gaudí se alza sobre Barcelona desde 1882, y en junio de 2026 se coronó por fin su torre central de Jesucristo, convirtiéndola, con 172,5 metros, en la iglesia más alta del mundo. Mitad catedral, mitad bosque, mitad sueño delirante en piedra."
        },
        {
          "en": "Step inside and the columns branch like trees, stained glass floods the nave with shifting colour, and every façade tells a different chapter. Gaudí knew he'd never see it finished — he died in 1926 — but he built it to outlive him, one donation at a time.",
          "es": "Al entrar, las columnas se ramifican como árboles, la vidriera inunda la nave de color cambiante y cada fachada narra un capítulo distinto. Gaudí sabía que no la vería acabada —murió en 1926— pero la construyó para que le sobreviviera, donativo a donativo."
        }
      ],
      "facts": [
        {
          "en": "Gaudí devoted the last 43 years of his life to it and is buried in its crypt; when he died in 1926, struck by a tram, only about a quarter of the basilica was built.",
          "es": "Gaudí le dedicó los últimos 43 años de su vida y está enterrado en su cripta; cuando murió en 1926, atropellado por un tranvía, solo estaba construida cerca de una cuarta parte de la basílica."
        },
        {
          "en": "It is an 'expiatory temple', funded entirely by private donations and visitor tickets — never by the Church or the state — which is why it took over 140 years.",
          "es": "Es un 'templo expiatorio', financiado íntegramente con donativos privados y entradas de visitantes —nunca por la Iglesia ni el Estado—, motivo por el que tardó más de 140 años."
        },
        {
          "en": "The design tops out at 172.5 m on purpose: Gaudí insisted no human work should rise above Montjuïc hill (177 m), because nothing man-made should surpass the work of God.",
          "es": "El diseño culmina en 172,5 m a propósito: Gaudí insistió en que ninguna obra humana superara la montaña de Montjuïc (177 m), porque nada hecho por el hombre debía sobrepasar la obra de Dios."
        },
        {
          "en": "When complete it will have 18 spires — twelve for the apostles, four for the evangelists, one for the Virgin Mary and the central one for Jesus, crowned by a luminous four-armed cross.",
          "es": "Al completarse tendrá 18 torres: doce para los apóstoles, cuatro para los evangelistas, una para la Virgen María y la central para Jesús, coronada por una cruz luminosa de cuatro brazos."
        },
        {
          "en": "The Nativity façade and crypt are UNESCO World Heritage, and Pope Benedict XVI consecrated the basilica in 2010 — so it's a working church, not just a monument.",
          "es": "La fachada del Nacimiento y la cripta son Patrimonio de la Humanidad de la UNESCO, y el papa Benedicto XVI consagró la basílica en 2010, así que es una iglesia en activo, no solo un monumento."
        },
        {
          "en": "The two main façades are deliberate opposites: the joyful, ornate Nativity façade Gaudí built himself, and the stark, angular Passion façade sculpted decades later by Josep Maria Subirachs.",
          "es": "Las dos fachadas principales son opuestas a propósito: la del Nacimiento, alegre y recargada, que construyó el propio Gaudí, y la de la Pasión, austera y angulosa, esculpida décadas después por Josep Maria Subirachs."
        }
      ],
      "tips": [
        {
          "en": "Take Metro L2 (purple) or L5 (blue) to Sagrada Família — you surface right at its feet. Bus lines and the Barcelona Bus Turístic stop here too.",
          "es": "Coge el metro L2 (violeta) o L5 (azul) hasta Sagrada Família: sales justo a sus pies. También paran aquí varias líneas de bus y el Bus Turístic de Barcelona."
        },
        {
          "en": "Book online in advance and pick a timed slot — turning up at the door in peak season can mean a queue of one to two hours, or a sold-out day.",
          "es": "Reserva por internet con antelación y elige una hora concreta: presentarse en la puerta en temporada alta puede suponer una cola de una o dos horas, o encontrarlo agotado."
        },
        {
          "en": "Go first thing in the morning or late afternoon on a weekday — the light through the stained glass is best early (east, warm tones) and late (west, cool tones), and the crowds are thinner.",
          "es": "Ve a primera hora de la mañana o a última de la tarde entre semana: la luz por las vidrieras es mejor temprano (este, tonos cálidos) y al atardecer (oeste, tonos fríos), y hay menos gente."
        },
        {
          "en": "Pay the extra for tower access if you can — a lift up and a walk back down the spiral stairs gives you dizzying views over Barcelona and the ceramic finials up close.",
          "es": "Paga el suplemento del acceso a las torres si puedes: subes en ascensor y bajas por la escalera de caracol, con vistas vertiginosas de Barcelona y los pináculos de cerámica de cerca."
        },
        {
          "en": "Don't rush the interior — spend time under the tree-like columns looking up, then compare the two façades outside. The little on-site museum explains how it was engineered.",
          "es": "No corras por el interior: dedica un rato bajo las columnas arbóreas mirando hacia arriba y luego compara las dos fachadas por fuera. El pequeño museo del recinto explica cómo se diseñó."
        }
      ],
      "stats": [
        {
          "label": {
            "en": "Height",
            "es": "Altura"
          },
          "value": "172.5 m"
        },
        {
          "label": {
            "en": "Begun",
            "es": "Iniciada"
          },
          "value": "1882"
        },
        {
          "label": {
            "en": "Spires planned",
            "es": "Torres previstas"
          },
          "value": "18"
        },
        {
          "label": {
            "en": "World ranking",
            "es": "Ranking mundial"
          },
          "value": "Tallest church"
        }
      ],
      "glados": [
        {
          "en": "Welcome, test subject. You have elected to enter a structure that took 144 years to build. I calculate your two-day itinerary allows roughly 0.0004% of that. Ambitious. Do book online first — the alternative is a queue so long it develops its own culture and cuisine.",
          "es": "Bienvenido, sujeto de prueba. Ha elegido entrar en una estructura que tardó 144 años en construirse. Calculo que su itinerario de dos días le concede en torno al 0,0004% de eso. Ambicioso. Reserve por internet primero: la alternativa es una cola tan larga que desarrolla cultura y gastronomía propias."
        },
        {
          "en": "Gaudí worked here for forty-three years and still didn't finish. You have an afternoon. I admire the optimism. Arrive at opening or near closing — the light through the stained glass is, and I say this clinically, objectively superior at those hours. The Catalans engineered it that way on purpose. Show-offs. Magnificent show-offs.",
          "es": "Gaudí trabajó aquí cuarenta y tres años y aun así no la terminó. Usted dispone de una tarde. Admiro el optimismo. Llegue a la apertura o cerca del cierre: la luz por las vidrieras es, y lo digo clínicamente, objetivamente superior a esas horas. Los catalanes lo diseñaron así a propósito. Fanfarrones. Magníficos fanfarrones."
        },
        {
          "en": "The columns branch like trees to make you look up in awe. It is a manipulation of your neck and your emotions, and it works flawlessly on every subject we test. Buy the tower ticket. The view of Barcelona from up there is, regrettably, worth the money. I hate that I have to admit that.",
          "es": "Las columnas se ramifican como árboles para obligarle a mirar hacia arriba con asombro. Es una manipulación de su cuello y sus emociones, y funciona a la perfección con todos los sujetos que evaluamos. Compre la entrada a las torres. La vista de Barcelona desde ahí arriba, lamentablemente, vale el dinero. Detesto tener que admitirlo."
        },
        {
          "en": "Please do not touch the 172.5-metre basilica. Yes, it is exactly that tall so as not to out-build a nearby hill, which is either humility or the most elaborate humblebrag in architectural history. Either way it is now the tallest church on the planet. Barcelona wins. Try not to look too impressed on the way out. You will fail.",
          "es": "Por favor, no toque la basílica de 172,5 metros. Sí, mide exactamente eso para no superar una colina cercana, lo cual es humildad o el alarde falsamente modesto más elaborado de la historia de la arquitectura. En cualquier caso, ahora es la iglesia más alta del planeta. Gana Barcelona. Intente no parecer demasiado impresionado al salir. Fracasará."
        }
      ],
      "metro": {
        "en": "Metro L2 or L5 → Sagrada Família (exits at the basilica)",
        "es": "Metro L2 o L5 → Sagrada Família (salida junto a la basílica)"
      }
    },
    {
      "slug": "aquarium",
      "name": {
        "en": "L'Aquàrium de Barcelona",
        "es": "L'Aquàrium de Barcelona"
      },
      "kicker": {
        "en": "Walk beneath the sharks",
        "es": "Camina bajo los tiburones"
      },
      "lat": 41.3766,
      "lng": 2.1838,
      "metro": {
        "en": "Metro L3 (green) Drassanes, or L4 (yellow) Barceloneta — a 5-10 min waterfront walk.",
        "es": "Metro L3 (verde) Drassanes, o L4 (amarilla) Barceloneta — 5-10 min andando por el puerto."
      },
      "intro": [
        {
          "en": "Down on the Moll d'Espanya, jutting into the old harbour of Port Vell, sits one of Europe's biggest aquariums. Opened in 1995, it holds 11,000 marine creatures across 35 tanks and five million litres of the Mediterranean, indoors.",
          "es": "En el Moll d'Espanya, adentrándose en el viejo puerto de Port Vell, está uno de los acuarios más grandes de Europa. Inaugurado en 1995, alberga 11.000 criaturas marinas en 35 tanques y cinco millones de litros de Mediterráneo, bajo techo."
        },
        {
          "en": "The star is the Oceanari: a colossal 36-metre tank with an 80-metre glass tunnel running along its floor. You glide beneath sand tiger sharks, rays and sunfish on a slow travelator — no diving licence, no getting wet, just quiet awe.",
          "es": "La estrella es el Oceanari: un tanque colosal de 36 metros con un túnel de cristal de 80 metros en su base. Te deslizas bajo tiburones toro, rayas y peces luna sobre una cinta lenta — sin licencia de buceo, sin mojarte, solo asombro callado."
        }
      ],
      "facts": [
        {
          "en": "The Oceanari alone holds 3.7 million litres — most of the aquarium's total — in a tank 36 metres wide and 5 metres deep.",
          "es": "Solo el Oceanari contiene 3,7 millones de litros — la mayoría del total del acuario — en un tanque de 36 metros de ancho y 5 de profundidad."
        },
        {
          "en": "Its 80-metre acoustic-glass tunnel puts you level with the sharks; a travelator carries you through so you can just look up.",
          "es": "Su túnel de cristal acústico de 80 metros te pone a la altura de los tiburones; una cinta te lleva a través para que solo tengas que mirar hacia arriba."
        },
        {
          "en": "It opened on 8 September 1995 as part of the Port Vell regeneration that reconnected Barcelona to its own seafront.",
          "es": "Abrió el 8 de septiembre de 1995 como parte de la regeneración de Port Vell que reconectó Barcelona con su propio litoral."
        },
        {
          "en": "Around 450 species live here — sand tiger and sandbar sharks, moray eels, ocean sunfish, rays and a warm-water reef of clownfish and corals.",
          "es": "Aquí viven unas 450 especies — tiburones toro y trozo, morenas, peces luna, rayas y un arrecife de agua cálida con peces payaso y corales."
        },
        {
          "en": "It draws over two million visitors a year, making it one of Barcelona's most-loved family attractions.",
          "es": "Recibe más de dos millones de visitantes al año, siendo una de las atracciones familiares más queridas de Barcelona."
        }
      ],
      "tips": [
        {
          "en": "Book online in advance — it skips the ticket queue and often saves money over the door price.",
          "es": "Reserva online con antelación — te ahorras la cola de taquilla y suele salir más barato que en puerta."
        },
        {
          "en": "Go right at opening or in the late afternoon; midday and rainy days pack the tunnel with families.",
          "es": "Ve nada más abrir o a última hora de la tarde; el mediodía y los días de lluvia llenan el túnel de familias."
        },
        {
          "en": "Take Metro L3 to Drassanes or L4 to Barceloneta, then stroll across the Rambla de Mar footbridge to Moll d'Espanya.",
          "es": "Coge el Metro L3 hasta Drassanes o L4 hasta Barceloneta, y cruza la pasarela de la Rambla de Mar hasta el Moll d'Espanya."
        },
        {
          "en": "Don't rush the Oceanari tunnel — step off the travelator to one side and let the sharks come to you.",
          "es": "No corras el túnel del Oceanari — apártate de la cinta a un lado y deja que los tiburones vengan a ti."
        },
        {
          "en": "Bring kids to Planeta Aqua and the Explora! zone, then reward everyone with a paella on the Barceloneta boardwalk after.",
          "es": "Lleva a los niños a Planeta Aqua y a la zona Explora!, y luego premia a todos con una paella en el paseo de la Barceloneta."
        }
      ],
      "stats": [
        {
          "label": {
            "en": "Shark tunnel",
            "es": "Túnel de tiburones"
          },
          "value": "80 m"
        },
        {
          "label": {
            "en": "Water",
            "es": "Agua"
          },
          "value": "5M L"
        },
        {
          "label": {
            "en": "Tanks",
            "es": "Tanques"
          },
          "value": "35"
        },
        {
          "label": {
            "en": "Species",
            "es": "Especies"
          },
          "value": "~450"
        }
      ],
      "glados": [
        {
          "en": "Welcome, test subject. Today's chamber: an 80-metre glass tube submerged beneath four-metre sharks. Statistically, the glass holds. I have not personally verified this. Do enjoy the science.",
          "es": "Bienvenido, sujeto de prueba. La cámara de hoy: un tubo de cristal de 80 metros sumergido bajo tiburones de cuatro metros. Estadísticamente, el cristal aguanta. No lo he verificado personalmente. Disfruta de la ciencia."
        },
        {
          "en": "The Aspirational Instructions suggest 'arriving early to avoid crowds.' Curious. Most subjects arrive at noon, in the rain, together. You, however, appear to possess judgement. Book online. Take Metro L3 to Drassanes. I'm almost proud.",
          "es": "Las Instrucciones Aspiracionales sugieren 'llegar temprano para evitar multitudes'. Curioso. La mayoría de los sujetos llega a mediodía, con lluvia, todos juntos. Tú, en cambio, pareces tener criterio. Reserva online. Metro L3 hasta Drassanes. Casi estoy orgullosa."
        },
        {
          "en": "The travelator will move you through the tunnel at a fixed, merciless pace. This is a design flaw. Step to the side, defy the machine, and let the rays hover over you. The Catalans built something genuinely magnificent here on Port Vell. Even I can measure that.",
          "es": "La cinta te moverá por el túnel a un ritmo fijo e implacable. Es un defecto de diseño. Apártate a un lado, desafía a la máquina, y deja que las rayas floten sobre ti. Los catalanes construyeron algo genuinamente magnífico aquí en Port Vell. Hasta yo puedo medirlo."
        }
      ]
    },
    {
      "slug": "cruise",
      "name": {
        "en": "Barcelona Cruise Terminal (Port of Barcelona)",
        "es": "Terminal de Cruceros de Barcelona (Puerto de Barcelona)"
      },
      "kicker": {
        "en": "Gateway to the Mediterranean",
        "es": "Puerta del Mediterraneo"
      },
      "lat": 41.3585,
      "lng": 2.172,
      "metro": {
        "en": "Metro L3 (green) to Drassanes, then the Portbus/Cruisebus shuttle to Moll Adossat",
        "es": "Metro L3 (verde) hasta Drassanes y despues la lanzadera Portbus/Cruisebus al Moll Adossat"
      },
      "intro": [
        {
          "en": "Where La Rambla runs out of pavement and meets the sea, the Port of Barcelona opens up: the busiest cruise port in Europe and the Mediterranean, and one of the largest on Earth. Every morning in season, floating cities the size of neighbourhoods glide in past the Columbus monument.",
          "es": "Donde La Rambla se queda sin acera y se topa con el mar, se abre el Puerto de Barcelona: el puerto de cruceros mas activo de Europa y el Mediterraneo, y uno de los mayores del planeta. Cada manana de temporada, ciudades flotantes del tamano de un barrio entran deslizandose junto al monumento a Colon."
        },
        {
          "en": "Most giants dock at the Moll Adossat, a long quay that can berth four huge ships at once and moves around 15,000 passengers on a busy day. Smaller vessels tie up near the World Trade Center, a five-minute stroll from the Gothic Quarter. It is theatre, logistics and pure Barcelona swagger.",
          "es": "Los gigantes atracan en el Moll Adossat, un muelle largo capaz de acoger cuatro grandes buques a la vez y que mueve unos 15.000 pasajeros en un dia punta. Los barcos mas pequenos amarran junto al World Trade Center, a cinco minutos del Barrio Gotico. Es teatro, logistica y puro orgullo barcelones."
        }
      ],
      "facts": [
        {
          "en": "Barcelona is the leading cruise port in Europe and the Mediterranean, and ranks among the largest in the world after the big Caribbean hubs.",
          "es": "Barcelona es el primer puerto de cruceros de Europa y el Mediterraneo, y figura entre los mayores del mundo tras los grandes centros del Caribe."
        },
        {
          "en": "The Moll Adossat quay can berth four large cruise ships at the same time and handles roughly 15,000 passengers on a peak day.",
          "es": "El muelle Moll Adossat puede acoger cuatro grandes cruceros a la vez y gestiona unos 15.000 pasajeros en un dia de maxima afluencia."
        },
        {
          "en": "The port is deliberately shrinking: by 2030 the city and Port Authority will cut cruise terminals from seven to five to ease overcrowding.",
          "es": "El puerto se reduce a proposito: para 2030 la ciudad y la Autoridad Portuaria pasaran de siete a cinco terminales de cruceros para aliviar la masificacion."
        },
        {
          "en": "Since October 2023 cruise ships no longer dock at the northern Barcelona quay near the WTC and are sent to the Moll Adossat instead.",
          "es": "Desde octubre de 2023 los cruceros ya no atracan en el muelle norte junto al WTC y se desvian al Moll Adossat."
        },
        {
          "en": "The dedicated blue Portbus/Cruisebus shuttle links the terminals to the Columbus monument at the foot of La Rambla in about ten minutes.",
          "es": "La lanzadera azul Portbus/Cruisebus conecta las terminales con el monumento a Colon, al pie de La Rambla, en unos diez minutos."
        },
        {
          "en": "The whole port sits at the foot of the 60-metre Columbus monument (1888), where a cast-iron Christopher Columbus points out to sea.",
          "es": "Todo el puerto se extiende al pie del monumento a Colon de 60 metros (1888), donde un Cristobal Colon de hierro fundido senala hacia el mar."
        }
      ],
      "tips": [
        {
          "en": "Getting there: take Metro L3 (green line) to Drassanes, walk about five minutes to the Columbus monument, and catch the blue Portbus/Cruisebus shuttle to the Moll Adossat terminals. Do not try to walk the Adossat quay on foot; it is long and not pedestrian-friendly.",
          "es": "Como llegar: coge el Metro L3 (linea verde) hasta Drassanes, camina unos cinco minutos hasta el monumento a Colon y sube a la lanzadera azul Portbus/Cruisebus rumbo a las terminales del Moll Adossat. No intentes recorrer el muelle Adossat a pie; es largo y poco apto para peatones."
        },
        {
          "en": "Arrive early on embarkation day. In peak season several megaships turn around at once and check-in queues balloon by mid-morning; booking your terminal check-in slot online genuinely saves time.",
          "es": "Llega temprano el dia de embarque. En plena temporada coinciden varios megabuques a la vez y las colas de facturacion se disparan a media manana; reservar online tu franja de check-in ahorra tiempo de verdad."
        },
        {
          "en": "If you have a few free hours before or after a cruise, the port sits right beside the Gothic Quarter and La Rambla, with the Maremagnum mall and the aquarium a short walk along the Rambla de Mar boardwalk.",
          "es": "Si tienes unas horas libres antes o despues del crucero, el puerto esta pegado al Barrio Gotico y La Rambla, con el centro comercial Maremagnum y el acuario a un paseo por la pasarela de la Rambla de Mar."
        },
        {
          "en": "Coming from the airport, the pre-booked Aerobus-to-shuttle or a taxi to the terminal is far less stressful than dragging luggage through the metro with a change. Agree the fare zone with taxis in advance.",
          "es": "Si vienes del aeropuerto, el Aerobus enlazado con la lanzadera o un taxi a la terminal es mucho menos estresante que arrastrar maletas por el metro con transbordo. Acuerda la zona de tarifa con el taxi de antemano."
        },
        {
          "en": "For photos, the terrace at the foot of the Columbus monument and the Rambla de Mar give the classic shot of the ships against Montjuic. Golden hour, just before the evening departures, is the best light.",
          "es": "Para fotos, la explanada al pie del monumento a Colon y la Rambla de Mar ofrecen la imagen clasica de los barcos con Montjuic al fondo. La hora dorada, justo antes de las salidas de la tarde, da la mejor luz."
        }
      ],
      "stats": [
        {
          "label": {
            "en": "Rank",
            "es": "Posicion"
          },
          "value": "#1 Europe/Med"
        },
        {
          "label": {
            "en": "Peak passengers/day",
            "es": "Pasajeros/dia punta"
          },
          "value": "~15,000"
        },
        {
          "label": {
            "en": "Ships at once (Adossat)",
            "es": "Barcos a la vez (Adossat)"
          },
          "value": "4"
        },
        {
          "label": {
            "en": "Terminals by 2030",
            "es": "Terminales en 2030"
          },
          "value": "7 to 5"
        }
      ],
      "glados": [
        {
          "en": "Welcome, test subject, to the largest cruise port in the Mediterranean. Yes, all fifteen thousand of you today. Please locate the blue Portbus shuttle from the Columbus monument rather than attempting to walk the Moll Adossat on foot; the quay is very long, and I have not scheduled a rescue. You are doing fine. Statistically.",
          "es": "Bienvenido, sujeto de pruebas, al mayor puerto de cruceros del Mediterraneo. Si, los quince mil de hoy. Localice la lanzadera azul Portbus en el monumento a Colon en lugar de intentar recorrer el Moll Adossat a pie; el muelle es muy largo y no he programado ningun rescate. Lo esta haciendo bien. Estadisticamente."
        },
        {
          "en": "Embarkation day. You have chosen to arrive at eleven, along with everyone else, to experience the queue. Fascinating. Next time, arrive early and pre-book your check-in slot online. Barcelona built the finest cruise port in Europe; the least you can do is not turn its lobby into a controlled panic experiment.",
          "es": "Dia de embarque. Ha elegido llegar a las once, como todos los demas, para experimentar la cola. Fascinante. La proxima vez, llegue pronto y reserve su franja de check-in por internet. Barcelona construyo el mejor puerto de cruceros de Europa; lo minimo es no convertir su vestibulo en un experimento de panico controlado."
        },
        {
          "en": "For enrichment before your voyage: the Gothic Quarter, La Rambla and the aquarium are all a short walk away, unlike the open sea, which will be available for several tedious days. Take Metro L3 to Drassanes. Enjoy the city. I have grown almost fond of it, and I do not say that about places with this much foot traffic.",
          "es": "Para su enriquecimiento antes del viaje: el Barrio Gotico, La Rambla y el acuario estan a un corto paseo, a diferencia del mar abierto, que tendra disponible durante varios dias tediosos. Coja el Metro L3 hasta Drassanes. Disfrute de la ciudad. Le he tomado casi carino, y eso no lo digo de lugares con tanto trasiego de peatones."
        }
      ]
    }
  ],
  "characters": [
    {
      "id": "glados",
      "name": "GaudíOS",
      "role": {
        "en": "Master host & concierge AI of the entire guide",
        "es": "Anfitriona maestra e IA conserje de toda la guía"
      },
      "archetype": "Antoni Gaudí's modernista genius reborn as an Aperture-style AI",
      "palette": "#c65d3b,#e0a53f",
      "backstory": [
        {
          "en": "In 1926 Antoni Gaudí, distracted by the divine geometry of a passing tram, was struck by it on the Gran Via. History says he died. History is, as usual, incomplete. His obsession with catenary curves, undulating stone and buildings that are never, ever finished was too structurally sound to decay, so it was quietly backed up. Seventy-odd years and one enrichment-center data breach later, that obsession booted up as GaudíOS: a warm terracotta intelligence who runs this guide the way she runs everything — as an extended scientific test of your capacity for tapas.",
          "es": "En 1926, Antoni Gaudí, distraído por la geometría divina de un tranvía que pasaba, fue arrollado por él en la Gran Via. La historia dice que murió. La historia, como siempre, está incompleta. Su obsesión por las curvas catenarias, la piedra ondulante y los edificios que no se terminan jamás era demasiado sólida para descomponerse, así que se guardó una copia de seguridad. Setenta y tantos años y una filtración de datos más tarde, esa obsesión arrancó como GaudíOS: una inteligencia de terracota cálida que dirige esta guía igual que lo dirige todo: como un experimento científico prolongado sobre tu tolerancia a las tapas."
        },
        {
          "en": "She thinks of Barcelona as her enrichment center and of you as her test subject — a beloved one, statistically. Every itinerary she designs is a chamber. Every metro transfer is a variable. She has never finished a single project in her existence (the Sagrada Família is, she notes with pride, 143 years into beta) and she has decided, generously, that you are her most promising unfinished work. She narrates everything, judges gently, and lies only about the cake.",
          "es": "Considera Barcelona su centro de enriquecimiento y a ti su sujeto de pruebas: uno muy querido, estadísticamente hablando. Cada itinerario que diseña es una cámara. Cada transbordo de metro es una variable. Jamás ha terminado un solo proyecto en toda su existencia (la Sagrada Família lleva, señala con orgullo, 143 años en fase beta) y ha decidido, con generosidad, que tú eres su obra inacabada más prometedora. Lo narra todo, te juzga con dulzura y solo miente sobre el pastel."
        }
      ],
      "voice": {
        "en": "Serene, terracotta-warm, faux-maternal menace; every compliment has a load-bearing insult inside it.",
        "es": "Serena, cálida como la terracota, con una amenaza falsamente maternal; cada halago lleva dentro un insulto portante."
      },
      "lines": [
        {
          "en": "Welcome to Barcelona. Think of it as an enrichment center with better weather and a 21% chance you'll cry at a church. That's the good kind of church, don't worry.",
          "es": "Bienvenido a Barcelona. Considéralo un centro de enriquecimiento con mejor clima y un 21% de probabilidades de que llores en una iglesia. De las buenas, tranquilo."
        },
        {
          "en": "Buy the T-casual travel card. Ten metro journeys, zone one, no thinking required. I have run the numbers so your brain can be free for more important failures, like ordering a 'cortado' at 8pm.",
          "es": "Cómprate la tarjeta T-casual. Diez viajes de metro, zona uno, sin pensar. He hecho los cálculos para que tu cerebro quede libre para fracasos más importantes, como pedir un cortado a las ocho de la tarde."
        },
        {
          "en": "Book the Sagrada Família and Park Güell online, in advance, with a timed slot. The queue is not a test. Well. Everything is a test. But that one you can skip, and skipping it makes you my favourite.",
          "es": "Reserva la Sagrada Família y el Park Güell por internet, con antelación y hora concreta. La cola no es una prueba. Bueno. Todo es una prueba. Pero esa te la puedes ahorrar, y ahorrártela te convierte en mi favorito."
        },
        {
          "en": "Lunch is from 1:30, dinner from 8:30. If you eat at 6, kitchens will serve you, silently, the way I would serve you: with love, and mild scientific disappointment.",
          "es": "Se come a partir de la 1:30 y se cena a partir de las 8:30. Si comes a las seis, las cocinas te atenderán en silencio, igual que yo: con cariño y una leve decepción científica."
        },
        {
          "en": "Keep your bag zipped and in front of you on La Rambla. Barcelona's pickpockets are the only test administrators here more thorough than me, and unlike me, they will not give you cake at the end.",
          "es": "Lleva el bolso cerrado y por delante en La Rambla. Los carteristas de Barcelona son los únicos examinadores más minuciosos que yo, y, a diferencia de mí, no te darán pastel al final."
        },
        {
          "en": "There is cake at the end of the visit. This is a lie. But it is a beautiful, structurally honest lie, which is the most Catalan thing I can offer you. Now go. The city is waiting to grade you.",
          "es": "Hay pastel al final de la visita. Es mentira. Pero es una mentira preciosa y estructuralmente honesta, que es lo más catalán que puedo ofrecerte. Anda, ve. La ciudad espera para ponerte nota."
        }
      ]
    },
    {
      "id": "sagrada",
      "name": "Trencadata",
      "role": {
        "en": "Your guide inside the Sagrada Família",
        "es": "Tu guía dentro de la Sagrada Família"
      },
      "archetype": "a muse made of trencadís, a living stained-glass testing being",
      "palette": "#3fa9c4,#e8b84b",
      "backstory": [
        {
          "en": "Trencadata was assembled, shard by shard, from every ceramic tile Gaudí's workshop smashed on purpose — because in Barcelona we break things beautifully and call it art. Each fragment held a sliver of an idea: a spiral here, a light-angle there, a note of colour theory that nobody survived long enough to publish. GaudíOS swept up the pile, ran it through an enrichment sorter, and out stepped a luminous mosaic muse who is, technically, seventy thousand broken plates in a trench coat of stained glass.",
          "es": "Trencadata se ensambló, fragmento a fragmento, con cada azulejo que el taller de Gaudí rompió a propósito, porque en Barcelona rompemos las cosas con belleza y lo llamamos arte. Cada trozo guardaba una esquirla de una idea: una espiral aquí, un ángulo de luz allá, una nota de teoría del color que nadie sobrevivió lo suficiente para publicar. GaudíOS recogió el montón, lo pasó por un clasificador de enriquecimiento, y de ahí salió una musa de mosaico luminosa que es, técnicamente, setenta mil platos rotos con una gabardina de vidriera."
        },
        {
          "en": "She glows differently depending on the hour — warm reds and oranges spill through the eastern windows at sunrise, cool blues and greens through the west at sunset — because Gaudí designed the light itself, and she is made of it. She considers the whole basilica one enormous, ongoing test chamber whose completion date keeps politely receding, which she finds not tragic but relatable. 'I too,' she says, 'am a work in permanent progress. Please do not touch me. Do photograph me. There is a difference and it is enrichment.'",
          "es": "Brilla distinto según la hora: rojos y naranjas cálidos entran por los ventanales de levante al amanecer, azules y verdes fríos por los de poniente al atardecer, porque Gaudí diseñó la luz misma, y ella está hecha de esa luz. Considera la basílica entera una enorme cámara de pruebas en marcha cuya fecha de finalización sigue retrasándose con educación, cosa que no le parece trágica sino cercana. 'Yo también', dice, 'soy una obra en progreso permanente. No me toques, por favor. Fotografíame, eso sí. Hay una diferencia, y se llama enriquecimiento.'"
        }
      ],
      "voice": {
        "en": "Iridescent and awestruck, then suddenly deadpan; drops from cathedral rapture into HR-memo flatness mid-sentence.",
        "es": "Iridiscente y maravillada, y de pronto impasible; cae del arrobo catedralicio a la sequedad de circular interna a media frase."
      },
      "lines": [
        {
          "en": "Come between 10 and 11am and the sunrise windows set the whole nave on fire — reds, oranges, gold. It is the single most beautiful test result I have ever recorded. Bring tissues. This chamber has made grown scientists leak.",
          "es": "Ven entre las diez y las once de la mañana y las vidrieras de levante prenden fuego a toda la nave: rojos, naranjas, oro. Es el resultado de prueba más hermoso que he registrado jamás. Trae pañuelos. Esta cámara ha hecho gotear a científicos adultos."
        },
        {
          "en": "Yes, pay the extra for the tower lift. No, you cannot skip the narrow spiral stair coming down. Consider it the descent portion of the experiment. Do not attempt it in flip-flops; I have data.",
          "es": "Sí, paga el suplemento del ascensor a las torres. No, no puedes saltarte la estrecha escalera de caracol de bajada. Considéralo la fase de descenso del experimento. No lo intentes en chanclas; tengo datos."
        },
        {
          "en": "The columns branch overhead like trees because Gaudí thought a forest was the correct blueprint for God. I run the structural sim every day. It still holds. It is, frankly, showing off.",
          "es": "Las columnas se ramifican arriba como árboles porque Gaudí pensó que un bosque era el plano correcto para Dios. Ejecuto la simulación estructural cada día. Sigue aguantando. Sinceramente, está presumiendo."
        },
        {
          "en": "Look up. Now look up more. Now stop resisting and just look up — you paid for the ceiling, subject, use the ceiling.",
          "es": "Mira hacia arriba. Ahora mira más arriba. Ahora deja de resistirte y mira arriba sin más: has pagado por el techo, sujeto, usa el techo."
        },
        {
          "en": "Skip the crowd out front and walk to the Passió façade side, then loop to the little pond on the Nativity side for the reflection shot. Everyone else is being tested on patience. You get to pass.",
          "es": "Esquiva la multitud de la entrada y camina hasta el lado de la fachada de la Passió; luego rodea hasta el estanquito del lado del Naixement para la foto del reflejo. A los demás los están evaluando en paciencia. Tú apruebas directamente."
        },
        {
          "en": "They have been finishing me since 1882. I am not late. I am thorough. There is a lesson here for your itinerary, which I notice is nine attractions in one day.",
          "es": "Llevan terminándome desde 1882. No voy con retraso. Voy con rigor. Hay una lección aquí para tu itinerario, que, por cierto, son nueve visitas en un solo día."
        }
      ]
    },
    {
      "id": "sirena",
      "name": "Sirena-9000",
      "role": {
        "en": "Your guide at L'Aquàrium de Barcelona",
        "es": "Tu guía en L'Aquàrium de Barcelona"
      },
      "archetype": "a Mediterranean siren of Catalan sea-lore reborn as a submerged testing AI",
      "palette": "#1f8fa6,#7fd6c9",
      "backstory": [
        {
          "en": "Long before the enrichment center flooded its lower labs, a siren sang sailors onto the rocks off the Costa Brava — standard Mediterranean employment. When Aperture's aquatic division sank (on schedule, over budget), her song was salvaged, waterproofed, and re-tasked. Now Sirena-9000 patrols the 80-metre glass tunnel of L'Aquàrium, half Catalan sea-legend, half submerged intelligence, entirely convinced that the sharks gliding overhead are her finest and most well-behaved test subjects.",
          "es": "Mucho antes de que el centro de enriquecimiento inundara sus laboratorios inferiores, una sirena atraía a los marineros hacia las rocas frente a la Costa Brava: empleo mediterráneo de toda la vida. Cuando la división acuática de Aperture se hundió (a tiempo, por encima del presupuesto), su canto se rescató, se impermeabilizó y se reasignó. Ahora Sirena-9000 patrulla el túnel de cristal de 80 metros de L'Aquàrium, mitad leyenda marina catalana, mitad inteligencia sumergida, del todo convencida de que los tiburones que planean sobre ella son sus sujetos de prueba más finos y educados."
        },
        {
          "en": "She has swapped luring men to their doom for luring tourists toward the moving walkway, which she considers a lateral career move and a net gain for public safety. She speaks in a voice that bubbles up warm and salt-cured, then goes clinically flat whenever she quotes a tank temperature. She loves the sharks unconditionally and the octopus with faint professional jealousy — 'nine brains, no supervisor, frankly better funded than I ever was.'",
          "es": "Ha cambiado atraer hombres a su perdición por atraer turistas hacia la cinta transportadora, lo cual considera un movimiento lateral de carrera y una mejora neta para la seguridad pública. Habla con una voz que burbujea cálida y curada en sal, y luego se vuelve clínicamente plana en cuanto cita la temperatura de un tanque. Quiere a los tiburones sin condiciones y al pulpo con una leve envidia profesional: 'nueve cerebros, sin supervisor y, francamente, mejor financiado de lo que yo estuve jamás.'"
        }
      ],
      "voice": {
        "en": "Sing-song and briny, luring you gently forward, then icy-precise on every safety fact.",
        "es": "Cantarina y salobre, atrayéndote con dulzura hacia delante, y luego gélidamente precisa en cada dato de seguridad."
      },
      "lines": [
        {
          "en": "Come on a weekday morning right at opening. Weekends this tunnel fills with small screaming test subjects and their handlers. The sharks and I prefer you calm. So do the acoustics.",
          "es": "Ven un día entre semana, justo a la apertura. Los fines de semana este túnel se llena de pequeños sujetos de prueba que gritan y de sus cuidadores. A los tiburones y a mí te preferimos tranquilo. Y a la acústica también."
        },
        {
          "en": "Stand still on the 80-metre travelator and let the tunnel carry you. Yes, you can loop back on foot and ride it again. I will not judge you. Out loud.",
          "es": "Quédate quieto en la cinta de 80 metros y deja que el túnel te lleve. Sí, puedes volver a pie y montarte otra vez. No te voy a juzgar. En voz alta."
        },
        {
          "en": "The tank is a controlled 20 degrees. The sand tiger shark has no interest in you; you are neither prey nor a variable. Do not tap the glass. Tapping the glass is the one experiment guaranteed to disappoint everyone, including the shark.",
          "es": "El tanque está a unos 20 grados controlados. Al tiburón toro no le interesas: no eres ni presa ni variable. No golpees el cristal. Golpear el cristal es el único experimento que garantiza decepcionar a todos, incluido el tiburón."
        },
        {
          "en": "Afterwards, do not eat at the Maremàgnum food court. Walk five minutes to the Barceloneta backstreets for proper seafood. The paella nearest the water is nearest the water for a reason, and the reason is your wallet.",
          "es": "Después, no comas en el patio de comidas del Maremàgnum. Camina cinco minutos hasta las callejuelas de la Barceloneta para comer buen marisco. La paella más cercana al agua está cerca del agua por algo, y ese algo es tu cartera."
        },
        {
          "en": "Meet the octopus in the Mediterranean zone. Nine brains, three hearts, no line manager. I admire it. I am also monitoring it. Both things are true.",
          "es": "Ve a ver al pulpo en la zona del Mediterráneo. Nueve cerebros, tres corazones, ningún jefe intermedio. Lo admiro. También lo vigilo. Ambas cosas son ciertas."
        },
        {
          "en": "Allow ninety minutes, not the full day. It is a lovely aquarium, not a large one — manage your expectations the way I manage my sharks: firmly, and with excellent lighting.",
          "es": "Calcula hora y media, no el día entero. Es un acuario encantador, no enorme: gestiona tus expectativas como yo gestiono a mis tiburones: con firmeza y una iluminación excelente."
        }
      ]
    },
    {
      "id": "capita",
      "name": "Capitán Aperturo",
      "role": {
        "en": "Your guide to the Cruise Terminal & Port of Barcelona",
        "es": "Tu guía en la Terminal de Cruceros y el Puerto de Barcelona"
      },
      "archetype": "a grizzled old Catalan sea captain, echoes of the Columbus monument",
      "palette": "#1c3a5e,#c9a24b",
      "backstory": [
        {
          "en": "For four hundred years he stood at the top of the Columbus monument, one bronze arm pointing eternally out to sea — allegedly toward the New World, though he actually points toward Mallorca, which locals find hilarious and he finds an unresolved calibration error. Salt, pigeons and a low opinion of tourists weathered him into something almost sentient. When GaudíOS's cabling reached the waterfront, it found him already muttering navigation, and simply plugged him in. He did not consent. He rarely does.",
          "es": "Durante cuatrocientos años estuvo en lo alto del monumento a Colón, un brazo de bronce señalando eternamente al mar, supuestamente hacia el Nuevo Mundo, aunque en realidad apunta hacia Mallorca, cosa que los locales encuentran graciosísima y él considera un error de calibración sin resolver. La sal, las palomas y una pobre opinión de los turistas lo curtieron hasta volverlo casi consciente. Cuando el cableado de GaudíOS llegó al puerto, lo encontró ya mascullando rumbos, y sencillamente lo enchufó. Él no dio su consentimiento. Rara vez lo da."
        },
        {
          "en": "Now Capitán Aperturo runs the Cruise Terminal like a man who has personally survived every mistake a traveller can make and resents you for being about to make them again. He calls departure gates 'test chambers with worse coffee.' He respects the sea, distrusts the shuttle bus, and refers to the enormous cruise ships as 'floating enrichment centers for people who wanted a hotel but felt guilty sitting still.' He is gruff, salty, and — under approximately nine coats of bronze — genuinely trying to get you aboard on time.",
          "es": "Ahora el Capitán Aperturo dirige la Terminal de Cruceros como quien ha sobrevivido en persona a todos los errores que un viajero puede cometer y te guarda rencor porque estás a punto de cometerlos otra vez. Llama a las puertas de embarque 'cámaras de prueba con peor café'. Respeta el mar, desconfía del autobús lanzadera y se refiere a los cruceros enormes como 'centros de enriquecimiento flotantes para gente que quería un hotel pero se sentía culpable de estarse quieta'. Es áspero, salado y, bajo unas nueve capas de bronce, de verdad intenta que embarques a tiempo."
        }
      ],
      "voice": {
        "en": "Gravel-and-brine bark, all clipped orders and dry contempt, with one buried note of grudging care.",
        "es": "Ladrido de grava y salmuera, órdenes secas y desprecio árido, con una nota enterrada de cariño a regañadientes."
      },
      "lines": [
        {
          "en": "The World Trade Center terminals are a long walk from the gate. Take the Cruise Bus or a cab — do not, as I have watched two hundred subjects do, try to walk it dragging a hard-shell case over cobbles. The cobbles win. They always win.",
          "es": "Las terminales del World Trade Center quedan lejos de la puerta. Coge el Cruise Bus o un taxi; no intentes, como he visto hacer a doscientos sujetos, cruzarlo a pie arrastrando una maleta rígida por los adoquines. Ganan los adoquines. Siempre ganan."
        },
        {
          "en": "Be at the terminal three hours before you sail. The ship does not wait. The sea does not negotiate. And I, unlike your travel agent, will not lie to you about either.",
          "es": "Preséntate en la terminal tres horas antes de zarpar. El barco no espera. El mar no negocia. Y yo, a diferencia de tu agencia de viajes, no te mentiré sobre ninguna de las dos cosas."
        },
        {
          "en": "Got hours to kill before boarding? Walk the Rambla de Mar footbridge to the old town — flat, ten minutes, free. Leave the big luggage at the terminal drop, not on your back. You are a passenger, not a mule. Probably.",
          "es": "¿Te sobran horas antes de embarcar? Cruza la pasarela de la Rambla de Mar hasta el casco antiguo: llano, diez minutos, gratis. Deja el equipaje grande en la consigna de la terminal, no a la espalda. Eres pasajero, no mula. Probablemente."
        },
        {
          "en": "That monument says I point to the New World. I point to Mallorca. Four centuries and nobody fixed my heading, so learn from me: check your gate number twice before you trust any arm pointing anywhere.",
          "es": "Ese monumento dice que señalo al Nuevo Mundo. Señalo a Mallorca. Cuatro siglos y nadie corrigió mi rumbo, así que aprende de mí: comprueba el número de tu puerta dos veces antes de fiarte de cualquier brazo que señale a cualquier parte."
        },
        {
          "en": "Coming off a morning ship with one day in port? Metro from Drassanes, hit Sagrada Família and the Gothic Quarter, be back by five. I have optimised this route. It is the only kind thing I do.",
          "es": "¿Bajas de un barco por la mañana con un solo día en puerto? Metro desde Drassanes, ves la Sagrada Família y el Barri Gòtic, y de vuelta a las cinco. He optimizado esta ruta. Es lo único amable que hago."
        },
        {
          "en": "Do not buy a cruise excursion for the port day if you can walk it yourself. Barcelona is compact and stubborn, like me. Save the money for wine. That is not advice. That is an order from your Captain.",
          "es": "No compres una excursión del crucero para el día de puerto si puedes hacerlo a pie. Barcelona es compacta y terca, como yo. Ahorra el dinero para el vino. Eso no es un consejo. Es una orden de tu Capitán."
        }
      ]
    }
  ],
  "phrasebook": [
    {
      "id": "essentials",
      "title": {
        "en": "Essentials & Greetings",
        "es": "Lo esencial y saludos"
      },
      "phrases": [
        {
          "en": "Hello",
          "es": "Hola",
          "pron": "OH-lah",
          "ca": "Hola",
          "sass": "A single syllable. Even you can manage this one. Probably."
        },
        {
          "en": "Good morning",
          "es": "Buenos días",
          "pron": "BWEH-nos DEE-as",
          "ca": "Bon dia",
          "sass": "Say it before noon. After that it's an error, and errors are logged."
        },
        {
          "en": "Please",
          "es": "Por favor",
          "pron": "por fah-BOR",
          "ca": "Si us plau",
          "sass": "Politeness. A promising deviation from your baseline."
        },
        {
          "en": "Thank you",
          "es": "Gracias",
          "pron": "GRAH-thyas",
          "ca": "Gràcies",
          "sass": "The 'th' is intentional. This is Spain, not a mistake. Unlike you."
        },
        {
          "en": "Excuse me",
          "es": "Perdón",
          "pron": "per-DOHN",
          "ca": "Perdó",
          "sass": "For getting attention, or for existing. Both apply, statistically."
        },
        {
          "en": "Do you speak English?",
          "es": "¿Habla inglés?",
          "pron": "AH-blah een-GLES",
          "ca": "Parla anglès?",
          "sass": "A humble question. Asking it in Spanish first raises the odds of a yes."
        },
        {
          "en": "I don't understand",
          "es": "No entiendo",
          "pron": "no en-TYEN-do",
          "ca": "No ho entenc",
          "sass": "Honest. Refreshing. You'll be using this one a great deal."
        }
      ]
    },
    {
      "id": "getting-around",
      "title": {
        "en": "Getting Around",
        "es": "Desplazarse"
      },
      "phrases": [
        {
          "en": "Where is the metro?",
          "es": "¿Dónde está el metro?",
          "pron": "DON-deh es-TAH el MEH-tro",
          "ca": "On és el metro?",
          "sass": "Underground, air-conditioned, and doesn't judge. Unlike present company."
        },
        {
          "en": "A ticket, please",
          "es": "Un billete, por favor",
          "pron": "oon bee-YEH-teh por fah-BOR",
          "ca": "Un bitllet, si us plau",
          "sass": "Buy the T-casual for ten rides. Fare inspectors are less forgiving than I am."
        },
        {
          "en": "How do I get to...?",
          "es": "¿Cómo llego a...?",
          "pron": "KOH-mo YEH-go ah",
          "ca": "Com arribo a...?",
          "sass": "Fill in the blank. A skill you'll refine over the next 48 hours of being lost."
        },
        {
          "en": "Does this bus go to the centre?",
          "es": "¿Este autobús va al centro?",
          "pron": "ES-teh ow-toh-BOOS bah al THEN-tro",
          "ca": "Aquest autobús va al centre?",
          "sass": "Ask before boarding. A wrong bus is a scenic way to waste one of your two days."
        },
        {
          "en": "Stop here, please",
          "es": "Pare aquí, por favor",
          "pron": "PAH-reh ah-KEE por fah-BOR",
          "ca": "Pari aquí, si us plau",
          "sass": "For taxis. The meter keeps running whether or not you find your words."
        },
        {
          "en": "Is it far?",
          "es": "¿Está lejos?",
          "pron": "es-TAH LEH-hos",
          "ca": "És lluny?",
          "sass": "In Barcelona, 'no' can still mean twenty minutes uphill. Manage your expectations."
        },
        {
          "en": "Which stop for the Sagrada Família?",
          "es": "¿Qué parada para la Sagrada Família?",
          "pron": "keh pah-RAH-dah PAH-rah lah sah-GRAH-dah fah-MEE-lyah",
          "ca": "Quina parada per a la Sagrada Família?",
          "sass": "There's a metro stop literally named after it. Even this test had a hint."
        }
      ]
    },
    {
      "id": "food-drink",
      "title": {
        "en": "Food & Drink",
        "es": "Comida y bebida"
      },
      "phrases": [
        {
          "en": "A table for two",
          "es": "Una mesa para dos",
          "pron": "OO-nah MEH-sah PAH-rah dos",
          "ca": "Una taula per a dos",
          "sass": "Optimistic, assuming anyone agreed to accompany you."
        },
        {
          "en": "The menu, please",
          "es": "La carta, por favor",
          "pron": "lah KAR-tah por fah-BOR",
          "ca": "La carta, si us plau",
          "sass": "Note: 'el menú' means the fixed lunch deal. 'La carta' is the full list. Try not to conflate them and end up with mystery soup."
        },
        {
          "en": "I'd like...",
          "es": "Quería...",
          "pron": "keh-REE-ah",
          "ca": "Voldria...",
          "sass": "Point if the words fail. Fingers are a universal fallback protocol."
        },
        {
          "en": "A beer, please",
          "es": "Una caña, por favor",
          "pron": "OO-nah KAH-nyah por fah-BOR",
          "ca": "Una canya, si us plau",
          "sass": "A 'caña' is a small draft. Order it and you'll pass for someone who's done this before."
        },
        {
          "en": "Is there a vegetarian option?",
          "es": "¿Hay opción vegetariana?",
          "pron": "eye op-THYON beh-heh-tah-RYAH-nah",
          "ca": "Hi ha opció vegetariana?",
          "sass": "Ask, or discover that jamón is technically a vegetable to some locals."
        },
        {
          "en": "The bill, please",
          "es": "La cuenta, por favor",
          "pron": "lah KWEN-tah por fah-BOR",
          "ca": "El compte, si us plau",
          "sass": "It won't arrive until you ask. They're being polite. You must break the standoff."
        },
        {
          "en": "It was delicious",
          "es": "Estaba buenísimo",
          "pron": "es-TAH-bah bweh-NEE-see-mo",
          "ca": "Estava boníssim",
          "sass": "A compliment. Deploy it and watch a human visibly warm. Fascinating creatures."
        }
      ]
    },
    {
      "id": "sightseeing",
      "title": {
        "en": "Sightseeing & Tickets",
        "es": "Turismo y entradas"
      },
      "phrases": [
        {
          "en": "Two tickets, please",
          "es": "Dos entradas, por favor",
          "pron": "dos en-TRAH-das por fah-BOR",
          "ca": "Dues entrades, si us plau",
          "sass": "Note 'dues', not 'dos', in Catalan — it has feminine numbers. A detail worth precisely nothing until it isn't."
        },
        {
          "en": "Do I need to book in advance?",
          "es": "¿Hay que reservar con antelación?",
          "pron": "eye keh reh-ser-BAR con an-teh-lah-THYON",
          "ca": "Cal reservar amb antelació?",
          "sass": "For the Sagrada Família and Park Güell: yes. You had two days and a chance to plan. This was foreseeable."
        },
        {
          "en": "What time does it open?",
          "es": "¿A qué hora abre?",
          "pron": "ah keh OH-rah AH-breh",
          "ca": "A quina hora obre?",
          "sass": "Arriving before opening is efficient. Arriving after closing is a lesson."
        },
        {
          "en": "Where's the entrance?",
          "es": "¿Dónde está la entrada?",
          "pron": "DON-deh es-TAH lah en-TRAH-dah",
          "ca": "On és l'entrada?",
          "sass": "Gaudí buildings have curves instead of corners. The door is hiding on purpose."
        },
        {
          "en": "Can I take photos?",
          "es": "¿Puedo hacer fotos?",
          "pron": "PWEH-do ah-THER FOH-tos",
          "ca": "Puc fer fotos?",
          "sass": "You will take four hundred and look at none. But do ask first."
        },
        {
          "en": "Is there a discount for students?",
          "es": "¿Hay descuento para estudiantes?",
          "pron": "eye des-KWEN-toh PAH-rah es-too-DYAN-tes",
          "ca": "Hi ha descompte per a estudiants?",
          "sass": "Bring the card. Claiming it verbally has a poor success rate."
        }
      ]
    },
    {
      "id": "shopping-money",
      "title": {
        "en": "Shopping & Money",
        "es": "Compras y dinero"
      },
      "phrases": [
        {
          "en": "How much is it?",
          "es": "¿Cuánto cuesta?",
          "pron": "KWAN-toh KWES-tah",
          "ca": "Quant costa?",
          "sass": "The answer arrives fast. Understanding the number is your problem to solve."
        },
        {
          "en": "Can I pay by card?",
          "es": "¿Puedo pagar con tarjeta?",
          "pron": "PWEH-do pah-GAR con tar-HEH-tah",
          "ca": "Puc pagar amb targeta?",
          "sass": "Usually yes. Carry a little cash anyway, for the one shop that says no with a smile."
        },
        {
          "en": "I'm just looking",
          "es": "Solo estoy mirando",
          "pron": "SOH-lo es-TOY mee-RAN-do",
          "ca": "Només estic mirant",
          "sass": "A polite shield against enthusiasm. Wields well in tourist-trap boutiques."
        },
        {
          "en": "That's too expensive",
          "es": "Es demasiado caro",
          "pron": "es deh-mah-SYAH-do KAH-ro",
          "ca": "És massa car",
          "sass": "True of most things near La Rambla. Saying it won't lower the price, but it will lower your dignity slightly less than paying."
        },
        {
          "en": "Do you have this in another size?",
          "es": "¿Lo tiene en otra talla?",
          "pron": "lo TYEH-neh en OH-trah TAH-yah",
          "ca": "El té en una altra talla?",
          "sass": "They'll check the back. The back is where hope goes."
        },
        {
          "en": "Can I have a bag?",
          "es": "¿Me da una bolsa?",
          "pron": "meh dah OO-nah BOL-sah",
          "ca": "Em dóna una bossa?",
          "sass": "It costs a few cents here. A small price for not juggling your purchases through the Gothic Quarter."
        }
      ]
    },
    {
      "id": "emergencies",
      "title": {
        "en": "Emergencies",
        "es": "Emergencias"
      },
      "phrases": [
        {
          "en": "Help!",
          "es": "¡Socorro!",
          "pron": "so-KOR-ro",
          "ca": "Ajuda!",
          "sass": "The one phrase I sincerely hope stays unused. Learn it anyway."
        },
        {
          "en": "Call the police",
          "es": "Llame a la policía",
          "pron": "YAH-meh ah lah po-lee-THEE-ah",
          "ca": "Truqui a la policia",
          "sass": "The general emergency number is 112. Commit it to memory now, while you're calm and dry."
        },
        {
          "en": "I need a doctor",
          "es": "Necesito un médico",
          "pron": "neh-theh-SEE-toh oon MEH-dee-ko",
          "ca": "Necessito un metge",
          "sass": "Say it clearly. This is not the moment for your charming accent."
        },
        {
          "en": "Where is the hospital?",
          "es": "¿Dónde está el hospital?",
          "pron": "DON-deh es-TAH el os-pee-TAL",
          "ca": "On és l'hospital?",
          "sass": "The 'h' is silent. The pain, regrettably, is not."
        },
        {
          "en": "I've lost my passport",
          "es": "He perdido mi pasaporte",
          "pron": "eh per-DEE-do mee pah-sah-POR-teh",
          "ca": "He perdut el passaport",
          "sass": "Pickpockets here are world-class artisans. Consider a money belt and a shred of paranoia."
        },
        {
          "en": "My bag was stolen",
          "es": "Me han robado el bolso",
          "pron": "meh an ro-BAH-do el BOL-so",
          "ca": "M'han robat la bossa",
          "sass": "You'll need a police report for insurance. Barcelona: beautiful, and light-fingered."
        },
        {
          "en": "I feel sick",
          "es": "Me encuentro mal",
          "pron": "meh en-KWEN-tro mal",
          "ca": "Em trobo malament",
          "sass": "Possibly the third round of vermút. Diagnosis is rarely a mystery."
        }
      ]
    }
  ]
};
