// ============================================================
// mos-6502 — the words and the worked examples
// ------------------------------------------------------------
// Everything the page says that is not produced by running the
// emulator lives here: the history, the machines, the per-mode
// walkthroughs, the quirk demonstrations and the source ledger.
//
// The quirk demonstrations are source code, not prose about source
// code. The page assembles and runs each one in front of you and
// prints what actually happened, so if the emulator were wrong the
// claims would visibly fail rather than quietly stand.
// ============================================================
(function (global) {
  "use strict";

  // ---------------------------------------------------------------
  // How it came to exist
  // ---------------------------------------------------------------
  const HISTORY = [
    {
      year: "1974",
      title: "A processor costs more than the computer around it",
      where: "Motorola, Phoenix",
      summary: "Motorola's MC6800 was a good design sold at a price that kept it out of the products Chuck Peddle was hearing about from customers. Intel's 8080 cost about the same. A microprocessor was a component you budgeted for like a car engine — around $179 in 1975 money, before any memory, any support chips, any board.",
      detail: [
        "Peddle, a Motorola applications engineer, kept meeting customers who wanted the chip and could not justify the price.",
        "His answer was not a better processor. It was a processor stripped of everything a customer was not going to pay for.",
        "Motorola's management told him, in writing, to stop working on it. He kept the letter.",
      ],
      numbers: [["MC6800", "$179"], ["Intel 8080", "$179"], ["Target", "under $30"]],
    },
    {
      year: "Aug 1974",
      title: "Eight people leave, and go to Pennsylvania",
      where: "MOS Technology, Norristown",
      summary: "Peddle and seven colleagues from the 6800 team joined MOS Technology, a calculator-chip maker with something more valuable than a design: a fabrication line whose yields they understood well enough to bet a price on.",
      detail: [
        "Bill Mensch, Rod Orgill, Harry Bawcom, Ray Hirt, Wil Mathys, Mike Janes and Sydney-Anne Holt went with him.",
        "The economics were the design constraint. A smaller die yields more good chips per wafer, and yield — not cleverness — is what sets the price of a chip.",
        "So the register set was cut to the bone: one accumulator, two index registers, an eight-bit stack pointer. What is missing from the 6502 is the product.",
      ],
      numbers: [["Engineers", "8"], ["Registers kept", "3"], ["Registers cut", "most"]],
    },
    {
      year: "16 Sep 1975",
      title: "Sold out of a jar at a trade show",
      where: "WESCON, San Francisco",
      summary: "WESCON did not allow selling on the show floor, so MOS Technology took a suite at the St. Francis hotel and filled two jars with chips. The 6501 was $20, the 6502 was $25. Both were real, working parts, and everyone assumed they were seconds because nothing that cheap could be new.",
      detail: [
        "The 6501 was pin-compatible with the 6800 so a customer could drop it into an existing board. The 6502 was not, and needed only a crystal — the clock generator was on the die.",
        "The jars were partly theatre. They were also mostly full of good parts, which was the actual claim being made.",
        "A $25 processor changed which products could exist at all. Every 8-bit home computer of the next decade is downstream of that price.",
      ],
      numbers: [["6501", "$20"], ["6502", "$25"], ["Cheaper by", "7x"]],
    },
    {
      year: "1975-76",
      title: "Motorola sues, and MOS gives up the wrong chip",
      where: "The courts",
      summary: "Motorola sued in November 1975 over the 6501's pin compatibility and over trade secrets carried out of Arizona. The settlement cost MOS Technology $200,000 and the 6501, which was withdrawn. The 6502 — the one that needed no external clock, and the one nobody could call a copy — survived.",
      detail: [
        "Losing the drop-in replacement forced customers to design around the 6502 rather than substitute it, which turned out to make the 6502 the platform.",
        "The earliest chips also had a genuine defect: ROR did not work. MOS documented the omission, and the first 6502 data sheets simply do not list the instruction.",
        "It was fixed during 1976. Software written for the earliest machines avoids ROR for that reason.",
      ],
      numbers: [["Settlement", "$200,000"], ["Chips withdrawn", "6501"], ["Missing instruction", "ROR"]],
    },
    {
      year: "1976-77",
      title: "The machines arrive at once",
      where: "Cupertino, Norristown, Sunnyvale",
      summary: "Steve Wozniak had wanted a 6800 and could not afford one; at $25 the Apple I became possible. Within eighteen months the 6502 was in the Apple II, the Commodore PET and the Atari Video Computer System, and Commodore had bought MOS Technology outright.",
      detail: [
        "Commodore acquired MOS Technology in October 1976, so the 6502 was now made by a computer company that also used it.",
        "The Atari VCS used the 6507: the same die in a 28-pin package with 13 address pins brought out, which is why that machine sees only 8K of address space.",
        "Each of these machines put the processor's cheapness directly into the product: less silicon around it, more done in software.",
      ],
      numbers: [["Apple I", "1976"], ["Apple II & PET", "1977"], ["Atari VCS", "1977"]],
    },
    {
      year: "1982-83",
      title: "Tens of millions of them",
      where: "Living rooms",
      summary: "The Commodore 64 used a 6510 — a 6502 with an I/O port bolted to it for bank switching — and became the best-selling computer model ever made. Nintendo's Famicom used a Ricoh 2A03: a 6502 core with the decimal-mode circuitry disabled and a sound generator in its place.",
      detail: [
        "The 2A03's missing decimal mode is a licensing story as much as an engineering one, and it means NES code never uses SED.",
        "The BBC Micro ran a 6502A at 2 MHz, which is why British school software of the era feels quick.",
        "By this point the instruction set was fixed and the culture around it — the tricks, the undocumented opcodes, the cycle counting — was the real asset.",
      ],
      numbers: [["C64 sold", "~12.5M+"], ["NES CPU", "Ricoh 2A03"], ["BBC Micro", "2 MHz"]],
    },
    {
      year: "Now",
      title: "Still shipping, fifty years on",
      where: "Western Design Center, Mesa",
      summary: "Bill Mensch, who drew much of the original layout, founded the Western Design Center and has been making 6502-family parts continuously ever since. The W65C02S is a current, buyable, CMOS part. The architecture has outlived nearly every machine that made it famous.",
      detail: [
        "It survives because it is small enough to be cheap, simple enough to be understood completely, and documented enough that fifty years of accumulated knowledge still applies.",
        "This page is part of that: everything below runs a 6502 in your browser, cycle by cycle, and shows its work.",
      ],
      numbers: [["Introduced", "1975"], ["Still made", "yes"], ["Transistors", "3,510"]],
    },
  ];

  // ---------------------------------------------------------------
  // Where it ended up
  // ---------------------------------------------------------------
  const MACHINES = [
    { name: "Apple I", year: 1976, chip: "6502", mhz: 1.023, note: "Wozniak chose it on price; he had designed for the 6800 and could not afford one." },
    { name: "Commodore PET", year: 1977, chip: "6502", mhz: 1.0, note: "Built by the company that by then owned the chip." },
    { name: "Apple II", year: 1977, chip: "6502", mhz: 1.023, note: "Its video timing and its CPU share one clock, which is why the display is woven into the memory map." },
    { name: "Atari VCS / 2600", year: 1977, chip: "6507", mhz: 1.19, note: "The same die, 28 pins, 13 address lines: 8K of address space and no interrupts." },
    { name: "Atari 400/800", year: 1979, chip: "6502B", mhz: 1.79, note: "Nearly twice the clock, with custom chips stealing cycles for the display." },
    { name: "VIC-20", year: 1980, chip: "6502", mhz: 1.02, note: "The first computer of any kind to sell a million units." },
    { name: "BBC Micro", year: 1981, chip: "6502A", mhz: 2.0, note: "A 2 MHz part, and a generation of British programmers who learned assembler on it." },
    { name: "Commodore 64", year: 1982, chip: "6510", mhz: 0.985, note: "A 6502 with a six-bit I/O port used to bank ROM in and out from software." },
    { name: "NES / Famicom", year: 1983, chip: "Ricoh 2A03", mhz: 1.79, note: "A 6502 with decimal mode removed and an audio unit in its place." },
    { name: "Apple IIc", year: 1984, chip: "65C02", mhz: 1.023, note: "The CMOS revision: new instructions, a fixed indirect JMP, and much less power." },
    { name: "Atari Lynx", year: 1989, chip: "65SC02", mhz: 4, note: "A colour handheld whose custom Mikey chip has a 6502 core inside it, fourteen years after WESCON." },
    { name: "W65C02S", year: "current", chip: "W65C02S", mhz: 14, note: "Still made, still sold, still the same programmer's model." },
  ];

  // ---------------------------------------------------------------
  // The programmer's model
  // ---------------------------------------------------------------
  const REGISTERS = [
    { id: "a", name: "A", full: "Accumulator", bits: 8, blurb: "The only register arithmetic happens in. Every add, subtract, AND, OR and shift of memory goes through A — which is why 6502 code moves values in and out of it constantly." },
    { id: "x", name: "X", full: "Index X", bits: 8, blurb: "An index, a counter, and the only register that can reach the stack pointer. It has modes A and Y do not: (zp,X), and it is the register that indexes zero-page tables." },
    { id: "y", name: "Y", full: "Index Y", bits: 8, blurb: "The other index. Its private mode, (zp),Y, follows a pointer and then adds Y — the natural way to walk an array whose address is not known until run time." },
    { id: "s", name: "S", full: "Stack pointer", bits: 8, blurb: "Eight bits, not sixteen: the stack is always in page one, $0100-$01FF, and S is only the offset within it. 256 bytes, which is 128 nested subroutine calls and no more." },
    { id: "pc", name: "PC", full: "Program counter", bits: 16, blurb: "The only 16-bit register on the chip. Everything else that needs an address has to build it a byte at a time." },
    { id: "p", name: "P", full: "Status", bits: 8, blurb: "Six real flags, one bit that is always 1, and one bit — B — that exists only in the copy pushed onto the stack. There is no B flag inside the processor to set or clear." },
  ];

  const FLAGS = [
    { bit: 7, letter: "N", name: "Negative", blurb: "A copy of bit 7 of the last result. Not a judgement about the number: bit 7 of $F0 is set whether you meant -16 or 240." },
    { bit: 6, letter: "V", name: "Overflow", blurb: "Set when a signed add or subtract produced an answer of the wrong sign. Also loadable straight from bit 6 of memory by BIT, and settable directly by a pin on the chip — the only flag with its own wire." },
    { bit: 5, letter: "-", name: "unused", blurb: "Always reads as 1. There is nothing behind it." },
    { bit: 4, letter: "B", name: "Break", blurb: "Not a flag at all. It exists only in the byte that BRK and PHP push, where it says \"software put me here\". A hardware interrupt pushes it clear." },
    { bit: 3, letter: "D", name: "Decimal", blurb: "Switches ADC and SBC from binary to packed BCD. Nothing else on the chip is affected, and the NES's 6502 has this circuit disabled entirely." },
    { bit: 2, letter: "I", name: "Interrupt disable", blurb: "Holds off the IRQ line. It cannot hold off NMI, which is the entire point of having two interrupt pins." },
    { bit: 1, letter: "Z", name: "Zero", blurb: "The last result was zero. On a compare, that means equal." },
    { bit: 0, letter: "C", name: "Carry", blurb: "Bit 8 of an addition, the borrow-not of a subtraction, and the bit shifted out by a shift. It is also the 6502's only way to join two bytes into a bigger number, which is why CLC before ADC is a reflex." },
  ];

  const MEMORY_MAP = [
    { from: 0x0000, to: 0x00ff, name: "Page zero", blurb: "Addressable in one byte. Every instruction that can use it is one byte shorter and one cycle faster, and it is the only place a pointer can live. On a 6502 machine, page zero is the register file the chip does not have." },
    { from: 0x0100, to: 0x01ff, name: "The stack", blurb: "Fixed in hardware. S indexes into it, it grows downwards, and when it runs off the bottom it wraps silently to the top and starts overwriting." },
    { from: 0x0200, to: 0x05ff, name: "Display (this page)", blurb: "Not a 6502 convention — this simulator's own. 32 x 32 pixels, one byte each, low nibble selects a colour." },
    { from: 0x0600, to: 0xfff9, name: "Yours", blurb: "RAM, ROM and hardware registers, in whatever arrangement the machine's designer chose. The 6502 itself has no opinion: reading an address is reading an address." },
    { from: 0xfffa, to: 0xffff, name: "The vectors", blurb: "Six bytes, three addresses: NMI, RESET, IRQ/BRK. The only addresses the chip knows about before it has executed anything." },
  ];

  // ---------------------------------------------------------------
  // Addressing: one worked example per mode, run live.
  // `setup` is applied to a fresh CPU before the instruction is
  // stepped, so the trace the page shows is the trace that happened.
  // ---------------------------------------------------------------
  const ADDRESSING = [
    { mode: "imp", sample: "INX", setup: { x: 0x41 },
      why: "Nothing to address. The second cycle still happens — the 6502 always fetches the byte after an opcode, then throws it away if there was no operand.",
      cost: "2 cycles, 1 byte" },
    { mode: "acc", sample: "ASL A", setup: { a: 0x81 },
      why: "The accumulator is the operand. No memory cycle at all, which makes this the cheapest shift on the chip.",
      cost: "2 cycles, 1 byte" },
    { mode: "imm", sample: "LDA #$41", setup: {},
      why: "The value is in the instruction. Use it for constants; you cannot use it to write, because there is nowhere to write to.",
      cost: "2 cycles, 2 bytes" },
    { mode: "zp", sample: "LDA $30", setup: { mem: { 0x0030: 0x7f } },
      why: "One address byte instead of two. A byte saved and a cycle saved on every access is why 6502 programs keep their working set in page zero.",
      cost: "3 cycles, 2 bytes" },
    { mode: "zpx", sample: "LDA $F0,X", setup: { x: 0x20, mem: { 0x0010: 0x99, 0x0110: 0xee } },
      why: "A table lookup inside page zero. Note the wrap: $F0 + $20 is $10, not $0110. The high byte is never computed, so it can never carry.",
      cost: "4 cycles, 2 bytes" },
    { mode: "zpy", sample: "LDX $F0,Y", setup: { y: 0x05, mem: { 0x00f5: 0x2a } },
      why: "The same thing with Y, and only LDX and STX have it. The 6502's mode table is full of small asymmetries like this one.",
      cost: "4 cycles, 2 bytes" },
    { mode: "abs", sample: "LDA $2000", setup: { mem: { 0x2000: 0x5c } },
      why: "Any address in the 64K, spelled low byte first. Little-endian is not a style choice here: it lets the chip start adding an index to the low byte before the high byte has even arrived.",
      cost: "4 cycles, 3 bytes" },
    { mode: "abx", sample: "LDA $20F0,X", setup: { x: 0x20, mem: { 0x2110: 0x3d } },
      why: "An array anywhere in memory. Watch the fourth cycle read $2010 — the wrong address — because the carry out of the low byte is not known yet. That wasted cycle is the famous page-crossing penalty.",
      cost: "4 cycles, +1 if the index crosses a page" },
    { mode: "aby", sample: "LDA $2000,Y", setup: { y: 0x04, mem: { 0x2004: 0x71 } },
      why: "The same, with Y. Here nothing crosses a page, so there is no extra cycle and no wasted read.",
      cost: "4 cycles, +1 if the index crosses a page" },
    { mode: "ind", sample: "JMP ($30FF)", setup: { mem: { 0x30ff: 0x00, 0x3000: 0x80, 0x3100: 0x40 } },
      why: "The only instruction with this mode, and the one with the most famous bug on the chip: the pointer's high byte is fetched from the same page as its low byte, so ($30FF) reads $30FF and $3000. This jumps to $8000, not $4000.",
      cost: "5 cycles, 3 bytes" },
    { mode: "izx", sample: "LDA ($20,X)", setup: { x: 0x04, mem: { 0x0024: 0x00, 0x0025: 0x21, 0x2100: 0x6b } },
      why: "Index a table of pointers, then follow the one you land on. X selects which pointer; the pointer says where the data is. Rare in practice, and always inside page zero.",
      cost: "6 cycles, 2 bytes" },
    { mode: "izy", sample: "LDA ($20),Y", setup: { y: 0x10, mem: { 0x0020: 0xf0, 0x0021: 0x21, 0x2200: 0x5a } },
      why: "Follow one pointer, then index. This is how you walk an array whose address is only known at run time, and it is the most-used addressing mode in most real 6502 code.",
      cost: "5 cycles, +1 if Y crosses a page" },
    { mode: "rel", sample: "BNE $0610", setup: { z: 0 },
      why: "A signed byte added to the address of the next instruction: -128 to +127. There is no long branch. When a target is out of reach you branch over a JMP instead.",
      cost: "2 cycles, +1 if taken, +2 if the branch leaves the page" },
  ];

  // ---------------------------------------------------------------
  // What each of the 56 instructions does, in one line.
  // ---------------------------------------------------------------
  const INSTRUCTIONS = {
    ADC: "Add memory to A with carry. The only add on the chip — there is no add-without-carry, so CLC first.",
    AND: "Bitwise AND memory into A. With a mask of $0F it keeps the low nibble; with $80 it isolates the sign bit.",
    ASL: "Shift memory or A left one bit: bit 7 falls into carry, a 0 comes in at the bottom. A multiply by two.",
    BCC: "Branch if carry clear — after a compare, if A was below the operand.",
    BCS: "Branch if carry set — after a compare, if A was at or above the operand.",
    BEQ: "Branch if the zero flag is set — after a compare, if the two values were equal.",
    BIT: "AND A with memory for the Z flag only, and copy bits 7 and 6 of memory into N and V. Tests without disturbing A.",
    BMI: "Branch if the negative flag is set — if bit 7 of the last result was 1.",
    BNE: "Branch if the zero flag is clear — after a compare, if the two values differed.",
    BPL: "Branch if the negative flag is clear — if bit 7 of the last result was 0.",
    BRK: "Software interrupt. Pushes PC+2 and the status byte with B set, then jumps through the IRQ vector.",
    BVC: "Branch if the overflow flag is clear: the last signed arithmetic stayed in range.",
    BVS: "Branch if the overflow flag is set: the last signed add or subtract wrapped.",
    CLC: "Clear the carry. The prelude to almost every ADC, because there is no add-without-carry.",
    CLD: "Clear decimal mode. Worth doing at reset; the flag's power-on state is undefined.",
    CLI: "Clear the interrupt disable, letting the IRQ line through again.",
    CLV: "Clear overflow. There is no SEV — only the chip's own SO pin can set V directly.",
    CMP: "Compare A with memory: a subtraction that sets flags and discards the answer.",
    CPX: "Compare X with memory. Flags only, X unchanged — the standard loop terminator.",
    CPY: "Compare Y with memory. Flags only, Y unchanged.",
    DEC: "Decrement a memory location by one. Read, write the old value back, write the new one.",
    DEX: "Decrement X, setting N and Z. Counting down to zero is cheaper than counting up to a limit.",
    DEY: "Decrement Y, setting N and Z.",
    EOR: "Bitwise exclusive-OR into A. EOR #$FF is the 6502's NOT.",
    INC: "Increment a memory location by one.",
    INX: "Increment X, setting N and Z. Wraps from $FF to $00 in silence.",
    INY: "Increment Y, setting N and Z. Wraps from $FF to $00 in silence.",
    JMP: "Jump. Absolute, or through a pointer — and the indirect form has the page-boundary bug.",
    JSR: "Jump to subroutine, pushing the address of its own last byte: the return address minus one.",
    LDA: "Load A from memory, setting N and Z. Available in more addressing modes than any other instruction.",
    LDX: "Load X from memory, setting N and Z.",
    LDY: "Load Y from memory, setting N and Z.",
    LSR: "Shift right one bit; bit 0 goes to carry, bit 7 becomes 0. An unsigned divide by two.",
    NOP: "Do nothing for two cycles. Used to pad timing loops to the exact cycle.",
    ORA: "Bitwise OR memory into A — the usual way to set particular bits while leaving the others alone.",
    PHA: "Push A onto the stack, the only way to save the accumulator without naming somewhere to put it.",
    PHP: "Push the status byte, always with B set.",
    PLA: "Pull A, setting N and Z from what came back.",
    PLP: "Pull the status byte off the stack and install it, restoring every flag at once.",
    ROL: "Rotate left through carry: carry becomes bit 0, bit 7 becomes carry. Nine bits in a circle.",
    ROR: "Rotate right through carry. Missing from the first year's chips, which genuinely did not have it.",
    RTI: "Return from interrupt: pull the status byte and the exact address pushed. No plus one.",
    RTS: "Return from subroutine: pull an address and add one, undoing what JSR did.",
    SBC: "Subtract memory from A with borrow. Carry SET means no borrow, so SEC first.",
    SEC: "Set the carry, which on this chip means no borrow. The prelude to almost every SBC.",
    SED: "Set decimal mode, turning ADC and SBC into packed-BCD arithmetic and nothing else.",
    SEI: "Set the interrupt disable, holding IRQ off. NMI is unaffected — that is what it is for.",
    STA: "Store A to memory. Sets no flags.",
    STX: "Store X to memory. Sets no flags.",
    STY: "Store Y to memory. Sets no flags.",
    TAX: "Transfer A to X, setting N and Z from the value moved.",
    TAY: "Transfer A to Y, setting N and Z from the value moved.",
    TSX: "Transfer the stack pointer to X — the only way to read it.",
    TXA: "Transfer X to A, setting N and Z from the value moved.",
    TXS: "Transfer X to the stack pointer. The one transfer that sets no flags.",
    TYA: "Transfer Y to A, setting N and Z from the value moved.",
    LAX: "Undocumented: load the same byte into A and X at once, setting N and Z from it.",
    SAX: "Undocumented: store A AND X to memory, setting no flags because nothing computed a result.",
    SLO: "Undocumented: ASL memory, then ORA the result into A.",
    RLA: "Undocumented: ROL memory, then AND the result into A.",
    SRE: "Undocumented: LSR memory, then EOR the result into A.",
    RRA: "Undocumented: ROR memory, then ADC the result into A.",
    DCP: "Undocumented: DEC memory, then CMP it against A.",
    ISC: "Undocumented: INC memory, then SBC it from A.",
    ANC: "Undocumented: AND immediate, then copy bit 7 into carry.",
    ALR: "Undocumented: AND immediate, then LSR A.",
    ARR: "Undocumented: AND immediate, then ROR A — with flags out of the adder, not the shifter.",
    SBX: "Undocumented: (A AND X) minus an immediate, into X, with no borrow in.",
    ANE: "Undocumented and unstable: involves an internal bus value that depends on the chip and the temperature.",
    LXA: "Undocumented and unstable: the same magic constant, into both A and X.",
    SHA: "Undocumented and unstable: stores A AND X AND (high byte of address + 1).",
    SHX: "Undocumented and unstable: stores X AND (high byte of address + 1).",
    SHY: "Undocumented and unstable: stores Y AND (high byte of address + 1).",
    TAS: "Undocumented and unstable: sets S to A AND X, then stores like SHA.",
    LAS: "Undocumented and unstable: ANDs memory with S into all of A, X and S.",
    JAM: "Undocumented: stops the processor dead, both clock phases latched. Only RESET brings it back.",
  };

  // ---------------------------------------------------------------
  // The quirks. Each runs on the page's own emulator.
  // `check` is evaluated against the finished machine and must
  // describe what actually happened.
  // ---------------------------------------------------------------
  const QUIRKS = [
    {
      id: "jmp-indirect",
      title: "The indirect jump cannot cross a page",
      lede: "JMP ($xxFF) reads the pointer's low byte from $xxFF and its high byte from $xx00 — the start of the same page, not the start of the next one. The address adder that would carry into the high byte simply is not wired to this path.",
      source: [
        "; a pointer deliberately placed at the last byte of a page",
        "  .org $0600",
        "  LDA #$00",
        "  STA $30FF     ; low byte of the pointer",
        "  LDA #$40",
        "  STA $3100     ; the high byte a sane chip would read",
        "  LDA #$80",
        "  STA $3000     ; the high byte THIS chip reads",
        "  JMP ($30FF)",
      ].join("\n"),
      steps: 7,
      report: (cpu) => `PC is now $${hex4(cpu.pc)} — the pointer bytes came from $30FF and $3000.`,
      expect: (cpu) => cpu.pc === 0x8000,
      moral: "Assemblers will not warn you. The 65C02 fixed it in 1983 — and charged an extra cycle to do so.",
    },
    {
      id: "rmw-double-write",
      title: "Read-modify-write writes twice",
      lede: "INC, DEC, ASL, LSR, ROL and ROR on memory all do the same three bus cycles: read the byte, write the OLD byte back, then write the new one. The processor has nowhere to park a value while the ALU works, so it parks it on the bus.",
      source: [
        "  .org $0600",
        "  LDA #$41",
        "  STA $3000",
        "  INC $3000",
      ].join("\n"),
      steps: 3,
      watchWrites: 0x3000,
      report: (cpu, log) => {
        const hits = log.filter((entry) => entry.addr === 0x3000).map((entry) => `$${hex2(entry.value)}`);
        return `Writes to $3000, in order: ${hits.join(", ")}. The middle one is the dummy.`;
      },
      expect: (cpu, log) => log.filter((entry) => entry.addr === 0x3000).length === 3,
      moral: "Harmless on RAM. On a hardware register that clears itself when written, it fires twice — which is exactly how NES and C64 code acknowledges an interrupt in one instruction.",
    },
    {
      id: "indexed-dummy-read",
      title: "An indexed access reads the wrong address first",
      lede: "The 6502 adds the index to the low byte and reads there immediately, a cycle before it knows whether the high byte needed a carry. If it did, the read went to an address 256 bytes too low — and on real hardware that read really happened.",
      source: [
        "  .org $0600",
        "  LDX #$20",
        "  LDA $20F0,X   ; wanted $2110",
      ].join("\n"),
      steps: 2,
      report: (cpu, log, traces) => {
        const last = traces[traces.length - 1];
        const reads = last.trace.filter((c) => c.rw === "r").map((c) => `$${hex4(c.addr)}`);
        return `Bus reads this instruction: ${reads.join(" → ")}. $2010 was never wanted.`;
      },
      expect: (cpu, log, traces) => traces[traces.length - 1].trace.some((c) => c.addr === 0x2010),
      moral: "On a machine where reading a register has a side effect, an indexed read near a page boundary can trigger it twice. Console programmers keep their tables away from page ends for this reason alone.",
    },
    {
      id: "jsr-minus-one",
      title: "JSR pushes the return address minus one",
      lede: "JSR pushes the address of its own last byte, and RTS adds one on the way back. It is not an off-by-one error: incrementing on the way out would have cost a cycle the designers did not want to spend.",
      source: [
        "  .org $0600",
        "  JSR sub",
        "  BRK",
        "sub:",
        "  TSX           ; look at the stack without disturbing it",
        "  LDA $0101,X   ; low byte of the pushed address",
        "  RTS",
      ].join("\n"),
      steps: 4,
      report: (cpu) => `The pushed low byte is $${hex2(cpu.a)}; the instruction after JSR is at $0603.`,
      expect: (cpu) => cpu.a === 0x02,
      moral: "It buys you a computed jump for free: push an address minus one, execute RTS, and the processor goes there. Every 6502 jump table in existence is built on this.",
    },
    {
      id: "zp-wrap",
      title: "Zero-page indexing can never leave page zero",
      lede: "$F0 indexed by $20 is $10. The high byte of a zero-page address is not computed at all, so there is no carry to propagate and no way out of the page.",
      source: [
        "  .org $0600",
        "  LDA #$99",
        "  STA $0010",
        "  LDA #$EE",
        "  STA $0110",
        "  LDX #$20",
        "  LDA $F0,X",
      ].join("\n"),
      steps: 7,
      report: (cpu) => `A = $${hex2(cpu.a)} — $99 came from $0010, not $EE from $0110.`,
      expect: (cpu) => cpu.a === 0x99,
      moral: "A feature more often than a bug: circular buffers in page zero need no bounds check at all.",
    },
    {
      id: "brk-two-bytes",
      title: "BRK is a two-byte instruction that looks like one",
      lede: "BRK pushes PC+2, so the byte after it is skipped on return. Nothing reads that byte — but plenty of operating systems put a call number in it and fish it off the stack.",
      source: [
        "  .org $0600",
        "  BRK",
        "  .byte $42     ; never executed, but not ignored either",
        "  NOP",
      ].join("\n"),
      steps: 1,
      vectors: { irq: 0x0700 },
      report: (cpu) => {
        const low = cpu.peek(0x01fc), high = cpu.peek(0x01fd);
        return `Pushed return address $${hex4((high << 8) | low)}, and the pushed status byte is $${hex2(cpu.peek(0x01fb))} with B set.`;
      },
      expect: (cpu) => cpu.peek(0x01fc) === 0x02 && (cpu.peek(0x01fb) & 0x10) !== 0,
      moral: "The B bit in that pushed byte is the only way a shared IRQ handler can tell a BRK from a real interrupt — and B exists nowhere else on the chip.",
    },
    {
      id: "decimal-flags",
      title: "In decimal mode, only the carry can be trusted",
      lede: "SED switches ADC and SBC to packed BCD. The NMOS 6502 corrects the result and the carry, but leaves N, V and Z reporting on the binary arithmetic that happened underneath.",
      source: [
        "  .org $0600",
        "  SED",
        "  CLC",
        "  LDA #$99",
        "  ADC #$01      ; 99 + 1 = 100",
        "  PHP           ; capture the flags",
        "  CLD",
      ].join("\n"),
      steps: 6,
      report: (cpu) => {
        const p = cpu.peek(0x01fd);
        return `A = $${hex2(cpu.a)} with carry ${p & 1 ? "set" : "clear"} — correct. But Z reads ${p & 2 ? "set" : "clear"}, and the answer is not zero.`;
      },
      expect: (cpu) => cpu.a === 0x00 && (cpu.peek(0x01fd) & 1) === 1,
      moral: "The CMOS 65C02 fixes the flags and spends an extra cycle doing it. Nintendo took the other route and removed decimal mode from the NES's chip entirely.",
    },
    {
      id: "stack-wrap",
      title: "The stack wraps instead of overflowing",
      lede: "S is eight bits and the stack is page one. Push past the bottom and the next push lands at $01FF, quietly overwriting whatever was there. There is no stack-overflow trap because there is no room in the design for one.",
      source: [
        "  .org $0600",
        "  LDX #$00",
        "  TXS           ; stack pointer at the very bottom",
        "  LDA #$AA",
        "  PHA           ; lands at $0100",
        "  LDA #$BB",
        "  PHA           ; wraps to $01FF",
      ].join("\n"),
      steps: 6,
      report: (cpu) => `$0100 = $${hex2(cpu.peek(0x0100))}, $01FF = $${hex2(cpu.peek(0x01ff))}, S = $${hex2(cpu.s)}.`,
      expect: (cpu) => cpu.peek(0x0100) === 0xaa && cpu.peek(0x01ff) === 0xbb,
      moral: "128 nested subroutine calls is the hard ceiling, and nothing tells you when you pass it.",
    },
    {
      id: "undocumented",
      title: "The 105 opcodes that were never meant to work",
      lede: "The decode logic is a sparse matrix of transistors, not a table with a default case. An undefined opcode activates whatever control lines happen to match its bit pattern — which usually means two real instructions firing at once, in the cycles of one.",
      source: [
        "  .org $0600",
        "  LDA #$81",
        "  STA $30",
        "  LDA #$01",
        "  .byte $07, $30    ; SLO $30: ASL the byte, then ORA it into A",
      ].join("\n"),
      steps: 4,
      report: (cpu) => `$30 = $${hex2(cpu.peek(0x30))} (shifted left), A = $${hex2(cpu.a)} (OR'd with it), carry ${cpu.c ? "set" : "clear"} — one instruction, five cycles.`,
      expect: (cpu) => cpu.peek(0x30) === 0x02 && cpu.a === 0x03 && cpu.c === 1,
      moral: "Demo and game programmers used these for years. A handful of others depend on charge left on an internal bus and give different answers on different chips, at different temperatures.",
    },
  ];

  // ---------------------------------------------------------------
  // Programs for the machine.
  // ---------------------------------------------------------------
  const PROGRAMS = [
    {
      id: "pixels",
      name: "Four pixels",
      blurb: "The shortest thing that makes the screen do something. Stores four colour bytes into the top-left of the display.",
      source: [
        "; The display is 32x32 bytes starting at $0200.",
        "; The low nibble of each byte picks a colour.",
        "  .org $0600",
        "  LDA #$01      ; white",
        "  STA $0200",
        "  LDA #$05      ; green",
        "  STA $0201",
        "  LDA #$08      ; orange",
        "  STA $0202",
        "  LDA #$07      ; yellow",
        "  STA $0203",
        "  BRK",
      ].join("\n"),
    },
    {
      id: "fill",
      name: "Fill the screen",
      blurb: "A nested loop over 1,024 bytes using (zp),Y — the mode that makes arrays possible. Watch the cycle counter: this is what 1 MHz feels like.",
      source: [
        "  .org $0600",
        "SCREEN = $0200",
        "PTR    = $10",
        "",
        "  LDA #<SCREEN",
        "  STA PTR",
        "  LDA #>SCREEN",
        "  STA PTR+1",
        "  LDX #$04      ; four pages of 256 bytes",
        "  LDY #$00",
        "  LDA #$0E      ; light blue",
        "page:",
        "  STA (PTR),Y",
        "  INY",
        "  BNE page",
        "  INC PTR+1     ; next page",
        "  DEX",
        "  BNE page",
        "  BRK",
      ].join("\n"),
    },
    {
      id: "rainbow",
      name: "Rainbow",
      blurb: "One colour per row, by letting the index register's high bits pick the colour. 1,024 stores and a little arithmetic.",
      source: [
        "  .org $0600",
        "PTR = $10",
        "",
        "  LDA #$00",
        "  STA PTR",
        "  LDA #$02",
        "  STA PTR+1",
        "  LDX #$00      ; row counter",
        "row:",
        "  TXA",
        "  AND #$0F      ; 16 colours, then repeat",
        "  LDY #$00",
        "col:",
        "  STA (PTR),Y",
        "  INY",
        "  CPY #$20      ; 32 pixels per row",
        "  BNE col",
        "  CLC           ; advance the pointer one row",
        "  LDA PTR",
        "  ADC #$20",
        "  STA PTR",
        "  LDA PTR+1",
        "  ADC #$00      ; carry into the high byte",
        "  STA PTR+1",
        "  INX",
        "  CPX #$20",
        "  BNE row",
        "  BRK",
      ].join("\n"),
    },
    {
      id: "random",
      name: "Static",
      blurb: "Reads $FE, which hands back a fresh random byte every time it is read — a hardware register, in other words, with a side effect. Run it and leave it running.",
      source: [
        "  .org $0600",
        "PTR = $10",
        "",
        "  LDA #$00",
        "  STA PTR",
        "  LDA #$02",
        "  STA PTR+1",
        "loop:",
        "  LDY #$00",
        "fill:",
        "  LDA $FE       ; a new random byte on every read",
        "  STA (PTR),Y",
        "  INY",
        "  BNE fill",
        "  INC PTR+1",
        "  LDA PTR+1",
        "  CMP #$06      ; past the end of the screen?",
        "  BNE loop",
        "  LDA #$02      ; back to the top",
        "  STA PTR+1",
        "  JMP loop",
      ].join("\n"),
    },
    {
      id: "multiply",
      name: "Multiply",
      blurb: "The 6502 has no multiply instruction. This is the classic shift-and-add: eight iterations, one bit at a time, 8 x 8 into 16 bits. Results land in $20 and $21.",
      source: [
        "; multiplier $10, multiplicand $12:$11, product $21:$20",
        "  .org $0600",
        "  LDA #$0D",
        "  STA $10       ; 13",
        "  LDA #$13",
        "  STA $11       ; 19",
        "",
        "  LDA #$00",
        "  STA $12       ; the multiplicand grows to 16 bits",
        "  STA $20",
        "  STA $21",
        "  LDX #$08      ; eight bits to go",
        "loop:",
        "  LSR $10       ; shift the next bit of the multiplier out",
        "  BCC skip      ; that bit was 0 — nothing to add",
        "  CLC",
        "  LDA $20       ; product += multiplicand, 16 bits wide",
        "  ADC $11",
        "  STA $20",
        "  LDA $21",
        "  ADC $12",
        "  STA $21",
        "skip:",
        "  ASL $11       ; double the multiplicand ...",
        "  ROL $12       ; ... carrying into its high byte",
        "  DEX",
        "  BNE loop",
        "  BRK           ; 13 x 19 = 247 = $00F7",
      ].join("\n"),
    },
    {
      id: "sort",
      name: "Sort",
      blurb: "A bubble sort over sixteen bytes, drawn on screen as it goes: each pass leaves one more value in place. Indexed addressing doing what it is for.",
      source: [
        "  .org $0600",
        "DATA = $0300",
        "",
        "  LDX #$00      ; fill the array with random bytes",
        "seed:",
        "  LDA $FE",
        "  AND #$0F",
        "  STA DATA,X",
        "  INX",
        "  CPX #$10",
        "  BNE seed",
        "",
        "pass:",
        "  LDY #$00      ; Y counts swaps this pass",
        "  LDX #$00",
        "compare:",
        "  LDA DATA,X",
        "  CMP DATA+1,X",
        "  BCC ordered   ; already in order",
        "  BEQ ordered",
        "  PHA           ; swap them",
        "  LDA DATA+1,X",
        "  STA DATA,X",
        "  PLA",
        "  STA DATA+1,X",
        "  INY",
        "ordered:",
        "  INX",
        "  CPX #$0F",
        "  BNE compare",
        "",
        "  JSR draw",
        "  CPY #$00      ; any swaps? then go again",
        "  BNE pass",
        "  BRK",
        "",
        "draw:",
        "  LDX #$00",
        "bar:",
        "  LDA DATA,X",
        "  STA $0200,X   ; one pixel per value, top row",
        "  INX",
        "  CPX #$10",
        "  BNE bar",
        "  RTS",
      ].join("\n"),
    },
    {
      id: "sieve",
      name: "Sieve",
      blurb: "The sieve of Eratosthenes over the first 256 numbers, with each prime lighting a pixel. A benchmark that ran on every 8-bit machine there was.",
      source: [
        "  .org $0600",
        "FLAGS = $0300   ; 1 = still a candidate",
        "",
        "  LDX #$00      ; mark everything as prime",
        "init:",
        "  LDA #$01",
        "  STA FLAGS,X",
        "  INX",
        "  BNE init",
        "",
        "  LDX #$02      ; start at 2",
        "outer:",
        "  LDA FLAGS,X",
        "  BEQ next      ; already crossed out",
        "  LDA #$05      ; X is prime: light a pixel, green",
        "  STA $0200,X",
        "  STX $10       ; cross out every multiple of X",
        "  TXA",
        "mark:",
        "  CLC",
        "  ADC $10",
        "  BCS next      ; past 255",
        "  TAY",
        "  LDA #$00",
        "  STA FLAGS,Y",
        "  TYA",
        "  JMP mark",
        "next:",
        "  INX",
        "  BNE outer",
        "  BRK",
      ].join("\n"),
    },
    {
      id: "walk",
      name: "Random walk",
      blurb: "A dot wandering the screen, wrapping at the edges. Reads the random register, masks two bits out of it, and moves. Leave it running.",
      source: [
        "  .org $0600",
        "POS  = $10      ; 16-bit screen pointer",
        "",
        "  LDA #$10",
        "  STA POS",
        "  LDA #$03",
        "  STA POS+1",
        "loop:",
        "  LDY #$00",
        "  LDA #$00      ; erase the old dot",
        "  STA (POS),Y",
        "",
        "  LDA $FE       ; pick a direction",
        "  AND #$03",
        "  CMP #$00",
        "  BEQ up",
        "  CMP #$01",
        "  BEQ down",
        "  CMP #$02",
        "  BEQ left",
        "",
        "right:",
        "  INC POS",
        "  BNE draw",
        "  INC POS+1",
        "  JMP draw",
        "left:",
        "  LDA POS",
        "  BNE noborrow",
        "  DEC POS+1",
        "noborrow:",
        "  DEC POS",
        "  JMP draw",
        "up:",
        "  SEC",
        "  LDA POS",
        "  SBC #$20      ; one row is 32 bytes",
        "  STA POS",
        "  LDA POS+1",
        "  SBC #$00",
        "  STA POS+1",
        "  JMP draw",
        "down:",
        "  CLC",
        "  LDA POS",
        "  ADC #$20",
        "  STA POS",
        "  LDA POS+1",
        "  ADC #$00",
        "  STA POS+1",
        "",
        "draw:",
        "  LDA POS+1     ; keep the dot on the screen",
        "  CMP #$02",
        "  BCC reset",
        "  CMP #$06",
        "  BCS reset",
        "  LDA #$07      ; yellow",
        "  LDY #$00",
        "  STA (POS),Y",
        "  JMP loop",
        "reset:",
        "  LDA #$10",
        "  STA POS",
        "  LDA #$03",
        "  STA POS+1",
        "  JMP loop",
      ].join("\n"),
    },
  ];

  // ---------------------------------------------------------------
  // Instructions worth watching cycle by cycle. Each is executed on a
  // machine set up as described, and what the page draws is the bus
  // trace that came back.
  // ---------------------------------------------------------------
  const CYCLE_TRACES = [
    { label: "LDA #$41", sample: "LDA #$41", setup: {},
      note: "The floor: fetch the opcode, fetch the value. Two bytes, two cycles, and no memory access beyond the instruction itself." },
    { label: "LDA $30", sample: "LDA $30", setup: { mem: { 0x0030: 0x7f } },
      note: "Zero page. One address byte, so three cycles — a byte and a cycle cheaper than naming the same location in full." },
    { label: "LDA $2000", sample: "LDA $2000", setup: { mem: { 0x2000: 0x5c } },
      note: "Absolute. The address arrives low byte first, which is what lets the chip start indexing before the high byte has even been fetched." },
    { label: "LDA $20F0,X", sample: "LDA $20F0,X", setup: { x: 0x20, mem: { 0x2110: 0x3d, 0x2010: 0xba } },
      note: "Cycle 4 reads $2010: the index was added to the low byte and the carry into the high byte is not known yet. Cycle 5 does it again, correctly. This is the page-crossing penalty." },
    { label: "LDA $2000,X", sample: "LDA $2000,X", setup: { x: 0x04, mem: { 0x2004: 0x71 } },
      note: "The same instruction with an index that does not cross a page. No wasted read, no fifth cycle: the penalty is not a property of the instruction, it is a property of the data." },
    { label: "STA $2000,X", sample: "STA $2000,X", setup: { a: 0x42, x: 0x04 },
      note: "A write pays the extra cycle whether or not it crossed a page. It cannot afford to guess: a write to the wrong address cannot be taken back." },
    { label: "INC $2000", sample: "INC $2000", setup: { mem: { 0x2000: 0x41 } },
      note: "Read-modify-write. Three accesses to one address: read it, write the OLD value back while the ALU works, then write the new one. The chip has nowhere else to park the byte." },
    { label: "ASL $20F0,X", sample: "ASL $20F0,X", setup: { x: 0x20, mem: { 0x2110: 0x81 } },
      note: "The most expensive documented instruction on the chip at seven cycles: an indexed address that always pays its dummy read, plus a read-modify-write that always writes twice." },
    { label: "LDA ($20),Y", sample: "LDA ($20),Y", setup: { y: 0x10, mem: { 0x0020: 0xf0, 0x0021: 0x21, 0x2200: 0x5a } },
      note: "The workhorse: fetch a pointer out of page zero, add Y, read. Six cycles here because $21F0 + $10 crossed into the next page." },
    { label: "JSR $0700", sample: "JSR $0700", setup: {},
      note: "Six cycles: fetch the low byte, look at the stack without using it, push the two halves of the return address, and only then fetch the high byte of where it is going." },
    { label: "RTS", sample: "RTS", setup: { s: 0xfb, mem: { 0x01fc: 0x02, 0x01fd: 0x06 } },
      note: "Six cycles to undo JSR, of which three read nothing useful. The last one exists purely to add one to the address, because JSR pushed one short." },
    { label: "JMP ($30FF)", sample: "JMP ($30FF)", setup: { mem: { 0x30ff: 0x00, 0x3000: 0x80, 0x3100: 0x40 } },
      note: "Watch cycles 4 and 5: the pointer's high byte comes from $3000, not $3100. The address adder cannot carry on this path, and never could." },
    { label: "PHA", sample: "PHA", setup: { a: 0xaa },
      note: "Three cycles, one of which fetches the byte after the opcode and throws it away. The 6502 always fetches it; there is no decode path that knows not to." },
    { label: "PLA", sample: "PLA", setup: { s: 0xfc, mem: { 0x01fd: 0xaa } },
      note: "Four cycles: the throwaway fetch, a read of the stack at the pointer's current value — also thrown away — and then the real read, one slot up." },
    { label: "BRK", sample: "BRK", vectors: { irq: 0x9000 }, setup: {},
      note: "Seven cycles, and the same seven an IRQ or an NMI takes. The only difference between them is which two bytes the last pair of cycles reads, and whether bit 4 of the pushed status byte is set." },
  ];

  // The C64 palette, which is what every 6502 tutorial since has used.
  const PALETTE = [
    "#000000", "#ffffff", "#880000", "#aaffee", "#cc44cc", "#00cc55", "#0000aa", "#eeee77",
    "#dd8855", "#664400", "#ff7777", "#333333", "#777777", "#aaff66", "#0088ff", "#bbbbbb",
  ];

  // ---------------------------------------------------------------
  // What this page does not model
  // ---------------------------------------------------------------
  const LIMITS = [
    "Interrupts are sampled between instructions, not at the second-to-last cycle of one. The real chip's one-instruction delay after CLI, SEI, PLP and RTI is therefore not reproduced, and neither is the case where an NMI arriving during a BRK hijacks its vector.",
    "The six unstable undocumented opcodes — ANE, LXA, SHA, SHX, SHY and TAS — use the commonly published model. On real silicon their results depend on charge on an internal bus, and vary with the individual chip, its temperature and its supply voltage. Treat what this page shows for them as one plausible answer, not the answer.",
    "There is no RDY pin, no SO pin, no bus contention and no cycle stealing by a video chip. On an Apple II or a C64 those effects are a large part of what the processor actually experiences.",
    "This is a model of the NMOS 6502. The CMOS 65C02 fixes the indirect JMP bug, corrects the decimal flags, turns most undocumented opcodes into NOPs, and adds instructions. Where the two differ, this page follows the NMOS part.",
    "The 32 x 32 display, the random byte at $FE and the keyboard byte at $FF are this simulator's conventions, borrowed from Nick Morgan's Easy 6502 so that programs can be pasted between the two. No real 6502 machine was laid out this way.",
  ];

  // ---------------------------------------------------------------
  // Sources
  // ---------------------------------------------------------------
  const SOURCES = [
    { title: "MCS6500 Microcomputer Family Programming Manual", pub: "MOS Technology, January 1976",
      href: "https://archive.org/details/6500-50a_mcs6500pgmmanjan76",
      use: "The primary document: the instruction set, the addressing modes and the cycle counts, as published by the people who made the chip." },
    { title: "MCS6500 Microcomputer Family Hardware Manual", pub: "MOS Technology, 1976",
      href: "https://archive.org/details/mos_microcomputers_hardware_manual",
      use: "Pin functions, bus timing, the reset and interrupt sequences modelled cycle by cycle in sections 3 and 8." },
    { title: "6502 Instruction Set reference", pub: "Norbert Landsteiner, masswerk.at",
      href: "https://www.masswerk.at/6502/6502_instruction_set.html",
      use: "The opcode matrix checked against the cycle table in this page's tests, including the page-crossing and branch-taken rules." },
    { title: "Decimal Mode", pub: "Bruce Clark, 6502.org",
      href: "https://6502.org/tutorials/decimal_mode.html",
      use: "The exact NMOS behaviour of ADC and SBC with D set, including which flags mean nothing afterwards. The algorithm in this page's ALU is the one described here." },
    { title: "6502_65C02_functional_tests", pub: "Klaus Dormann",
      href: "https://github.com/Klaus2m5/6502_65C02_functional_tests",
      use: "The conformance oracle. This page's core runs it to its success trap at $3469 after 30,646,177 instructions." },
    { title: "How MOS 6502 Illegal Opcodes really work", pub: "Michael Steil, pagetable.com",
      href: "https://www.pagetable.com/?p=39",
      use: "Why the undefined opcodes do what they do — the decode ROM's structure rather than a list of special cases — and which of them are unstable." },
    { title: "The 6502 overflow flag explained mathematically", pub: "Ken Shirriff",
      href: "https://www.righto.com/2012/12/the-6502-overflow-flag-explained.html",
      use: "The derivation behind the overflow formula used in the ALU section, and the gate-level circuit that implements it." },
    { title: "Visual6502: a transistor-level simulation from die photographs", pub: "Greg James, Barry Silverman, Brian Silverman",
      href: "https://www.visual6502.org/JSSim/index.html",
      use: "The ground truth for cycle-level behaviour, and the source of the transistor counts quoted here: 3,510 enhancement transistors plus 1,018 depletion-mode pull-ups." },
    { title: "64doc: 6502 cycle-by-cycle instruction timing", pub: "John West and Marko Mäkelä",
      href: "https://www.nesdev.org/6502_cpu.txt",
      use: "The per-cycle bus activity of every addressing mode, including which cycles are dummy reads and dummy writes. The emulator's trace follows this document." },
    { title: "CPU unofficial opcodes", pub: "NESdev Wiki",
      href: "https://www.nesdev.org/wiki/CPU_unofficial_opcodes",
      use: "Cross-check on the undocumented instruction behaviour and timings, and on which are considered safe to use." },
    { title: "Oral History of Charles Ingerham \"Chuck\" Peddle", pub: "Computer History Museum, 12 June 2014",
      href: "https://www.computerhistory.org/collections/catalog/102739939",
      use: "Peddle's own account of leaving Motorola, the WESCON jars, and what the price target did to the design." },
    { title: "MOS Technology 6502", pub: "Wikipedia",
      href: "https://en.wikipedia.org/wiki/MOS_Technology_6502",
      use: "The commercial chronology: the lawsuit and its settlement, the Commodore acquisition, and the machine-by-machine variant list." },
    { title: "Easy 6502", pub: "Nick Morgan",
      href: "https://skilldrick.github.io/easy6502/",
      use: "The source of the memory conventions this simulator adopts — the display at $0200, the random byte at $FE, the keyboard byte at $FF — so programs can move between the two." },
    { title: "W65C02S datasheet", pub: "Western Design Center",
      href: "https://www.westerndesigncenter.com/wdc/documentation/w65c02s.pdf",
      use: "What the architecture became: the current CMOS part, its fixes to the NMOS bugs, and the evidence that it is still in production." },
  ];

  function hex2(n) { return (n & 0xff).toString(16).toUpperCase().padStart(2, "0"); }
  function hex4(n) { return (n & 0xffff).toString(16).toUpperCase().padStart(4, "0"); }

  const api = { HISTORY, MACHINES, REGISTERS, FLAGS, MEMORY_MAP, ADDRESSING, CYCLE_TRACES, INSTRUCTIONS, QUIRKS, PROGRAMS, PALETTE, LIMITS, SOURCES };
  if (typeof module === "object" && module.exports) module.exports = api;
  global.SIX502 = api;
})(typeof globalThis !== "undefined" ? globalThis : this);
