// @ts-check
export const STORE_NAME="nihon-travel-rpg";export const STORE_VERSION=1;
export const DEFAULT_SETTINGS=Object.freeze({romajiMode:"fade",reducedMotion:false,audioRate:.92,showKana:true,aiMode:false,aiEndpoint:"https://api.openai.com/v1/chat/completions",aiModel:"gpt-4o-mini",apiKey:"",privacyAcknowledged:false});
export const AVATAR_DEFAULT=Object.freeze({name:"Traveller",hair:"bob",jacket:"indigo",accessory:"scarf"});
export const day=864e5;
export function makeReviewCard(source,type,chapterId,now=Date.now()){return{id:`${type}:${source.id}`,sourceId:source.id,chapterId,type,front:type==="sign"?source.text:source.japanese,back:type==="sign"?`${source.reading} — ${source.meaning}`:source.english,prompt:type==="sign"?source.where:source.politeness,due:now,intervalDays:0,ease:2.3,lapses:0,reps:0,lastGrade:null}}
export function createInitialProgress(chapters,now=Date.now()){const reviewCards=[];for(const chapter of chapters){chapter.phrases.forEach(p=>reviewCards.push(makeReviewCard(p,"phrase",chapter.id,now)));chapter.signs.forEach(s=>reviewCards.push(makeReviewCard(s,"sign",chapter.id,now)))}return{version:1,startedAt:new Date(now).toISOString(),lastVisited:new Date(now).toISOString(),completedLessons:[],completedRoleplays:[],stamps:[],learnedPhraseIds:[],learnedSignIds:[],confidenceChecks:{},journalNotes:{},favourites:[],reviewCards,reviewLog:[],avatar:{...AVATAR_DEFAULT}}}
export function mergeSettings(saved){return{...DEFAULT_SETTINGS,...(saved||{})}}
export function clone(value){return typeof structuredClone==="function"?structuredClone(value):JSON.parse(JSON.stringify(value))}
export function mergeProgress(saved,chapters,now=Date.now()){const base=createInitialProgress(chapters,now);if(!saved||typeof saved!=="object")return base;const next={...base,...saved};for(const key of["completedLessons","completedRoleplays","stamps","learnedPhraseIds","learnedSignIds","favourites","reviewLog"])next[key]=Array.isArray(saved[key])?saved[key]:[];next.confidenceChecks=saved.confidenceChecks&&typeof saved.confidenceChecks==="object"?saved.confidenceChecks:{};next.journalNotes=saved.journalNotes&&typeof saved.journalNotes==="object"?saved.journalNotes:{};next.avatar={...AVATAR_DEFAULT,...(saved.avatar||{})};const old=new Map((Array.isArray(saved.reviewCards)?saved.reviewCards:[]).map(c=>[c.id,c]));next.reviewCards=base.reviewCards.map(c=>({...c,...(old.get(c.id)||{})}));return next}
export function addUnique(list,item){if(!list.includes(item))list.push(item);return list}
export function completeLesson(progress,chapter,now=Date.now()){const next=clone(progress);addUnique(next.completedLessons,chapter.id);addUnique(next.stamps,chapter.id);chapter.phrases.forEach(p=>addUnique(next.learnedPhraseIds,p.id));chapter.signs.forEach(s=>addUnique(next.learnedSignIds,s.id));next.lastVisited=new Date(now).toISOString();return next}
export function completeRoleplay(progress,chapterId,now=Date.now()){const next=clone(progress);addUnique(next.completedRoleplays,chapterId);next.lastVisited=new Date(now).toISOString();return next}
export function setConfidence(progress,chapterId,index,checked){const next=clone(progress);next.confidenceChecks[chapterId]=Array.isArray(next.confidenceChecks[chapterId])?next.confidenceChecks[chapterId]:[];next.confidenceChecks[chapterId][index]=Boolean(checked);return next}
export function routeUnlockState(chapter,progress,chapters){if(!chapter.unlockAfter)return{unlocked:true,reason:"Start here"};if(progress.completedLessons.includes(chapter.id))return{unlocked:true,reason:"Completed"};if(chapter.routeType==="side")return progress.completedLessons.includes(chapter.unlockAfter)?{unlocked:true,reason:"Side quest available"}:{unlocked:false,reason:`Unlocked after ${titleFor(chapter.unlockAfter,chapters)}`};const prev=chapters.filter(c=>c.routeType==="main"&&c.order<chapter.order).sort((a,b)=>b.order-a.order)[0];return !prev||progress.completedLessons.includes(prev.id)?{unlocked:true,reason:"Next main stop"}:{unlocked:false,reason:`Unlocked after ${prev.mapLabel||prev.title}`}}
export function titleFor(id,chapters){return(chapters.find(c=>c.id===id)||{}).title||id}
export function isChapterComplete(progress,id){return progress.completedLessons.includes(id)}
export function nextRecommendedChapter(progress,chapters){return chapters.filter(c=>c.routeType==="main").find(c=>routeUnlockState(c,progress,chapters).unlocked&&!isChapterComplete(progress,c.id))||chapters.find(c=>routeUnlockState(c,progress,chapters).unlocked&&!isChapterComplete(progress,c.id))||chapters.at(-1)}
export function toggleFavourite(progress,phraseId){const next=clone(progress);next.favourites=next.favourites.includes(phraseId)?next.favourites.filter(id=>id!==phraseId):[...next.favourites,phraseId];return next}
export function dueCards(progress,now=Date.now(),mode="daily"){const limit=mode==="deep"?40:12;return progress.reviewCards.filter(c=>c.due<=now).sort((a,b)=>a.due-b.due||a.reps-b.reps).slice(0,limit)}
export function scheduleCard(card,grade,now=Date.now()){const c={...card,reps:(card.reps||0)+1,lastGrade:grade};if(grade==="again"){c.intervalDays=0;c.ease=Math.max(1.3,(c.ease||2.3)-.25);c.lapses=(c.lapses||0)+1;c.due=now+10*60*1000}else if(grade==="hard"){c.intervalDays=Math.max(1,Math.round((c.intervalDays||1)*1.2));c.ease=Math.max(1.5,(c.ease||2.3)-.1);c.due=now+c.intervalDays*day}else if(grade==="easy"){c.intervalDays=Math.max(3,Math.round(((c.intervalDays||1)+1)*((c.ease||2.3)+.35)));c.ease=Math.min(3.2,(c.ease||2.3)+.15);c.due=now+c.intervalDays*day}else{c.intervalDays=Math.max(1,Math.round(((c.intervalDays||1)+.25)*(c.ease||2.3)));c.due=now+c.intervalDays*day}return c}
export function gradeReview(progress,cardId,grade,now=Date.now()){const next=clone(progress);next.reviewCards=next.reviewCards.map(c=>c.id===cardId?scheduleCard(c,grade,now):c);next.reviewLog.push({cardId,grade,at:new Date(now).toISOString()});return next}
export const normalise=value=>String(value||"").toLowerCase().normalize("NFKC").replace(/\s+/g," ").trim();
export function searchPhrasebook(query,phrases,{situation="all"}={}){const q=normalise(query);return phrases.filter(p=>(situation==="all"||p.chapterId===situation)&&(!q||[p.japanese,p.kana,p.romaji,p.english,p.politeness,p.usage,p.chapterTitle].some(v=>normalise(v).includes(q))))}
export function shouldShowRomaji(settings,chapterOrder,helpOpen=false){if(helpOpen)return true;if(settings.romajiMode==="always")return true;if(settings.romajiMode==="mostly-off")return false;return Number(chapterOrder||1)<=4}
export function aiModeStatus(settings){const hasKey=Boolean(settings.apiKey&&String(settings.apiKey).trim().length>12);return{enabled:Boolean(settings.aiMode&&hasKey),hasKey,reason:hasKey?(settings.aiMode?"AI roleplay is enabled.":"API key saved locally; AI mode is off."):"Add your own API key to enable AI roleplay."}}
export function scriptedFeedback(input,step,phraseLookup){const answer=normalise(input);const suggestions=step.expectedPhraseIds.map(id=>phraseLookup.get(id)).filter(Boolean);if(!answer)return{quality:"empty",title:"No problem — try a short traveller phrase.",message:"In real travel, even one clear keyword can help. Try the safest polite version below.",suggestions};const hit=step.acceptKeywords.some(k=>answer.includes(normalise(k)))||suggestions.some(p=>[p.japanese,p.kana,p.romaji,p.english].some(v=>answer.includes(normalise(v))));return hit?{quality:"understood",title:"Good — that would likely be understood.",message:step.tip||"Here is the safest polite version to keep in your travel toolkit.",suggestions}:{quality:"almost",title:"Almost there — this would still help in real travel.",message:"Here is a slightly more natural and safer version for this situation.",suggestions}}
export function progressSummary(progress,chapters){const total=chapters.length,done=progress.completedLessons.length,mainTotal=chapters.filter(c=>c.routeType==="main").length,mainDone=chapters.filter(c=>c.routeType==="main"&&progress.completedLessons.includes(c.id)).length;return{done,total,mainDone,mainTotal,percent:Math.round(done/total*100),stamps:progress.stamps.length,phrases:progress.learnedPhraseIds.length,signs:progress.learnedSignIds.length}}
export function exportSave(progress,settings){return btoa(unescape(encodeURIComponent(JSON.stringify({progress,settings,exportedAt:new Date().toISOString()}))))}
export function importSave(code){const decoded=JSON.parse(decodeURIComponent(escape(atob(code.trim()))));if(!decoded||typeof decoded!=="object"||!decoded.progress)throw new Error("Save code is not a valid travel journal export.");return decoded}
export function createMemoryStore(initial={}){const data=new Map(Object.entries(initial));return{kind:"memory",async get(key,fallback=null){return data.has(key)?clone(data.get(key)):fallback},async set(key,value){data.set(key,clone(value));return value},async remove(key){data.delete(key)},async clear(){data.clear()}}}
export function createLocalStorageStore(){const prefix=`${STORE_NAME}:`;return{kind:"localstorage",async get(key,fallback=null){try{const raw=localStorage.getItem(prefix+key);return raw==null?fallback:JSON.parse(raw)}catch{return fallback}},async set(key,value){localStorage.setItem(prefix+key,JSON.stringify(value));return value},async remove(key){localStorage.removeItem(prefix+key)},async clear(){Object.keys(localStorage).filter(k=>k.startsWith(prefix)).forEach(k=>localStorage.removeItem(k))}}}
export function createBrowserStore(){if(typeof indexedDB==="undefined")return createLocalStorageStore();let dbPromise;const open=()=>dbPromise||(dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(STORE_NAME,STORE_VERSION);req.onupgradeneeded=()=>req.result.createObjectStore("kv");req.onerror=()=>reject(req.error||new Error("Could not open IndexedDB."));req.onsuccess=()=>resolve(req.result)}).catch(()=>null));const op=async(mode,fn,fallback)=>{const db=await open();if(!db)return fallback;return new Promise((resolve,reject)=>{const tx=db.transaction("kv",mode);const store=tx.objectStore("kv");const req=fn(store);req.onerror=()=>reject(req.error||new Error("Storage operation failed."));req.onsuccess=()=>resolve(req.result===undefined?fallback:req.result)})};return{kind:"indexeddb",async get(key,fallback=null){const db=await open();return db?op("readonly",s=>s.get(key),fallback):createLocalStorageStore().get(key,fallback)},async set(key,value){const db=await open();if(!db)return createLocalStorageStore().set(key,value);await op("readwrite",s=>s.put(value,key));return value},async remove(key){const db=await open();return db?op("readwrite",s=>s.delete(key)):createLocalStorageStore().remove(key)},async clear(){const db=await open();return db?op("readwrite",s=>s.clear()):createLocalStorageStore().clear()}}}
