import {CARS,STAGES,Stage,Vehicle,Records,clamp,angle,formatTime,medal,nextNote,ghostPose} from './core.mjs';
import {Renderer} from './render.mjs';
const $=id=>document.getElementById(id), show=(id,on=true)=>{$(id).hidden=!on;};
let storage=null;try{storage=window.localStorage;}catch{/* Private mode still supports a full session. */}
const defaults={quality:matchMedia('(pointer:coarse)').matches?'medium':'high',automatic:true,assists:true,ghost:true,voice:true,sound:true,volume:.55};
let settings={...defaults};try{const saved=JSON.parse(storage?.getItem('southern-cross.settings')||'null');if(saved&&typeof saved==='object')for(const key of Object.keys(defaults))if(typeof saved[key]===typeof defaults[key])settings[key]=saved[key];}catch{}
if(!['low','medium','high'].includes(settings.quality))settings.quality='high';settings.volume=clamp(settings.volume,0,1);
class Sound {
  constructor(){this.ctx=null;this.lastGear=1;}
  start(){try{if(!this.ctx){const Context=window.AudioContext||window.webkitAudioContext;if(!Context)return;const c=this.ctx=new Context();this.master=c.createGain();this.master.gain.value=0;this.master.connect(c.destination);this.engine=c.createGain();this.engine.connect(this.master);this.engine.gain.value=0;this.osc=c.createOscillator();this.osc.type='sawtooth';this.filter=c.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=700;this.osc.connect(this.filter);this.filter.connect(this.engine);this.osc.start();this.sub=c.createOscillator();this.sub.type='triangle';this.subGain=c.createGain();this.subGain.gain.value=.3;this.sub.connect(this.subGain);this.subGain.connect(this.engine);this.sub.start();const buffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+(Math.random()*2-1)*.03)/1.03;data[i]=last*5;}this.noise=c.createBufferSource();this.noise.buffer=buffer;this.noise.loop=true;this.road=c.createGain();this.road.gain.value=0;this.noise.connect(this.road);this.road.connect(this.master);this.noise.start();}void this.ctx.resume().catch(()=>{});}catch(error){console.warn('Audio is unavailable:',error.message);}}
  update(v,input,active){if(!this.ctx)return;const c=this.ctx,t=c.currentTime;this.master.gain.setTargetAtTime(settings.sound?settings.volume*.38:0,t,.04);this.engine.gain.setTargetAtTime(active?.18+(input.throttle||0)*.16:0,t,.06);this.osc.frequency.setTargetAtTime(35+(v.rpm||1000)/60*1.8,t,.05);this.sub.frequency.setTargetAtTime(18+(v.rpm||1000)/60*.6,t,.05);this.filter.frequency.setTargetAtTime(380+(input.throttle||0)*1300+(v.rpm||1000)*.09,t,.05);this.road.gain.setTargetAtTime(active?clamp(Math.abs(v.speed||0)/55,0,.6)*(.18+(v.slip||0)*.4):0,t,.1);if(active&&v.lastImpact>2)this.beep(60,.13,.4);if(active&&this.lastGear!==v.gear){this.beep(115,.04,.04);this.lastGear=v.gear;}}
  beep(freq=660,duration=.12,volume=.13){if(!this.ctx||!settings.sound)return;const c=this.ctx,o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;o.connect(g);g.connect(this.master);g.gain.setValueAtTime(volume,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);o.start();o.stop(c.currentTime+duration);}
  say(text){if(!settings.voice||!settings.sound||!window.speechSynthesis)return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text),voices=speechSynthesis.getVoices().filter(v=>v.localService);if(!voices.length)return;u.voice=voices.find(v=>v.lang==='en-NZ')||voices.find(v=>v.lang==='en-AU')||voices.find(v=>v.lang==='en-GB')||voices.find(v=>v.lang.startsWith('en'))||voices[0];u.lang='en-NZ';u.rate=1.2;u.volume=settings.volume; speechSynthesis.speak(u);}catch{}}
  stop(){if(window.speechSynthesis)speechSynthesis.cancel();if(this.ctx){this.engine.gain.setTargetAtTime(0,this.ctx.currentTime,.04);this.road.gain.setTargetAtTime(0,this.ctx.currentTime,.04);}}
}
const sound=new Sound(), records=new Records(storage),keys=new Set(),touch=new Set();
let renderer,stage,vehicle,carIndex=0,stageIndex=0,phase='loading',runOptions={...settings},cup=null,carryDamage=0,accumulator=0,lastFrame=0,countdown=3,countBeep=4,cameraMode=0,samples=[],lastSample=-1,best=null,lastNote=null,lastCheckpoint=0,toastUntil=0,replayTime=0,gamepadButtons=[],lastInput={steer:0,throttle:0,brake:0,handbrake:false},hudTick=0,selectionToken=0,settingsReturnFocus=null;
const stageCache=STAGES.map(d=>new Stage(d));
function toast(text,seconds=2.5){$('toast').textContent=text;toastUntil=performance.now()+seconds*1000;show('toast');}
function clearInput(){keys.clear();touch.clear();document.querySelectorAll('.touch-controls button').forEach(b=>b.classList.remove('pressed'));lastInput={steer:0,throttle:0,brake:0,handbrake:false};}
function mapPath(s,w=120,h=40){const xs=s.points.map(p=>p.x),zs=s.points.map(p=>p.z),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),scale=Math.min((w-14)/(maxZ-minZ||1),(h-8)/(maxX-minX||1));return s.points.filter((_,i)=>i%7===0).map((p,i)=>`${i?'L':'M'}${(w/2+(p.z-(minZ+maxZ)/2)*scale).toFixed(1)},${(h/2-(p.x-(minX+maxX)/2)*scale).toFixed(1)}`).join(' ');}

function drawMenu(){
  $('cars').innerHTML=CARS.map((c,i)=>`<button class="car-card ${i===carIndex?'selected':''}" data-car="${i}" aria-pressed="${i===carIndex}"><span class="swatch" style="background:rgb(${c.colour.map(v=>Math.round(v*255)).join(',')})"></span><b>${c.name}</b><small>${c.drive} / ${Math.round(c.power/745.7)} BHP</small><div class="car-stats"><span>${c.mass} KG</span><span>6-SPEED</span><span>${c.number}</span></div></button>`).join('');
  $('stages').innerHTML=stageCache.map((s,i)=>`<button class="stage-card ${i===stageIndex?'selected':''}" data-stage="${i}" aria-pressed="${i===stageIndex}"><span class="number">SS 0${i+1}</span><svg viewBox="0 0 120 40" aria-hidden="true"><path d="${mapPath(s)}" fill="none" stroke="${i===stageIndex?'#f4ad58':'#ccd8bd'}" stroke-width="2.1" stroke-linecap="round"/></svg><b>${s.def.name}</b><small>${(s.finish/1000).toFixed(2)} KM · ${s.def.wet>.5?'WET':'GRAVEL'}</small></button>`).join('');
  $('car-description').textContent=CARS[carIndex].description;$('drive-badge').textContent=CARS[carIndex].drive;
  const d=STAGES[stageIndex];$('region').textContent=`SS 0${stageIndex+1} / ${d.region}`;$('stage-name').textContent=d.name;$('stage-description').textContent=d.description;$('stage-length').textContent=`${(stageCache[stageIndex].finish/1000).toFixed(2)} km`;$('weather').textContent=d.weather;$('best-time').textContent=formatTime(records.read(d.id,CARS[carIndex].id,settings.assists)?.time);
  $('start').innerHTML=$('mode').value==='cup'?'START THE RALLY <span>↗</span>':'TAKE THE START <span>↗</span>';
}
const paint=()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
async function loadStage(index,forRace=false){const token=++selectionToken;show('loading');$('loading-text').textContent=`Preparing ${STAGES[index].name}…`;await paint();if(token!==selectionToken)return;stageIndex=index;stage=stageCache[index];renderer.setStage(stage);vehicle=new Vehicle(stage,CARS[carIndex],forRace?carryDamage:0);drawMenu();show('loading',false);if(forRace)beginCountdown();else{phase='menu';show('menu');document.body.classList.remove('driving');}}
function beginCountdown(){renderer.clearEffects();phase='countdown';runOptions={...settings};samples=[];lastSample=-1;best=records.read(stage.def.id,CARS[carIndex].id,runOptions.assists);countdown=3;countBeep=4;accumulator=0;lastNote=null;lastCheckpoint=0;clearInput();show('menu',false);show('hud');show('results',false);show('paused',false);show('service',false);show('countdown');$('countdown').textContent='3';document.body.classList.add('driving');$('hud-stage-number').textContent=`${cup?'SOUTHERN CROSS RALLY':'TIME TRIAL'} / SS 0${stageIndex+1}`;$('hud-stage-name').textContent=stage.def.name;sound.start();updateHUD();}
async function start(){if(phase!=='menu')return;sound.start();carryDamage=0;cup=$('mode').value==='cup'?{results:[],servicePenalty:0,car:carIndex}:null;if(cup&&stageIndex!==0){await loadStage(0,true);}else{vehicle=new Vehicle(stage,CARS[carIndex]);beginCountdown();}}
function pause(){if(phase==='race'||phase==='countdown'){phaseBeforePause=phase;phase='paused';show('paused');clearInput();sound.stop();$('resume').focus();}else if(phase==='paused'&&$('settings').hidden)resume();}
let phaseBeforePause='race';
function resume(){phase=phaseBeforePause;show('paused',false);accumulator=0;clearInput();sound.start();}
function toMenu(){renderer.clearEffects();selectionToken++;phase='menu';cup=null;carryDamage=0;clearInput();sound.stop();for(const id of ['hud','paused','results','countdown','service','replay-bar','settings','toast'])show(id,false);show('menu');document.body.classList.remove('driving');vehicle=new Vehicle(stage,CARS[carIndex]);drawMenu();}
function restart(){sound.stop();clearInput();show('paused',false);show('results',false);vehicle=new Vehicle(stage,CARS[carIndex],carryDamage);beginCountdown();}
function openSettings(){settingsReturnFocus=document.activeElement;show('settings');$('quality').value=settings.quality;$('transmission').value=settings.automatic?'auto':'manual';for(const k of ['assists','ghost','voice','sound'])$(k).checked=settings[k];$('volume').value=settings.volume;$('assists').disabled=phase!=='menu';$('transmission').disabled=phase!=='menu';$('settings-close').focus();}
function closeSettings(){settings.quality=$('quality').value;settings.automatic=$('transmission').value==='auto';for(const k of ['assists','ghost','voice','sound'])settings[k]=$(k).checked;settings.volume=Number($('volume').value);renderer.quality=settings.quality;try{storage?.setItem('southern-cross.settings',JSON.stringify(settings));}catch{}if(!settings.sound||!settings.voice)sound.stop();show('settings',false);if(phase==='menu')drawMenu();settingsReturnFocus?.focus();}
function recover(){if(phase!=='race')return;vehicle.reset(true);lastNote=null;clearInput();toast('RECOVERED TO ROAD · +5.000s');}
function changeCamera(){cameraMode=(cameraMode+1)%3;toast(['CHASE CAMERA','HIGH CHASE CAMERA','BONNET CAMERA'][cameraMode],1.1);}
function readInput(){let gamepad=null;try{gamepad=Array.from(navigator.getGamepads?.()||[]).find(g=>g&&g.mapping==='standard');}catch{}let steer=0,throttle=0,brake=0,handbrake=false;
  if(gamepad){const a=gamepad.axes[0]||0;steer=Math.abs(a)>.12?Math.sign(a)*(Math.abs(a)-.12)/.88:0;throttle=gamepad.buttons[7]?.value||0;brake=gamepad.buttons[6]?.value||0;handbrake=!!gamepad.buttons[0]?.pressed;const now=gamepad.buttons.map(b=>b.pressed);for(const [i,fn]of [[9,pause],[3,changeCamera],[1,recover],[4,()=>vehicle?.shift(-1)],[5,()=>vehicle?.shift(1)]])if(now[i]&&!gamepadButtons[i])fn();gamepadButtons=now;}else gamepadButtons=[];
  if(keys.has('KeyA')||keys.has('ArrowLeft')||touch.has('left'))steer-=1;if(keys.has('KeyD')||keys.has('ArrowRight')||touch.has('right'))steer+=1;
  if(keys.has('KeyW')||keys.has('ArrowUp')||touch.has('throttle'))throttle=1;if(keys.has('KeyS')||keys.has('ArrowDown')||touch.has('brake'))brake=1;if(keys.has('Space')||touch.has('handbrake'))handbrake=true;
  return {steer:clamp(steer,-1,1),throttle,brake,handbrake};
}
function record(){if(samples.length&&+vehicle.elapsed.toFixed(3)<=samples.at(-1)[0])return;if(vehicle.elapsed-lastSample<.10&&!vehicle.finished)return;lastSample=vehicle.elapsed;samples.push([+vehicle.elapsed.toFixed(3),+vehicle.x.toFixed(3),+vehicle.y.toFixed(3),+vehicle.z.toFixed(3),+vehicle.yaw.toFixed(4),+vehicle.pitch.toFixed(4),+vehicle.roll.toFixed(4)]);if(samples.length>18000)samples.splice(0,2);}
function complete(){if(phase!=='race')return;record();phase='results';sound.stop();clearInput();carryDamage=vehicle.damage;show('hud',false);show('countdown',false);const pb=records.save(stage.def.id,CARS[carIndex].id,vehicle.total,samples,runOptions.assists);if(cup)cup.results.push({stage:stageIndex,time:vehicle.total,damage:vehicle.damage});$('result-eyebrow').textContent=`SS 0${stageIndex+1} / ${stage.def.name}`;$('result-heading').textContent=cup&&stageIndex===5?'The rally is yours.':'Across the line.';$('result-time').textContent=formatTime(vehicle.total);$('result-medal').textContent=`${medal(vehicle.total,stage.def.target)}${pb?' · PERSONAL BEST':''}`;$('result-detail').textContent=`Driving ${formatTime(vehicle.elapsed)} · Penalties ${vehicle.penalty.toFixed(0)}s · Car condition ${Math.round(100-vehicle.damage)}%. Gold target ${formatTime(stage.def.target)}.`;$('split-results').innerHTML=vehicle.splits.map((t,i)=>`<div class="split-row"><span>${i===3?'FINISH':`SPLIT 0${i+1}`}</span><b>${formatTime(t)}</b><span>${t-stage.def.target*(i+1)/4>=0?'+':'−'}${Math.abs(t-stage.def.target*(i+1)/4).toFixed(2)}s / target</span></div>`).join('');
  $('cup-summary').textContent=cup?`${cup.results.length}/6 stages · Rally total ${formatTime(cup.results.reduce((sum,r)=>sum+r.time,0)+cup.servicePenalty)}${cup.servicePenalty?` · Includes ${cup.servicePenalty}s service`:''}`:'';
  $('next').textContent=cup&&stageIndex<5?'NEXT STAGE →':'BACK TO THE MENU →';$('retry').hidden=!!cup;show('results');$('next').focus();if(records.warning)toast(records.warning,5);
}
async function nextStage(){if(!cup||stageIndex===5){toMenu();return;}if(stageIndex===1||stageIndex===3){show('results',false);show('service');$('service-detail').textContent=`Two stages down. Current car condition: ${Math.round(100-carryDamage)}%.`;$('repair').focus();return;}await loadStage(stageIndex+1,true);}
function service(repair){if(repair){carryDamage=0;cup.servicePenalty+=20;}show('service',false);void loadStage(stageIndex+1,true);}
function replay(){if(!samples.length)return;phase='replay';replayTime=0;show('results',false);show('replay-bar');sound.stop();}
function endReplay(){phase='results';show('replay-bar',false);show('results');}
function drawMap(){const c=$('map'),ctx=c.getContext('2d'),points=stage.points,minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minZ=Math.min(...points.map(p=>p.z)),maxZ=Math.max(...points.map(p=>p.z)),scale=Math.min(175/(maxX-minX||1),135/(maxZ-minZ||1));const point=p=>[120+(p.x-(minX+maxX)/2)*scale,93-(p.z-(minZ+maxZ)/2)*scale];ctx.clearRect(0,0,240,190);ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();points.forEach((p,i)=>{const q=point(p);i?ctx.lineTo(...q):ctx.moveTo(...q);});ctx.strokeStyle='#10261aaa';ctx.lineWidth=8;ctx.stroke();ctx.strokeStyle='#d4ddbcaa';ctx.lineWidth=2.5;ctx.stroke();for(const s of stage.checkpoints){const q=point(stage.at(s));ctx.beginPath();ctx.arc(...q,2.6,0,Math.PI*2);ctx.fillStyle=s<=vehicle.progress?'#f4ad58':'#f1efde';ctx.fill();}const q=point(vehicle);ctx.save();ctx.translate(...q);ctx.rotate(vehicle.yaw);ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(4.5,5);ctx.lineTo(0,3);ctx.lineTo(-4.5,5);ctx.closePath();ctx.fillStyle='#f4ad58';ctx.shadowColor='#071c15';ctx.shadowBlur=5;ctx.fill();ctx.restore();}
function updateHUD(){if(!vehicle)return;$('time').textContent=formatTime(vehicle.total);$('penalty').textContent=vehicle.penalty?`+${vehicle.penalty.toFixed(0)}s PENALTIES`:'';$('speed').textContent=Math.round(Math.abs(vehicle.speed)*3.6);$('gear').textContent=vehicle.reverse?'R':vehicle.gear;$('rpm-bar').style.width=`${clamp(vehicle.rpm/7800,0,1)*100}%`;$('rpm-text').textContent=`${Math.round(vehicle.rpm/100)*100} RPM`;$('health-text').textContent=`${Math.round(100-vehicle.damage)}%`;$('health-bar').style.width=`${100-vehicle.damage}%`;$('health-bar').style.background=vehicle.damage>65?'#ef7957':'#c5d89f';$('progress-bar').style.width=`${clamp(vehicle.progress/stage.finish,0,1)*100}%`;$('remaining').textContent=`${(Math.max(0,stage.finish-vehicle.progress)/1000).toFixed(2)} KM TO FINISH`;$('hud-surface').textContent=vehicle.progress>stage.checkpoints[vehicle.checkpoint]+25?'MISSED CONTROL · R TO RECOVER +5S':vehicle.airborne?'AIRBORNE':vehicle.surface;$('camera-label').textContent=['CHASE CAM','HIGH CHASE','BONNET CAM'][cameraMode];const note=nextNote(stage,vehicle.progress,vehicle.speed);if(note){$('pace-arrow').textContent=note.dir==='RIGHT'?'↱':'↰';$('pace-grade').textContent=note.grade;$('pace-distance').textContent=`${Math.max(0,Math.round((note.s-vehicle.progress)/10)*10)} M`;$('pace-extra').textContent=note.text.includes('tightens')?'TIGHTENS':'';if(phase==='race'&&lastNote!==note){lastNote=note;sound.say(`${note.text}, ${Math.max(0,Math.round((note.s-vehicle.progress)/10)*10)} metres`);}}else{$('pace-arrow').textContent='↑';$('pace-grade').textContent='';$('pace-distance').textContent='KEEP GOING';$('pace-extra').textContent='';}drawMap();}
function frame(now){const dt=lastFrame?Math.min(.1,(now-lastFrame)/1000):1/60;lastFrame=now;try{
  if(vehicle&&phase!=='loading'){
    // Poll even when paused so the controller Start button can resume play.
    lastInput=readInput();
    if(phase==='countdown'){countdown-=dt;const n=Math.ceil(countdown);if(n!==countBeep&&n>0){countBeep=n;$('countdown').textContent=n;sound.beep(560,.10,.18);}if(countdown<=0){phase='race';$('countdown').textContent='GO';sound.beep(950,.25,.17);toast('KEEP IT CLEAN. LISTEN TO YOUR CO-DRIVER.',2.5);}}
    if(phase==='race'){accumulator+=dt;while(accumulator>=1/120&&phase==='race'){vehicle.step(lastInput,1/120,runOptions);accumulator-=1/120;record();if(vehicle.lastImpact>3)toast(`IMPACT · CAR CONDITION ${Math.round(100-vehicle.damage)}%`,1.8);if(vehicle.checkpoint>lastCheckpoint){lastCheckpoint=vehicle.checkpoint;if(!vehicle.finished){const delta=vehicle.total-stage.def.target*lastCheckpoint/4;toast(`SPLIT ${lastCheckpoint} · ${delta>=0?'+':'−'}${Math.abs(delta).toFixed(2)}s TO TARGET`,3);sound.beep(840,.09,.09);}}if(vehicle.finished)complete();}if(vehicle.elapsed>1)show('countdown',false);}
    sound.update(vehicle,lastInput,phase==='race'||phase==='countdown');
    let display=vehicle,ghost=null;
    if(phase==='replay'){replayTime=Math.min(replayTime+dt,samples.at(-1)?.[0]||0);display=ghostPose(samples,replayTime)||vehicle;$('replay-time').textContent=formatTime(replayTime);if(replayTime>=(samples.at(-1)?.[0]||0))endReplay();}
    if(phase==='race'&&settings.ghost&&best?.samples)ghost=ghostPose(best.samples,vehicle.elapsed);
    renderer.render(display,carIndex,{dt,menu:phase==='menu',cameraMode,ghost,replay:phase==='replay',active:phase==='race'});
    hudTick+=dt;if(hudTick>.08&&(phase==='race'||phase==='countdown')){hudTick=0;updateHUD();}
  }
  if(now>toastUntil)show('toast',false);
}catch(error){phase='error';console.error(error);show('loading',false);show('error');$('error-message').textContent=error.message;sound.stop();return;}
requestAnimationFrame(frame);}
$('cars').addEventListener('click',e=>{const button=e.target.closest('[data-car]');if(!button||phase!=='menu')return;carIndex=Number(button.dataset.car);vehicle=new Vehicle(stage,CARS[carIndex]);drawMenu();});
$('stages').addEventListener('click',e=>{const button=e.target.closest('[data-stage]');if(!button||phase!=='menu')return;void loadStage(Number(button.dataset.stage));});
$('mode').addEventListener('change',drawMenu);$('start').addEventListener('click',start);$('pause').addEventListener('click',pause);$('resume').addEventListener('click',resume);$('restart').addEventListener('click',restart);$('quit').addEventListener('click',toMenu);$('camera').addEventListener('click',changeCamera);$('settings-button').addEventListener('click',openSettings);$('pause-settings').addEventListener('click',openSettings);$('settings-close').addEventListener('click',closeSettings);$('retry').addEventListener('click',restart);$('result-menu').addEventListener('click',toMenu);$('next').addEventListener('click',()=>void nextStage());$('repair').addEventListener('click',()=>service(true));$('no-repair').addEventListener('click',()=>service(false));$('replay').addEventListener('click',replay);$('end-replay').addEventListener('click',endReplay);
window.addEventListener('keydown',e=>{
  if(e.code==='Escape'){e.preventDefault();if(!$('settings').hidden)closeSettings();else if(phase==='replay')endReplay();else pause();return;}
  if(e.target.matches('input,select,textarea')||!$('settings').hidden)return;
  if(['race','countdown','paused'].includes(phase)&&['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();
  if(phase==='race'||phase==='countdown')keys.add(e.code);if(e.repeat)return;
  if(e.code==='KeyC'&&phase==='race')changeCamera();if(e.code==='KeyR')recover();if(e.code==='KeyM'){settings.sound=!settings.sound;if(!settings.sound)sound.stop();toast(settings.sound?'SOUND ON':'SOUND OFF',1);}
  if(phase==='race'&&!runOptions.automatic){if(e.code==='KeyQ')vehicle.shift(-1);if(e.code==='KeyE')vehicle.shift(1);}
  if(e.code==='Enter'&&phase==='menu'&&e.target===document.body)void start();
});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{clearInput();if(phase==='race'||phase==='countdown')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(phase==='race'||phase==='countdown')pause();}});window.addEventListener('gamepaddisconnected',()=>{gamepadButtons=[];clearInput();if(phase==='race')pause();});
for(const button of document.querySelectorAll('[data-control]')){const end=e=>{e.preventDefault();touch.delete(button.dataset.control);button.classList.remove('pressed');};button.addEventListener('pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);touch.add(button.dataset.control);button.classList.add('pressed');});button.addEventListener('pointerup',end);button.addEventListener('pointercancel',end);button.addEventListener('lostpointercapture',()=>{touch.delete(button.dataset.control);button.classList.remove('pressed');});}
// Keep keyboard focus inside open modal panels. The shared Almanac link remains independent.
document.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const modal=['settings','service','results','paused'].map($).find(n=>!n.hidden);if(!modal)return;const controls=[...modal.querySelectorAll('button,input,select')].filter(n=>!n.disabled&&!n.hidden&&n.offsetParent!==null);if(!controls.length)return;const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
await paint();renderer=new Renderer($('world'),settings.quality);renderer.onLost=()=>{if(phase==='race'||phase==='countdown')pause();$('error-message').textContent='The graphics context was lost. Reload the page to restart; saved personal bests are retained.';show('error');sound.stop();phase='error';};await loadStage(0);requestAnimationFrame(frame);
// Read-only public telemetry; deterministic test controls only exist with an explicit ?test URL.
Object.defineProperty(window,'rallyTelemetry',{get:()=>({phase,stage:stageIndex,car:carIndex,time:vehicle?.total,speed:vehicle?.speed,progress:vehicle?.progress,damage:vehicle?.damage,checkpoint:vehicle?.checkpoint,finished:vehicle?.finished})});
if(new URLSearchParams(location.search).has('test'))window.rallyTest={stageCache,renderer,get vehicle(){return vehicle;},get recording(){return samples;},get phase(){return phase;},start,loadStage,step(input,seconds){if(phase==='countdown'){phase='race';show('countdown',false);}for(let t=0;t<seconds&&phase==='race';t+=1/120){vehicle.step(input,1/120,runOptions);record();if(vehicle.finished)complete();}updateHUD();},setCar(index){carIndex=clamp(index,0,1);vehicle=new Vehicle(stage,CARS[carIndex]);drawMenu();}};
