from __future__ import annotations

import dataclasses
import datetime as dt
import hashlib
import json
import re
from collections import Counter
from pathlib import Path
from typing import Any, Iterable, Literal
from urllib.parse import urlparse

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from .schema import Example

PROFILE_SCHEMA = "scribeprint.human-benchmark-profile.v1"
MANIFEST_SCHEMA = "scribeprint.human-benchmark-manifest.v1"
LOCK_SCHEMA = "scribeprint.human-benchmark-lock.v1"
AUDIT_SCHEMA = "scribeprint.human-benchmark-audit.v1"
RECORD_SCHEMA = "scribeprint.human-benchmark-record.v1"

_WORD = re.compile(r"[A-Za-zÀ-ÖØ-öø-ÿ0-9]+(?:['’\-][A-Za-zÀ-ÖØ-öø-ÿ0-9]+)?")
_URL = re.compile(r"https?://\S+", flags=re.IGNORECASE)
_AI_MARKER = re.compile(
    r"\b(?:as an ai(?: language model)?|i (?:cannot|can't) (?:assist|comply|fulfil|fulfill)|"
    r"generated by (?:chatgpt|an? ai)|openai's? (?:chatgpt|gpt))\b",
    flags=re.IGNORECASE,
)
_IRC_PREFIX = re.compile(
    r"(?:^|\s)\[\d{2}:\d{2}(?::\d{2})?\]\s+(?:<[^>]{1,80}>|\*\s+\S+)\s*",
    flags=re.MULTILINE,
)
_SPACE = re.compile(r"[ \t]+")
_BLANKS = re.compile(r"\n{3,}")


def _sha256(value: str | bytes) -> str:
    if isinstance(value, str):
        value = value.encode("utf-8")
    return hashlib.sha256(value).hexdigest()


def _stable_int(*parts: object) -> int:
    payload = "\0".join(str(part) for part in parts)
    return int.from_bytes(hashlib.blake2b(payload.encode("utf-8"), digest_size=8).digest(), "big")


def _canonical_space(text: str) -> str:
    text = text.replace("\x00", "").replace("\r\n", "\n").replace("\r", "\n")
    lines = [_SPACE.sub(" ", line).strip() for line in text.splitlines()]
    return _BLANKS.sub("\n\n", "\n".join(lines)).strip()


def _word_count(text: str) -> int:
    return len(_WORD.findall(text))


def _text_hash(text: str) -> str:
    return _sha256(re.sub(r"\s+", " ", text).strip().casefold())


def _get_path(row: Any, path: str | None, default: Any = None) -> Any:
    if not path:
        return default
    value = row
    for part in path.split("."):
        if isinstance(value, dict):
            if part not in value:
                return default
            value = value[part]
        elif isinstance(value, (list, tuple)) and part.isdigit():
            index = int(part)
            if index >= len(value):
                return default
            value = value[index]
        else:
            return default
    return value


def _flatten_strings(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        candidate = value.strip()
        return [candidate] if candidate else []
    if isinstance(value, dict):
        output: list[str] = []
        for nested in value.values():
            output.extend(_flatten_strings(nested))
        return output
    if isinstance(value, (list, tuple, set)):
        output = []
        for nested in value:
            output.extend(_flatten_strings(nested))
        return output
    return [str(value)]


def _parse_datetime(value: Any) -> dt.datetime | None:
    if value in (None, ""):
        return None
    if isinstance(value, dt.datetime):
        return value if value.tzinfo else value.replace(tzinfo=dt.timezone.utc)
    if isinstance(value, dt.date):
        return dt.datetime.combine(value, dt.time.min, tzinfo=dt.timezone.utc)
    text = str(value).strip()
    if not text:
        return None
    # Common Pile news uses strings such as "Published on December 13, 2021".
    text = re.sub(r"^published\s+on\s+", "", text, flags=re.IGNORECASE).strip()
    iso = text.replace("Z", "+00:00")
    try:
        parsed = dt.datetime.fromisoformat(iso)
        return parsed if parsed.tzinfo else parsed.replace(tzinfo=dt.timezone.utc)
    except ValueError:
        pass
    for pattern in (
        "%B %d, %Y",
        "%b %d, %Y",
        "%Y-%m-%d",
        "%d %B %Y",
        "%d %b %Y",
    ):
        try:
            return dt.datetime.strptime(text, pattern).replace(tzinfo=dt.timezone.utc)
        except ValueError:
            continue
    match = re.search(r"\b(19\d{2}|20\d{2})\b", text)
    if match:
        return dt.datetime(int(match.group(1)), 1, 1, tzinfo=dt.timezone.utc)
    return None


def _normalise_author(value: str) -> str:
    value = value.strip().casefold()
    value = re.sub(r"https?://", "", value)
    return re.sub(r"\s+", " ", value)


def _find_stackexchange_host(metadata: Any) -> str | None:
    hosts = []
    for value in _flatten_strings(metadata):
        for match in re.finditer(r"https?://([^/\s]+)", value, flags=re.IGNORECASE):
            host = match.group(1).casefold().split(":", 1)[0]
            if host.endswith("stackexchange.com") or host in {
                "stackoverflow.com",
                "serverfault.com",
                "superuser.com",
                "askubuntu.com",
                "mathoverflow.net",
            }:
                hosts.append(host)
    if not hosts:
        return None
    # User profile URLs are repeated in metadata; the modal host is the site.
    return Counter(hosts).most_common(1)[0][0]


def _extract_host(value: Any) -> str | None:
    for candidate in _flatten_strings(value):
        parsed = urlparse(candidate)
        if parsed.hostname:
            return parsed.hostname.casefold()
    return None


class FilterSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    field: str
    op: Literal[
        "eq",
        "neq",
        "in",
        "not_in",
        "contains",
        "not_contains",
        "regex",
        "not_regex",
        "exists",
    ] = "eq"
    value: Any = None


class BenchmarkSourceSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    adapter: Literal["huggingface", "local_jsonl", "fce_xml"] = "huggingface"
    dataset: str
    revision: str = "main"
    split: str = "train"
    path_env: str | None = None
    required: bool = True
    redistributable: bool = False

    domain: str
    subdomain: str | None = None
    writer_population: str
    target: int = Field(gt=0)
    max_scan: int = Field(gt=0)
    oversample: int = Field(default=8, ge=1, le=50)
    shuffle_buffer: int = Field(default=20_000, ge=100)
    interleave_shards: bool = False

    text_field: str = "text"
    id_field: str = "id"
    date_field: str | None = None
    author_fields: list[str] = Field(default_factory=lambda: ["metadata.authors", "metadata.author"])
    licence_field: str | None = "metadata.license"
    url_field: str | None = "metadata.url"
    stratum_field: str | None = None
    stratum_transform: Literal["none", "lower", "host", "stackexchange_host"] = "none"

    licence_allow: list[str] = Field(default_factory=list)
    fixed_licence: str | None = None
    filters: list[FilterSpec] = Field(default_factory=list)
    transforms: list[Literal["normalise", "irc_dialogue", "pep_body"]] = Field(
        default_factory=lambda: ["normalise"]
    )

    min_words: int = Field(default=150, ge=20)
    max_words: int = Field(default=700, ge=100)
    target_words_min: int = Field(default=320, ge=50)
    target_words_max: int = Field(default=650, ge=100)
    maximum_url_density: float = Field(default=0.04, ge=0, le=1)
    minimum_alpha_ratio: float = Field(default=0.50, ge=0, le=1)
    maximum_duplicate_line_ratio: float = Field(default=0.45, ge=0, le=1)
    maximum_raw_characters: int = Field(default=1_000_000, ge=50_000)
    raw_slice_characters: int = Field(default=160_000, ge=20_000)

    historic_pre_llm: bool = False
    pre_llm_basis: str | None = None
    max_per_author: int = Field(default=3, ge=0)
    max_per_stratum: int = Field(default=250, ge=0)

    @model_validator(mode="after")
    def validate_source(self) -> "BenchmarkSourceSpec":
        if self.adapter != "huggingface" and not self.path_env:
            raise ValueError(f"{self.id}: local adapters require path_env")
        if self.historic_pre_llm and not self.pre_llm_basis:
            raise ValueError(f"{self.id}: historic_pre_llm requires pre_llm_basis")
        if self.target_words_min > self.target_words_max:
            raise ValueError(f"{self.id}: target_words_min exceeds target_words_max")
        if self.target_words_max > self.max_words:
            raise ValueError(f"{self.id}: target_words_max exceeds max_words")
        if self.max_scan < self.target:
            raise ValueError(f"{self.id}: max_scan must be at least target")
        if self.raw_slice_characters > self.maximum_raw_characters:
            raise ValueError(f"{self.id}: raw_slice_characters exceeds maximum_raw_characters")
        return self


class BenchmarkProfile(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    schema_version: Literal[PROFILE_SCHEMA] = Field(default=PROFILE_SCHEMA, alias="schema")
    benchmark_id: str
    description: str
    seed: int = 4433
    pre_llm_cutoff: dt.datetime
    minimum_total: int = Field(gt=0)
    near_duplicate_threshold: float = Field(default=0.90, ge=0.5, le=1.0)
    required_domains: dict[str, int] = Field(default_factory=dict)
    production_required_writer_populations: dict[str, int] = Field(default_factory=dict)
    sources: list[BenchmarkSourceSpec]

    @field_validator("pre_llm_cutoff", mode="before")
    @classmethod
    def parse_cutoff(cls, value: Any) -> dt.datetime:
        parsed = _parse_datetime(value)
        if parsed is None:
            raise ValueError("pre_llm_cutoff must be a parseable date")
        return parsed

    @model_validator(mode="after")
    def validate_profile(self) -> "BenchmarkProfile":
        ids = [source.id for source in self.sources]
        if len(ids) != len(set(ids)):
            raise ValueError("source ids must be unique")
        if sum(source.target for source in self.sources if source.required) < self.minimum_total:
            raise ValueError("required source targets do not reach minimum_total")
        return self


class BenchmarkRecord(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    schema_version: Literal[RECORD_SCHEMA] = Field(default=RECORD_SCHEMA, alias="schema")
    id: str
    text: str
    source_id: str
    source_dataset: str
    source_revision: str
    benchmark_source: str
    source_url: str | None = None
    source_licence: str
    redistributable: bool
    domain: str
    subdomain: str | None = None
    writer_population: str
    language: str = "en"
    document_date: str | None = None
    pre_llm_basis: str
    author_hashes: list[str] = Field(default_factory=list)
    stratum: str | None = None
    word_count: int = Field(gt=0)
    text_sha256: str
    transform_version: str = "human-benchmark-v1"

    def as_example(self) -> Example:
        return Example(
            id=self.id,
            text=self.text,
            label="human",
            split="test",
            source_id=f"{self.source_dataset}:{self.source_id}",
            domain=self.domain,
            subdomain=self.subdomain,
            language=self.language,
            writer_population=self.writer_population,
            created_at=self.document_date,
            human_provenance=(
                f"Human-only benchmark source {self.source_dataset}@{self.source_revision}; "
                f"pre-LLM basis: {self.pre_llm_basis}"
            ),
            licence=self.source_licence,
            metadata={
                "benchmark_schema": RECORD_SCHEMA,
                "benchmark_source": self.benchmark_source,
                "source_dataset": self.source_dataset,
                "source_revision": self.source_revision,
                "source_url": self.source_url,
                "source_licence": self.source_licence,
                "redistributable": self.redistributable,
                "pre_llm_basis": self.pre_llm_basis,
                "author_hashes": self.author_hashes,
                "stratum": self.stratum,
                "word_count": self.word_count,
                "text_sha256": self.text_sha256,
                "transform_version": self.transform_version,
            },
        )

    def lock_row(self) -> dict[str, Any]:
        row = self.model_dump(exclude={"text", "schema_version"}, by_alias=True)
        row["schema"] = LOCK_SCHEMA
        return row


@dataclasses.dataclass(slots=True)
class Candidate:
    source_id: str
    text: str
    text_sha256: str
    document_date: dt.datetime | None
    authors: list[str]
    licence: str
    source_url: str | None
    stratum: str | None
    priority: int


@dataclasses.dataclass(slots=True)
class AdapterResult:
    rows: Iterable[dict[str, Any]]
    resolved_revision: str
    source_reference: str


def load_profile(path: str | Path) -> tuple[BenchmarkProfile, str]:
    path = Path(path)
    source = path.read_text(encoding="utf-8")
    profile = BenchmarkProfile.model_validate_json(source)
    canonical = json.dumps(json.loads(source), sort_keys=True, separators=(",", ":"))
    return profile, _sha256(canonical)
