// All ECML historical data
// Sources: Wikipedia, NBR Study Group, GNR Society, RSSB, Network Rail, BBC, Grokipedia

const STATIONS = [
  { id: 'edi', name: 'Edinburgh Waverley', x: 270, y: 92,  side: 'L', mile: 393, opened: 1846 },
  { id: 'dun', name: 'Dunbar',             x: 300, y: 128, side: 'R', mile: 364, opened: 1846 },
  { id: 'res', name: 'Reston',             x: 314, y: 158, side: 'R', mile: 345, opened: 1846 },
  { id: 'ber', name: 'Berwick-upon-Tweed', x: 327, y: 188, side: 'R', mile: 335, opened: 1846 },
  { id: 'aln', name: 'Alnmouth',           x: 330, y: 232, side: 'R', mile: 304, opened: 1847 },
  { id: 'mor', name: 'Morpeth',            x: 332, y: 268, side: 'R', mile: 287, opened: 1847 },
  { id: 'ncl', name: 'Newcastle',          x: 330, y: 296, side: 'R', mile: 268, opened: 1850 },
  { id: 'dur', name: 'Durham',             x: 320, y: 322, side: 'L', mile: 254, opened: 1857 },
  { id: 'cle', name: 'Chester-le-Street',  x: 324, y: 308, side: 'R', mile: 261, opened: 1868 },
  { id: 'dar', name: 'Darlington',         x: 310, y: 355, side: 'L', mile: 232, opened: 1841 },
  { id: 'nth', name: 'Northallerton',      x: 304, y: 380, side: 'R', mile: 218, opened: 1841 },
  { id: 'thi', name: 'Thirsk',             x: 302, y: 398, side: 'R', mile: 209, opened: 1841 },
  { id: 'yrk', name: 'York',               x: 296, y: 425, side: 'L', mile: 188, opened: 1839 },
  { id: 'dnc', name: 'Doncaster',          x: 288, y: 475, side: 'L', mile: 156, opened: 1849 },
  { id: 'rtf', name: 'Retford',            x: 292, y: 502, side: 'R', mile: 138, opened: 1849 },
  { id: 'nwk', name: 'Newark North Gate',  x: 294, y: 538, side: 'R', mile: 120, opened: 1852 },
  { id: 'grn', name: 'Grantham',           x: 290, y: 568, side: 'L', mile: 105, opened: 1852 },
  { id: 'ptb', name: 'Peterborough',       x: 284, y: 615, side: 'L', mile: 76,  opened: 1850 },
  { id: 'stv', name: 'Stevenage',          x: 272, y: 692, side: 'L', mile: 27,  opened: 1850 },
  { id: 'kgx', name: "London King's Cross",x: 270, y: 740, side: 'R', mile: 0,   opened: 1852 },
];

// Three founding companies — each owns a colour and a stretch
const COMPANIES = [
  {
    id: 'nbr',
    name: 'North British Railway',
    short: 'NBR',
    period: '1844 – 1922',
    colour: '#7a3b1f',          // burgundy
    stretch: 'Edinburgh → Berwick-upon-Tweed',
    miles: '58 mi',
    hq: 'Edinburgh',
    chairmen: ['John Learmonth (1842)', 'Richard Hodgson (1855)'],
    body: 'Promoters first met on 8 January 1842 to build a 57-mile line linking Edinburgh with Berwick. Incorporated by Act of Parliament on 4 July 1844; the line opened 18 June 1846. Physically joined to the NER at Berwick on 29 August 1850 when Robert Stephenson’s Royal Border Bridge was opened by Queen Victoria — completing the through route to London.',
  },
  {
    id: 'ner',
    name: 'North Eastern Railway',
    short: 'NER',
    period: '1854 – 1922',
    colour: '#1c4a3a',          // bottle green
    stretch: 'Berwick-upon-Tweed → Shaftholme Jct',
    miles: '~180 mi',
    hq: 'York',
    chairmen: ['George Leeman', 'Lord Grey'],
    body: 'Formed in 1854 by amalgamation of the York, Newcastle & Berwick, the York & North Midland, and the Leeds Northern. Inherited Robert Stephenson’s High Level Bridge (Newcastle, 1849) and the Royal Border Bridge (1850). In 1871 it opened a direct line south of York via Selby to make an end-on junction with the GNR at Shaftholme — famously described as "a ploughed field four miles north of Doncaster".',
  },
  {
    id: 'gnr',
    name: 'Great Northern Railway',
    short: 'GNR',
    period: '1846 – 1922',
    colour: '#1a3a5f',          // navy
    stretch: 'Shaftholme → London King’s Cross',
    miles: '156 mi',
    hq: "King's Cross, London",
    chairmen: ['Edmund Denison'],
    body: 'Authorised 1846 after fierce parliamentary fights with George Hudson’s Midland interests. Engineer Joseph Cubitt drove the "Towns Line" via Peterborough, Grantham, Newark, Retford and Doncaster. King’s Cross terminus opened 14 October 1852 — Lewis Cubitt’s austere twin-arch shed, then the largest station in Britain. Through running to Edinburgh began the same year.',
  },
];

// Operators of the through service, in chronological order
const OPERATORS = [
  { id:'ecjs',  start:1860, end:1922, name:'East Coast Joint Stock',          colour:'#8b6b3f', note:'Collaborative rolling stock pool — NBR + NER + GNR' },
  { id:'lner',  start:1923, end:1947, name:'London & North Eastern Railway',  colour:'#7a8a2a', note:'Created by the Grouping (Railways Act 1921). Gresley era.' },
  { id:'br',    start:1948, end:1994, name:'British Railways / British Rail', colour:'#a82828', note:'Nationalisation. Deltics 1961, HSTs 1978, full wires 1991.' },
  { id:'gner',  start:1996, end:2007, name:'GNER (Sea Containers)',           colour:'#16284a', note:'Famous dark-blue livery and "Route of the Flying Scotsman".' },
  { id:'nxec',  start:2007, end:2009, name:'National Express East Coast',     colour:'#cc5500', note:'Handed back the keys when revenue collapsed.' },
  { id:'eco',   start:2009, end:2015, name:'East Coast (DOR)',                colour:'#26566f', note:'Operator of Last Resort — publicly owned, returned £1bn premium.' },
  { id:'vtec',  start:2015, end:2018, name:'Virgin Trains East Coast',        colour:'#9c1a1a', note:'Stagecoach/Virgin JV. Walked away after over-bidding.' },
  { id:'lner2', start:2018, end:2099, name:'London North Eastern Railway',    colour:'#a4133c', note:'Public OLR; Azuma (Class 800/801) bi-modes from 2019.' },
];

// All milestone events
const EVENTS = [
  { year:1825, label:'Stockton & Darlington opens — world’s first public steam railway. Serves the eventual ECML town of Darlington.', tag:'origin', loc:'dar' },
  { year:1839, label:'Y&NMR opens York to Normanton — York gains its first railway, 13 years before through trains to London.', tag:'origin', loc:'yrk' },
  { year:1841, label:'Great North of England Railway opens Darlington–York.', tag:'origin', loc:'dar' },
  { year:1842, label:'8 January — first meeting of promoters for the Edinburgh-to-Berwick line, parent of the NBR.', tag:'origin', loc:'edi' },
  { year:1844, label:'4 July — North British Railway Act of Parliament.', tag:'origin', loc:'edi' },
  { year:1846, label:'18 June — NBR opens Edinburgh (North Bridge) to Berwick.', tag:'open', loc:'ber' },
  { year:1846, label:'Great Northern Railway authorised after the most expensive parliamentary contest in British railway history.', tag:'origin', loc:'kgx' },
  { year:1849, label:'High Level Bridge at Newcastle opens — Robert Stephenson’s double-deck rail/road bridge across the Tyne.', tag:'engineering', loc:'ncl' },
  { year:1849, label:'GNR running powers over the NER agreed (Shaftholme Jct → York).', tag:'agreement', loc:'yrk' },
  { year:1850, label:'7 August — Queen Victoria opens Newcastle Central Station (John Dobson).', tag:'engineering', loc:'ncl' },
  { year:1850, label:'29 August — Royal Border Bridge at Berwick opened by Queen Victoria. The ECML is now physically continuous.', tag:'milestone', loc:'ber' },
  { year:1850, label:'7 August — first GNR trains run to a temporary Maiden Lane terminus.', tag:'open', loc:'kgx' },
  { year:1852, label:'14 October — Lewis Cubitt’s King’s Cross opens; through London-to-Edinburgh services begin.', tag:'milestone', loc:'kgx' },
  { year:1854, label:'North Eastern Railway formed by merger of three companies — controls the middle stretch.', tag:'company', loc:'yrk' },
  { year:1860, label:'East Coast Joint Stock created — first purpose-built through rolling-stock pool in Britain.', tag:'agreement', loc:'yrk' },
  { year:1862, label:'10:00 King’s Cross departure named the "Special Scotch Express" — later "The Flying Scotsman".', tag:'service', loc:'kgx' },
  { year:1868, label:'Edinburgh Waverley opens as a unified NBR terminus in the valley between Old and New Towns.', tag:'station', loc:'edi' },
  { year:1871, label:'NER opens its direct Shaftholme–Selby–York line, shortening the route and breaking with the Knottingley diversion.', tag:'engineering', loc:'dnc' },
  { year:1876, label:'21 January — Abbots Ripton accident. Frozen signals stuck "clear" in a snowstorm; three-train pile-up. 13 dead. The disaster that converted Britain to "normally at danger" signalling.', tag:'accident', loc:'ptb' },
  { year:1888, label:'First "Race to the North" — ECML and WCML expresses compete openly for the fastest London-to-Edinburgh time.', tag:'race', loc:'kgx' },
  { year:1890, label:'Forth Bridge opens — Benjamin Baker & John Fowler’s 8,094-ft cantilever marvel; extends ECML thinking to Aberdeen.', tag:'engineering', loc:'edi' },
  { year:1895, label:'Second Race to the North — 8h 40m London–Aberdeen on the East Coast. Races abandoned over safety concerns.', tag:'race', loc:'kgx' },
  { year:1906, label:'King Edward VII Bridge opens at Newcastle, finally giving the ECML a through route — no more reversal at Newcastle Central.', tag:'engineering', loc:'ncl' },
  { year:1923, label:'1 January — Grouping. NBR + NER + GNR (and 30+ others) become the London & North Eastern Railway. The LNER’s flagship route.', tag:'company', loc:'kgx' },
  { year:1928, label:'1 May — non-stop "Flying Scotsman" begins, 392 miles King’s Cross to Edinburgh, made possible by Gresley’s corridor tender.', tag:'service', loc:'kgx' },
  { year:1934, label:'30 November — Flying Scotsman (LNER A1 4472) becomes the first locomotive in the world authenticated at 100 mph.', tag:'record', loc:'grn' },
  { year:1935, label:'27 September — Silver Jubilee, first British streamlined service, opens. Gresley A4 Pacifics in silver-grey livery.', tag:'service', loc:'kgx' },
  { year:1938, label:'3 July — Mallard (A4 4468) reaches 126 mph down Stoke Bank south of Grantham. World steam record, still unbroken.', tag:'record', loc:'grn' },
  { year:1947, label:'26 October — Goswick accident, just south of Berwick. The "Flying Scotsman" overruns signals and takes a 15 mph crossover at 60+ mph. 28 dead. Hastens BR\u2019s Automatic Warning System.', tag:'accident', loc:'ber' },
  { year:1948, label:'1 January — Nationalisation. LNER becomes the Eastern, North Eastern and Scottish Regions of British Railways.', tag:'company', loc:'kgx' },
  { year:1955, label:'Modernisation Plan: steam to be replaced by diesel. ECML earmarked for early treatment.', tag:'plan', loc:'kgx' },
  { year:1961, label:'English Electric "Deltic" (Class 55) enters service. 22 locos, 3,300 hp, twin Napier engines — cut London–Edinburgh to 6 hours.', tag:'loco', loc:'kgx' },
  { year:1973, label:'Prototype HST (Class 41) records 143 mph on the ECML — still the world diesel record.', tag:'record', loc:'ptb' },
  { year:1976, label:'First phase of 25 kV electrification: King’s Cross to Hitchin energised (Great Northern Suburban scheme).', tag:'engineering', loc:'stv' },
  { year:1978, label:'May — InterCity 125 (HST) takes over from Deltics on the principal expresses. New 4½-hour London–Edinburgh timing.', tag:'loco', loc:'kgx' },
  { year:1983, label:'Selby Diversion opens. New 14-mile alignment between Temple Hirst and Colton Junction bypasses the Selby coalfield.', tag:'engineering', loc:'dnc' },
  { year:1984, label:'July — government authorises full electrification to Edinburgh and Leeds. "The longest construction site in the world."', tag:'plan', loc:'kgx' },
  { year:1989, label:'Wires reach Doncaster and York.', tag:'engineering', loc:'dnc' },
  { year:1990, label:'Wires reach Newcastle. InterCity 225 (Class 91 + Mk 4) introduced. Designed for 140 mph but limited to 125 mph.', tag:'engineering', loc:'ncl' },
  { year:1991, label:'July — electrification complete to Edinburgh Waverley. Best non-stop time falls to 3h 29m.', tag:'milestone', loc:'edi' },
  { year:1996, label:'Privatisation. GNER (Sea Containers) wins the InterCity East Coast franchise; navy livery, fine dining returns.', tag:'company', loc:'kgx' },
  { year:2000, label:'17 October — Hatfield rail crash. GNER 12:10 King’s Cross–Leeds derails at 115 mph on a fatigued rail. 4 killed.', tag:'accident', loc:'stv' },
  { year:2001, label:'28 February — Great Heck (Selby). Land Rover from M62 ends up on the line; ICE 225 hits it, derails into a coal train. 10 killed. Highest closing speed of any UK rail accident.', tag:'accident', loc:'dnc' },
  { year:2002, label:'10 May — Potters Bar derailment on the ECML. Faulty points; 7 killed.', tag:'accident', loc:'stv' },
  { year:2002, label:'Network Rail replaces Railtrack after Hatfield-driven collapse.', tag:'company', loc:'kgx' },
  { year:2007, label:'National Express East Coast takes over from GNER after Sea Containers’ parent goes bust.', tag:'company', loc:'kgx' },
  { year:2009, label:'14 November — NXEC hands back the keys. State-owned "East Coast" runs the line for 5 years, returning ~£1bn to the Treasury.', tag:'company', loc:'kgx' },
  { year:2015, label:'1 March — Virgin Trains East Coast (Stagecoach 90% / Virgin 10%) starts. Over-bid and underperforms.', tag:'company', loc:'kgx' },
  { year:2018, label:'24 June — VTEC contract terminated three years early. LNER name revived for the public Operator of Last Resort.', tag:'company', loc:'kgx' },
  { year:2019, label:'Azuma (Hitachi Class 800/801) enters service. HSTs retired after 41 years on the ECML.', tag:'loco', loc:'kgx' },
  { year:2021, label:'Class 91 "Lucky" — the only loco involved in both Hatfield and Selby (it survived both) — finally scrapped.', tag:'trivia', loc:'dnc' },
  { year:2024, label:'Open-access boom: Lumo (Edinburgh), Grand Central (Sunderland/Bradford), Hull Trains all share the wires with LNER.', tag:'service', loc:'kgx' },
  { year:2025, label:'Railway 200 — bicentenary of the Stockton & Darlington, the ECML’s great-grandfather. ECML upgrade programme paused mid-design.', tag:'milestone', loc:'dar' },
];

// Locomotives that defined the line
const LOCOS = [
  {
    id:'stirling',
    name:'Stirling Single',
    builder:'GNR (Patrick Stirling)',
    years:'1870 – 1914',
    speed:'85 mph',
    blurb:'Single 8-ft driving wheel. Hauled the East Coast expresses out of King’s Cross for a generation; one survives at the National Railway Museum, York.',
    swatch:'#1a3a5f',
  },
  {
    id:'ivatt',
    name:'GNR Atlantic (Ivatt)',
    builder:'GNR (Henry Ivatt)',
    years:'1898 – 1950',
    speed:'90 mph',
    blurb:'Britain’s first Atlantic (4-4-2). Took the strain when train weights ballooned. Bridged the gap to Gresley’s Pacifics.',
    swatch:'#1a3a5f',
  },
  {
    id:'a3',
    name:'LNER A1 / A3 Pacific',
    builder:'Gresley (Doncaster)',
    years:'1922 – 1966',
    speed:'108 mph',
    blurb:'No. 4472 Flying Scotsman is one of these. First loco in the world authenticated at 100 mph (30 Nov 1934). 78 built; one — 60103 — still earns its keep on charters.',
    swatch:'#1d6b3a',
  },
  {
    id:'a4',
    name:'LNER A4 Pacific',
    builder:'Gresley (Doncaster, 1935)',
    years:'1935 – 1966',
    speed:'126 mph (Mallard)',
    blurb:'Streamlined; air-smoothed Bugatti-influenced casing. Mallard (4468) holds the world steam speed record since 3 July 1938 on Stoke Bank. Six A4s survive.',
    swatch:'#1f5a7a',
  },
  {
    id:'a1p',
    name:'Peppercorn A1',
    builder:'Peppercorn (Doncaster, post-war)',
    years:'1948 – 1966',
    speed:'100+ mph',
    blurb:'The post-war heavy Pacific. All scrapped — but new-build No. 60163 Tornado entered traffic in 2008, the first main-line steam loco built in Britain in nearly 50 years.',
    swatch:'#7a1f1f',
  },
  {
    id:'deltic',
    name:'Class 55 "Deltic"',
    builder:'English Electric, Vulcan Foundry',
    years:'1961 – 1981',
    speed:'100 mph',
    blurb:'22 locos, twin Napier Deltic 18-cylinder engines, 3,300 hp. Most powerful single-unit diesels in the world at introduction. Cult following on the ECML.',
    swatch:'#1c4a3a',
  },
  {
    id:'hst',
    name:'InterCity 125 (HST)',
    builder:'BREL (Class 43)',
    years:'1978 – 2019',
    speed:'148 mph (test) / 125 mph',
    blurb:'Two power cars top-and-tail Mk3 coaches. Still holds the world diesel speed record at 148 mph. Ran on the ECML for 41 years.',
    swatch:'#a82828',
  },
  {
    id:'ic225',
    name:'InterCity 225 (Class 91)',
    builder:'BREL Crewe',
    years:'1990 – 2024',
    speed:'162 mph (test) / 125 mph',
    blurb:'4,540 kW push-pull electrics. Designed for 140 mph but the infrastructure never got the signalling. Mk4 coaches with DVT at the King’s Cross end.',
    swatch:'#26566f',
  },
  {
    id:'azuma',
    name:'Class 800 / 801 Azuma',
    builder:'Hitachi (Newton Aycliffe)',
    years:'2019 –',
    speed:'125 mph',
    blurb:'Bi-mode (800) and electric-only (801). Build in County Durham, the same ground Stephenson knew. Reaches Aberdeen and Inverness on diesel power off the wires.',
    swatch:'#a4133c',
  },
];

const PEOPLE = [
  { name:'Robert Stephenson', role:'Engineer', dates:'1803 – 1859', note:'High Level Bridge, Royal Border Bridge — physically welded the ECML together.' },
  { name:'George Hudson',     role:'"Railway King"',   dates:'1800 – 1871', note:'Y&NMR / NER architect. Created the York hub, then ruined by fraud in 1849.' },
  { name:'Edmund Denison',    role:'GNR Chairman',     dates:'1787 – 1874', note:'Pushed the GNR Bill through Parliament against Hudson’s Midland.' },
  { name:'Lewis Cubitt',      role:'Architect',        dates:'1799 – 1883', note:'Designed King’s Cross station — two arches, two clocks, no fuss.' },
  { name:'Joseph Cubitt',     role:'GNR Engineer',     dates:'1811 – 1872', note:'Surveyed and built the "Towns Line" from Peterborough northward.' },
  { name:'Patrick Stirling',  role:'GNR Locomotive Supt', dates:'1820 – 1895', note:'The Stirling Single — 8-ft drivers, the most beautiful loco of its age.' },
  { name:'Nigel Gresley',     role:'LNER CME',         dates:'1876 – 1941', note:'A1, A3, A4 Pacifics; the conjugated valve gear; Mallard’s 126 mph.' },
  { name:'Edward Thompson / Arthur Peppercorn', role:'LNER CMEs', dates:'1881–1954 / 1889–1951', note:'Carried Gresley’s legacy through war and into nationalisation.' },
];

const FACTS = [
  { k:'393', v:'miles, King’s Cross to Edinburgh Waverley.' },
  { k:'126', v:'mph — Mallard’s world steam record, 3 July 1938.' },
  { k:'1,600+', v:'bridges, viaducts and culverts on the route.' },
  { k:'1 in 61', v:'steepest gradient — Cockburnspath, climbing out of Dunbar.' },
  { k:'295', v:'levers in York’s old signal box — biggest manual in Britain.' },
  { k:'1850', v:'year the line became physically continuous (Royal Border Bridge).' },
  { k:'5', v:'minutes between trains at peak, south of Peterborough.' },
  { k:'4h 17m', v:'fastest scheduled London – Edinburgh today.' },
];

window.ECML = { STATIONS, COMPANIES, OPERATORS, EVENTS, LOCOS, PEOPLE, FACTS };
