// ============================================================
// Kotoba — answer pool
//   window.WORDS : array of { k: hiragana, r: romaji, m: English gloss }
// Curated common JLPT N5 vocabulary, all hiragana, 3–5 kana cells.
// The puzzle length adapts to the chosen word's cell count.
// Edit here to tune difficulty or add words; keep every entry hiragana.
// ============================================================
window.WORDS = [
  // ---- 3 cells ----
  { k: "あたま", r: "atama", m: "head" },
  { k: "くるま", r: "kuruma", m: "car" },
  { k: "あした", r: "ashita", m: "tomorrow" },
  { k: "たまご", r: "tamago", m: "egg" },
  { k: "さかな", r: "sakana", m: "fish" },
  { k: "やさい", r: "yasai", m: "vegetable" },
  { k: "くだもの", r: "kudamono", m: "fruit" },
  { k: "おかね", r: "okane", m: "money" },
  { k: "かぞく", r: "kazoku", m: "family" },
  { k: "てがみ", r: "tegami", m: "letter" },
  { k: "なまえ", r: "namae", m: "name" },
  { k: "みかん", r: "mikan", m: "mandarin orange" },
  { k: "えいが", r: "eiga", m: "movie" },
  { k: "でんわ", r: "denwa", m: "telephone" },
  { k: "とけい", r: "tokei", m: "clock, watch" },
  { k: "つくえ", r: "tsukue", m: "desk" },
  { k: "めがね", r: "megane", m: "glasses" },
  { k: "かばん", r: "kaban", m: "bag" },
  { k: "さいふ", r: "saifu", m: "wallet" },
  { k: "ぼうし", r: "boushi", m: "hat" },
  { k: "てんき", r: "tenki", m: "weather" },
  { k: "げんき", r: "genki", m: "healthy, lively" },
  { k: "えいご", r: "eigo", m: "English (language)" },
  { k: "きれい", r: "kirei", m: "pretty, clean" },
  { k: "あおい", r: "aoi", m: "blue" },
  { k: "あかい", r: "akai", m: "red" },
  { k: "しろい", r: "shiroi", m: "white" },
  { k: "たかい", r: "takai", m: "tall, expensive" },
  { k: "やすい", r: "yasui", m: "cheap" },
  { k: "さむい", r: "samui", m: "cold (weather)" },
  { k: "あつい", r: "atsui", m: "hot" },
  { k: "はやい", r: "hayai", m: "fast, early" },
  { k: "ふるい", r: "furui", m: "old (thing)" },
  { k: "わるい", r: "warui", m: "bad" },
  { k: "おおい", r: "ooi", m: "many, a lot" },
  { k: "ざっし", r: "zasshi", m: "magazine" },
  { k: "こども", r: "kodomo", m: "child" },
  { k: "ことば", r: "kotoba", m: "word, language" },
  { k: "たてもの", r: "tatemono", m: "building" },

  // ---- 4 cells ----
  { k: "たべもの", r: "tabemono", m: "food" },
  { k: "のみもの", r: "nomimono", m: "drink" },
  { k: "がっこう", r: "gakkou", m: "school" },
  { k: "せんせい", r: "sensei", m: "teacher" },
  { k: "にほんご", r: "nihongo", m: "Japanese (language)" },
  { k: "ともだち", r: "tomodachi", m: "friend" },
  { k: "たまねぎ", r: "tamanegi", m: "onion" },
  { k: "くつした", r: "kutsushita", m: "socks" },
  { k: "しんぶん", r: "shinbun", m: "newspaper" },
  { k: "ひこうき", r: "hikouki", m: "airplane" },
  { k: "くうこう", r: "kuukou", m: "airport" },
  { k: "ぎんこう", r: "ginkou", m: "bank" },
  { k: "だいがく", r: "daigaku", m: "university" },
  { k: "たいへん", r: "taihen", m: "tough, awful" },
  { k: "でんしゃ", r: "densha", m: "train" },
  { k: "かいしゃ", r: "kaisha", m: "company" },
  { k: "おはよう", r: "ohayou", m: "good morning" },
  { k: "たべます", r: "tabemasu", m: "to eat" },
  { k: "のみます", r: "nomimasu", m: "to drink" },
  { k: "いきます", r: "ikimasu", m: "to go" },
  { k: "みじかい", r: "mijikai", m: "short" },
  { k: "てんいん", r: "tenin", m: "shop clerk" },
  { k: "ください", r: "kudasai", m: "please give me" },
  { k: "おいしい", r: "oishii", m: "delicious" },
  { k: "おおきい", r: "ookii", m: "big" },
  { k: "ちいさい", r: "chiisai", m: "small" },
  { k: "たのしい", r: "tanoshii", m: "fun, enjoyable" },
  { k: "やさしい", r: "yasashii", m: "kind, easy" },
  { k: "つめたい", r: "tsumetai", m: "cold (to touch)" },
  { k: "げつよう", r: "getsuyou", m: "Monday" },
  { k: "きんよう", r: "kinyou", m: "Friday" },
  { k: "まいにち", r: "mainichi", m: "every day" },
  { k: "れいぞうこ", r: "reizouko", m: "refrigerator" },

  // ---- 5 cells ----
  { k: "ありがとう", r: "arigatou", m: "thank you" },
  { k: "さようなら", r: "sayounara", m: "goodbye" },
  { k: "こんにちは", r: "konnichiwa", m: "hello" },
  { k: "こんばんは", r: "konbanwa", m: "good evening" },
  { k: "すみません", r: "sumimasen", m: "excuse me, sorry" },
  { k: "わかります", r: "wakarimasu", m: "to understand" },
  { k: "あるきます", r: "arukimasu", m: "to walk" },
  { k: "はなします", r: "hanashimasu", m: "to speak" },
  { k: "あたらしい", r: "atarashii", m: "new" },
  { k: "むずかしい", r: "muzukashii", m: "difficult" },
  { k: "いそがしい", r: "isogashii", m: "busy" },
  { k: "あたたかい", r: "atatakai", m: "warm" },
  { k: "えいがかん", r: "eigakan", m: "cinema" }
].filter(function (w) { return w.r && w.m; });
