export const GAME_VERSION = 1;
export const CAMPAIGN_QUARTERS = 24;

export const SEGMENTS = ["family", "value", "premium", "luxury", "adventure"];

export const DIFFICULTIES = {
  relaxed: {
    id: "relaxed",
    name: "Fair winds",
    icon: "🌤️",
    description: "More cash, softer rivals and forgiving demand.",
    startingCash: 310,
    startingDebt: 55,
    demand: 1.12,
    ai: 0.88,
    incident: 0.72,
    interest: 0.012,
  },
  standard: {
    id: "standard",
    name: "Open sea",
    icon: "🌊",
    description: "The intended balance: room to experiment, but weak ships hurt.",
    startingCash: 240,
    startingDebt: 85,
    demand: 1,
    ai: 1,
    incident: 1,
    interest: 0.015,
  },
  hard: {
    id: "hard",
    name: "Heavy weather",
    icon: "⛈️",
    description: "Tighter finance, sharper rivals and less forgiving incidents.",
    startingCash: 190,
    startingDebt: 110,
    demand: 0.94,
    ai: 1.13,
    incident: 1.3,
    interest: 0.019,
  },
};

export const FOCUSES = {
  family: {
    id: "family",
    name: "Family resort",
    icon: "🎢",
    colour: "#ff845f",
    tagline: "Big days, easy nights, everyone included.",
    fit: { family: 1.36, value: 1.12, premium: 0.94, luxury: 0.78, adventure: 0.82 },
    onboard: 1.08,
  },
  premium: {
    id: "premium",
    name: "Premium escape",
    icon: "🥂",
    colour: "#8f78ff",
    tagline: "Better food, calmer decks and thoughtful service.",
    fit: { family: 0.95, value: 0.86, premium: 1.36, luxury: 1.13, adventure: 0.98 },
    onboard: 1.12,
  },
  luxury: {
    id: "luxury",
    name: "Small-ship luxury",
    icon: "✨",
    colour: "#e6b84c",
    tagline: "Space, discretion and ports the giants cannot reach.",
    fit: { family: 0.72, value: 0.68, premium: 1.16, luxury: 1.52, adventure: 1.04 },
    onboard: 1.24,
  },
  adventure: {
    id: "adventure",
    name: "Adventure & discovery",
    icon: "🧭",
    colour: "#27c39d",
    tagline: "Wild coasts, expert guides and stories worth retelling.",
    fit: { family: 0.84, value: 0.8, premium: 1.02, luxury: 1.04, adventure: 1.56 },
    onboard: 1.04,
  },
  value: {
    id: "value",
    name: "Sunshine value",
    icon: "☀️",
    colour: "#3aa8ff",
    tagline: "A bright week away at a price people can say yes to.",
    fit: { family: 1.08, value: 1.47, premium: 0.84, luxury: 0.64, adventure: 0.76 },
    onboard: 0.94,
  },
};

export const LEVELS = [
  {
    id: 1,
    name: "Harbour upstart",
    badge: "⚓",
    minReputation: 0,
    minValue: 0,
    minFleet: 1,
    minPassengers: 0,
    summary: "Prove one ship can earn repeat custom.",
    unlockText: "Mediterranean and short-break markets · boutique newbuilds",
  },
  {
    id: 2,
    name: "Regional line",
    badge: "🌊",
    minReputation: 16,
    minValue: 360,
    minFleet: 1,
    minPassengers: 8_000,
    summary: "Build a recognisable regional brand.",
    unlockText: "Caribbean and Alaska · mid-size ships · family and culinary features",
  },
  {
    id: 3,
    name: "International operator",
    badge: "🌍",
    minReputation: 31,
    minValue: 680,
    minFleet: 2,
    minPassengers: 34_000,
    summary: "Run a fleet across distinct seasons and audiences.",
    unlockText: "Northern Europe and polar markets · resort and expedition hulls · cleaner propulsion",
  },
  {
    id: 4,
    name: "Global brand",
    badge: "👑",
    minReputation: 50,
    minValue: 1_250,
    minFleet: 3,
    minPassengers: 95_000,
    summary: "Turn scale into a brand rather than a bureaucracy.",
    unlockText: "Asia and South Pacific · mega ships · private clubs and signature entertainment",
  },
  {
    id: 5,
    name: "Ocean icon",
    badge: "🏆",
    minReputation: 68,
    minValue: 2_050,
    minFleet: 4,
    minPassengers: 210_000,
    summary: "Lead the rankings and make the fleet fit for the next decade.",
    unlockText: "World voyages · flagship technology · early campaign victory becomes available",
  },
];

export const HULLS = {
  boutique: {
    id: "boutique",
    name: "Boutique",
    icon: "⛵",
    unlockLevel: 1,
    cost: 145,
    buildQuarters: 1,
    pax: 720,
    sailings: 12,
    featureSlots: 3,
    fuel: 2.8,
    crew: 2.2,
    maintenance: 1.4,
    baseAppeal: 49,
    baseEco: 47,
    resale: 0.76,
    description: "Nimble, characterful and able to use smaller ports.",
  },
  mid: {
    id: "mid",
    name: "Mid-size",
    icon: "🛳️",
    unlockLevel: 2,
    cost: 315,
    buildQuarters: 2,
    pax: 1_650,
    sailings: 12,
    featureSlots: 4,
    fuel: 6.2,
    crew: 4.8,
    maintenance: 3,
    baseAppeal: 52,
    baseEco: 43,
    resale: 0.74,
    description: "A flexible workhorse with enough space for a strong identity.",
  },
  resort: {
    id: "resort",
    name: "Resort ship",
    icon: "🏝️",
    unlockLevel: 3,
    cost: 625,
    buildQuarters: 3,
    pax: 3_250,
    sailings: 12,
    featureSlots: 5,
    fuel: 12.5,
    crew: 9.2,
    maintenance: 5.7,
    baseAppeal: 55,
    baseEco: 36,
    resale: 0.71,
    description: "A floating resort with scale, spectacle and serious fixed costs.",
  },
  expedition: {
    id: "expedition",
    name: "Expedition",
    icon: "🧊",
    unlockLevel: 3,
    cost: 235,
    buildQuarters: 2,
    pax: 320,
    sailings: 7,
    featureSlots: 4,
    fuel: 2.4,
    crew: 2,
    maintenance: 1.7,
    baseAppeal: 58,
    baseEco: 53,
    resale: 0.78,
    description: "Low capacity, high fares and access to the edge of the map.",
  },
  mega: {
    id: "mega",
    name: "Mega resort",
    icon: "🎡",
    unlockLevel: 4,
    cost: 1_080,
    buildQuarters: 4,
    pax: 5_250,
    sailings: 12,
    featureSlots: 6,
    fuel: 20,
    crew: 14.5,
    maintenance: 9,
    baseAppeal: 58,
    baseEco: 31,
    resale: 0.68,
    description: "A destination in its own right — and a balance-sheet event.",
  },
};

export const CABIN_PLANS = {
  dense: {
    id: "dense",
    name: "High density",
    mix: "58% inside · 34% balcony · 8% suites",
    capacity: 1.12,
    fare: 0.92,
    appeal: { family: 3, value: 12, premium: -4, luxury: -10, adventure: -2 },
    description: "More berths and sharper prices; service pressure rises at high occupancy.",
  },
  balanced: {
    id: "balanced",
    name: "Balanced",
    mix: "38% inside · 48% balcony · 14% suites",
    capacity: 1,
    fare: 1,
    appeal: { family: 3, value: 1, premium: 5, luxury: 2, adventure: 2 },
    description: "A broad mix that works in most markets.",
  },
  balcony: {
    id: "balcony",
    name: "Balcony-led",
    mix: "20% inside · 62% balcony · 18% suites",
    capacity: 0.91,
    fare: 1.11,
    appeal: { family: 0, value: -5, premium: 12, luxury: 8, adventure: 7 },
    description: "Lower density, better views and a premium fare ceiling.",
  },
  suites: {
    id: "suites",
    name: "Suite-led",
    mix: "9% inside · 48% balcony · 43% suites",
    capacity: 0.72,
    fare: 1.34,
    appeal: { family: -8, value: -13, premium: 10, luxury: 22, adventure: 5 },
    description: "Fewer guests, far higher expectations and more revenue per cabin.",
  },
};

export const SPEEDS = {
  economy: {
    id: "economy",
    name: "Efficiency tuned",
    buildCost: 0.97,
    fuel: 0.84,
    sailings: 0.94,
    appeal: { adventure: 2, luxury: 1 },
    eco: 8,
    description: "Slower itineraries and lower fuel exposure.",
  },
  balanced: {
    id: "balanced",
    name: "Balanced plant",
    buildCost: 1,
    fuel: 1,
    sailings: 1,
    appeal: {},
    eco: 0,
    description: "The dependable default.",
  },
  fast: {
    id: "fast",
    name: "Fast turnarounds",
    buildCost: 1.05,
    fuel: 1.19,
    sailings: 1.08,
    appeal: { family: 2, value: 4, premium: 2 },
    eco: -7,
    description: "More departures and broader itineraries, paid for at the bunker terminal.",
  },
};

export const FEATURES = {
  theatre: {
    id: "theatre",
    name: "Grand theatre",
    icon: "🎭",
    cost: 18,
    running: 0.35,
    unlockLevel: 1,
    appeal: { family: 6, value: 5, premium: 6, luxury: 1, adventure: 0 },
    onboard: 0.01,
    eco: 0,
    description: "A dependable evening anchor for almost every audience.",
  },
  spa: {
    id: "spa",
    name: "Sea-view spa",
    icon: "🪷",
    cost: 17,
    running: 0.32,
    unlockLevel: 1,
    appeal: { family: 1, value: 0, premium: 9, luxury: 15, adventure: 2 },
    onboard: 0.08,
    eco: 0,
    description: "High-margin calm, especially valuable to premium guests.",
  },
  observation: {
    id: "observation",
    name: "Observation lounge",
    icon: "🔭",
    cost: 13,
    running: 0.18,
    unlockLevel: 1,
    appeal: { family: 2, value: 1, premium: 6, luxury: 8, adventure: 12 },
    onboard: 0.03,
    eco: 1,
    description: "A reason to look outward, not merely at the ship.",
  },
  familyClub: {
    id: "familyClub",
    name: "Family club",
    icon: "🧸",
    cost: 14,
    running: 0.38,
    unlockLevel: 2,
    appeal: { family: 18, value: 8, premium: 1, luxury: -2, adventure: 0 },
    onboard: 0.035,
    eco: 0,
    description: "Supervised clubs, teen space and a better holiday for parents.",
  },
  culinary: {
    id: "culinary",
    name: "Culinary hall",
    icon: "🍽️",
    cost: 23,
    running: 0.5,
    unlockLevel: 2,
    appeal: { family: 5, value: 2, premium: 13, luxury: 13, adventure: 3 },
    onboard: 0.075,
    eco: 0,
    description: "Distinct restaurants with pricing power and social-media pull.",
  },
  waterpark: {
    id: "waterpark",
    name: "Water park",
    icon: "🌊",
    cost: 31,
    running: 0.68,
    unlockLevel: 2,
    blockedHulls: ["boutique", "expedition"],
    appeal: { family: 23, value: 8, premium: -1, luxury: -8, adventure: 0 },
    onboard: 0.045,
    eco: -4,
    description: "A booking engine for families, but thirsty for deck space and power.",
  },
  expeditionLab: {
    id: "expeditionLab",
    name: "Discovery lab",
    icon: "🔬",
    cost: 16,
    running: 0.28,
    unlockLevel: 3,
    appeal: { family: 4, value: -1, premium: 4, luxury: 5, adventure: 20 },
    onboard: 0.025,
    eco: 5,
    description: "Naturalists, citizen science and genuine destination knowledge.",
  },
  hybrid: {
    id: "hybrid",
    name: "Hybrid propulsion",
    icon: "🔋",
    cost: 42,
    running: 0.1,
    unlockLevel: 3,
    fuel: 0.84,
    appeal: { family: 1, value: 1, premium: 4, luxury: 5, adventure: 7 },
    onboard: 0,
    eco: 19,
    description: "Battery-supported hotel loads and lower fuel burn in port.",
  },
  shorePower: {
    id: "shorePower",
    name: "Shore power",
    icon: "🔌",
    cost: 11,
    running: 0.05,
    unlockLevel: 3,
    fuel: 0.96,
    appeal: { family: 1, value: 0, premium: 2, luxury: 2, adventure: 4 },
    onboard: 0,
    eco: 11,
    description: "Plug in alongside instead of running generators beneath the city.",
  },
  privateClub: {
    id: "privateClub",
    name: "Private club deck",
    icon: "🗝️",
    cost: 29,
    running: 0.4,
    unlockLevel: 4,
    appeal: { family: -1, value: -3, premium: 10, luxury: 19, adventure: 1 },
    onboard: 0.11,
    eco: 0,
    description: "A ship-within-a-ship product for guests who pay to avoid queues.",
  },
  signatureShow: {
    id: "signatureShow",
    name: "Signature spectacular",
    icon: "🎆",
    cost: 36,
    running: 0.8,
    unlockLevel: 4,
    blockedHulls: ["boutique", "expedition"],
    appeal: { family: 13, value: 8, premium: 10, luxury: 2, adventure: 0 },
    onboard: 0.035,
    eco: -1,
    description: "A headline show that turns the ship into the destination.",
  },
  marina: {
    id: "marina",
    name: "Stern marina",
    icon: "🤿",
    cost: 26,
    running: 0.38,
    unlockLevel: 4,
    blockedHulls: ["mega"],
    appeal: { family: 4, value: 1, premium: 8, luxury: 13, adventure: 15 },
    onboard: 0.07,
    eco: 1,
    description: "Direct access to kayaks, tenders and warm water.",
  },
  methanolReady: {
    id: "methanolReady",
    name: "Methanol-ready plant",
    icon: "🌱",
    cost: 58,
    running: 0.13,
    unlockLevel: 5,
    fuel: 0.79,
    appeal: { family: 2, value: 1, premium: 6, luxury: 7, adventure: 10 },
    onboard: 0,
    eco: 28,
    description: "Expensive flexibility for a lower-carbon fuel future.",
  },
};

export const MARKETING_CHANNELS = {
  digital: {
    id: "digital",
    name: "Digital & creators",
    icon: "📱",
    fit: { family: 1.2, value: 1.18, premium: 1.04, luxury: 0.82, adventure: 1.12 },
    description: "Fast reach, strong launches and volatile attention.",
  },
  agents: {
    id: "agents",
    name: "Travel partners",
    icon: "🤝",
    fit: { family: 1.03, value: 0.96, premium: 1.22, luxury: 1.25, adventure: 1.08 },
    description: "Trusted advice for complex and higher-value itineraries.",
  },
  broadcast: {
    id: "broadcast",
    name: "Big brand media",
    icon: "📺",
    fit: { family: 1.22, value: 1.2, premium: 1.02, luxury: 0.76, adventure: 0.82 },
    description: "Expensive reach that makes a regional line feel national.",
  },
  loyalty: {
    id: "loyalty",
    name: "Loyalty & CRM",
    icon: "💌",
    fit: { family: 1.03, value: 1.02, premium: 1.18, luxury: 1.2, adventure: 1.08 },
    description: "Slower burn, stronger repeats and more resilient demand.",
  },
};

export const MARKETS = {
  med: {
    id: "med",
    name: "Mediterranean",
    short: "Med",
    icon: "🏛️",
    unlockLevel: 1,
    map: { x: 51, y: 48 },
    baseDemand: 48_000,
    baseFare: 1_180,
    onboard: 310,
    portCost: 118,
    distance: 1,
    seasonality: [0.83, 1.18, 1.34, 0.74],
    traits: { family: 1.05, value: 1, premium: 1.16, luxury: 1.08, adventure: 0.9 },
    description: "Culture, beaches and dense port competition. Summer is fierce and lucrative.",
  },
  short: {
    id: "short",
    name: "Short breaks",
    short: "Short",
    icon: "🎉",
    unlockLevel: 1,
    map: { x: 44, y: 35 },
    baseDemand: 36_000,
    baseFare: 850,
    onboard: 300,
    portCost: 96,
    distance: 0.68,
    seasonality: [0.84, 1.08, 1.13, 1.04],
    traits: { family: 1.05, value: 1.28, premium: 0.88, luxury: 0.66, adventure: 0.72 },
    description: "Low fares, frequent departures and ruthless price comparison.",
  },
  caribbean: {
    id: "caribbean",
    name: "Caribbean",
    short: "Carib",
    icon: "🌴",
    unlockLevel: 2,
    map: { x: 25, y: 56 },
    baseDemand: 65_000,
    baseFare: 1_320,
    onboard: 390,
    portCost: 126,
    distance: 1.12,
    seasonality: [1.25, 0.95, 0.78, 1.36],
    traits: { family: 1.27, value: 1.14, premium: 1.02, luxury: 0.9, adventure: 0.82 },
    description: "The scale market: families, private-island spectacle and winter sun.",
  },
  alaska: {
    id: "alaska",
    name: "Alaska",
    short: "Alaska",
    icon: "🐋",
    unlockLevel: 2,
    map: { x: 10, y: 25 },
    baseDemand: 32_000,
    baseFare: 1_820,
    onboard: 360,
    portCost: 151,
    distance: 1.18,
    seasonality: [0.42, 1.19, 1.48, 0.35],
    traits: { family: 0.96, value: 0.78, premium: 1.2, luxury: 1.02, adventure: 1.34 },
    description: "A short, high-yield season where views and guiding matter more than slides.",
  },
  northEurope: {
    id: "northEurope",
    name: "Northern Europe",
    short: "North EU",
    icon: "🏰",
    unlockLevel: 3,
    map: { x: 45, y: 24 },
    baseDemand: 39_000,
    baseFare: 1_540,
    onboard: 325,
    portCost: 142,
    distance: 1.08,
    seasonality: [0.55, 1.12, 1.31, 0.62],
    traits: { family: 0.88, value: 0.82, premium: 1.24, luxury: 1.08, adventure: 1.12 },
    description: "Fjords, capitals and weather-sensitive guests with high expectations.",
  },
  expedition: {
    id: "expedition",
    name: "Polar expedition",
    short: "Polar",
    icon: "🐧",
    unlockLevel: 3,
    map: { x: 58, y: 84 },
    baseDemand: 7_800,
    baseFare: 5_900,
    onboard: 540,
    portCost: 390,
    distance: 1.46,
    seasonality: [1.1, 0.66, 0.72, 1.34],
    traits: { family: 0.42, value: 0.34, premium: 1.04, luxury: 1.3, adventure: 1.74 },
    hullPreference: { expedition: 1.34, boutique: 1.12, mid: 0.82, resort: 0.48, mega: 0.28 },
    description: "Tiny volumes, vast fares and zero patience for generic hardware.",
  },
  asia: {
    id: "asia",
    name: "East & Southeast Asia",
    short: "Asia",
    icon: "🏮",
    unlockLevel: 4,
    map: { x: 82, y: 49 },
    baseDemand: 49_000,
    baseFare: 1_480,
    onboard: 350,
    portCost: 128,
    distance: 1.15,
    seasonality: [1.13, 0.88, 0.82, 1.17],
    traits: { family: 1.02, value: 1.05, premium: 1.2, luxury: 1.08, adventure: 0.96 },
    description: "A varied growth market where distribution and food credibility count.",
  },
  pacific: {
    id: "pacific",
    name: "South Pacific",
    short: "Pacific",
    icon: "🌺",
    unlockLevel: 4,
    map: { x: 91, y: 69 },
    baseDemand: 20_000,
    baseFare: 2_650,
    onboard: 470,
    portCost: 184,
    distance: 1.38,
    seasonality: [1.12, 0.9, 0.84, 1.16],
    traits: { family: 0.88, value: 0.7, premium: 1.12, luxury: 1.38, adventure: 1.25 },
    description: "Long distances, gorgeous ports and guests willing to pay for space.",
  },
  world: {
    id: "world",
    name: "World voyage",
    short: "World",
    icon: "🌐",
    unlockLevel: 5,
    map: { x: 67, y: 39 },
    baseDemand: 13_500,
    baseFare: 8_900,
    onboard: 1_280,
    portCost: 690,
    distance: 2.15,
    seasonality: [1.08, 0.96, 1, 0.98],
    traits: { family: 0.48, value: 0.38, premium: 1.18, luxury: 1.55, adventure: 1.2 },
    hullPreference: { boutique: 1.05, mid: 1.18, resort: 1.04, expedition: 0.72, mega: 0.88 },
    description: "The prestige product: long commitments, high fares and nowhere to hide weak service.",
  },
};

export const RIVAL_PROFILES = [
  {
    id: "sunburst",
    name: "Sunburst Cruises",
    icon: "☀️",
    colour: "#ff7658",
    focus: "family",
    temperament: "expander",
    price: 0.94,
    service: 0.95,
    marketing: 5.7,
    reputation: 28,
    sustainability: 28,
    startingFleet: ["resort", "mid"],
    homeMarkets: ["caribbean", "med", "short"],
    bio: "Big ships, bright campaigns and a relentless appetite for family capacity.",
  },
  {
    id: "meridian",
    name: "Meridian Voyages",
    icon: "✦",
    colour: "#806df5",
    focus: "premium",
    temperament: "disciplined",
    price: 1.1,
    service: 1.12,
    marketing: 4.3,
    reputation: 39,
    sustainability: 43,
    startingFleet: ["mid", "boutique"],
    homeMarkets: ["med", "northEurope", "alaska"],
    bio: "Measured growth, strong food and a loyal premium customer base.",
  },
  {
    id: "atlas",
    name: "Atlas Expeditions",
    icon: "🧭",
    colour: "#19ad91",
    focus: "adventure",
    temperament: "specialist",
    price: 1.18,
    service: 1.08,
    marketing: 3.2,
    reputation: 35,
    sustainability: 57,
    startingFleet: ["expedition", "boutique"],
    homeMarkets: ["expedition", "alaska", "northEurope"],
    bio: "A focused specialist that wins small markets with the right hardware.",
  },
  {
    id: "bluewave",
    name: "BlueWave Holidays",
    icon: "🌊",
    colour: "#258fe8",
    focus: "value",
    temperament: "discounter",
    price: 0.84,
    service: 0.86,
    marketing: 5,
    reputation: 23,
    sustainability: 24,
    startingFleet: ["mid", "mid"],
    homeMarkets: ["short", "med", "caribbean"],
    bio: "Low fares, high utilisation and very little fear of a price war.",
  },
];

export const GLOBAL_EVENTS = [
  { id: "steady", title: "A steady travel quarter", icon: "🌤️", body: "Demand develops broadly in line with the board plan.", weight: 18, demand: 1, fuel: 1 },
  { id: "fuel-spike", title: "Bunker prices jump", icon: "🛢️", body: "Fuel costs surge after a tight energy market. Efficient ships earn their keep.", weight: 4, demand: 0.99, fuel: 1.29 },
  { id: "travel-boom", title: "The sea is suddenly fashionable", icon: "📈", body: "A broad travel boom lifts searches and late bookings across the market.", weight: 5, demand: 1.14, fuel: 1.03 },
  { id: "consumer-squeeze", title: "Household budgets tighten", icon: "🧾", body: "Value propositions hold up while premium discretionary demand softens.", weight: 4, demand: 0.91, fuel: 0.96, focusDemand: { value: 1.12, family: 1.03, premium: 0.93, luxury: 0.88, adventure: 0.94 } },
  { id: "aviation-disruption", title: "Air disruption boosts drive-to ports", icon: "🧳", body: "Short-haul aviation disruption shifts demand towards nearby embarkation ports.", weight: 3, demand: 1.02, fuel: 1, marketDemand: { short: 1.2, med: 1.08, caribbean: 0.92, asia: 0.92, pacific: 0.88 } },
  { id: "port-strike", title: "Port labour disruption", icon: "🚧", body: "Schedule changes and compensation dent the busiest European itineraries.", weight: 3, demand: 0.98, fuel: 1.02, marketDemand: { med: 0.82, northEurope: 0.86, short: 0.9 }, cost: 4 },
  { id: "eco-wave", title: "Cleaner ships win the headlines", icon: "🌱", body: "A wave of scrutiny rewards efficient ships and punishes obvious laggards.", weight: 3, demand: 1, fuel: 1.01, ecoSensitivity: 1.5 },
  { id: "weak-currency", title: "Currency tailwind", icon: "💱", body: "Favourable exchange rates lift onboard spend and destination demand.", weight: 3, demand: 1.06, fuel: 1, onboard: 1.12 },
];

export const COMPANY_EVENTS = [
  { id: "crew-praise", title: "Crew praise goes viral", icon: "💛", body: "Guests single out the crew by name. Good employment policy becomes good marketing.", test: ({ company }) => company.crewPay >= 1.08, chance: 0.22, effects: { reputation: 3 } },
  { id: "engine-repair", title: "Unplanned machinery repair", icon: "🔧", body: "A defect is caught before failure, but the repair bill arrives immediately.", test: ({ company }) => company.maintenance < 1.02, chance: 0.24, effects: { reputation: -1, cash: -11 } },
  { id: "outbreak", title: "A difficult health week", icon: "🧼", body: "A cluster of illness triggers deep cleaning, compensation and ugly headlines.", test: ({ company, report }) => company.serviceSpend < 145 || report.averageOccupancy > 0.97, chance: 0.12, effects: { reputation: -5, cash: -16 } },
  { id: "award", title: "Editors’ choice award", icon: "🏅", body: "The fleet’s product consistency earns useful third-party credibility.", test: ({ company, report }) => company.serviceSpend >= 175 && report.satisfaction >= 72, chance: 0.2, effects: { reputation: 4 } },
  { id: "efficiency-bonus", title: "Efficiency programme pays back", icon: "⚙️", body: "Fuel, itinerary and procurement teams find savings the board can actually see.", test: ({ company }) => company.sustainabilitySpend >= 7, chance: 0.2, effects: { reputation: 1, cash: 9, sustainability: 2 } },
  { id: "creator-hit", title: "A ship tour breaks out online", icon: "📹", body: "A creator’s tour becomes the week’s default daydream.", test: ({ company }) => company.marketing.digital >= 7, chance: 0.2, effects: { reputation: 2, cash: 5 } },
  { id: "quiet", title: "Operations stay out of the news", icon: "🗞️", body: "For once, the quarter’s story is simply the numbers.", test: () => true, chance: 1, effects: {} },
];

export const SHIP_NAMES = [
  "Aurora", "Endeavour", "Celestine", "North Star", "Solstice", "Odyssey", "Caledonia", "Serenity", "Mariner", "Discovery", "Halcyon", "Radiance", "Constellation", "Voyager", "Eclipse", "Polaris", "Horizon", "Liberty",
];

export const COMPANY_NAMES = [
  "Ministry of Mild Peril Voyages",
  "The Admiralty of Snacks",
  "Mandatory Leisure Directorate",
  "Mostly Afloat plc",
  "Committee for Applied Deckchairs",
  "Bureau of Acceptable Sunsets",
  "Maritime Optimisation Laboratory",
  "Department of Buoyancy",
  "Compulsory Horizons Group",
  "Upper Deck Research Collective",
  "Wake Compliance Authority",
  "Cruise Dynamics (Probably)",
  "Oceanic Amenities Test Facility",
  "The Floating Expense Account",
  "Premium Biscuit Navigation",
  "Deckchair Propulsion Group",
  "Cabin Pressure Holdings",
  "Whimsy & Ballast",
  "Reasonably Seaworthy Adventures",
  "The Institute of Better Portholes",
  "Applied Holiday Sciences",
  "Provisional Paradise Bureau",
  "Seaborne Synergy Committee",
  "Guest Containment Partners",
  "The Unscheduled Fjord Company",
  "Form 27B Ocean Holidays",
  "Bureaucratic Mermaid Ventures",
  "North Atlantic Customer Experiment",
];

export const TIPS = [
  "A ship can be excellent and still be wrong for its market.",
  "Discounting fills cabins quickly; it also teaches guests what your product is worth.",
  "High occupancy is not automatically healthy when service and maintenance lag.",
  "Rivals expose capacity before the quarter closes — route around them or out-design them.",
  "A newbuild’s financing leaves the balance sheet now; its capacity arrives later.",
  "The cheapest fuel is the fuel your hull and itinerary never need.",
  "Loyalty spending is quiet in the forecast and loud in a downturn.",
];
