// ============================================================
// The Triangle Engine — history.js
// ------------------------------------------------------------
// The narrative data: the timeline of machines, the pipeline stages,
// and the sourced claims. Kept apart from app.js so the prose can be
// checked without reading the rendering code.
//
// `stages` on each era records WHERE each job ran at the time:
//   "none"  the stage did not exist yet
//   "cpu"   general-purpose software on the host processor
//   "fixed" dedicated silicon doing one wired-in thing
//   "prog"  dedicated silicon running a program you supply
// Scrubbing the timeline animates those migrations, which is the whole
// story of the field in one bar.
// ============================================================
(function (global) {
  "use strict";

  var ERAS = [
    {
      id: "sketchpad",
      year: 1963,
      short: "1963",
      name: "Sketchpad",
      maker: "Ivan Sutherland · MIT Lincoln Laboratory",
      machine: "TX-2",
      headline: "A picture becomes a data structure.",
      primitive: "Line segments, drawn by deflecting a beam",
      api: "A light pen and a bank of toggle switches",
      summary:
        "Sutherland's doctoral system let a person draw on a screen with a light pen and — the part that mattered — have the machine remember the drawing as structure rather than as marks. Lines belonged to objects, objects had constraints, and a change to a master copy propagated to every instance. Nothing here is 3D in the modern sense, and there is no shading of any kind: the display is a vector oscilloscope that traces line segments directly, one at a time, refreshed fast enough to look steady. But the idea that a picture is a model held in memory, redrawn on demand, is the foundation everything else is built on.",
      detail: [
        "The TX-2 was one of the first transistorised computers, and Sketchpad had roughly the memory of a modern icon file to work in.",
        "The display was a calligraphic vector scope. There were no pixels to fill, so there was no rasterization problem to solve yet.",
        "Sutherland's constraint solver — make these lines parallel, make this angle right — anticipated parametric CAD by twenty years.",
      ],
      numbers: [
        { k: "Primitive", v: "line" },
        { k: "Pixels", v: "none — vector beam" },
        { k: "Shading", v: "none" },
      ],
      stages: { geometry: "cpu", setup: "none", raster: "none", texture: "none", fragment: "none", rop: "none", ray: "none" },
    },
    {
      id: "flightsim",
      year: 1968,
      short: "1968",
      name: "The hidden-surface problem",
      maker: "Evans & Sutherland · General Electric · Arthur Appel",
      machine: "Room-sized flight simulators",
      headline: "Solid objects need to know what is in front of what.",
      primitive: "Convex polygons",
      api: "Wire-wrapped, per-installation",
      summary:
        "Sutherland left Harvard for a chair at Utah and, with David Evans, founded Evans & Sutherland there, selling image generators to the people who needed them most: airlines and the military, for flight simulation. Solid surfaces raised a question a wireframe never had — which surface is nearest the eye at this point on the screen? Through the late sixties and early seventies a dozen different answers were proposed and, in 1974, Sutherland, Sproull and Schumacker famously sorted them into a single taxonomy. In the same period Arthur Appel described casting a ray per picture point to find the first thing it hits, the idea that hardware would finally be built for in 2018.",
      detail: [
        "Simulator image generators sorted polygons in hardware, front to back, at a fixed and guaranteed frame rate — the guarantee mattered more than the picture.",
        "Appel's 1968 ray casting is the direct ancestor of what became hardware-accelerated in 2018.",
        "Almost every hidden-surface algorithm of the period is a sorting algorithm in disguise: sort in depth, sort in scanlines, or sort in screen space.",
      ],
      numbers: [
        { k: "Primitive", v: "polygon" },
        { k: "Typical budget", v: "hundreds of polygons" },
        { k: "Cost", v: "millions of dollars" },
      ],
      stages: { geometry: "fixed", setup: "fixed", raster: "fixed", texture: "none", fragment: "none", rop: "fixed", ray: "cpu" },
    },
    {
      id: "utah",
      year: 1971,
      short: "1971–75",
      name: "Utah invents shading",
      maker: "Gouraud · Phong · Catmull · Newell · Blinn",
      machine: "University of Utah, PDP-10",
      headline: "Four papers that still run in every game you own.",
      primitive: "Polygons with per-vertex normals",
      api: "Hand-written Fortran, on a shared PDP-10",
      summary:
        "In four years one graduate school produced most of the vocabulary. Henri Gouraud (1971) computed lighting at the corners of a polygon and interpolated the result across it, so a faceted model could look curved. Bui Tuong Phong (1973 thesis, 1975 paper) interpolated the normal instead of the colour and added a specular term, so surfaces could look shiny. Ed Catmull's 1974 thesis introduced both texture mapping and the z-buffer — spend a word of memory per pixel holding the nearest depth so far, and the hidden-surface problem dissolves into a comparison. Martin Newell modelled a teapot from his kitchen in 1975 because he needed a test object with curvature, a handle and a hole in it; it is still in use. Jim Blinn added bump mapping and, in 1977, replaced Phong's reflected vector with the cheaper halfway vector.",
      detail: [
        "Wolfgang Strasser described the depth-buffer idea independently in his 1974 dissertation in Germany.",
        "Catmull's z-buffer was considered extravagant: a word per pixel was an unthinkable amount of memory to spend on bookkeeping.",
        "Gouraud shading cannot show a highlight smaller than a polygon, which is why low-poly Gouraud models look plastic and flat.",
        "The teapot as usually rendered is squashed: the original data was displayed on a non-square-pixel screen, and the vertical scaling stuck.",
      ],
      numbers: [
        { k: "Z-buffer cost", v: "1 word / pixel" },
        { k: "Teapot patches", v: "32 bicubic" },
        { k: "Frame time", v: "hours" },
      ],
      stages: { geometry: "cpu", setup: "cpu", raster: "cpu", texture: "cpu", fragment: "cpu", rop: "cpu", ray: "cpu" },
    },
    {
      id: "geometryengine",
      year: 1982,
      short: "1982",
      name: "The Geometry Engine",
      maker: "Jim Clark & Marc Hannah · Silicon Graphics",
      machine: "SGI IRIS workstations",
      headline: "The matrix multiply moves into silicon.",
      primitive: "Transformed, clipped polygons",
      api: "IRIS GL",
      summary:
        "Clark's insight at Stanford was that the front of the pipeline — transform, clip, project — is a fixed sequence of 4x4 matrix operations on a stream of points, and a fixed sequence is exactly what you can etch into a chip. The Geometry Engine was the first VLSI implementation of a geometry pipeline: twelve of them in a row, each doing one stage, points flowing through. Clark and Hannah founded Silicon Graphics around it in 1982, and for the next decade a 3D workstation meant an SGI. Their library, IRIS GL, is the direct ancestor of OpenGL, and the shape of its pipeline is the shape of every pipeline since.",
      detail: [
        "A systolic array: each chip does one matrix stage and hands the point on, so throughput is one point per cycle regardless of how many stages there are.",
        "SGI sold the workstations on which Jurassic Park and Terminator 2 were made, and on which a generation of artists learned the craft. The render farms were often someone else's: Toy Story, in 1995, was rendered on a room full of Sun SPARCstations.",
        "The workstation model — a big price, a small market, a huge lead — is exactly what the PC 3D card would demolish fifteen years later.",
      ],
      numbers: [
        { k: "Chips per pipe", v: "12" },
        { k: "Precision", v: "floating point" },
        { k: "Price", v: "$50k and up" },
      ],
      stages: { geometry: "fixed", setup: "fixed", raster: "fixed", texture: "none", fragment: "fixed", rop: "fixed", ray: "cpu" },
    },
    {
      id: "edgefunction",
      year: 1988,
      short: "1988",
      name: "Edge functions and shading languages",
      maker: "Juan Pineda · Pat Hanrahan · Pixar",
      machine: "Apollo workstations · Pixar's RenderMan",
      headline: "Two ideas from one year that took thirty to converge.",
      primitive: "Triangles, tested in parallel",
      api: "The RenderMan Interface Specification",
      summary:
        "Pineda's paper described filling a triangle by evaluating three linear functions — one per edge — at every candidate pixel and keeping the pixels where all three are positive. It sounds wasteful next to walking a scanline, and on a serial machine it is; but every pixel's test is independent of every other, so you can test a whole block at once, and the functions update by addition as you step. That is the algorithm in every GPU rasterizer built since. In the same year Pixar published the RenderMan interface, whose shading language let an artist write the code that computes a surface's colour. One idea made rasterization parallel; the other made shading programmable. Consumer hardware would take until 1996 and 2001 respectively to catch up.",
      detail: [
        "The edge function is twice the signed area of a triangle, so its sign is also the winding test that gives you backface culling for free.",
        "Because it is linear, stepping one pixel right adds a constant. Hardware evaluates a tile of them with adders, not multipliers.",
        "RenderMan's shading language descends from Rob Cook's 1984 'shade trees'; HLSL and GLSL are its direct descendants.",
      ],
      numbers: [
        { k: "Tests / pixel", v: "3" },
        { k: "Per-pixel cost", v: "3 adds" },
        { k: "Parallelism", v: "unbounded" },
      ],
      stages: { geometry: "fixed", setup: "fixed", raster: "fixed", texture: "cpu", fragment: "cpu", rop: "fixed", ray: "cpu" },
    },
    {
      id: "opengl",
      year: 1992,
      short: "1992",
      name: "OpenGL and RealityEngine",
      maker: "Silicon Graphics · Kurt Akeley",
      machine: "SGI IRIS Crimson RealityEngine",
      headline: "The pipeline gets a specification, and a name.",
      primitive: "Triangles with texture coordinates",
      api: "OpenGL 1.0",
      summary:
        "SGI stripped the machine-specific parts out of IRIS GL and published the rest, and on 30 June 1992 the OpenGL 1.0 specification was complete; an Architecture Review Board of competing vendors was formed to steer it. The document did something subtle and durable: it defined the pipeline as a state machine with a precisely specified order of operations, so that a program could produce the same picture on any conforming implementation. The hardware alongside it, RealityEngine, is the first machine that would be recognisable to a modern graphics programmer — real-time texture mapping with mipmaps, full-scene antialiasing by multisampling, and a per-pixel depth buffer, all at once.",
      detail: [
        "OpenGL's ordering guarantees are why blending works: fragments from one primitive must land in framebuffer order even though everything else may be parallel.",
        "RealityEngine's antialiasing worked by keeping several subsamples per pixel — the direct ancestor of the MSAA switch in every game's options menu.",
        "The specification is written as a description of a machine, not an implementation. Nothing in it says any of it must be done in hardware.",
      ],
      numbers: [
        { k: "Spec completed", v: "30 Jun 1992" },
        { k: "Texture memory", v: "up to 16 MB" },
        { k: "Subsamples", v: "up to 16 / pixel" },
      ],
      stages: { geometry: "fixed", setup: "fixed", raster: "fixed", texture: "fixed", fragment: "fixed", rop: "fixed", ray: "cpu" },
    },
    {
      id: "software",
      year: 1993,
      short: "1993–96",
      name: "3D without hardware",
      maker: "id Software · Michael Abrash · John Carmack",
      machine: "A 486, then a Pentium",
      headline: "The trick was knowing exactly what you could refuse to compute.",
      primitive: "Vertical wall columns, then real polygons",
      api: "None. Write to the framebuffer.",
      summary:
        "Doom, in 1993, is not a 3D engine: it draws a two-dimensional map with heights, using a binary space partition to visit walls in the right order, and it cannot put one room above another. That constraint is what made it run at speed on a machine with no floating-point performance to speak of. Quake, in 1996, is the real thing — arbitrary polygons, a genuine perspective projection, precomputed lighting — rendered entirely in software on a Pentium. Its most famous trick belongs to this page: perspective-correct texturing needs a divide per pixel, and the Pentium's floating-point divide takes many cycles, but it runs on a separate unit. So Abrash and Carmack issued the divide for the pixel sixteen ahead and filled the wait with integer work, interpolating affinely in between. Correct where it counts, free where it does not.",
      detail: [
        "Doom's BSP tree gives a guaranteed front-to-back order for any viewpoint, which removes the need for a depth buffer entirely.",
        "Quake's span buffer, surface cache and overdraw avoidance were all in aid of not touching a pixel twice — memory bandwidth was the wall then too.",
        "GLQuake, in January 1997, was the demonstration that a consumer 3D card could beat the best hand-written software renderer in the world.",
      ],
      numbers: [
        { k: "Divide interval", v: "every 16 px" },
        { k: "Target", v: "320x200, 35 Hz" },
        { k: "Depth buffer", v: "none" },
      ],
      stages: { geometry: "cpu", setup: "cpu", raster: "cpu", texture: "cpu", fragment: "cpu", rop: "cpu", ray: "cpu" },
    },
    {
      id: "nv1",
      year: 1995,
      short: "1995",
      name: "NV1, and the road not taken",
      maker: "Nvidia · Sega · Sony",
      machine: "Diamond Edge 3D · Saturn · PlayStation",
      headline: "Everyone agreed on 3D. Nobody agreed on the primitive.",
      primitive: "Quadratic patches, and quads",
      api: "Nvidia's own, before Direct3D existed",
      summary:
        "Nvidia's first chip could draw a triangle, but it was not built to. NV1 was designed around quadratic texture mapping: curved quadrilateral patches, drawn by forward mapping — walking across the texture and depositing texels into the framebuffer — rather than by walking across the screen and looking texels up. Fewer primitives for a curved surface, and Sega's Saturn used quads too, so the ports came easily. Then Microsoft announced that Direct3D would accept triangles and only triangles, and the argument was over in a season. Sony's PlayStation drew triangles and quads alike, but with no depth buffer at all and no perspective correction, which is why its textures crawl and its polygons snap: its geometry unit worked in fixed point and screen coordinates were rounded to whole pixels.",
      detail: [
        "Forward mapping cannot easily antialias or filter, because several texels can land on one pixel and no pixel knows in advance how many.",
        "A triangle is the only polygon that is always planar and always convex — which is exactly why the hardware people wanted it.",
        "The PlayStation sorted polygons with an ordering table, a per-frame bucket sort by depth, so interpenetrating objects simply could not be drawn correctly.",
        "NV2, contracted for Sega's next console, was cancelled in 1996 over the same argument: Sega wanted triangles and Nvidia wanted patches. The Dreamcast went to 3dfx and then, in 1997, to NEC's PowerVR. Nvidia's third design, RIVA 128, drew triangles.",
      ],
      numbers: [
        { k: "NV1 primitive", v: "quadratic patch" },
        { k: "PS1 depth buffer", v: "none" },
        { k: "PS1 vertices", v: "integer pixels" },
      ],
      stages: { geometry: "cpu", setup: "fixed", raster: "fixed", texture: "fixed", fragment: "fixed", rop: "fixed", ray: "cpu" },
    },
    {
      id: "voodoo",
      year: 1996,
      short: "1996",
      name: "Voodoo Graphics, and Direct3D",
      maker: "3dfx Interactive · Microsoft",
      machine: "Orchid Righteous 3D · Windows 95",
      headline: "The triangle wins, and it costs $299.",
      primitive: "The triangle, decisively",
      api: "Glide · Direct3D · OpenGL",
      summary:
        "3dfx's Voodoo Graphics could not draw a window, a menu or a character. It had no 2D at all: you ran a cable from your ordinary video card into the Voodoo, and the Voodoo passed the signal through untouched until a game started, at which point it seized the display. What it did do was fill textured, depth-buffered, bilinear-filtered, fogged pixels faster than any software renderer could hope to, and it did it under a small honest API — Glide — that was little more than the hardware's register set with names. Microsoft, which had bought RenderMorphics in February 1995 for its Reality Lab engine, shipped Direct3D in DirectX 2.0 in June 1996 with a much less loved design: you built 'execute buffers' of packed commands by hand. It took until DirectX 5 in 1997 for DrawPrimitive to put that right.",
      detail: [
        "Bilinear filtering is the single change that made 1996 hardware look different from 1996 software: no more lego-brick texels up close.",
        "The Voodoo's 16-bit colour and 16-bit depth were chosen for bandwidth, not quality. Both would be regretted within two years.",
        "The Glide-versus-Direct3D-versus-OpenGL argument of 1996-97 was bitter, and John Carmack's public case for OpenGL carried real weight.",
        "In 1996 both companies sold chips to board makers — this one went to Orchid. 3dfx then bet on a proprietary API and, after buying STB in 1998, on building the boards itself; Nvidia bet on standard APIs and on selling chips to anyone who would fit them. Nvidia bought 3dfx's assets in 2000.",
      ],
      numbers: [
        { k: "Fill rate", v: "45 Mpixel/s" },
        { k: "Frame buffer", v: "2 MB" },
        { k: "Colour depth", v: "16-bit" },
      ],
      stages: { geometry: "cpu", setup: "fixed", raster: "fixed", texture: "fixed", fragment: "fixed", rop: "fixed", ray: "cpu" },
    },
    {
      id: "geforce",
      year: 1999,
      short: "1999",
      name: "GeForce 256 — the word 'GPU'",
      maker: "Nvidia",
      machine: "GeForce 256, October 1999",
      headline: "The front of the pipeline comes back into hardware.",
      primitive: "Triangles, transformed on the card",
      api: "Direct3D 7 · OpenGL 1.2",
      summary:
        "For three years the consumer 3D card had been a back-end only: the CPU transformed and lit every vertex and handed screen-space triangles across the bus. GeForce 256 put transform and lighting back on the card — the job SGI had moved into silicon seventeen years earlier — and Nvidia coined 'graphics processing unit' to mark the change. The practical effect was that polygon budgets stopped being a function of your processor. The conceptual effect was larger: a card that owns both ends of the pipeline is a machine you can program, and the argument for the next decade would be about what language to program it in.",
      detail: [
        "The lighting was fixed-function: eight lights, one model, take it or leave it. Artists immediately wanted to leave it.",
        "The name was retroactively contentious — earlier chips had done geometry — but the marketing stuck, and the category with it.",
        "Cube maps, register combiners and hardware anisotropic filtering arrive around here, all of them workarounds for the absence of real programmability.",
      ],
      numbers: [
        { k: "Transistors", v: "23 million" },
        { k: "Triangles/s", v: "15 million" },
        { k: "Fixed lights", v: "8" },
      ],
      stages: { geometry: "fixed", setup: "fixed", raster: "fixed", texture: "fixed", fragment: "fixed", rop: "fixed", ray: "cpu" },
    },
    {
      id: "shaders",
      year: 2001,
      short: "2001–02",
      name: "Programmable shading arrives",
      maker: "Nvidia GeForce 3 · ATI Radeon 9700",
      machine: "NV20, February 2001 · R300, 2002",
      headline: "You stop configuring the pipeline and start writing it.",
      primitive: "Triangles, shaded by your code",
      api: "DirectX 8, then DirectX 9 · GLSL",
      summary:
        "GeForce 3 shipped a programmable vertex unit — a small, branch-free assembly language you wrote yourself, replacing the fixed transform-and-light block outright — alongside pixel shader 1.1, which was still more a configurable combiner than a processor. The following year ATI's Radeon 9700 made the whole thing floating point: 24-bit float throughout the fragment pipeline, long enough shaders to be useful, and a decisive performance lead. From here the fixed-function pipeline is a compatibility layer over a machine that would rather be told what to compute. High-level languages follow immediately: Cg and HLSL in 2002, GLSL in 2004.",
      detail: [
        "Early vertex shaders had no branches and a hard instruction limit — 128 instructions on GeForce 3. You unrolled everything.",
        "Nvidia's answering GeForce FX kept a mix of 16- and 32-bit float and a fragile scheduler; it lost the generation.",
        "Per-pixel normal mapping becomes practical here, and Doom 3 in 2004 is the game that makes the whole industry adopt it.",
      ],
      numbers: [
        { k: "NV20 transistors", v: "57 million" },
        { k: "Shader length", v: "128 instructions" },
        { k: "R300 precision", v: "24-bit float" },
      ],
      stages: { geometry: "prog", setup: "fixed", raster: "fixed", texture: "fixed", fragment: "prog", rop: "fixed", ray: "cpu" },
    },
    {
      id: "unified",
      year: 2005,
      short: "2005–07",
      name: "Unified shaders, and CUDA",
      maker: "ATI Xenos · Nvidia G80",
      machine: "Xbox 360, 2005 · GeForce 8800, Nov 2006",
      headline: "The pipeline dissolves into a pool of identical cores.",
      primitive: "Threads",
      api: "DirectX 10 · CUDA",
      summary:
        "Separate vertex and pixel units waste silicon: a scene heavy in geometry starves the pixel units, and a scene heavy in fill starves the vertex units. ATI's Xenos in the Xbox 360 (2005) was the first shipping design to merge them into one pool of processors scheduled between roles on demand; Nvidia's G80 brought unified shaders to the desktop in November 2006 as the first DirectX 10 part. Once the hardware is a general array of processors with a scheduler, graphics is only one thing it can be asked to do — and CUDA, in 2007, said so out loud. The machine-learning boom of the following decade ran on this hardware, bought for graphics and repurposed.",
      detail: [
        "G80's cores run in groups of 32 threads in lockstep — a 'warp' — which is why divergent branches cost you both sides.",
        "Geometry shaders arrive with DirectX 10, are used sparingly, and are a cautionary tale about stages that can amplify their own output.",
        "Compute shaders turn the GPU back into a machine for the whole frame: culling, particles, post-processing, lighting, hierarchies.",
      ],
      numbers: [
        { k: "G80 cores", v: "128" },
        { k: "Warp width", v: "32 threads" },
        { k: "Transistors", v: "681 million" },
      ],
      stages: { geometry: "prog", setup: "fixed", raster: "fixed", texture: "fixed", fragment: "prog", rop: "fixed", ray: "cpu" },
    },
    {
      id: "explicit",
      year: 2013,
      short: "2013–16",
      name: "Explicit APIs",
      maker: "AMD Mantle · Khronos · Microsoft · Apple",
      machine: "Vulkan, February 2016",
      headline: "The driver stops guessing what you meant.",
      primitive: "Command buffers, recorded in parallel",
      api: "Mantle · Metal · Direct3D 12 · Vulkan",
      summary:
        "By the 2010s the expensive part of a draw call was not the drawing. It was the driver: validating state, chasing shader recompiles, guessing which of a thousand combinations of settings you had just implied, and doing it on one thread. AMD's Mantle (2013) proposed the alternative — hand the application the pipeline state objects, the memory allocation, the synchronisation and the command buffers, and get out of the way. Apple's Metal followed in 2014, Direct3D 12 and Vulkan in 2015 and February 2016. The bargain is explicit: far more code, far more ways to corrupt memory, and a CPU that can feed the GPU from every core it has.",
      detail: [
        "A pipeline state object bakes the whole fixed-function configuration and the compiled shaders into one immutable thing, so nothing has to be recompiled mid-frame.",
        "Synchronisation becomes yours: barriers, fences and semaphores, wrongly placed, produce corruption rather than a helpful error.",
        "The reward is command buffers recorded on many threads at once, which is the only way to issue tens of thousands of draws per frame.",
      ],
      numbers: [
        { k: "Driver overhead", v: "~10x lower" },
        { k: "Recording threads", v: "all of them" },
        { k: "Validation", v: "opt-in layer" },
      ],
      stages: { geometry: "prog", setup: "fixed", raster: "fixed", texture: "fixed", fragment: "prog", rop: "fixed", ray: "cpu" },
    },
    {
      id: "raytracing",
      year: 2018,
      short: "2018–now",
      name: "Rays, and rasterization in software again",
      maker: "Nvidia Turing · Microsoft DXR · Epic",
      machine: "RTX 2080, 2018 · Unreal Engine 5, 2021",
      headline: "Appel's 1968 idea returns, in silicon.",
      primitive: "Rays against a bounding-volume hierarchy",
      api: "DXR · Vulkan Ray Tracing",
      summary:
        "DirectX Raytracing was announced in March 2018 and Nvidia's Turing shipped that September with fixed-function units for the two operations that dominate a ray tracer: walking a bounding-volume hierarchy and intersecting a ray with a triangle. Rays are not a replacement for rasterization — nothing beats a rasterizer at finding the nearest surface for every pixel of a primary view — but they answer the questions rasterization cannot: what does this surface see, what light reaches this point, what is behind the camera. Because the sample counts affordable in real time are tiny, the picture arrives noisy and is cleaned up by a temporal denoiser, which is itself increasingly a neural network. And the work has started moving back: Unreal Engine 5's Nanite rasterizes triangles smaller than a pixel in a compute shader — in software, on the GPU — because for that size the hardware rasterizer's fixed 2x2 pixel quad is the wrong shape.",
      detail: [
        "A bounding-volume hierarchy turns intersection from a linear scan of every triangle into a logarithmic walk, and building it well is most of the work.",
        "Hardware rasterizers shade in 2x2 quads so that neighbouring pixels can difference each other for texture derivatives; a sub-pixel triangle wastes three quarters of that.",
        "Denoising, temporal accumulation and upscaling are now inseparable from the renderer: the raw sampled image is never what you see.",
      ],
      numbers: [
        { k: "Rays/s", v: "~10 billion" },
        { k: "Samples/pixel", v: "1–4, then denoise" },
        { k: "Nanite triangles", v: "sub-pixel" },
      ],
      stages: { geometry: "prog", setup: "fixed", raster: "fixed", texture: "fixed", fragment: "prog", rop: "fixed", ray: "fixed" },
    },
  ];

  // ----------------------------------------------------------
  // The pipeline, stage by stage. Each entry is one stop in the
  // step-through instrument.
  // ----------------------------------------------------------
  var PIPELINE = [
    {
      id: "input",
      name: "Vertex fetch",
      space: "Object space",
      one: "Read the corners out of memory.",
      body:
        "A model is an array of vertices and a list of indices into it. The indices matter more than they look: in a closed triangle mesh every corner is shared by six triangles on average, so indexing them rather than repeating them cuts the transform work by roughly six and the memory by roughly three. Everything downstream is a stream of these corners.",
      hardware: "A fixed-function fetch unit with a small post-transform cache, so a shared vertex is usually transformed once.",
    },
    {
      id: "vertex",
      name: "Vertex shading",
      space: "Object → clip space",
      one: "Multiply each corner by one 4x4 matrix.",
      body:
        "Every vertex is multiplied by the model matrix (where the object sits in the world), the view matrix (where the camera is) and the projection matrix (what the lens does), usually pre-multiplied into one. In fixed-function days this stage also computed the lighting, which is why it was called transform and lighting. Since 2001 it is your program, and it can compute anything it likes as long as it emits a clip-space position.",
      hardware: "Programmable cores. Runs in wide lockstep groups, so all vertices execute the same instruction on different data.",
    },
    {
      id: "clip",
      name: "Clipping",
      space: "Clip space",
      one: "Cut away what is outside the box — and behind the eye.",
      body:
        "Clip space is the last place where the geometry is still linear, which is why clipping happens here. Only one plane genuinely must be clipped: the near plane, where w passes through zero. A vertex behind the eye has negative w, and dividing by it flips the point through the origin to somewhere plausible-looking and completely wrong. The other five planes are an optimisation — a rasterizer that clamps its bounding box handles them.",
      hardware: "Fixed function, and expensive enough that hardware avoids it: most triangles are trivially accepted or rejected by a bounding test first.",
    },
    {
      id: "divide",
      name: "Perspective divide",
      space: "Clip → NDC",
      one: "Divide x, y and z by w. This is perspective.",
      body:
        "The projection matrix does not create perspective; it only arranges for w to hold the viewer-space depth. The division is what makes distant things small — and it is the only non-linear step in the whole pipeline, which is where most of the difficulties that follow come from. Attributes that were linear across the triangle in 3D are not linear across it on screen any more, and depth values get crushed towards the near plane.",
      hardware: "One reciprocal per vertex. The cheapest instruction in the pipeline, and the one everything else has to work around.",
    },
    {
      id: "viewport",
      name: "Viewport transform",
      space: "NDC → screen",
      one: "Scale the unit cube onto the pixel grid.",
      body:
        "Normalised device coordinates run from -1 to +1 in x and y. The viewport transform maps that onto the actual pixel rectangle and flips y, because screens count rows downward and mathematics counts upward. Coordinates are then snapped to a fixed sub-pixel grid — Direct3D requires at least eight fractional bits — which is what makes the coverage rules that follow exact rather than a matter of floating-point luck.",
      hardware: "Fixed function. Also where the guard band lives: a region beyond the screen a triangle may occupy without needing real clipping.",
    },
    {
      id: "setup",
      name: "Triangle setup",
      space: "Screen space",
      one: "Compute the three edge functions, and the area.",
      body:
        "Setup turns three corners into the coefficients of three linear edge functions plus the interpolation gradients for every attribute. The signed area falls out of the same arithmetic, and its sign is the winding — which is how backface culling costs nothing: roughly half of a closed model's triangles face away, and they are discarded here before a single pixel is considered.",
      hardware: "Fixed function, and a classic bottleneck. A triangle costs the same to set up whether it covers a thousand pixels or none.",
    },
    {
      id: "raster",
      name: "Rasterization",
      space: "Screen space",
      one: "Ask every pixel: are all three edge functions positive?",
      body:
        "The rasterizer walks tiles of the triangle's bounding box and evaluates the three edge functions at each sample. All three positive means covered. Pixels exactly on a shared edge are resolved by the top-left rule so that two adjacent triangles cover them exactly once — no seams, no double-blending. Output is fragments: candidate pixels, each with interpolated attributes, in 2x2 quads so that neighbours can be differenced for texture derivatives.",
      hardware: "Fixed function, hierarchical, and massively parallel — whole tiles tested at once, then refined.",
    },
    {
      id: "fragment",
      name: "Fragment shading",
      space: "Per pixel",
      one: "Run your program once per covered sample.",
      body:
        "Attributes arrive interpolated — and interpolated the hard way, dividing through by w, because screen space and 3D space disagree about what 'halfway' means. The shader samples textures, evaluates a lighting model and returns a colour. This is where almost all of a modern frame's arithmetic happens, and where the pipeline's parallelism is at its most extreme: thousands of pixels in flight, each stalled on memory most of the time.",
      hardware: "Programmable cores, the same pool as the vertex stage since 2006. Texture fetches are asynchronous; the scheduler hides them behind other work.",
    },
    {
      id: "depth",
      name: "Depth and stencil test",
      space: "Per pixel",
      one: "Is anything already nearer?",
      body:
        "Compare the fragment's depth against what the buffer holds and discard it if something nearer is already there. Catmull's 1974 idea, still unbeaten, and order-independent: draw the triangles in any sequence and get the same answer. Modern hardware runs the test BEFORE the fragment shader whenever it legally can — the shader must not write its own depth or discard — which is why an early depth pre-pass is worth the extra geometry.",
      hardware: "Fixed function, heavily compressed, with a coarse hierarchical stage that rejects whole tiles at once.",
    },
    {
      id: "blend",
      name: "Blend and write",
      space: "Framebuffer",
      one: "Combine with what is already there, in order.",
      body:
        "Blending is the one stage that must respect the order the application submitted its primitives, because alpha compositing is not commutative. That single ordering requirement is the reason transparent geometry still has to be sorted by hand thirty years on, and the reason a dozen order-independent transparency schemes exist and none has won.",
      hardware: "Fixed function, in the ROP units, sitting directly on the memory controller.",
    },
  ];

  var STAGE_KEYS = [
    { id: "geometry", label: "Transform" },
    { id: "setup", label: "Setup" },
    { id: "raster", label: "Rasterize" },
    { id: "texture", label: "Texture" },
    { id: "fragment", label: "Shade" },
    { id: "rop", label: "Depth / blend" },
    { id: "ray", label: "Ray trace" },
  ];

  var STAGE_STATES = {
    none: { label: "does not exist", short: "—" },
    cpu: { label: "software on the CPU", short: "CPU" },
    fixed: { label: "fixed-function silicon", short: "FIXED" },
    prog: { label: "programmable silicon", short: "PROG" },
  };

  var SOURCES = [
    { claim: "Sketchpad, 1963: a drawing held as structure, edited with a light pen on the TX-2.",
      cite: "Ivan E. Sutherland, 'Sketchpad: A Man-Machine Graphical Communication System', MIT PhD thesis, 1963." },
    { claim: "Ray casting proposed as a way to find visible surfaces, 1968.",
      cite: "Arthur Appel, 'Some Techniques for Shading Machine Renderings of Solids', AFIPS 1968." },
    { claim: "Interpolating vertex colours across a polygon, 1971.",
      cite: "Henri Gouraud, 'Continuous Shading of Curved Surfaces', IEEE Transactions on Computers C-20(6), 1971." },
    { claim: "Interpolating normals, and adding a specular term, 1973–75.",
      cite: "Bui Tuong Phong, University of Utah PhD thesis, 1973; 'Illumination for Computer Generated Pictures', CACM 18(6), 1975." },
    { claim: "The z-buffer and texture mapping, 1974.",
      cite: "Edwin Catmull, 'A Subdivision Algorithm for Computer Display of Curved Surfaces', University of Utah PhD thesis, 1974. The depth-buffer idea was described independently by Wolfgang Strasser in his 1974 dissertation." },
    { claim: "A taxonomy of the ten hidden-surface algorithms then known, 1974.",
      cite: "Sutherland, Sproull & Schumacker, 'A Characterization of Ten Hidden-Surface Algorithms', ACM Computing Surveys 6(1), 1974." },
    { claim: "The halfway vector replaces the reflection vector, 1977.",
      cite: "James F. Blinn, 'Models of Light Reflection for Computer Synthesized Pictures', SIGGRAPH 1977." },
    { claim: "Shadow maps, 1978; bump mapping, 1978.",
      cite: "Lance Williams, 'Casting Curved Shadows on Curved Surfaces', SIGGRAPH 1978; James F. Blinn, 'Simulation of Wrinkled Surfaces', SIGGRAPH 1978." },
    { claim: "Mipmaps: a pyramid of prefiltered textures costing just under one third extra memory, 1983.",
      cite: "Lance Williams, 'Pyramidal Parametrics', SIGGRAPH 1983." },
    { claim: "The Geometry Engine, the first VLSI geometry pipeline, 1982.",
      cite: "James H. Clark, 'The Geometry Engine: A VLSI Geometry System for Graphics', SIGGRAPH 1982. Silicon Graphics was founded the same year." },
    { claim: "Filling a triangle by evaluating three edge functions in parallel, 1988.",
      cite: "Juan Pineda, 'A Parallel Algorithm for Polygon Rasterization', SIGGRAPH 1988." },
    { claim: "A programmable shading language in a production renderer, 1988.",
      cite: "Pat Hanrahan & Jim Lawson, 'A Language for Shading and Lighting Calculations', SIGGRAPH 1990; the RenderMan Interface Specification, Pixar, 1988. Descends from Rob Cook, 'Shade Trees', SIGGRAPH 1984." },
    { claim: "Perspective-correct interpolation: interpolate attribute/w and 1/w, then divide.",
      cite: "Paul Heckbert & Henry Moreton, 'Interpolation for Polygon Texture Mapping and Shading', in State of the Art in Computer Graphics, 1991." },
    { claim: "OpenGL 1.0 completed 30 June 1992; the Architecture Review Board formed the same year.",
      cite: "'The OpenGL Graphics System: A Specification (Version 1.0)', Silicon Graphics, 1992." },
    { claim: "RealityEngine: real-time texture mapping, mipmapping and multisample antialiasing in one machine.",
      cite: "Kurt Akeley, 'RealityEngine Graphics', SIGGRAPH 1993. The system shipped in 1992." },
    { claim: "Quake's software renderer issued a floating-point divide 16 pixels ahead and interpolated affinely between.",
      cite: "Michael Abrash, 'Graphics Programming Black Book', 1997, especially the chapters on Quake's texture mapping and the Pentium's FDIV latency." },
    { claim: "NV1, 1995: quadratic texture mapping onto quadrilateral patches, drawn by forward mapping.",
      cite: "Nvidia NV1 / SGS-Thomson STG-2000 product documentation, 1995; Jon Peddie, 'Nvidia's Quadratic Processor: The NV1'." },
    { claim: "Microsoft acquired RenderMorphics in February 1995; Direct3D shipped in DirectX 2.0 in June 1996.",
      cite: "Microsoft DirectX release history, 1995-1997; Servan Keondjian's Reality Lab became Direct3D's Immediate and Retained modes. DrawPrimitive replaced execute buffers in DirectX 5, 1997." },
    { claim: "Voodoo Graphics, October 1996: 3D only, with a VGA pass-through cable and the Glide API.",
      cite: "3dfx Interactive SST-1 documentation; Orchid Righteous 3D, released 7 October 1996." },
    { claim: "GeForce 256, 11 October 1999: hardware transform and lighting, marketed as the first 'GPU'.",
      cite: "Nvidia GeForce 256 product materials, 1999." },
    { claim: "GeForce 3 (NV20), February 2001: programmable vertex shaders, vertex and pixel shader 1.1.",
      cite: "Erik Lindholm, Mark Kilgard & Henry Moreton, 'A User-Programmable Vertex Engine', SIGGRAPH 2001." },
    { claim: "Radeon 9700 (R300), 2002: a fully floating-point fragment pipeline at 24-bit precision.",
      cite: "ATI R300 architecture documentation, 2002; DirectX 9 shader model 2.0, 2002. Nvidia's competing NV30 mixed 16- and 32-bit float and lost the generation." },
    { claim: "Xenos (Xbox 360, 2005) was the first shipping unified-shader GPU; G80 (November 2006) was the first on the desktop.",
      cite: "Jeff Andrews & Nick Baker, 'Xbox 360 System Architecture', IEEE Micro 26(2), 2006; Nvidia G80 / GeForce 8800 architecture materials." },
    { claim: "The microfacet distribution that became the industry default.",
      cite: "Trowbridge & Reitz, 1975; Bruce Walter et al., 'Microfacet Models for Refraction through Rough Surfaces', EGSR 2007; Brent Burley, 'Physically-Based Shading at Disney', SIGGRAPH 2012 course notes." },
    { claim: "Mantle, 2013, and Vulkan, February 2016: explicit command buffers and pipeline state objects.",
      cite: "AMD Mantle announced September 2013; the Mantle Programming Guide and API Reference followed in March 2015. Khronos Vulkan 1.0 specification, 16 February 2016." },
    { claim: "DirectX Raytracing announced March 2018; Nvidia Turing shipped hardware BVH traversal and ray-triangle intersection in September 2018.",
      cite: "Microsoft DXR specification, GDC 2018; Nvidia Turing architecture whitepaper, 2018." },
    { claim: "Nanite rasterizes sub-pixel triangles in a compute shader rather than in the hardware rasterizer.",
      cite: "Brian Karis, Rune Stubbe & Graham Wihlidal, 'A Deep Dive into Nanite Virtualized Geometry', SIGGRAPH 2021 Advances in Real-Time Rendering course." },
  ];

  // ----------------------------------------------------------
  // The ledger: version numbers, and the silicon that answered them.
  // ------------------------------------------------------------
  // Two lanes on one year axis, because the interesting part is the race
  // between them — sometimes the specification led and the hardware
  // followed, sometimes the reverse, and a few times a version number
  // marked nothing at all. `explains` links an entry to the section of
  // this page that describes the mechanism it introduced, so the ledger
  // is a way back into the explanations rather than a list of trivia.
  // ----------------------------------------------------------
  var API_LEDGER = [
    { year: 1982, name: "IRIS GL", who: "Silicon Graphics", family: "gl",
      what: "The library the Geometry Engine spoke. Machine-specific, and the direct ancestor of OpenGL.", explains: "transform" },
    { year: 1992, name: "OpenGL 1.0", when: "30 June", who: "Silicon Graphics; the Architecture Review Board convened the same year", family: "gl",
      what: "A pipeline defined as a state machine with a specified order of operations, so the same program produced the same picture on anyone's hardware.", explains: "pipeline" },
    { year: 1995, name: "DirectX 1.0", when: "September", who: "Microsoft", family: "d3d",
      what: "DirectDraw, DirectSound, DirectInput. No 3D whatsoever — the 3D came from RenderMorphics, bought that February." },
    { year: 1996, name: "Direct3D, in DirectX 2.0", when: "June", who: "Microsoft", family: "d3d",
      what: "Triangles, and only triangles — the decision that ended the quad-versus-patch argument in a season. Drawing meant packing 'execute buffers' by hand, and it was widely loathed.", explains: "raster" },
    { year: 1996, name: "Glide", who: "3dfx", family: "vendor",
      what: "Barely more than Voodoo's register set with names on it. Small, honest and fast, which is why 1996 games looked better on 3dfx than on anything else." },
    { year: 1996, name: "DirectX 3.0", when: "September", who: "Microsoft", family: "d3d",
      what: "A maintenance release. DirectX 4 was announced, then cancelled, and never shipped at all." },
    { year: 1997, name: "OpenGL 1.1", who: "ARB", family: "gl",
      what: "Texture objects and vertex arrays: state you could name and reuse instead of re-sending." },
    { year: 1997, name: "DirectX 5.0", when: "August", who: "Microsoft", family: "d3d",
      what: "DrawPrimitive. You could finally hand the driver a list of triangles rather than assembling a command buffer yourself.", explains: "pipeline" },
    { year: 1998, name: "DirectX 6.0", when: "August", who: "Microsoft", family: "d3d",
      what: "Multitexturing in a single pass, DXTC texture compression, and stencil buffers. The release where Direct3D stopped being the weaker option.", explains: "texture" },
    { year: 1998, name: "OpenGL 1.2", who: "ARB", family: "gl",
      what: "Three-dimensional textures, BGRA pixel formats and the imaging subset — the release where the extension mechanism, not the version number, was where the action was." },
    { year: 1999, name: "DirectX 7.0", when: "September", who: "Microsoft", family: "d3d",
      what: "Hardware transform and lighting, cube maps, vertex blending — written for a chip that did not exist yet when the specification was drafted.", explains: "transform" },
    { year: 2000, name: "DirectX 8.0", when: "November", who: "Microsoft", family: "d3d",
      what: "Programmable vertex and pixel shaders — vertex shader 1.1, pixel shader 1.0 and 1.1. The fixed-function pipeline becomes optional for the first time in the field's history.", explains: "shading" },
    { year: 2001, name: "OpenGL 1.3", who: "ARB", family: "gl",
      what: "Multitexturing, cube maps and compressed textures reach core — three years after Direct3D, via the extension mechanism.", explains: "texture" },
    { year: 2001, name: "DirectX 8.1", when: "October", who: "Microsoft", family: "d3d",
      what: "Pixel shader 1.4, ATI's longer and more flexible variant, bolted into the standard." },
    { year: 2002, name: "OpenGL 1.4", who: "ARB", family: "gl",
      what: "Depth textures and shadow comparison: Williams's 1978 shadow map, twenty-four years later, in core.", explains: "depth" },
    { year: 2002, name: "DirectX 9.0", when: "December", who: "Microsoft", family: "d3d",
      what: "Shader model 2.0 and a floating-point fragment pipeline, plus HLSL — a C-like language instead of shader assembly.", explains: "shading" },
    { year: 2003, name: "OpenGL 1.5", who: "ARB", family: "gl",
      what: "Vertex buffer objects: geometry finally lives in graphics memory instead of being pushed across the bus every frame.", explains: "pipeline" },
    { year: 2004, name: "DirectX 9.0c", when: "August", who: "Microsoft", family: "d3d",
      what: "Shader model 3.0 — real branching and loops in a fragment shader, and the reason section 08's divergence problem started mattering to everybody.", explains: "parallel" },
    { year: 2004, name: "OpenGL 2.0", when: "September", who: "ARB", family: "gl",
      what: "GLSL promoted into core, multiple render targets, and non-power-of-two textures. Shaders stop being an extension you check for and become the way the API works.", explains: "shading" },
    { year: 2006, name: "DirectX 10", when: "November", who: "Microsoft", family: "d3d",
      what: "One unified shader model, geometry shaders, and the abolition of capability bits: hardware either implemented the whole specification or did not claim it.", explains: "parallel" },
    { year: 2007, name: "CUDA 1.0", when: "June, after a February beta", who: "NVIDIA", family: "compute",
      what: "The GPU addressed as a parallel computer rather than as a renderer. Everything in the following two decades of machine learning goes through this door.", explains: "parallel" },
    { year: 2008, name: "OpenGL 3.0", when: "August", who: "Khronos", family: "gl",
      what: "The promised clean rewrite — 'Longs Peak' — abandoned for a deprecation model. The specification's low point, and the moment the industry started looking for a successor." },
    { year: 2009, name: "OpenGL 3.1 and 3.2", who: "Khronos", family: "gl",
      what: "The fixed-function pipeline removed outright, and split into core and compatibility profiles." },
    { year: 2009, name: "DirectX 11", when: "October", who: "Microsoft", family: "d3d",
      what: "Compute shaders and hardware tessellation, shader model 5.0, and command lists that could be built on several threads. The GPU becomes a machine for the whole frame.", explains: "parallel" },
    { year: 2010, name: "OpenGL 4.0", when: "March", who: "Khronos", family: "gl",
      what: "Tessellation shaders and double precision, catching up with Direct3D 11 five months later." },
    { year: 2011, name: "WebGL 1.0", when: "March", who: "Khronos", family: "web",
      what: "OpenGL ES 2.0 in a browser tab with no plug-in. Shaders, on any machine, from a URL." },
    { year: 2012, name: "OpenGL 4.3", when: "August", who: "Khronos", family: "gl",
      what: "Compute shaders in OpenGL, and debug output that finally said what you had done wrong.", explains: "parallel" },
    { year: 2013, name: "Mantle", when: "September, announced", who: "AMD", family: "explicit",
      what: "The argument that the driver, not the hardware, was the bottleneck — and a proof of it. Donated to Khronos and became Vulkan.", explains: "pipeline" },
    { year: 2014, name: "Metal", when: "September, announced in June", who: "Apple", family: "explicit",
      what: "Pipeline state objects, command buffers, and no driver guessing what you meant — shipped to users with iOS 8, eight months after Mantle's public driver had made the same argument on the desktop." },
    { year: 2015, name: "Direct3D 12", when: "July", who: "Microsoft", family: "explicit",
      what: "Pipeline state objects, descriptor heaps, explicit memory and synchronisation. Far more code, far more ways to corrupt memory, and every core feeding the GPU." },
    { year: 2016, name: "Vulkan 1.0", when: "16 February", who: "Khronos", family: "explicit",
      what: "Mantle, finished and made portable. The successor OpenGL 3.0 had failed to be." },
    { year: 2017, name: "WebGL 2.0", who: "Khronos", family: "web",
      what: "OpenGL ES 3.0 in the browser: transform feedback, instancing, integer textures." },
    { year: 2017, name: "OpenGL 4.6", when: "July", who: "Khronos", family: "gl",
      what: "SPIR-V ingestion and anisotropic filtering in core. No feature release has followed it, and none is planned — the work moved to Vulkan." },
    { year: 2018, name: "DirectX Raytracing", when: "March, announced", who: "Microsoft", family: "d3d",
      what: "Acceleration structures, ray generation, and hit and miss shaders — a second pipeline, running beside the rasterizer.", explains: "rays" },
    { year: 2020, name: "DirectX 12 Ultimate", when: "May, announced in March", who: "Microsoft", family: "d3d",
      what: "Mesh shaders, variable-rate shading, sampler feedback and DXR 1.1 — and the same feature set in the consoles for the first time." },
    { year: 2020, name: "Vulkan Ray Tracing", when: "November", who: "Khronos", family: "explicit",
      what: "The same acceleration structures and shader stages as DXR, cross-vendor and cross-platform.", explains: "rays" },
    { year: 2023, name: "WebGPU", when: "May, announced in April", who: "the W3C's GPU for the Web group", family: "web",
      what: "Explicit, compute-capable graphics in a browser tab. The successor to WebGL, and the first web API that can express a modern renderer." },
  ];

  var HARDWARE_LEDGER = [
    { year: 1983, name: "SGI IRIS 1000", when: "November", who: "Silicon Graphics", family: "workstation",
      what: "SGI's first product: the Geometry Engine sold as a terminal you plugged into a real computer. The IRIS 2000 workstations followed in 1985.", explains: "transform" },
    { year: 1992, name: "SGI RealityEngine", who: "Silicon Graphics", family: "workstation",
      what: "Real-time texture mapping with mipmaps, a per-pixel depth buffer, and multisample antialiasing — all three at once, for the first time.", explains: "texture" },
    { year: 1993, name: "Super FX", who: "Argonaut and Nintendo", family: "console",
      what: "A co-processor inside the cartridge, drawing flat-shaded polygons on a 16-bit console. Star Fox ran at roughly fifteen frames a second." },
    { year: 1994, name: "Sony PlayStation", who: "Sony", family: "console",
      what: "Textured polygons at a consumer price — with no depth buffer, no perspective correction, and integer screen coordinates.", explains: "depth" },
    { year: 1994, name: "Sega Saturn", who: "Sega", family: "console",
      what: "Quadrilaterals rather than triangles, and two video processors that were difficult to use together." },
    { year: 1995, name: "NVIDIA NV1", who: "NVIDIA and SGS-Thomson", family: "consumer",
      what: "Quadratic patches drawn by forward mapping. Sold as Diamond Edge 3D, and obsolete the moment Direct3D chose triangles.", explains: "raster" },
    { year: 1995, name: "S3 ViRGE", when: "November, announced", who: "S3 Incorporated", family: "consumer",
      what: "So slow at filtered, depth-buffered 3D that it was widely nicknamed a decelerator — software was often faster." },
    { year: 1996, name: "Rendition Vérité V1000", when: "October", who: "Rendition", family: "consumer",
      what: "A programmable RISC core rather than a fixed pipeline, announced in 1995 and late to ship. vQuake, that December, was the first hardware-accelerated Quake — ahead of GLQuake, and on the road not taken." },
    { year: 1996, name: "3dfx Voodoo Graphics", when: "October", who: "3dfx Interactive", family: "consumer",
      what: "Bilinear filtering, depth buffering and fill rate, with no 2D at all: a pass-through cable from your ordinary video card.", explains: "texture" },
    { year: 1996, name: "PowerVR PCX1", who: "VideoLogic and NEC", family: "consumer",
      what: "Tile-based deferred rendering: sort the scene into screen tiles first and never touch external memory for depth." },
    { year: 1996, name: "Nintendo 64", who: "SGI and Nintendo", family: "console",
      what: "Perspective-correct, mipmapped, trilinear and z-buffered — SGI's pipeline in a toy — behind a 4 KB texture cache that made everything blurry.", explains: "texture" },
    { year: 1997, name: "NVIDIA RIVA 128", who: "NVIDIA", family: "consumer",
      what: "NVIDIA's third design and its first triangle part: 2D and Direct3D 3D on one chip, and the company's survival." },
    { year: 1998, name: "3dfx Voodoo2", who: "3dfx Interactive", family: "consumer",
      what: "Single-pass multitexturing, and SLI — two cards splitting alternate scanlines of the same frame." },
    { year: 1998, name: "NVIDIA RIVA TNT", who: "NVIDIA", family: "consumer",
      what: "Two pixel pipelines and 32-bit colour, against the Voodoo2's 16. The quality argument begins." },
    { year: 1998, name: "S3 Savage3D", who: "S3 Incorporated", family: "consumer",
      what: "S3TC texture compression, which Microsoft adopted as DXTC and which is still in every game you own." },
    { year: 1998, name: "Sega Dreamcast", when: "November", who: "Sega, with VideoLogic and NEC", family: "console",
      what: "PowerVR2: tile-based deferred rendering in a console, and the contract NVIDIA lost when NV2 was cancelled." },
    { year: 1999, name: "NVIDIA GeForce 256", when: "October", who: "NVIDIA", family: "consumer",
      what: "Transform and lighting back on the card, seventeen years after SGI put them in silicon — and the marketing that made 'GPU' the name of the category. Sony had already called the PlayStation's rasterizer a GPU in 1994.", explains: "transform" },
    { year: 2000, name: "ATI Radeon (R100)", who: "ATI", family: "consumer",
      what: "HyperZ: hierarchical depth, depth compression and fast clears. Bandwidth, not arithmetic, was already the wall.", explains: "depth" },
    { year: 2000, name: "3dfx Voodoo5 5500", who: "3dfx Interactive", family: "consumer",
      what: "The T-buffer and rotated-grid antialiasing, arriving late and hot. NVIDIA bought 3dfx's assets that December." },
    { year: 2001, name: "NVIDIA GeForce 3 (NV20)", when: "February", who: "NVIDIA", family: "consumer",
      what: "A programmable vertex unit with a 128-instruction limit and no branches. You unrolled everything.", explains: "shading" },
    { year: 2001, name: "Microsoft Xbox (NV2A)", when: "November", who: "NVIDIA and Microsoft", family: "console",
      what: "A GeForce 3 derivative with unified memory — and the console that made Direct3D the default target for a generation." },
    { year: 2001, name: "ATI Radeon 8500", who: "ATI", family: "consumer",
      what: "Pixel shader 1.4: longer, more flexible, and standardised into DirectX 8.1 for ATI's benefit." },
    { year: 2002, name: "ATI Radeon 9700 Pro (R300)", when: "August", who: "ATI", family: "consumer",
      what: "A fully floating-point fragment pipeline at 24 bits, eight pipelines wide, and a decisive lead.", explains: "shading" },
    { year: 2003, name: "NVIDIA GeForce FX 5800 (NV30)", who: "NVIDIA", family: "consumer",
      what: "Mixed 16- and 32-bit float, a fragile scheduler and a famously loud cooler. It lost the generation." },
    { year: 2004, name: "NVIDIA GeForce 6800", who: "NVIDIA", family: "consumer",
      what: "Shader model 3.0: branching in a fragment shader, and the first hardware where divergence cost you visibly.", explains: "parallel" },
    { year: 2005, name: "ATI Xenos, in the Xbox 360", when: "November", who: "ATI and Microsoft", family: "console",
      what: "The first shipping unified shader architecture: one pool of processors scheduled between vertex and pixel work on demand.", explains: "parallel" },
    { year: 2006, name: "NVIDIA G80 / GeForce 8800 GTX", when: "November", who: "NVIDIA", family: "consumer",
      what: "Unified shaders on the desktop, DirectX 10, 128 cores in warps of 32 — and, the following year, CUDA.", explains: "parallel" },
    { year: 2007, name: "AMD R600 / Radeon HD 2900", who: "AMD", family: "consumer",
      what: "A VLIW unified architecture — designed at ATI before AMD bought the company in 2006, and the first part to reach the market under the new name." },
    { year: 2009, name: "ATI Radeon HD 5870", when: "September", who: "ATI, by then part of AMD", family: "consumer",
      what: "The first DirectX 11 hardware: compute shaders and tessellation, a month before the API shipped." },
    { year: 2010, name: "NVIDIA Fermi / GTX 480", who: "NVIDIA", family: "consumer",
      what: "A real cache hierarchy, and the first architecture designed as much for the datacentre as for pixels — though ECC memory and half-rate double precision were reserved for the Tesla parts and fused off on this one." },
    { year: 2011, name: "AMD GCN / Radeon HD 7970", when: "22 December", who: "AMD", family: "consumer",
      what: "A compute-first scalar architecture with 64-wide wavefronts, which then went into both consoles and outlived a decade." },
    { year: 2013, name: "PlayStation 4 and Xbox One", when: "November", who: "Sony, Microsoft and AMD", family: "console",
      what: "GCN in both, with x86 processors and unified memory. For the first time in twenty years, the two consoles and the PC were the same machine." },
    { year: 2016, name: "NVIDIA Pascal / GTX 1080", who: "NVIDIA", family: "consumer",
      what: "16 nm, high clocks, and the generation consumer virtual reality was actually built on." },
    { year: 2017, name: "NVIDIA Volta", who: "NVIDIA", family: "compute",
      what: "Tensor cores: fixed-function units for small matrix multiplies, put there for machine learning and later used to reconstruct frames." },
    { year: 2018, name: "NVIDIA Turing / RTX 2080", when: "September", who: "NVIDIA", family: "consumer",
      what: "RT cores doing bounding-volume traversal and ray-triangle intersection in silicon, next to tensor cores whose shipped job was upscaling the result.", explains: "rays" },
    { year: 2019, name: "AMD RDNA / Radeon RX 5700", when: "July", who: "AMD", family: "consumer",
      what: "A 32-wide wavefront and a redesign aimed at games rather than compute, after eight years of GCN." },
    { year: 2020, name: "PlayStation 5 and Xbox Series X", when: "November", who: "Sony, Microsoft and AMD", family: "console",
      what: "RDNA 2, with ray accelerators and variable-rate shading. Hardware ray tracing arrives in consoles two years after the desktop.", explains: "rays" },
    { year: 2020, name: "Apple M1", when: "November", who: "Apple", family: "consumer",
      what: "A tile-based deferred GPU with unified memory, in a laptop — the PowerVR lineage, thirty years on." },
    { year: 2022, name: "Intel Arc Alchemist", who: "Intel", family: "consumer",
      what: "The first credible third entrant in twenty years, with hardware ray tracing and matrix units for upscaling — Intel's second attempt at a discrete card after the i740." },
    { year: 2022, name: "NVIDIA Ada / RTX 4090", when: "October", who: "NVIDIA", family: "consumer",
      what: "Shader execution reordering to claw back ray-tracing divergence, and frame generation: pictures nothing ever rasterized.", explains: "rays" },
    { year: 2023, name: "Apple M3", when: "November, announced in October", who: "Apple", family: "consumer",
      what: "Hardware ray tracing and dynamic caching on Apple silicon, and mesh shading on a phone-derived architecture." },
  ];

  var LEDGER_FAMILIES = [
    { id: "d3d", label: "Direct3D", lane: "api" },
    { id: "gl", label: "OpenGL", lane: "api" },
    { id: "explicit", label: "Explicit APIs", lane: "api" },
    { id: "web", label: "The web", lane: "api" },
    { id: "compute", label: "Compute", lane: "api" },
    { id: "vendor", label: "Vendor APIs", lane: "api" },
    { id: "workstation", label: "Workstations", lane: "hardware" },
    { id: "consumer", label: "Consumer cards", lane: "hardware" },
    { id: "console", label: "Consoles", lane: "hardware" },
  ];

  global.TRI_HISTORY = {
    eras: ERAS,
    pipeline: PIPELINE,
    stageKeys: STAGE_KEYS,
    stageStates: STAGE_STATES,
    sources: SOURCES,
    ledger: { apis: API_LEDGER, hardware: HARDWARE_LEDGER, families: LEDGER_FAMILIES },
  };
})(typeof window !== "undefined" ? window : globalThis);
