/* Original practice material, not an official question bank or marking scheme. */
(function (root, factory) { const a = factory(); if (typeof module === 'object' && module.exports)
    module.exports = a;
else
    root.MeiosisLearning = a; })(typeof globalThis !== 'undefined' ? globalThis : this, function () {
    'use strict';
    const quiz = [
        { q: 'A cell has 6 chromosomes before S phase. Immediately after S phase, what does it contain?', options: ['12 chromosomes and 12 DNA molecules', '6 chromosomes and 12 DNA molecules', '6 chromosomes and 6 DNA molecules', '3 chromosomes and 6 DNA molecules'], answer: 1, feedback: ['Replication makes sister chromatids; it does not yet create independently segregating daughter chromosomes.', 'Yes. Each of the six chromosomes now contains two sister chromatids: twelve DNA molecules altogether.', 'That describes the cell before replication. Each chromosome has now acquired a second DNA molecule.', 'The number of homologous sets has not been halved. That happens at the first meiotic division.'], link: 'inventory' },
        { q: 'Which description identifies a homologous pair?', options: ['Two strands of the same DNA double helix', 'Two copies made by replicating one chromosome', 'Two chromosomes carrying corresponding genes at corresponding loci', 'Any two chromosomes that travel to the same pole'], answer: 2, feedback: ['Both DNA strands belong to one DNA molecule; they are not separate chromosomes.', 'Those are sister chromatids, not homologues.', 'Yes. Homologues have corresponding gene loci, although their alleles may differ.', 'An assortment can send unrelated chromosome types to the same pole. Destination does not define homology.'], link: 'inventory' },
        { q: 'What separates in meiosis I?', options: ['The strands of each DNA molecule', 'The two arms of each chromosome', 'Sister chromatids', 'Homologous chromosomes'], answer: 3, feedback: ['Unzipping the DNA double helix is part of replication, not this segregation step.', 'Chromosome arms are not cut apart as a normal segregation mechanism.', 'That is the defining separation in meiosis II.', 'Yes. Each future nucleus receives one homologue from each pair, with sisters still joined.'], link: 'division-one' },
        { q: 'Immediately after meiosis I, a daughter cell is best described as…', options: ['haploid, with replicated chromosomes', 'diploid, with unreplicated chromosomes', 'haploid, with half a chromosome of each type', 'diploid, because the chromosomes are still X-shaped'], answer: 0, feedback: ['Yes. It has one homologous set, even though each chromosome still contains two chromatids.', 'It has one member of every homologous pair, not both, and the chromosomes are still replicated.', 'It receives whole chromosomes. “Haploid” does not mean broken or incomplete chromosomes.', 'Shape does not define ploidy. Count homologous sets, not arms or chromatids.'], link: 'division-two' },
        { q: 'One reciprocal crossover occurs between B and C in a bivalent with ABCD and abcd homologues. Which four chromatid combinations can result?', options: ['ABCD, ABCD, abcd, abcd', 'ABCD, ABcd, abCD, abcd', 'ABCD, ABCd, abcD, abcd', 'ABCD, abcd, ABCDabcd, nothing'], answer: 1, feedback: ['This is the no-crossover result for these marker loci.', 'Yes. Two non-sister chromatids exchange corresponding segments; two remain parental.', 'That would describe a crossover between C and D, not between B and C.', 'A normal reciprocal exchange trades corresponding segments; it does not fuse both chromosomes into one product.'], link: 'crossing-over' },
        { q: 'Ignoring crossing over, how many chromosome-origin combinations are possible across many meioses in an organism with 2n = 10?', options: ['10', '20', '32', '1,024'], answer: 2, feedback: ['Count choices per homologous pair, not the starting number of chromosomes.', 'The choices multiply; adding or doubling the chromosome total is not the rule.', 'Yes. There are five homologous pairs, so 2⁵ = 32 possible combinations.', 'The exponent is the haploid number, n = 5, not the diploid number, 2n = 10.'], link: 'assortment' },
        { q: 'In a no-crossover model with three heterozygous chromosome pairs, how many distinct chromosome-origin combinations occur among the four products of ONE meiosis?', options: ['Eight', 'Four, always', 'Three', 'Two'], answer: 3, feedback: ['Eight is the range across many different orientations, not the output of one division.', 'Without crossing over, identical sisters give matching pairs of products in this model.', 'The two meiosis-I products are complementary, and each is copied into two products by sister separation.', 'Yes. The two complementary combinations each appear twice. Across many meioses, eight combinations are possible.'], link: 'assortment' },
        { q: 'During anaphase II, the chromosome count in an undivided cell rises. Why?', options: ['Each separated chromatid is now counted as a daughter chromosome', 'DNA replication has restarted', 'The cell has gained another homologous set from outside', 'Every chromosome has broken into two arms'], answer: 0, feedback: ['Yes. The counting units change at sister separation; the DNA quantity does not.', 'There is no intervening S phase.', 'No chromosomes have entered. Each future nucleus still receives one homologous set.', 'Sisters separate at their cohesion connections; chromosome arms are not the two products.'], link: 'counting' },
        { q: 'In a test cross, 420 AB, 420 ab, 80 Ab and 80 aB offspring are observed. AB and ab are the parental combinations. What is the observed recombination frequency?', options: ['8%', '16%', '42%', '84%'], answer: 1, feedback: ['This counts only one of the two recombinant classes.', 'Yes. (80 + 80) / 1,000 × 100 = 16%.', '420 is one parental class; it is not the recombinant total.', '84% is the parental proportion. The recombinant proportion is its complement here.'], link: 'linkage' },
        { q: 'A single homologous pair fails to separate in meiosis I; the remaining events are normal. What are the four products?', options: ['n + 1, n − 1, n, n', 'n, n, n, n', 'n + 1, n + 1, n − 1, n − 1', '2n, 2n, 0, 0'], answer: 2, feedback: ['That pattern follows failure in one of the two meiosis-II cells in the simple model.', 'The division error affects distribution of one chromosome type.', 'Yes. Both first-division lineages are affected, so all four products have an extra or missing chromosome.', 'Only one homologous pair mis-segregates. The other chromosomes still segregate normally.'], link: 'errors' },
        { q: 'Why can genes on the same chromosome show a recombination frequency close to 50%?', options: ['The genes must actually be on different chromosomes', 'The chromosome disappears in half the cells', 'Crossing over always changes every allele', 'Crossovers between widely separated loci can make their inheritance appear independent'], answer: 3, feedback: ['Different chromosomes are one explanation, but distant loci on the same chromosome can produce the same two-locus result.', 'Chromosome loss is not the explanation for ordinary recombination.', 'Crossing over rearranges combinations; it does not have to change an allele’s sequence.', 'Yes. At large separations, multiple crossovers can obscure linkage. 50% does not prove different chromosomes.'], link: 'linkage' },
        { q: 'Which statement about meiotic products is most accurate?', options: ['Four haploid products in a symmetric model do not necessarily mean four mature gametes', 'Meiosis in humans always gives four mature eggs', 'All plants make gametes directly by meiosis', 'Four meiotic products must always be genetically distinct'], answer: 0, feedback: ['Yes. Spermatids still differentiate; oogenesis is asymmetric; many plant life cycles produce spores by meiosis.', 'Most cytoplasm is retained in one egg lineage, with polar bodies taking the other chromosome sets.', 'In plants, meiosis makes haploid spores; the haploid generation makes gametes by mitosis.', 'Variation is generated, but genetic differences among all four products are not a universal guarantee.'], link: 'life-cycles' }
    ];
    const glossary = [
        ['Allele', 'A version of a DNA sequence at a locus. For a gene, different alleles may have different effects.', 'inventory'],
        ['Aneuploidy', 'An extra or missing individual chromosome, rather than a change in the number of complete sets.', 'errors'],
        ['Autosome', 'A chromosome that is not a sex chromosome. The two-pair model on this page uses autosomes.', 'inventory'],
        ['Bivalent', 'A pair of homologous chromosomes associated in meiosis I. After replication, it contains four chromatids; also called a tetrad.', 'division-one'],
        ['C value', 'Relative DNA amount: 1C is the DNA content of one unreplicated haploid nuclear genome. C is not the number of sets.', 'counting'],
        ['Centromere', 'A specialised chromosome region where the kinetochore assembles. Cohesion near it helps keep sister chromatids associated until separation.', 'inventory'],
        ['Chiasma (plural: chiasmata)', 'A visible connection between homologues associated with a crossover; its maintenance also depends on chromatid cohesion.', 'crossing-over'],
        ['Chromatid', 'One DNA molecule, with associated proteins, in the chromosomal unit. A replicated chromosome has two sister chromatids.', 'inventory'],
        ['Chromosome', 'An organised DNA molecule with associated proteins; after replication it consists of two joined sister chromatids until they separate.', 'inventory'],
        ['Cohesin', 'A protein complex that holds sister chromatids together. Meiotic release occurs in two steps.', 'division-one'],
        ['Crossing over', 'Reciprocal exchange of corresponding DNA segments between non-sister chromatids of homologous chromosomes.', 'crossing-over'],
        ['Cytokinesis', 'Division of the cytoplasm, packaging nuclei into separate cells. It is distinct from nuclear division.', 'division-two'],
        ['Diploid (2n)', 'Having two homologous chromosome sets. It does not specify whether each chromosome has replicated.', 'counting'],
        ['Gamete', 'A reproductive cell, such as a sperm or egg, whose nucleus can fuse with another at fertilisation.', 'life-cycles'],
        ['Haploid (n)', 'Having one chromosome set: one of each chromosome type, not half of each chromosome.', 'counting'],
        ['Homologous chromosomes', 'Chromosomes with corresponding genes at corresponding loci; their alleles may differ.', 'inventory'],
        ['Independent assortment', 'Independent orientation and segregation of different homologous pairs, generating different combinations of parental homologues.', 'assortment'],
        ['Kinetochore', 'The protein assembly at a centromere that links a chromosome to spindle microtubules.', 'division-one'],
        ['Linked genes', 'Genes on the same chromosome. Close loci tend to be inherited together because crossovers between them are less frequent.', 'linkage'],
        ['Locus (plural: loci)', 'A particular position on a chromosome. Think of the address, not the allele occupying it.', 'inventory'],
        ['Non-disjunction', 'Failure of homologues or sister chromatids to segregate normally to opposite poles.', 'errors'],
        ['Ploidy', 'The number of homologous sets in a nucleus: n, 2n, and so on. Not the DNA-copy count.', 'counting'],
        ['Polar body', 'A small cell produced by asymmetric meiotic division during egg formation. It receives chromosomes but little cytoplasm.', 'life-cycles'],
        ['Recombinant', 'A chromosome, chromatid, gamete or offspring with an allele combination different from the specified parental combinations.', 'crossing-over'],
        ['S phase', 'The DNA-synthesis phase before meiosis I. There is no equivalent replication between I and II.', 'inventory'],
        ['Sister chromatids', 'The two chromatids produced by replication of one chromosome. They need not remain genetically identical after crossing over.', 'inventory'],
        ['Spindle', 'A microtubule-based apparatus that organises and separates chromosomes during nuclear division.', 'division-one'],
        ['Synapsis', 'Close pairing and alignment of homologous chromosomes in prophase I.', 'division-one'],
        ['Zygote', 'The cell formed following fertilisation; fusion of two haploid nuclear genomes restores diploidy.', 'life-cycles']
    ];
    return { quiz, glossary };
});
