/* ============================================================
   DARMOK curriculum — Weeks 1–3
   Vocab entry: [jp (kanji[furigana] allowed), kana, romaji, en, type]
   ============================================================ */

/* ================= WEEK 1 — FIRST CONTACT ================= */
DK.week({
  n: 1,
  name: "FIRST CONTACT",
  brief: "Stardate 79519.1. The USS Linguist has entered orbit of Nihon Prime. The universal translator cannot be used here — first contact protocol requires you to speak for yourself. Mission one: rebuild your foundations properly. You have used these words for a year; this week you will finally be told how they actually work.",
  lessons: [
    {
      id: "1.1",
      title: "The Shape of a Sentence",
      sub: "X は Y です — topic, comment, and why the verb hides at the end",
      briefing: [
        ["h", "Japanese is a topic language"],
        ["p", "An English sentence is built around a subject doing something: *I* drink tea. A Japanese sentence is built around a **topic** — the thing we are talking about — followed by a **comment** about it. The pattern you already know, {{XはYです}}, literally means “as for X, (it) is Y”."],
        ["ex", [
          ["私[わたし]は学生[がくせい]です。", "わたしはがくせいです", "I am a student.", "as for me — student — is"],
          ["これはお茶[ちゃ]です。", "これはおちゃです", "This is tea."],
        ]],
        ["p", "Because particles like {{は}} label each word's job, word order is flexible. The one hard rule: **the verb (or です) comes last**. Everything before it is negotiable."],
        ["h", "です — the polite full stop"],
        ["p", "{{です}} is the polite copula — “am / is / are” rolled into one word. It never changes for *I / you / she / they*, which means one form covers everything English needs six for. It carries the politeness of the whole sentence:"],
        ["table", ["Form", "Japanese", "Meaning"], [
          ["present", "学生です", "am/is a student"],
          ["negative", "学生じゃないです", "am not a student"],
          ["past", "学生でした", "was a student"],
          ["past negative", "学生じゃなかったです", "wasn't a student"],
        ]],
        ["note", "は is written with the kana “ha” but **pronounced “wa” when it is a particle**. Duolingo just marks you wrong about this; now you know the rule. (Same story with へ→“e” and を→“o”, coming soon.)"],
        ["h", "Japanese omits the obvious"],
        ["p", "If everyone knows you're talking about yourself, {{私は}} is dropped. {{学生です}} — “(I'm) a student” — is a complete, natural sentence. Duolingo's habit of demanding 私は everywhere teaches slightly robotic Japanese; real speakers state a topic once, then leave it out until it changes."],
        ["tip", "When a sentence confuses you, find です or the verb at the end, then work backwards asking “what job does each particle give its word?”. That one habit replaces a hundred memorised patterns."],
      ],
      vocab: [
        ["私[わたし]", "わたし", "watashi", "I, me", "pronoun"],
        ["学生[がくせい]", "がくせい", "gakusei", "student", "noun"],
        ["先生[せんせい]", "せんせい", "sensei", "teacher", "noun"],
        ["医者[いしゃ]", "いしゃ", "isha", "doctor", "noun"],
        ["艦長[かんちょう]", "かんちょう", "kanchou", "(ship's) captain", "noun"],
        ["日本語[にほんご]", "にほんご", "nihongo", "Japanese (language)", "noun"],
        ["英語[えいご]", "えいご", "eigo", "English (language)", "noun"],
        ["お茶[ちゃ]", "おちゃ", "ocha", "(green) tea", "noun"],
        ["水[みず]", "みず", "mizu", "water", "noun"],
        ["はい", "はい", "hai", "yes", "expression"],
        ["いいえ", "いいえ", "iie", "no", "expression"],
      ],
      exercises: [
        { t: "mc", q: "Which particle marks the **topic** of a sentence?", choices: ["は", "を", "に", "の"], a: 0,
          whyWrong: {
            "を": "を marks the **object** — the thing a verb acts on (パンを食べる), not the topic.",
            "に": "に marks a **destination or location** (駅に行く), not the topic.",
            "の": "の links two nouns as possession (私の船 = “my ship”); it doesn't mark the topic.",
          },
          why: "は tells the listener “here's what we're talking about”. The others mark different jobs: を (object), に (destination/location), の (possession)." },
        { t: "mc", q: "Pick the missing particle.", jp: "私[わたし]＿＿学生[がくせい]です。", speak: false,
          choices: ["は", "を", "へ", "か"], a: 0,
          whyWrong: {
            "を": "を is for objects, but 学生 here **describes** 私 — nothing is being acted on.",
            "へ": "へ points toward a destination; nobody's going anywhere in this sentence.",
            "か": "か would turn this into a question; here you're making a plain statement.",
          },
          why: "A plain statement about yourself: 私 is the topic, so it takes は. {{私は学生です}} — “as for me, (I'm) a student.”" },
        { t: "build", en: "I am a student.", tokens: ["私", "は", "学生", "です"], extra: ["を", "か"],
          why: "Topic (私) + は + comment (学生) + です. The polite copula always comes last." },
        { t: "mc", q: "The は in 私は is pronounced…", choices: ["wa", "ha", "ba", "silent"], a: 0,
          whyWrong: {
            "ha": "は is *written* “ha”, but as the **topic particle** it's said “wa”. Only inside a word (はい) does it stay “ha”.",
            "ba": "ば is the voiced kana (with dakuten ゛); plain は never sounds “ba”.",
            "silent": "It's fully pronounced — just “wa” rather than “ha” in this job.",
          },
          why: "Written は, said “wa” — but only when it's the particle. Inside a word (like はい) it stays “ha”." },
        { t: "type", q: "Say: “I am the captain.”", accept: ["私は艦長です", "わたしはかんちょうです"],
          show: "私[わたし]は艦長[かんちょう]です。",
          why: "Topic + は + role + です. Every officer should be able to claim the big chair." },
        { t: "mc", q: "A crewmate asks: {{学生ですか}}. The most natural “Yes, I'm a student” is:",
          choices: ["はい、学生です。", "はい、私はあなたは学生です。", "学生、はい、です。", "はい、です学生。"], a: 0,
          whyWrong: {
            "はい、私はあなたは学生です。": "Two topics (私は…あなたは…) collide, and you'd never spell out the obvious 私は here — over-stuffed and unnatural.",
            "学生、はい、です。": "です is stranded with nothing in front of it; the pieces are in the wrong order.",
            "はい、です学生。": "です must come **last**, after 学生 — never before it.",
          },
          why: "The topic (私) is obvious, so drop it. はい、学生です is complete and natural — no robot-speak required." },
        { t: "build", en: "This is tea.", tokens: ["これ", "は", "お茶", "です"], extra: ["が", "を"],
          why: "これ (this) is the topic; お茶 is the comment. これはお茶です。" },
        { t: "mc", q: "Which is a complete, natural Japanese sentence?",
          choices: ["医者です。", "です医者。", "医者はです。", "は医者です。"], a: 0,
          whyWrong: {
            "です医者。": "です comes **last**, never first — 医者です, not です医者.",
            "医者はです。": "は needs a real word in front to make it the topic; here it just dangles before です.",
            "は医者です。": "は can't open a sentence — it labels the word before it, and here there's nothing to label.",
          },
          why: "医者です — “(I'm) a doctor.” The topic can vanish, but です must stay at the end, and は needs a word in front of it." },
      ],
    },
    {
      id: "1.2",
      title: "は vs が — The Explanation Duolingo Owes You",
      sub: "old information vs new information — the single most-asked question in Japanese",
      briefing: [
        ["h", "Two particles, two different questions"],
        ["p", "{{は}} and {{が}} both stand near the start of a sentence, and Duolingo swaps between them without a word of explanation. The core difference is simple: **は marks old information — what we're already talking about. が marks new information — the answer to a question.**"],
        ["ex", [
          ["私[わたし]は先生[せんせい]です。", "わたしはせんせいです", "I'm a teacher.", "you already know we're discussing me; the news is “teacher”"],
          ["誰[だれ]が艦長[かんちょう]ですか。", "だれがかんちょうですか", "WHO is the captain?"],
          ["ピカードさんが艦長[かんちょう]です。", "ぴかーどさんがかんちょうです", "PICARD is the captain.", "the who is the news, so it takes が"],
        ]],
        ["h", "The spotlight rule"],
        ["p", "Think of が as a spotlight on the word **before** it, and は as a spotlight on everything **after** it. {{私は学生です}} highlights “student” (what am I? a student). {{私が学生です}} highlights “me” (who's the student? ME — not him)."],
        ["h", "Question words never take は"],
        ["p", "{{誰}} (who), {{何}} (what), {{どこ}} (where) can never be a topic — you can't already be talking about an unknown! So they always take **が** in subject position, and so does the word that answers them."],
        ["table", ["Situation", "Particle", "Example"], [
          ["introducing yourself", "は", "私はマリコです。"],
          ["question word as subject", "が", "誰が先生ですか。"],
          ["answering “who/which”", "が", "田中さんが先生です。"],
          ["something new appears", "が", "猫がいます！ (a cat!)"],
          ["continuing to discuss it", "は", "猫は白いです。(the cat is white)"],
        ]],
        ["note", "There's a bonus meaning: **contrast**. {{紅茶は好きです}} with a stressed は hints “tea I like… (coffee, not so much)”. If a Japanese speaker sounds like they're implying something, は is usually the culprit."],
        ["tip", "Don't aim for perfection here — even advanced learners refine は/が for years. Aim for the two reflexes: question words take が, and “as for X” takes は. Those two cover most of daily life."],
      ],
      vocab: [
        ["誰[だれ]", "だれ", "dare", "who", "question"],
        ["何[なに]", "なに", "nani", "what", "question"],
        ["猫[ねこ]", "ねこ", "neko", "cat", "noun"],
        ["犬[いぬ]", "いぬ", "inu", "dog", "noun"],
        ["人[ひと]", "ひと", "hito", "person", "noun"],
        ["友達[ともだち]", "ともだち", "tomodachi", "friend", "noun"],
        ["名前[なまえ]", "なまえ", "namae", "name", "noun"],
        ["紅茶[こうちゃ]", "こうちゃ", "koucha", "black tea", "noun"],
        ["コーヒー", "こーひー", "koohii", "coffee", "noun"],
        ["宇宙船[うちゅうせん]", "うちゅうせん", "uchuusen", "spaceship", "noun"],
        ["白[しろ]い", "しろい", "shiroi", "white", "adjective"],
      ],
      exercises: [
        { t: "mc", q: "Pick the missing particle.", jp: "誰[だれ]＿＿艦長[かんちょう]ですか。", speak: false,
          choices: ["が", "は", "を", "の"], a: 0,
          whyWrong: {
            "は": "Question words like 誰 can **never** take は — you can't already be discussing an unknown.",
            "を": "を marks an object; 誰 here is the **subject** you're asking about.",
            "の": "の links two nouns; it can't attach a question word to です like this.",
          },
          why: "Question words can never be topics — you can't already be discussing an unknown. 誰 always takes が as a subject." },
        { t: "mc", q: "Now answer it: “TANAKA is the captain.”", choices: ["田中さんが艦長です。", "田中さんは艦長です。", "田中さんを艦長です。", "田中さんの艦長です。"], a: 0,
          whyWrong: {
            "田中さんは艦長です。": "Grammatical, but は answers a *different* question — “tell me about Tanaka”. The reply to a が-question keeps が.",
            "田中さんを艦長です。": "を marks the object of a verb; there's no verb acting on Tanaka here, just です.",
            "田中さんの艦長です。": "の would make it “Tanaka's captain” — possession, not “Tanaka **is** the captain”.",
          },
          why: "The answer to a が-question is the new information, so it takes が too. 田中さんは艦長です isn't wrong grammar, but it answers a different question (“tell me about Tanaka”)." },
        { t: "mc", q: "You want to say “I like TEA (as for tea, it's fine — unlike coffee…)”. Which particle carries that contrastive hint?",
          choices: ["は", "が", "を", "も"], a: 0,
          whyWrong: {
            "が": "が spotlights new information plainly; it carries no “…unlike the others” hint. は is the contrastive one.",
            "を": "を marks an object, but 好き pairs with は/が, and を can't add contrast anyway.",
            "も": "も means “too/also” — it would *include* coffee, the opposite of the contrast you want.",
          },
          why: "は has a second job: contrast. 紅茶は… implies “tea, at least” — the unspoken comparison hangs in the air, very Japanese." },
        { t: "mc", q: "A cat suddenly walks onto the bridge. The natural cry is:",
          choices: ["猫がいます！", "猫はいます！", "猫のいます！", "猫でいます！"], a: 0,
          whyWrong: {
            "猫はいます！": "は marks something already under discussion — but the cat is **brand-new** to the scene, so が.",
            "猫のいます！": "の links two nouns; it can't sit between 猫 and the verb います.",
            "猫でいます！": "で marks a means or a place of action, not the thing that exists.",
          },
          why: "Something NEW enters the scene → が. Once everyone's watching it, you switch: 猫は白いです (the cat — it's white)." },
        { t: "build", en: "Who is the teacher?", tokens: ["誰", "が", "先生", "です", "か"], extra: ["は", "を"],
          why: "誰 + が (question word, so never は) + 先生です + か." },
        { t: "mc", q: "{{私が学生です}} (with が) most precisely means…",
          choices: ["I'M the student (not him)", "I am a student, in general", "Am I a student?", "I was a student"], a: 0,
          whyWrong: {
            "I am a student, in general": "That's the plain 私**は**学生です. The が version spotlights 私 — “it's ME”.",
            "Am I a student?": "There's no か and no question word — it's a statement, not a question.",
            "I was a student": "Nothing here is past tense; です is present.",
          },
          why: "が spotlights what comes before it. 私が = “it is I who…”. Very useful for claiming credit on the bridge." },
        { t: "type", q: "Ask “What is (your) name?” — use お名前", accept: ["お名前は何ですか", "おなまえはなんですか", "お名前はなんですか"],
          show: "お名前[なまえ]は何[なん]ですか。",
          why: "Adding お to 名前 makes it politely about *their* name. 何 reads なん before です." },
      ],
    },
    {
      id: "1.3",
      title: "Asking Questions — か and Friends",
      sub: "何・誰・どこ・いつ — interrogation, the polite way",
      briefing: [
        ["h", "か turns anything into a question"],
        ["p", "No word-order gymnastics, no “do/does”: put {{か}} at the end of a polite sentence and it becomes a question. In writing, か even replaces the question mark."],
        ["ex", [
          ["学生[がくせい]ですか。", "がくせいですか", "Are (you) a student?"],
          ["はい、学生[がくせい]です。", "はい、がくせいです", "Yes, (I) am."],
          ["いいえ、学生[がくせい]じゃないです。", "いいえ、がくせいじゃないです", "No, (I'm) not."],
        ]],
        ["h", "The question-word squad"],
        ["table", ["Word", "Meaning", "Example"], [
          ["何[なに]／何[なん]", "what", "これは何ですか。 What's this?"],
          ["誰[だれ]", "who", "あの人は誰ですか。 Who's that?"],
          ["どこ", "where", "トイレはどこですか。 Where's the toilet?"],
          ["いつ", "when", "会議はいつですか。 When's the meeting?"],
          ["どう", "how", "日本はどうですか。 How's Japan (treating you)?"],
        ]],
        ["p", "{{何}} reads **なん** before です, か, の and counters (なんですか), and **なに** most other places (なにを). Both are the same word; your mouth just takes the smoother path."],
        ["h", "そうです — the all-purpose reply"],
        ["p", "{{そうです}} = “that's right”. {{そうですか}} with falling tone = “I see…” — Japan's favourite way to show you're listening. You will say そうですか thousands of times and it will always be correct."],
        ["tip", "Notice the pattern XはどこですかB — the question word simply sits where the answer will go: トイレは【どこ】ですか → トイレは【あそこ】です。Ask the question, and the reply reuses your own sentence shape. Eavesdropping made easy."],
      ],
      vocab: [
        ["どこ", "どこ", "doko", "where", "question"],
        ["いつ", "いつ", "itsu", "when", "question"],
        ["どう", "どう", "dou", "how", "question"],
        ["トイレ", "といれ", "toire", "toilet", "noun"],
        ["駅[えき]", "えき", "eki", "station", "noun"],
        ["学校[がっこう]", "がっこう", "gakkou", "school", "noun"],
        ["家[いえ]", "いえ", "ie", "house, home", "noun"],
        ["今日[きょう]", "きょう", "kyou", "today", "time"],
        ["明日[あした]", "あした", "ashita", "tomorrow", "time"],
        ["今[いま]", "いま", "ima", "now", "time"],
        ["そうです", "そうです", "sou desu", "that's right", "expression"],
      ],
      exercises: [
        { t: "build", en: "Where is the toilet?", tokens: ["トイレ", "は", "どこ", "です", "か"], extra: ["が", "何"],
          why: "The survival sentence of every trip to Japan. Topic + は + question word + ですか." },
        { t: "mc", q: "What does {{そうですか}} (said with a falling tone) mean?",
          choices: ["I see…", "Is that so?! (shock)", "That's wrong", "Please repeat"], a: 0,
          whyWrong: {
            "Is that so?! (shock)": "That's そうですか with a **rising** tone. Falling tone is the gentle “ah, I see”.",
            "That's wrong": "“That's wrong” is ちがいます; そうですか never signals disagreement.",
            "Please repeat": "“Please repeat” is もう一度お願いします — a different phrase entirely.",
          },
          why: "With falling intonation it's the gentle “ah, I see” that keeps every Japanese conversation flowing. Rising tone makes it a genuine question." },
        { t: "mc", q: "Pick the reading: {{何}}ですか", choices: ["なん", "なに", "どこ", "だれ"], a: 0,
          whyWrong: {
            "なに": "何 reads なに before を/が, but before です (and か, の, counters) it smooths to なん.",
            "どこ": "どこ means “where”, not “what”.",
            "だれ": "だれ means “who”, not “what”.",
          },
          why: "何 reads なん before です (and か, の, counters). Before を or が it's なに. Same word, smoother mouth-path." },
        { t: "type", q: "Ask: “What is this?” (use これ)", accept: ["これは何ですか", "これはなんですか"],
          show: "これは何[なん]ですか。",
          why: "Point at mystery food, deploy これは何ですか, learn something new. Works on tricorders too." },
        { t: "mc", q: "Your colleague asks {{会議はいつですか}}. They want to know the meeting's…",
          choices: ["time/date", "place", "attendees", "agenda"], a: 0,
          whyWrong: {
            "place": "“Where” is どこ — 会議はどこですか.",
            "attendees": "“Who” is 誰 — 誰が会議に来ますか. いつ asks *when*.",
            "agenda": "That would ask 何 (what); いつ only asks *when*.",
          },
          why: "いつ = when. 明日です would be a fine answer. (どこ would ask where, 誰 who.)" },
        { t: "build", en: "When is (your) day off?", tokens: ["休み", "は", "いつ", "です", "か"], extra: ["どこ", "を"],
          why: "休み (rest / day off) as topic + いつですか. You'll meet 休み properly in week 3 — consider this a sensor ping." },
        { t: "mc", q: "How do you make {{駅はあそこです}} (“the station is over there”) into a question meaning “Where is the station?”",
          choices: ["Replace あそこ with どこ and add か", "Add か only", "Move です first", "Replace は with か"], a: 0,
          whyWrong: {
            "Add か only": "駅はあそこですか just asks “is the station over there?” — you must also swap あそこ for どこ.",
            "Move です first": "です always stays **last**; moving it breaks the sentence.",
            "Replace は with か": "は marks the topic (the station); drop it and you lose what you're asking about.",
          },
          why: "Question words sit exactly where the answer will: 駅は【どこ】ですか → 駅は【あそこ】です。" },
      ],
    },
    {
      id: "1.4",
      title: "This, That, and That Over There",
      sub: "これ・それ・あれ — the ko-so-a-do targeting system, plus の",
      briefing: [
        ["h", "A three-way pointing system"],
        ["p", "English has *this* and *that*. Japanese splits space three ways — near me ({{こ〜}}), near you ({{そ〜}}), away from both of us ({{あ〜}}) — plus a question form ({{ど〜}}). Learn one row and you've learned them all:"],
        ["table", ["", "near me こ", "near you そ", "over there あ", "which? ど"], [
          ["thing", "これ", "それ", "あれ", "どれ"],
          ["+ noun", "この本", "その本", "あの本", "どの本"],
          ["place", "ここ", "そこ", "あそこ", "どこ"],
        ]],
        ["p", "The crucial split: {{これ}} stands **alone** (“this”), while {{この}} must be **followed by a noun** (“this book”). {{これは本です}} but {{この本は私のです}}. Mixing these up is the classic error — and now you'll never make it."],
        ["ex", [
          ["これは何[なん]ですか。", "これはなんですか", "What is this (thing near me)?"],
          ["その宇宙船[うちゅうせん]は大[おお]きいですね。", "そのうちゅうせんはおおきいですね", "That starship (near you) is big, isn't it."],
          ["あそこはトイレです。", "あそこはトイレです", "Over there is the toilet."],
        ]],
        ["h", "の — the possessive glue"],
        ["p", "{{の}} links two nouns, with the owner/describer first: {{私の船}} “my ship”, {{日本語の先生}} “a teacher **of Japanese**”, {{京都の駅}} “the station **in Kyoto**”. Chain it freely: 私の友達の猫 — my friend's cat."],
        ["p", "When the second noun is obvious, drop it: {{この本は私のです}} — “this book is **mine**”. の quietly does the work of English “'s” and “mine/yours/hers” all at once."],
        ["note", "ね at the end of a sentence invites agreement (“…isn't it?”), よ asserts news (“…I tell you!”). {{大きいですね}} — “big, eh?” {{大きいですよ}} — “it's big, trust me.” Two tiny particles, endless mileage."],
      ],
      vocab: [
        ["これ", "これ", "kore", "this (thing)", "pronoun"],
        ["それ", "それ", "sore", "that (thing)", "pronoun"],
        ["あれ", "あれ", "are", "that (thing) over there", "pronoun"],
        ["どれ", "どれ", "dore", "which (thing)", "question"],
        ["ここ", "ここ", "koko", "here", "pronoun"],
        ["そこ", "そこ", "soko", "there", "pronoun"],
        ["あそこ", "あそこ", "asoko", "over there", "pronoun"],
        ["本[ほん]", "ほん", "hon", "book", "noun"],
        ["船[ふね]", "ふね", "fune", "ship, boat", "noun"],
        ["ペン", "ぺん", "pen", "pen", "noun"],
        ["部屋[へや]", "へや", "heya", "room", "noun"],
      ],
      exercises: [
        { t: "mc", q: "Pick the correct word.", jp: "＿＿ペンは私[わたし]のです。", speak: false,
          choices: ["この", "これ", "ここ", "どれ"], a: 0,
          whyWrong: {
            "これ": "これ stands **alone** (“this”); it can't sit directly in front of a noun like ペン. Use この.",
            "ここ": "ここ means “here” (a place), not “this (thing)”.",
            "どれ": "どれ asks “which one?” — a question word, not a pointer to your own pen.",
          },
          why: "A noun follows (ペン), so you need この. これ stands alone; この must hold a noun's hand." },
        { t: "mc", q: "And now this one.", jp: "＿＿は私[わたし]のペンです。", speak: false,
          choices: ["これ", "この", "ここ", "その"], a: 0,
          whyWrong: {
            "この": "この must be **followed by a noun** (この本); here the word stands alone before は, so これ.",
            "ここ": "ここ means “here” (a place), not “this thing”.",
            "その": "その also needs a noun after it (その本), and points near the listener, not to “this”.",
          },
          why: "No noun directly after — the word stands alone before は — so これ. The pair of this question and the last is the whole rule." },
        { t: "build", en: "This is my book.", tokens: ["これ", "は", "私", "の", "本", "です"], extra: ["この", "が"],
          why: "これは + 私の本 + です. の links owner → owned, in that order." },
        { t: "mc", q: "Your friend is holding a mysterious device. You ask about it with…",
          choices: ["それは何ですか。", "これは何ですか。", "あれは何ですか。", "どれは何ですか。"], a: 0,
          whyWrong: {
            "これは何ですか。": "これ is for something in **your own** hand; the device is with your friend, so それ.",
            "あれは何ですか。": "あれ is for something **far from both** of you, not in your friend's hand.",
            "どれは何ですか。": "どれ means “which one?” and never takes は — it's a question word.",
          },
          why: "It's near *them*, so それ. これ would be in your own hand; あれ across the room; どれ asks “which one”." },
        { t: "match", q: "Match the pointing word to its meaning.", pairs: [
          ["これ", "this thing (near me)"],
          ["それ", "that thing (near you)"],
          ["あれ", "that thing (far away)"],
          ["どこ", "where?"],
        ]},
        { t: "type", q: "Say: “That over there is my ship.” (use あれ)", accept: ["あれは私の船です", "あれはわたしのふねです"],
          show: "あれは私[わたし]の船[ふね]です。",
          why: "あれ — far from both speakers, like a starship in orbit. あれは私の船です. Every captain's favourite sentence." },
        { t: "mc", q: "{{日本語の先生}} means…",
          choices: ["a teacher of Japanese", "a Japanese person's teacher", "teaching Japan", "Japanese and a teacher"], a: 0,
          whyWrong: {
            "a Japanese person's teacher": "That would be 日本人の先生. 日本語 is the *language*, not a person.",
            "teaching Japan": "There's no verb here; の just links two nouns.",
            "Japanese and a teacher": "“and” between nouns is と, not の. の makes the first noun **describe** the second.",
          },
          why: "の makes the first noun describe the second: Japanese-language → teacher. Order matters: 先生の日本語 would be “the teacher's Japanese”." },
      ],
    },
    {
      id: "1.5",
      review: true,
      title: "Mission Review 01",
      sub: "です, は vs が, questions, ko-so-a-do, の — prove the foundations hold",
      briefing: [
        ["h", "Debrief: what you now actually know"],
        ["ul", [
          "**XはYです** — topic + comment; the verb-ish bit lives at the end; obvious topics are dropped.",
          "**は vs が** — は marks what we're already discussing; が marks news, answers, and question words. 誰**が**、私**は**.",
          "**か** makes questions; question words sit where the answer will go.",
          "**これ/それ/あれ/どれ** point near-me / near-you / far / which — and この/その/あの need a noun after them.",
          "**の** glues nouns: owner first, owned second. 私の船.",
        ]],
        ["p", "The simulation below mixes fresh grammar checks with your week's vocabulary. Anything you miss returns at the end — and joins your drill deck for later. That's not punishment; it's the computer being thorough."],
      ],
      vocab: [],
      exercises: [
        { t: "mc", q: "Pick the particle.", jp: "私[わたし]＿＿医者[いしゃ]です。", speak: false,
          choices: ["は", "が", "を", "の"], a: 0,
          whyWrong: {
            "が": "が would insist “**I'm** the doctor (not him)” — save it for reveals. A plain intro takes は.",
            "を": "を marks an object; 医者 here describes 私, and nothing is acted on.",
            "の": "の joins two nouns as possession; it can't link 私 to です.",
          },
          why: "Plain self-introduction: topic は. (が would insist “I'M the doctor” — save it for dramatic reveals.)" },
        { t: "mc", q: "Pick the particle.", jp: "誰[だれ]＿＿医者[いしゃ]ですか。", speak: false,
          choices: ["が", "は", "も", "の"], a: 0,
          whyWrong: {
            "は": "誰 is a question word — it can **never** take は. Question-word subjects always take が.",
            "も": "も means “too”; here you're asking *who*, not adding “also”.",
            "の": "の links nouns; it can't attach 誰 to です.",
          },
          why: "Question word as subject → always が. This reflex is the week's biggest prize." },
        { t: "build", en: "Is that (near you) coffee?", tokens: ["それ", "は", "コーヒー", "です", "か"], extra: ["この", "が"],
          why: "それ for near-the-listener + ですか question." },
        { t: "type", q: "Ask where the station is.", accept: ["駅はどこですか", "えきはどこですか"],
          show: "駅[えき]はどこですか。",
          why: "Topic + どこですか. This sentence will genuinely rescue you in Japan one day." },
        { t: "mc", q: "{{あの人は私の日本語の先生です}} means…",
          choices: ["That person over there is my Japanese teacher", "This person is Japan's teacher", "That teacher owns my Japanese", "Which person is the Japanese teacher?"], a: 0,
          whyWrong: {
            "This person is Japan's teacher": "あの points **far away** (“that person over there”), not “this”, and 日本語 is the language, not 日本.",
            "That teacher owns my Japanese": "Read the の chain left-to-right: 私の → 日本語の → 先生 — “my Japanese-teacher”, no owning of Japanese.",
            "Which person is the Japanese teacher?": "There's no question word or か — it's a statement, not a question.",
          },
          why: "あの+人 (that person yonder) → 私の (my) → 日本語の先生 (teacher of Japanese). Chained の reads left to right." },
      ],
    },
  ],
});

/* ================= WEEK 2 — AWAY TEAM ================= */
DK.week({
  n: 2,
  name: "AWAY TEAM",
  brief: "Stardate 79521.4. Beam-down clearance granted. An away team that cannot say where things are — or get themselves to the shuttle — is a liability. This week: existence, location, and motion. By Friday you can report the position of any object, lifeform, or pastry in the sector.",
  lessons: [
    {
      id: "2.1",
      title: "います・あります — Detecting Lifeforms",
      sub: "the two verbs of existence, and に for where things are",
      briefing: [
        ["h", "Japanese has two “there is”"],
        ["p", "English uses “there is” for everything. Japanese runs a lifeform scan first: {{います}} for things that are **alive and can move** (people, animals, androids arguably), {{あります}} for **everything else** (objects, plants, buildings, abstract things like time or plans)."],
        ["ex", [
          ["猫[ねこ]がいます。", "ねこがいます", "There is a cat."],
          ["時間[じかん]があります。", "じかんがあります", "There is time. / I have time."],
          ["木[き]があります。", "きがあります", "There is a tree.", "trees live, but they don't scurry — so あります"],
        ]],
        ["h", "The full pattern: PLACE に THING が います/あります"],
        ["p", "{{に}} marks **where something exists**. The default sentence shape is: place + に + thing + が + existence verb."],
        ["ex", [
          ["部屋[へや]に猫[ねこ]がいます。", "へやにねこがいます", "There's a cat in the room."],
          ["京都[きょうと]に古[ふる]いお寺[てら]があります。", "きょうとにふるいおてらがあります", "There are old temples in Kyoto."],
        ]],
        ["p", "Notice **が**, not は: the thing's existence is usually the news. Flip to は when the thing is the topic: {{猫はどこにいますか}} — “where's THE cat (we both know about)?”"],
        ["h", "Negatives and the “have” trick"],
        ["table", ["", "animate", "inanimate"], [
          ["there is", "います", "あります"],
          ["there isn't", "いません", "ありません"],
        ]],
        ["p", "あります/います also mean **to have**: {{時間がありますか}} “got a minute?”, {{兄弟がいますか}} “do you have siblings?”. Japanese treats possession as “existence near you” — which is honestly rather zen."],
        ["note", "Choosing います for a robot vacuum is a legitimate philosophical position, but the exam answer is あります. Data would be います. The bar is “does it move of its own will?”"],
      ],
      vocab: [
        ["います", "います", "imasu", "to exist, be (animate)", "verb"],
        ["あります", "あります", "arimasu", "to exist, be (inanimate)", "verb"],
        ["木[き]", "き", "ki", "tree", "noun"],
        ["山[やま]", "やま", "yama", "mountain", "noun"],
        ["川[かわ]", "かわ", "kawa", "river", "noun"],
        ["公園[こうえん]", "こうえん", "kouen", "park", "noun"],
        ["店[みせ]", "みせ", "mise", "shop", "noun"],
        ["レストラン", "れすとらん", "resutoran", "restaurant", "noun"],
        ["コンビニ", "こんびに", "konbini", "convenience store", "noun"],
        ["お寺[てら]", "おてら", "otera", "(Buddhist) temple", "noun"],
        ["時間[じかん]", "じかん", "jikan", "time; hour", "noun"],
      ],
      exercises: [
        { t: "mc", q: "A cat: います or あります?", choices: ["います", "あります", "either", "です"], a: 0,
          whyWrong: {
            "あります": "あります is for **inanimate** things — objects, plants, buildings. A cat moves of its own will → います.",
            "either": "The split is strict: a cat is animate, so only います.",
            "です": "です means “is (X)”; it can't say **there is / exists**. That's います/あります.",
          },
          why: "Cats are animate (allegedly obedient lifeforms) → います. あります is for objects, plants, buildings and abstractions." },
        { t: "mc", q: "A tree: います or あります?", choices: ["あります", "います", "either", "ですか"], a: 0,
          whyWrong: {
            "います": "います is for things that move of their own will. A tree is alive but rooted → あります.",
            "either": "The test isn't “alive?” but “moves by itself?” — a tree doesn't, so あります only.",
            "ですか": "That just makes a question with です; it doesn't say “there is” at all.",
          },
          why: "Alive but rooted — trees take あります. The test isn't “alive?” but “moves of its own will?”" },
        { t: "mc", q: "Pick the particle.", jp: "公園[こうえん]に犬[いぬ]＿＿います。", speak: false,
          choices: ["が", "は", "を", "の"], a: 0,
          whyWrong: {
            "は": "は marks something already known; a dog newly spotted at the park is **news** → が.",
            "を": "を marks an object of an action; います is existence, not an action on the dog.",
            "の": "の links two nouns; it can't sit before the verb います.",
          },
          why: "New thing spotted at a place → が. PLACE に THING が います is the default scan report." },
        { t: "build", en: "There is a cat in the room.", tokens: ["部屋", "に", "猫", "が", "います"], extra: ["は", "あります"],
          why: "Place + に + thing + が + います (animate). Textbook away-team report." },
        { t: "type", q: "Say: “There is a convenience store.” (blessed sentence of every Japan trip)",
          accept: ["コンビニがあります", "こんびにがあります"],
          show: "コンビニがあります。",
          why: "Inanimate → あります. In Japan this sentence is true approximately everywhere, always." },
        { t: "mc", q: "{{時間がありますか}} is best translated…",
          choices: ["Do you have time?", "Is time real?", "What time is it?", "Is there a clock?"], a: 0,
          whyWrong: {
            "Is time real?": "Japanese uses あります for **possession** too — “do you have time?”, not a metaphysics question.",
            "What time is it?": "That's 今何時ですか. This sentence asks whether time *exists for you*.",
            "Is there a clock?": "A clock is 時計. 時間 is “time / an hour” — here “a spare moment”.",
          },
          why: "The “have” trick: possession = existence. Literally “does time exist (for you)?” → got a minute?" },
        { t: "build", en: "There isn't a restaurant here.", tokens: ["ここ", "に", "レストラン", "が", "ありません"], extra: ["います", "いません"],
          why: "ここに + が + ありません (inanimate negative). いません would imply the restaurant were alive, which raises questions." },
      ],
    },
    {
      id: "2.2",
      title: "Above, Below, Inside, Behind",
      sub: "the location words — precision coordinates for everyday objects",
      briefing: [
        ["h", "Location words are nouns"],
        ["p", "“On the desk” in Japanese is literally “at the desk's TOP”: {{机の上に}}. The location word is a **noun**, connected with の, then aimed with に. One pattern, every preposition English ever taught you:"],
        ["table", ["Word", "Reading", "Meaning"], [
          ["上", "うえ", "top / above / on"],
          ["下", "した", "under / below"],
          ["中", "なか", "inside"],
          ["前", "まえ", "in front of"],
          ["後ろ", "うしろ", "behind"],
          ["隣", "となり", "next to"],
          ["近く", "ちかく", "near"],
        ]],
        ["ex", [
          ["机[つくえ]の上[うえ]に本[ほん]があります。", "つくえのうえにほんがあります", "There's a book on the desk.", "desk's top に book が exists"],
          ["銀行[ぎんこう]は駅[えき]の前[まえ]にあります。", "ぎんこうはえきのまえにあります", "The bank is in front of the station."],
          ["かばんの中[なか]に何[なに]がありますか。", "かばんのなかになにがありますか", "What's in the bag?"],
        ]],
        ["h", "Two sentence shapes, same facts"],
        ["p", "Scanning a place: {{机の上に本があります}} (“on the desk, there's a book” — the book is news). Locating a known thing: {{本は机の上にあります}} (“THE book is on the desk” — は because we're both looking for it). Same words, different particle, different question answered — this is は/が paying rent again."],
        ["tip", "隣 (next to) implies same-kind neighbours — a person next to a person, a shop next to a shop. 近く just means “in the vicinity”. If the coffee shop is *beside* the bank: 隣. Somewhere around it: 近く."],
      ],
      vocab: [
        ["上[うえ]", "うえ", "ue", "top, above, on", "location"],
        ["下[した]", "した", "shita", "under, below", "location"],
        ["中[なか]", "なか", "naka", "inside", "location"],
        ["前[まえ]", "まえ", "mae", "front, in front of", "location"],
        ["後[うし]ろ", "うしろ", "ushiro", "behind", "location"],
        ["隣[となり]", "となり", "tonari", "next to", "location"],
        ["近[ちか]く", "ちかく", "chikaku", "near, vicinity", "location"],
        ["机[つくえ]", "つくえ", "tsukue", "desk", "noun"],
        ["テーブル", "てーぶる", "teeburu", "table", "noun"],
        ["かばん", "かばん", "kaban", "bag", "noun"],
        ["銀行[ぎんこう]", "ぎんこう", "ginkou", "bank", "noun"],
      ],
      exercises: [
        { t: "build", en: "There is a book on the desk.", tokens: ["机", "の", "上", "に", "本", "が", "あります"], extra: ["は", "中"],
          why: "机の上 (“the desk's top”) is a noun phrase; aim it with に, then thing + が + あります." },
        { t: "mc", q: "Pick the location word.", jp: "テーブルの＿＿に猫[ねこ]がいます。（the cat is UNDER the table）", speak: false,
          choices: ["下", "上", "前", "中"], a: 0,
          whyWrong: {
            "上": "上 (うえ) means “on top / above” — the opposite of under.",
            "前": "前 (まえ) means “in front of”, not under.",
            "中": "中 (なか) means “inside”, not under.",
          },
          why: "下 (した) = under. Cats treat テーブルの下 as sovereign territory." },
        { t: "mc", q: "“What's inside the bag?” is…",
          choices: ["かばんの中に何がありますか。", "かばんの上に何がありますか。", "かばんに中の何がありますか。", "中のかばんに何がいますか。"], a: 0,
          whyWrong: {
            "かばんの上に何がありますか。": "上 is “on top of” the bag; “inside” is 中.",
            "かばんに中の何がありますか。": "The pieces are scrambled — it's always PLACE の LOCATION に (かばんの中に).",
            "中のかばんに何がいますか。": "中のかばん means “the inside's bag”, and います is for living things, not objects.",
          },
          why: "かばんの中 = the bag's inside. Order is always PLACE の LOCATION-WORD に." },
        { t: "match", q: "Match the location word to its meaning.", pairs: [
          ["上", "above / on"],
          ["後ろ", "behind"],
          ["隣", "next to"],
          ["中", "inside"],
        ]},
        { t: "mc", q: "You're looking for THE bank (both of you know which one). Which is right?",
          choices: ["銀行は駅の前にあります。", "銀行が駅の前にあります。", "銀行を駅の前にあります。", "銀行の駅は前にあります。"], a: 0,
          whyWrong: {
            "銀行が駅の前にあります。": "が presents the bank as **breaking news**; but you both know which bank, so topic は.",
            "銀行を駅の前にあります。": "を marks an object of a verb; あります is existence, with nothing acted on.",
            "銀行の駅は前にあります。": "The の attaches to the wrong noun — this says “the bank's station”, not your meaning.",
          },
          why: "A known thing being located → topic は: “as for the bank, it's in front of the station.” が would present the bank as breaking news." },
        { t: "type", q: "Say: “The cat is next to the dog.” (report this rare truce)",
          accept: ["猫は犬の隣にいます", "ねこはいぬのとなりにいます"],
          show: "猫[ねこ]は犬[いぬ]の隣[となり]にいます。",
          why: "Known cat → は; 犬の隣 “the dog's next-to”; animate → います." },
      ],
    },
    {
      id: "2.3",
      title: "も・と・や — And, Too, and Et Cetera",
      sub: "listing things and agreeing with people, the everyday glue",
      briefing: [
        ["h", "も — “too / also”"],
        ["p", "{{も}} **replaces** は or が (never stacks on them) and means “too”: {{私も学生です}} — “I'm a student too.” With negatives it means “neither/either”: {{私も分かりません}} — “I don't get it either.”"],
        ["ex", [
          ["田中[たなか]さんは先生[せんせい]です。私[わたし]も先生[せんせい]です。", "", "Tanaka is a teacher. I'm a teacher too."],
          ["部屋[へや]に猫[ねこ]もいます。", "", "There's also a cat in the room.", "on top of whatever else we mentioned"],
        ]],
        ["h", "と — the complete list"],
        ["p", "{{と}} joins nouns when you're naming **everything**: {{猫と犬がいます}} — “there's a cat and a dog (and that's all)”. It only joins nouns — never sentences (English “and” between sentences is そして)."],
        ["h", "や — the open-ended list"],
        ["p", "{{や}} joins **examples from a longer list**: {{机の上に本やペンがあります}} — “there are books, pens (and other stuff) on the desk.” Pair it with {{など}} (“…and so on”) for extra shrug. Choosing と when you mean や makes you sound weirdly exhaustive, like reading a cargo manifest."],
        ["table", ["Particle", "Vibe", "Example"], [
          ["と", "the complete list", "紅茶とコーヒー (tea and coffee — that's everything)"],
          ["や", "examples only", "紅茶やコーヒー (tea, coffee, that sort of thing)"],
          ["も", "addition", "紅茶も (tea as well)"],
        ]],
        ["note", "と has a second job you already half-know: “with (someone)” — {{友達と}} “with a friend”. Context makes it obvious which と you've met."],
      ],
      vocab: [
        ["も", "も", "mo", "also, too", "particle"],
        ["と", "と", "to", "and (complete); with", "particle"],
        ["や", "や", "ya", "and (among others)", "particle"],
        ["そして", "そして", "soshite", "and then (joins sentences)", "conjunction"],
        ["りんご", "りんご", "ringo", "apple", "noun"],
        ["パン", "ぱん", "pan", "bread", "noun"],
        ["卵[たまご]", "たまご", "tamago", "egg", "noun"],
        ["牛乳[ぎゅうにゅう]", "ぎゅうにゅう", "gyuunyuu", "milk", "noun"],
        ["魚[さかな]", "さかな", "sakana", "fish", "noun"],
        ["肉[にく]", "にく", "niku", "meat", "noun"],
      ],
      exercises: [
        { t: "mc", q: "Pick the particle.", jp: "田中[たなか]さんは学生[がくせい]です。私[わたし]＿＿学生[がくせい]です。", speak: false,
          choices: ["も", "は", "と", "や"], a: 0,
          whyWrong: {
            "は": "は just re-states the topic; it can't carry “too/also”. That's も, and も **replaces** は.",
            "と": "と joins two nouns (“A and B”); it can't mean “me too”.",
            "や": "や lists examples among others; it doesn't mean “also”.",
          },
          why: "“Me too” → も, and it replaces は entirely. 私もは is never grammatical — も eats the seat." },
        { t: "build", en: "There is a cat and a dog. (complete list)", tokens: ["猫", "と", "犬", "が", "います"], extra: ["や", "も"],
          why: "Both animals named, nothing left out → と. や would imply an unspecified menagerie." },
        { t: "mc", q: "{{かばんの中に本やペンがあります}} tells you the bag contains…",
          choices: ["books, pens, and other unlisted things", "exactly one book and one pen", "either books or pens", "neither books nor pens"], a: 0,
          whyWrong: {
            "exactly one book and one pen": "や doesn't count items; it gives **examples**, implying there's more.",
            "either books or pens": "や isn't “or” — it lists things that are *all* present, plus others.",
            "neither books nor pens": "There's no negative here — the things listed **do** exist in the bag.",
          },
          why: "や lists examples, not the whole inventory. For the complete list you'd hear と." },
        { t: "mc", q: "Join these SENTENCES: 「朝ご飯を食べます。＿＿学校に行きます。」",
          choices: ["そして", "と", "や", "も"], a: 0,
          whyWrong: {
            "と": "と only joins **nouns** (猫と犬), never two whole sentences.",
            "や": "や also joins nouns (examples among others), not sentences.",
            "も": "も means “too”; it can't glue two sentences together.",
          },
          why: "と and や only join nouns. Between sentences, use そして (“and then”)." },
        { t: "type", q: "Say: “Me too.” (two words' worth of instant friendship)",
          accept: ["私もです", "わたしもです"],
          show: "私[わたし]もです。",
          why: "私も + です politely agrees with almost any statement about preferences. Deploy liberally at dinner." },
        { t: "mc", q: "Pick the natural shopping report: you bought eggs, milk, bread *among other things*.",
          choices: ["卵や牛乳やパンを買いました", "卵と牛乳とパンを買いました", "卵も牛乳もパンを買いました", "卵の牛乳のパン"], a: 0,
          whyWrong: {
            "卵と牛乳とパンを買いました": "と is the **complete** list (“only these three”). “Among other things” → や.",
            "卵も牛乳もパンを買いました": "も…も stacks “also/even”; it's not an open example-list.",
            "卵の牛乳のパン": "の chains nouns into one phrase (“the egg's milk's bread”) — nonsense here, and there's no verb.",
          },
          why: "An open list of examples → や. (You'll formally meet 買いました “bought” next week — consider this a preview probe.)" },
      ],
    },
    {
      id: "2.4",
      title: "Going Boldly — 行きます・来ます・帰ります",
      sub: "motion verbs, destinations with に・へ, and transport with で",
      briefing: [
        ["h", "The three verbs of motion"],
        ["p", "{{行きます}} go (away from here), {{来ます}} come (toward here), {{帰ります}} return (to home base — home, homeland, HQ). Japanese picks the verb from the **speaker's** position: your friend at your door says 来ました, you at theirs say 行きました."],
        ["h", "Destination: に or へ"],
        ["p", "Both mark where you're headed, and for arrival points they're interchangeable: {{日本に行きます}} ≒ {{日本へ行きます}}. Nuance: に targets the **point of arrival**, へ the **direction of travel** (a touch more poetic — it's the one on airport signs). Use に and you'll never be wrong."],
        ["ex", [
          ["明日[あした]、京都[きょうと]に行[い]きます。", "あしたきょうとにいきます", "Tomorrow I'm going to Kyoto."],
          ["友達[ともだち]が家[いえ]に来[き]ます。", "ともだちがいえにきます", "A friend is coming to my house."],
          ["七時[しちじ]に家[いえ]に帰[かえ]ります。", "しちじにいえにかえります", "I'll head home at seven."],
        ]],
        ["h", "Transport: で"],
        ["p", "{{で}} marks the **means**: {{電車で}} by train, {{バスで}} by bus, {{車で}} by car. The special case: on foot is {{歩いて}} — no で, it's already a te-form (week 5 will explain why)."],
        ["ex", [
          ["新幹線[しんかんせん]で京都[きょうと]に行[い]きます。", "しんかんせんできょうとにいきます", "I'm going to Kyoto by bullet train."],
        ]],
        ["note", "These are ます-form verbs — polite present AND future in one (“I go / I will go”). Japanese has no separate future tense; context or a time word does that job. The full verb machinery is next week's mission — this week, just fly the three ships."],
      ],
      vocab: [
        ["行[い]きます", "いきます", "ikimasu", "to go", "verb"],
        ["来[き]ます", "きます", "kimasu", "to come", "verb"],
        ["帰[かえ]ります", "かえります", "kaerimasu", "to return, go home", "verb"],
        ["電車[でんしゃ]", "でんしゃ", "densha", "train", "noun"],
        ["バス", "ばす", "basu", "bus", "noun"],
        ["車[くるま]", "くるま", "kuruma", "car", "noun"],
        ["飛行機[ひこうき]", "ひこうき", "hikouki", "airplane", "noun"],
        ["自転車[じてんしゃ]", "じてんしゃ", "jitensha", "bicycle", "noun"],
        ["歩[ある]いて", "あるいて", "aruite", "on foot, walking", "expression"],
        ["日本[にほん]", "にほん", "nihon", "Japan", "noun"],
        ["京都[きょうと]", "きょうと", "kyouto", "Kyoto", "noun"],
        ["イギリス", "いぎりす", "igirisu", "the UK, Britain", "noun"],
      ],
      exercises: [
        { t: "build", en: "I'm going to Kyoto by train.", tokens: ["電車", "で", "京都", "に", "行きます"], extra: ["を", "へ"],
          why: "Means + で first, destination + に, verb last. (へ instead of に would also be fine — the builder just wanted に today.)" },
        { t: "mc", q: "Pick the particle for the MEANS of travel.", jp: "バス＿＿駅[えき]に行[い]きます。", speak: false,
          choices: ["で", "に", "を", "と"], a: 0,
          whyWrong: {
            "に": "に is already marking the destination (駅に). The *means* of travel takes で.",
            "を": "を marks an object; a bus you ride is the **means**, marked で.",
            "と": "と means “with (someone)” or “and”; a bus isn't your companion here.",
          },
          why: "Transport takes で (“by means of”). に is busy marking the destination." },
        { t: "mc", q: "You're at home. Your friend is on the way over. Which verb?",
          choices: ["来ます", "行きます", "帰ります", "います"], a: 0,
          whyWrong: {
            "行きます": "行く is motion **away** from the speaker. Your friend is moving **toward** you → 来ます.",
            "帰ります": "帰る is returning to one's *own* base; your friend is coming to **your** place, not going home.",
            "います": "います is existence (“there is”), not motion.",
          },
          why: "Movement toward the speaker → 来ます. From THEIR phone they'd text 行きます. Perspective decides." },
        { t: "mc", q: "The odd one out — “on foot” is…",
          choices: ["歩いて", "歩で", "歩に", "足で"], a: 0,
          whyWrong: {
            "歩で": "歩 isn't used alone with で; “on foot” is the set te-form 歩いて (week 5 explains the form).",
            "歩に": "に marks a destination, not a manner of moving.",
            "足で": "足で “by foot” is understood but sounds like a tourist; natural Japanese is 歩いて.",
          },
          why: "歩いて is its own word (a te-form, as week 5 will reveal). 足で “by foot” gets your meaning across but marks you as a tourist." },
        { t: "type", q: "Say: “I will go to Japan.”", accept: ["日本に行きます", "にほんにいきます", "日本へ行きます", "にほんへいきます"],
          show: "日本[にほん]に行[い]きます。",
          why: "Destination + に (or へ) + 行きます. Add 来年 (next year) later and it becomes a plan." },
        { t: "mc", q: "{{イギリスに帰ります}} — the speaker is…",
          choices: ["British, heading home", "Japanese, visiting Britain", "lost", "a train announcer"], a: 0,
          whyWrong: {
            "Japanese, visiting Britain": "帰る means returning to your **own** base. A Japanese person going to Britain would 行きます.",
            "lost": "帰る is a deliberate return home — the opposite of lost.",
            "a train announcer": "Nothing here marks an announcement; it's a plain “I'm heading home”.",
          },
          why: "帰る means returning to your base — home, hometown, home country. A Brit in Japan 帰ります to the UK; a Japanese person 行きます there." },
        { t: "build", en: "A friend is coming to (my) house.", tokens: ["友達", "が", "家", "に", "来ます"], extra: ["は", "行きます"],
          why: "New info (a friend!) → が; destination 家に; motion toward speaker → 来ます." },
      ],
    },
    {
      id: "2.5",
      review: true,
      title: "Mission Review 02",
      sub: "existence, location, lists, and motion — the away-team debrief",
      briefing: [
        ["h", "Debrief: sector two secure"],
        ["ul", [
          "**います / あります** — moves by its own will? います. Otherwise あります. Both also mean “to have”.",
          "**PLACE に THING が あります** — and known things flip to は: 本は机の上にあります.",
          "**Location words are nouns**: 机の上に、駅の前に、かばんの中に.",
          "**と** complete list · **や** examples · **も** “too” (replaces は/が).",
          "**行きます・来ます・帰ります** with destination に/へ and transport で.",
        ]],
        ["p", "Simulation begins. Misses recycle to the end of the queue and into your drill deck — the computer forgets nothing, so you don't have to."],
      ],
      vocab: [],
      exercises: [
        { t: "mc", q: "Pick the verb.", jp: "公園[こうえん]に木[き]が＿＿。", speak: false,
          choices: ["あります", "います", "です", "来ます"], a: 0,
          whyWrong: {
            "います": "います is for things that move by themselves; a tree is rooted → あります.",
            "です": "です means “is (X)”, not “there is”. Existence is あります/います.",
            "来ます": "来ます is “comes” (motion); trees don't come, they exist → あります.",
          },
          why: "Trees: alive, yes; free-roaming, no → あります." },
        { t: "build", en: "The bank is in front of the station.", tokens: ["銀行", "は", "駅", "の", "前", "に", "あります"], extra: ["が", "上"],
          why: "Known bank → は, then 駅の前に + あります." },
        { t: "mc", q: "Pick the particle.", jp: "机[つくえ]の上[うえ]に本[ほん]＿＿ペンがあります。（books, pens, other bits）", speak: false,
          choices: ["や", "と", "も", "の"], a: 0,
          whyWrong: {
            "と": "と is the **complete** list (“only book and pen”). “…and other bits” needs や.",
            "も": "も means “too”; it can't link two nouns into an example-list.",
            "の": "の joins nouns into a possessive phrase, not a list.",
          },
          why: "An open-ended list of examples → や." },
        { t: "type", q: "Say: “I'll go home by bus.”", accept: ["バスで家に帰ります", "ばすでいえにかえります", "バスで帰ります", "ばすでかえります"],
          show: "バスで家[いえ]に帰[かえ]ります。",
          why: "Transport で + destination に + 帰ります (returning to base)." },
        { t: "mc", q: "{{冷蔵庫の中に牛乳と卵があります}} — the fridge contains…",
          choices: ["milk and eggs, and that's the lot", "milk, eggs and other things", "either milk or eggs", "no milk or eggs"], a: 0,
          whyWrong: {
            "milk, eggs and other things": "と is the **complete** list — just those two. “And other things” would be や.",
            "either milk or eggs": "と isn't “or”; both are present.",
            "no milk or eggs": "There's no negative — both **do** exist in the fridge.",
          },
          why: "と is the complete list. や would leave the fridge door of possibility open. (冷蔵庫 = fridge — a freebie.)" },
      ],
    },
  ],
});

/* ================= WEEK 3 — MAIN ENGINEERING ================= */
DK.week({
  n: 3,
  name: "MAIN ENGINEERING",
  brief: "Stardate 79523.9. Chief Engineer's orders: stop treating verbs as magic incantations. Japanese verbs are a beautifully regular machine — three classes, a handful of rules, no exceptions worth fearing. Open the access panel. This week powers everything that follows.",
  lessons: [
    {
      id: "3.1",
      title: "The Verb Engine — Three Classes",
      sub: "godan, ichidan, and the two rebels — how every verb you'll ever meet is built",
      briefing: [
        ["h", "Why Duolingo verbs feel random"],
        ["p", "Duolingo shows you 食べます, 飲みます, 行きます as separate facts. They aren't. Every Japanese verb belongs to one of **three classes**, and once you know a verb's class, you can build *every* form it will ever take. This lesson is the single highest-value thing in this course."],
        ["h", "The dictionary form"],
        ["p", "Verbs have a plain “dictionary form” ending in an **-u sound**: 飲む, 食べる, 行く. The polite ます-forms you know are built from it. Class determines how:"],
        ["table", ["Class", "Also called", "How ます is made", "Example"], [
          ["五段 godan", "u-verbs", "final -u → -i, + ます", "飲む → 飲みます"],
          ["一段 ichidan", "ru-verbs", "drop る, + ます", "食べる → 食べます"],
          ["irregular", "the two rebels", "just memorise", "する → します、来る → 来[き]ます"],
        ]],
        ["h", "Spotting the class"],
        ["ul", [
          "Doesn't end in る? → **godan**, guaranteed. (飲む, 行く, 話す…)",
          "Ends in る with an **-iru / -eru** sound? → *usually* **ichidan** (食べる, 見る, 起きる).",
          "Ends in る with -aru/-uru/-oru? → **godan** (乗る, 作る, 分かる).",
          "A few -iru/-eru verbs are godan in disguise: **帰る**, 入る, 走る, 知る. Learn these as “the impostors”.",
        ]],
        ["ex", [
          ["食[た]べる → 食[た]べます", "", "eat (ichidan: drop る, add ます)"],
          ["書[か]く → 書[か]きます", "", "write (godan: ku → ki)"],
          ["帰[かえ]る → 帰[かえ]ります", "", "return (godan impostor! ri, not just る-drop)"],
        ]],
        ["tip", "How do you *know* 帰る is an impostor? Its ます-form: 帰ります (かえ**り**ます). If it were ichidan it would be かえます. Whenever you learn a verb, glance at both forms once — the pair tells you the class forever."],
        ["note", "Only する (do) and 来る (come) are truly irregular. Two. English, for comparison, has about 200 irregular verbs. The engine room here is tidy."],
      ],
      vocab: [
        ["食[た]べます", "たべます", "tabemasu", "to eat", "verb・ichidan"],
        ["飲[の]みます", "のみます", "nomimasu", "to drink", "verb・godan"],
        ["見[み]ます", "みます", "mimasu", "to see, watch", "verb・ichidan"],
        ["聞[き]きます", "ききます", "kikimasu", "to listen, ask", "verb・godan"],
        ["読[よ]みます", "よみます", "yomimasu", "to read", "verb・godan"],
        ["書[か]きます", "かきます", "kakimasu", "to write", "verb・godan"],
        ["買[か]います", "かいます", "kaimasu", "to buy", "verb・godan"],
        ["話[はな]します", "はなします", "hanashimasu", "to speak, talk", "verb・godan"],
        ["します", "します", "shimasu", "to do", "verb・irregular"],
        ["勉強[べんきょう]します", "べんきょうします", "benkyou shimasu", "to study", "verb・irregular"],
      ],
      exercises: [
        { t: "mc", q: "{{食べる}} (eat) ends in -eru. Its class is…",
          choices: ["ichidan (ru-verb)", "godan (u-verb)", "irregular", "adjective"], a: 0,
          whyWrong: {
            "godan (u-verb)": "-iru/-eru verbs are **usually ichidan**. 食べる (tabe-ru) drops る → 食べます.",
            "irregular": "Only する and 来る are irregular. 食べる is a regular ichidan verb.",
            "adjective": "食べる is a **verb** (“to eat”), not an adjective.",
          },
          why: "-iru/-eru ending → usually ichidan: drop る, add ます → 食べます. The friendly class." },
        { t: "mc", q: "{{帰る}} (return) also ends in -eru. Its class is…",
          choices: ["godan — it's an impostor", "ichidan, like 食べる", "irregular", "unknowable"], a: 0,
          whyWrong: {
            "ichidan, like 食べる": "Its ます-form gives it away: 帰り**ます**, not かえます. So it's a **godan** impostor.",
            "irregular": "Only する and 来る are irregular; 帰る just *looks* ichidan but conjugates godan.",
            "unknowable": "It's knowable from the ます-form — 帰ります reveals the godan り.",
          },
          why: "帰る is the most famous impostor: 帰り**ます**, not かえます. Fellow impostors: 入る, 走る, 知る, 切る." },
        { t: "mc", q: "Which pair is the complete set of irregular verbs?",
          choices: ["する と 来る", "する と 行く", "食べる と 飲む", "です と ます"], a: 0,
          whyWrong: {
            "する と 行く": "行く is a regular **godan** verb (行きます), not irregular.",
            "食べる と 飲む": "Both are regular — 食べる (ichidan) and 飲む (godan).",
            "です と ます": "Those are the copula and a polite ending, not verbs in a class.",
          },
          why: "Just two: する→します and 来る→来ます(きます). Everything else follows the rules." },
        { t: "match", q: "Match dictionary form to polite form.", pairs: [
          ["飲む", "飲みます"],
          ["書く", "書きます"],
          ["見る", "見ます"],
          ["する", "します"],
        ]},
        { t: "mc", q: "{{話す}} (speak) doesn't end in る at all. So it's…",
          choices: ["godan — automatically", "ichidan — automatically", "irregular", "a noun"], a: 0,
          whyWrong: {
            "ichidan — automatically": "Ichidan verbs **must** end in る. 話す ends in す → godan.",
            "irregular": "Only する and 来る are irregular; 話す is a textbook godan (話します).",
            "a noun": "話す is a **verb** (“to speak”); the noun is 話 (はなし).",
          },
          why: "No る = godan, no exceptions: 話す→話します (su→shi). This rule alone classifies half the dictionary." },
        { t: "mc", q: "Build the polite form: {{読む}} (read) →",
          choices: ["読みます", "読ます", "読べます", "読ります"], a: 0,
          whyWrong: {
            "読ます": "Godan slides the final -u to **-i** first: mu→mi. 読ます skips that step.",
            "読べます": "That treats it like an ichidan る-verb; 読む is godan (mu→mi).",
            "読ります": "り is for godan verbs ending in る (帰ります); 読む ends in む → み.",
          },
          why: "Godan: slide the final -u to -i (mu→mi), attach ます. 読む→読みます." },
        { t: "mc", q: "勉強します (study) is really…",
          choices: ["a noun + する", "an ichidan verb", "a godan verb", "a particle"], a: 0,
          whyWrong: {
            "an ichidan verb": "It's not one verb — it's the noun 勉強 + する (“do studying”).",
            "a godan verb": "The verb part is する, which is **irregular**, bolted onto a noun.",
            "a particle": "勉強 is a noun (“study”); nothing here is a particle.",
          },
          why: "勉強 (study) + する (do) = “do studying”. Thousands of verbs work like this — learn a noun, get a verb free: 電話する, 料理する, 掃除する…" },
      ],
    },
    {
      id: "3.2",
      title: "を and で — Objects and Workbenches",
      sub: "what you act on, where you act, and what you act with",
      briefing: [
        ["h", "を — the direct object"],
        ["p", "{{を}} (pronounced “o”) marks the thing the verb happens **to**: {{お茶を飲みます}} — “drink tea”, {{本を読みます}} — “read a book”. English shows this by word order; Japanese pins a badge on it, which is why the words can then wander."],
        ["ex", [
          ["水[みず]を飲[の]みます。", "みずをのみます", "I drink water."],
          ["日本語[にほんご]を勉強[べんきょう]します。", "にほんごをべんきょうします", "I study Japanese."],
        ]],
        ["h", "で — where the action happens"],
        ["p", "Last week に marked where things **exist**. For where things **happen**, use {{で}}: {{図書館で本を読みます}} — “I read books at the library.” The test: is the verb an action (で) or existence/arrival (に)?"],
        ["ex", [
          ["喫茶店[きっさてん]でコーヒーを飲[の]みます。", "きっさてんでこーひーをのみます", "I drink coffee at a café."],
          ["喫茶店[きっさてん]に猫[ねこ]がいます。", "きっさてんにねこがいます", "There's a cat in the café.", "existing, not acting → に"],
        ]],
        ["h", "で — also the tool"],
        ["p", "You met transport-で (電車で). Same particle, same idea: **means**. {{ペンで書きます}} — write with a pen. {{日本語で話します}} — speak in Japanese. A place-で is a workbench; a tool-で is a spanner; both answer “by means of what/where?”"],
        ["table", ["Particle", "Marks", "Example"], [
          ["を", "the thing acted on", "パンを買います"],
          ["で", "action's location", "店でパンを買います"],
          ["で", "tool / means", "ペンで書きます・電車で行きます"],
          ["に", "existence / arrival point", "店にパンがあります・店に行きます"],
        ]],
        ["tip", "Full sentence order, when everything shows up at once: TIME は/に PLACE で OBJECT を VERB — 今日、喫茶店でコーヒーを飲みます。Particles carry the meaning, so if you scramble it, a Japanese listener will still catch you. The badges never lie."],
      ],
      vocab: [
        ["音楽[おんがく]", "おんがく", "ongaku", "music", "noun"],
        ["映画[えいが]", "えいが", "eiga", "movie, film", "noun"],
        ["手紙[てがみ]", "てがみ", "tegami", "letter", "noun"],
        ["新聞[しんぶん]", "しんぶん", "shinbun", "newspaper", "noun"],
        ["図書館[としょかん]", "としょかん", "toshokan", "library", "noun"],
        ["喫茶店[きっさてん]", "きっさてん", "kissaten", "café, tea room", "noun"],
        ["ご飯[はん]", "ごはん", "gohan", "rice; a meal", "noun"],
        ["朝[あさ]ご飯[はん]", "あさごはん", "asagohan", "breakfast", "noun"],
        ["晩[ばん]ご飯[はん]", "ばんごはん", "bangohan", "dinner", "noun"],
        ["テレビ", "てれび", "terebi", "TV", "noun"],
      ],
      exercises: [
        { t: "mc", q: "Pick the particle.", jp: "お茶[ちゃ]＿＿飲[の]みます。", speak: false,
          choices: ["を", "が", "で", "に"], a: 0,
          whyWrong: {
            "が": "が marks a subject or new info; the tea is what's **drunk** — an object → を.",
            "で": "で marks a means or place of action, not the thing acted on.",
            "に": "に marks a destination or existence; drinking acts **on** the tea → を.",
          },
          why: "The tea is what gets drunk — direct object → を. (Pronounced “o”; the w is ceremonial.)" },
        { t: "mc", q: "Pick the particle.", jp: "図書館[としょかん]＿＿本[ほん]を読[よ]みます。", speak: false,
          choices: ["で", "に", "を", "へ"], a: 0,
          whyWrong: {
            "に": "に marks where things **exist**; reading is an **action** happening there → で.",
            "を": "を is already on the object (本を); the library is the *place of action* → で.",
            "へ": "へ points toward a destination; you're not travelling, you're reading there.",
          },
          why: "Reading is an ACTION happening at the library → で. If books merely *existed* there, you'd use に." },
        { t: "mc", q: "And this one.", jp: "図書館[としょかん]＿＿本[ほん]があります。", speak: false,
          choices: ["に", "で", "を", "も"], a: 0,
          whyWrong: {
            "で": "で is for where an **action** happens; あります is existence → に.",
            "を": "を marks an object, but existence has no object.",
            "も": "も means “too”; it doesn't mark the place of existence.",
          },
          why: "あります is existence, not action → に. This で/に pair is the whole trick — you just did both sides." },
        { t: "build", en: "I drink coffee at a café.", tokens: ["喫茶店", "で", "コーヒー", "を", "飲みます"], extra: ["に", "が"],
          why: "Action location で + object を + verb. The workbench sentence." },
        { t: "type", q: "Say: “I watch movies.”", accept: ["映画を見ます", "えいがをみます"],
          show: "映画[えいが]を見[み]ます。",
          why: "映画 + を + 見ます. Present AND habitual: this also means “I (regularly) watch films”." },
        { t: "mc", q: "“I write letters with a pen” — which で-job is ペンで doing?",
          jp: "ペンで手紙[てがみ]を書[か]きます。",
          choices: ["tool / means", "location", "direction", "possession"], a: 0,
          whyWrong: {
            "location": "A pen isn't a *place*; here で marks the **instrument** you write with.",
            "direction": "Direction is へ/に; で never marks direction.",
            "possession": "Possession is の; で marks the means — same as 電車で, 日本語で.",
          },
          why: "で marks the means — the pen is the instrument. Same particle as 電車で (by train) and 日本語で (in Japanese)." },
        { t: "build", en: "I study Japanese at school.", tokens: ["学校", "で", "日本語", "を", "勉強します"], extra: ["に", "は"],
          why: "TIME-PLACE-OBJECT-VERB assembly: 学校で + 日本語を + 勉強します." },
      ],
    },
    {
      id: "3.3",
      title: "Yesterday's Verbs — ました・ませんでした",
      sub: "the polite past, and where time words sit",
      briefing: [
        ["h", "Four forms, one table"],
        ["p", "Polite verbs conjugate at the **ます**, and only there. The verb stem never changes — no “eat/ate/eaten” nonsense:"],
        ["table", ["", "non-past", "past"], [
          ["affirmative", "飲みます", "飲みました"],
          ["negative", "飲みません", "飲みませんでした"],
        ]],
        ["ex", [
          ["昨日[きのう]、映画[えいが]を見[み]ました。", "きのうえいがをみました", "I watched a film yesterday."],
          ["朝[あさ]ご飯[はん]を食[た]べませんでした。", "あさごはんをたべませんでした", "I didn't eat breakfast."],
        ]],
        ["p", "That's the entire polite tense system. ます / ません / ました / ませんでした — every verb, all three classes, no exceptions. When people say Japanese conjugation is hard, they have not seen this table."],
        ["h", "Time words: に or nothing?"],
        ["p", "Clock times and calendar dates take {{に}}: {{七時に}} at 7:00, {{月曜日に}} on Monday. Relative time words — 今日, 昨日, 明日, 毎日, 先週 — take **nothing**. They just sit at the front, usually with a comma's worth of pause."],
        ["ex", [
          ["昨日[きのう]、仕事[しごと]をしました。", "きのうしごとをしました", "Yesterday I worked."],
          ["七時[しちじ]に晩[ばん]ご飯[はん]を食[た]べました。", "しちじにばんごはんをたべました", "I ate dinner at seven."],
        ]],
        ["note", "The rule of thumb: if English needs “at/on/in” before it (at 7, on Monday), Japanese needs に. If English doesn't (yesterday, every day), Japanese doesn't either. The languages secretly agree."],
      ],
      vocab: [
        ["昨日[きのう]", "きのう", "kinou", "yesterday", "time"],
        ["先週[せんしゅう]", "せんしゅう", "senshuu", "last week", "time"],
        ["週末[しゅうまつ]", "しゅうまつ", "shuumatsu", "weekend", "time"],
        ["朝[あさ]", "あさ", "asa", "morning", "time"],
        ["夜[よる]", "よる", "yoru", "night", "time"],
        ["買[か]い物[もの]", "かいもの", "kaimono", "shopping", "noun"],
        ["仕事[しごと]", "しごと", "shigoto", "work, job", "noun"],
        ["休[やす]み", "やすみ", "yasumi", "rest; day off", "noun"],
        ["少[すこ]し", "すこし", "sukoshi", "a little", "adverb"],
        ["たくさん", "たくさん", "takusan", "a lot", "adverb"],
      ],
      exercises: [
        { t: "mc", q: "Past tense of {{飲みます}}:",
          choices: ["飲みました", "飲みますた", "飲みましたです", "飲んだます"], a: 0,
          whyWrong: {
            "飲みますた": "The past sits on ます → **ました**, not a mangled “ますた”.",
            "飲みましたです": "です doesn't stack after a past verb; 飲みました is already complete.",
            "飲んだます": "飲んだ is the *plain* past; you can't glue ます onto it. Polite past is 飲みました.",
          },
          why: "Swap ます → ました. The stem 飲み never flinches." },
        { t: "mc", q: "“I didn't go” (polite) is…",
          choices: ["行きませんでした", "行きました", "行きませんです", "行かなかったます"], a: 0,
          whyWrong: {
            "行きました": "That's the **affirmative** past (“I went”); you need the negative.",
            "行きませんです": "The negative past is ません + **でした**, not ません + です.",
            "行かなかったます": "行かなかった is the plain negative past; ます can't attach to it. Use 行きませんでした.",
          },
          why: "Negative past = ません + でした. Two pieces, always in that order." },
        { t: "build", en: "I watched a movie yesterday.", tokens: ["昨日", "映画", "を", "見ました"], extra: ["に", "見ます"],
          why: "昨日 is relative time — no に. Then object を + past verb." },
        { t: "mc", q: "Pick what goes after 七時 (7 o'clock).", jp: "七時[しちじ]＿＿朝[あさ]ご飯[はん]を食[た]べました。", speak: false,
          choices: ["に", "で", "を", "(nothing)"], a: 0,
          whyWrong: {
            "で": "で marks a means or place of action; a clock **time** takes に (七時に).",
            "を": "を marks an object; a time isn't acted on.",
            "(nothing)": "Clock times need に (English needs “at 7”). Only *relative* words like 昨日 take nothing.",
          },
          why: "Clock times take に — English needs “at 7”, so Japanese needs 七時に. The languages secretly agree." },
        { t: "mc", q: "And after 昨日?", jp: "昨日[きのう]＿＿買[か]い物[もの]をしました。", speak: false,
          choices: ["(nothing)", "に", "で", "へ"], a: 0,
          whyWrong: {
            "に": "Relative time words (昨日, 今日, 毎日) take **no** particle — English says “yesterday”, not “on yesterday”.",
            "で": "で marks means or place of action, not a point in time.",
            "へ": "へ marks direction toward a place, not a time.",
          },
          why: "Relative time (yesterday/today/every day) takes no particle. English says “yesterday”, not “on yesterday” — same here." },
        { t: "type", q: "Say: “I didn't eat breakfast.”", accept: ["朝ご飯を食べませんでした", "あさごはんをたべませんでした"],
          show: "朝[あさ]ご飯[はん]を食[た]べませんでした。",
          why: "Object を + ませんでした. A sentence with countless real-world applications, sadly." },
        { t: "mc", q: "{{週末、たくさん休みました}} means…",
          choices: ["I rested a lot at the weekend", "I lost my weekend rest", "The weekend was short", "I will rest next weekend"], a: 0,
          whyWrong: {
            "I lost my weekend rest": "休みました is “rested” (past of 休む), not “lost”.",
            "The weekend was short": "Nothing here describes length; たくさん休みました = “rested a lot”.",
            "I will rest next weekend": "ました is **past**, and there's no “next” here — it already happened.",
          },
          why: "たくさん (a lot) + 休みました (rested, past). ました = past, every single time — no ambush exceptions." },
      ],
    },
    {
      id: "3.4",
      title: "How Often? — よく・時々・あまり・全然",
      sub: "frequency adverbs, and the two that demand a negative verb",
      briefing: [
        ["h", "The frequency dial"],
        ["p", "Slide from always to never. Adverbs sit anywhere before the verb, most naturally after the topic:"],
        ["table", ["Adverb", "Frequency", "Verb must be…"], [
          ["いつも", "always", "affirmative"],
          ["よく", "often", "affirmative"],
          ["時々 ときどき", "sometimes", "affirmative"],
          ["たまに", "occasionally", "affirmative"],
          ["あまり", "not much", "**negative!**"],
          ["全然 ぜんぜん", "not at all", "**negative!**"],
        ]],
        ["h", "The polarity trap"],
        ["p", "{{あまり}} and {{全然}} are **negative polarity items** — they must pair with a negative verb. {{全然分かりません}} “I don't understand at all” ✓. {{全然分かります}} ✗ — it short-circuits, like crossing the streams. Duolingo marks this wrong without explanation; the explanation is simply: these two words made a lifelong pact with ません."],
        ["ex", [
          ["よくコーヒーを飲[の]みます。", "よくこーひーをのみます", "I often drink coffee."],
          ["時々[ときどき]映画[えいが]を見[み]ます。", "ときどきえいがをみます", "I sometimes watch films."],
          ["あまりテレビを見[み]ません。", "あまりてれびをみません", "I don't watch much TV."],
          ["全然[ぜんぜん]お酒[さけ]を飲[の]みません。", "ぜんぜんおさけをのみません", "I don't drink alcohol at all."],
        ]],
        ["h", "毎 — the “every” prefix"],
        ["p", "{{毎}} bolts onto time words: 毎日 every day, 毎朝 every morning, 毎週 every week, 毎年 every year. Like 昨日 and 今日, these take no particle."],
        ["note", "In casual speech you'll hear 全然 with positives (全然いい！ “totally fine!”). It's real, it's slangy, and it's exactly the kind of thing to *recognise* now and *use* later. In polite Japanese, keep the pact: 全然 + negative."],
      ],
      vocab: [
        ["いつも", "いつも", "itsumo", "always", "adverb"],
        ["よく", "よく", "yoku", "often", "adverb"],
        ["時々[ときどき]", "ときどき", "tokidoki", "sometimes", "adverb"],
        ["たまに", "たまに", "tamani", "occasionally", "adverb"],
        ["あまり", "あまり", "amari", "not much (+neg)", "adverb"],
        ["全然[ぜんぜん]", "ぜんぜん", "zenzen", "not at all (+neg)", "adverb"],
        ["毎日[まいにち]", "まいにち", "mainichi", "every day", "time"],
        ["毎朝[まいあさ]", "まいあさ", "maiasa", "every morning", "time"],
        ["毎週[まいしゅう]", "まいしゅう", "maishuu", "every week", "time"],
        ["ニュース", "にゅーす", "nyuusu", "the news", "noun"],
        ["お酒[さけ]", "おさけ", "osake", "alcohol, sake", "noun"],
      ],
      exercises: [
        { t: "mc", q: "Complete it.", jp: "あまりテレビを＿＿。", speak: false,
          choices: ["見ません", "見ます", "見ました", "見ますか"], a: 0,
          whyWrong: {
            "見ます": "あまり demands a **negative** verb — the lifelong pact. あまり…見ます short-circuits.",
            "見ました": "Still affirmative (just past). あまり needs the negative 見ません.",
            "見ますか": "That's a question, still affirmative; あまり requires a negative verb.",
          },
          why: "あまり demands a negative verb — the lifelong pact. あまり…見ません = “don't watch much”." },
        { t: "mc", q: "Which is correct polite Japanese?",
          choices: ["全然分かりません", "全然分かります", "全然分かりました", "分かり全然ます"], a: 0,
          whyWrong: {
            "全然分かります": "全然 must pair with a **negative** in polite speech; 全然分かります breaks the pact.",
            "全然分かりました": "Affirmative (just past); 全然 still needs the negative 分かりません.",
            "分かり全然ます": "全然 is an adverb that sits **before** the verb, not wedged inside 分かります.",
          },
          why: "全然 + negative, always (in polite speech). 全然分かりません — the honest learner's motto, ideally temporary." },
        { t: "build", en: "I study Japanese every day.", tokens: ["毎日", "日本語", "を", "勉強します"], extra: ["に", "あまり"],
          why: "毎日 takes no particle; then object + verb. The sentence this app hopes you'll make true." },
        { t: "type", q: "Say: “I sometimes watch TV.”", accept: ["時々テレビを見ます", "ときどきてれびをみます"],
          show: "時々[ときどき]テレビを見[み]ます。",
          why: "時々 + affirmative. (Fun kanji fact: 々 is a repeat mark — 時々 is literally “time-time”.)" },
        { t: "mc", q: "Sort by frequency — which is the MOST frequent?",
          choices: ["いつも", "よく", "時々", "たまに"], a: 0,
          whyWrong: {
            "よく": "よく (often) is high on the dial, but いつも (always) is higher.",
            "時々": "時々 (sometimes) sits in the middle of the dial.",
            "たまに": "たまに (occasionally) is the least frequent of these four.",
          },
          why: "いつも (always) > よく (often) > 時々 (sometimes) > たまに (occasionally) > あまり…ない > 全然…ない." },
        { t: "mc", q: "{{毎朝コーヒーを飲みます。でも、昨日は飲みませんでした}} means…",
          choices: ["I drink coffee every morning, but yesterday I didn't", "I never drink coffee in the morning", "Yesterday I drank extra coffee", "I'll drink coffee tomorrow"], a: 0,
          whyWrong: {
            "I never drink coffee in the morning": "毎朝…飲みます says you drink it **every** morning — a habit, not “never”.",
            "Yesterday I drank extra coffee": "昨日は飲みませんでした is “yesterday I **didn't** drink”, not extra.",
            "I'll drink coffee tomorrow": "The verbs are present-habit and past; there's no tomorrow here.",
          },
          why: "毎朝 + 飲みます (habit), でも (but), 昨日は + ませんでした (past negative — and that は adds contrast: *yesterday*, exceptionally)." },
      ],
    },
    {
      id: "3.5",
      review: true,
      title: "Mission Review 03",
      sub: "verb classes, を・で, past tense, frequency — engineering sign-off",
      briefing: [
        ["h", "Debrief: the engine runs"],
        ["ul", [
          "**Three classes**: godan (u→i+ます), ichidan (る-drop+ます), and the two rebels する・来る. Beware -eru impostors like 帰る.",
          "**を** marks the object; **で** marks the action's location AND the tool; **に** stays with existence and arrival.",
          "**ました / ませんでした** — the whole polite past. Clock times take に; relative time words take nothing.",
          "**あまり・全然** made a pact with ません and never break it.",
        ]],
        ["p", "This is the week most learners never get told. You now understand more verb mechanics than a year of owl-based tapping delivers. Simulation begins."],
      ],
      vocab: [],
      exercises: [
        { t: "mc", q: "{{見る}} → polite form?", choices: ["見ます", "見ります", "見います", "見べます"], a: 0,
          whyWrong: {
            "見ります": "り is for godan る-verbs (帰ります); 見る is ichidan — just drop る.",
            "見います": "That invents an extra い; ichidan simply drops る and adds ます → 見ます.",
            "見べます": "べ belongs to no rule here; 見る (ichidan) → 見ます.",
          },
          why: "Ichidan: drop る, add ます. 見る→見ます." },
        { t: "mc", q: "Pick both particles: 「喫茶店[きっさてん]＿ 手紙[てがみ]＿ 書きました」",
          choices: ["で・を", "に・を", "を・で", "で・が"], a: 0,
          whyWrong: {
            "に・を": "Writing is an **action** at the café → で, not に (which is for existence/arrival).",
            "を・で": "The pair is flipped: the café is the *place* (で) and the letter the *object* (を).",
            "で・が": "The letter is what's **written** — an object → を, not が.",
          },
          why: "Writing happens AT the café (action → で) TO the letter (object → を)." },
        { t: "build", en: "I didn't drink alcohol last week.", tokens: ["先週", "お酒", "を", "飲みませんでした"], extra: ["に", "飲みました"],
          why: "先週 (relative time, no particle) + を + negative past." },
        { t: "type", q: "Say: “I always listen to music.”", accept: ["いつも音楽を聞きます", "いつもおんがくをききます"],
          show: "いつも音楽[おんがく]を聞[き]きます。",
          why: "いつも + object を + 聞きます. (聞く does double duty: listen AND ask.)" },
        { t: "mc", q: "Which sentence is broken — and why will you never break it?",
          choices: ["全然食べます", "あまり食べません", "たくさん食べました", "時々食べます"], a: 0,
          whyWrong: {
            "あまり食べません": "This one's **fine** — あまり pairs with the negative 食べません, honouring the pact. Not the broken one.",
            "たくさん食べました": "This one's **fine** — たくさん (a lot) takes an affirmative verb. Not the broken one.",
            "時々食べます": "This one's **fine** — 時々 (sometimes) takes an affirmative verb. Not the broken one.",
          },
          why: "全然 with an affirmative verb violates the pact. あまり・全然 → negative, forever and always." },
      ],
    },
  ],
});
