/* ============================================================
   DARMOK curriculum — Weeks 7–9
   ============================================================ */

/* ================= WEEK 7 — STELLAR CARTOGRAPHY ================= */
DK.week({
  n: 7,
  name: "STELLAR CARTOGRAPHY",
  brief: "Stardate 79534.0. Navigation requires numbers: coordinates, prices, times, dates — and Japanese counts nothing without a counter word. This week you chart the numeric sector: big numbers, the counter system (dragons included), the clock, and the calendar.",
  lessons: [
    {
      id: "7.1",
      title: "Big Numbers and Money",
      sub: "百・千・万 — and why 10,000 is the number Japanese actually thinks in",
      briefing: [
        ["h", "Assembling any number"],
        ["p", "Japanese numbers stack like Lego: {{さん}}(3) + {{びゃく}}(100) + {{ろくじゅう}}(60) + {{はち}}(8) = 368. Learn the tiers and the sound-changes at the joints, and every number to 99,999,999 is yours:"],
        ["table", ["Tier", "Reading", "Sound-change trio"], [
          ["十 10", "じゅう", "—"],
          ["百 100", "ひゃく", "300 さん**びゃく**・600 ろっ**ぴゃく**・800 はっ**ぴゃく**"],
          ["千 1,000", "せん", "3,000 さん**ぜん**・8,000 は**っせん**"],
          ["万 10,000", "まん", "always いち**まん** for plain 10,000"],
        ]],
        ["h", "The 万 mindset"],
        ["p", "English groups by thousands (10,000 = “ten thousand”); Japanese groups by **万** (10,000 = one 万). So 100,000 is {{十万}} (ten 万), a million is {{百万}} (a hundred 万). When a price tag says 25万円, read it as “25 ten-thousands” = ¥250,000. This flip is the single hardest habit in Japanese numbers — start practising it now and it becomes automatic."],
        ["h", "Shopping protocol"],
        ["ex", [
          ["すみません、これはいくらですか。", "すみませんこれはいくらですか", "Excuse me, how much is this?"],
          ["三千円[さんぜんえん]です。", "さんぜんえんです", "It's ¥3,000."],
          ["じゃあ、これをください。", "じゃあこれをください", "Then I'll take this one.", "を + ください = please give me"],
        ]],
        ["p", "{{ください}} straight after を = “please give me” — the noun version of the てください you already know. {{じゃあ}} (“well then…”) makes any decision sound considered."],
        ["note", "Prices in Japan are often quoted 税込 (tax in) or 税抜 (tax out). If the till asks for slightly more than the shelf said, the shelf was 税抜. Not a scam; a national pastime."],
      ],
      vocab: [
        ["百[ひゃく]", "ひゃく", "hyaku", "hundred", "number"],
        ["千[せん]", "せん", "sen", "thousand", "number"],
        ["万[まん]", "まん", "man", "ten thousand", "number"],
        ["円[えん]", "えん", "en", "yen", "counter"],
        ["いくら", "いくら", "ikura", "how much", "question"],
        ["お金[かね]", "おかね", "okane", "money", "noun"],
        ["財布[さいふ]", "さいふ", "saifu", "wallet", "noun"],
        ["切符[きっぷ]", "きっぷ", "kippu", "ticket", "noun"],
        ["お土産[みやげ]", "おみやげ", "omiyage", "souvenir", "noun"],
        ["カード", "かーど", "kaado", "(credit) card", "noun"],
        ["ください", "ください", "kudasai", "please (give me)", "expression"],
      ],
      exercises: [
        { t: "mc", q: "300 is read…", choices: ["さんびゃく", "さんひゃく", "さんぴゃく", "みひゃく"], a: 0,
          why: "The h hardens after ん: さんびゃく. Its siblings: 600 ろっぴゃく, 800 はっぴゃく. Everything else is plain ひゃく." },
        { t: "mc", q: "8,000 is read…", choices: ["はっせん", "はちせん", "はちぜん", "やせん"], a: 0,
          why: "はち + せん squeezes to はっせん. And 3,000 voices to さんぜん. The joints change; the Lego doesn't." },
        { t: "mc", q: "A price tag says {{10万円}}. That's…",
          choices: ["¥100,000", "¥10,000", "¥1,000,000", "¥10,000,000"], a: 0,
          why: "十万 = ten 万 = ten × 10,000 = 100,000. Thinking in 万 is the flip — you just did it." },
        { t: "type", q: "Say: “I'll take this one, please.” (pointing, decisively)",
          accept: ["これをください", "これください"],
          show: "これをください。",
          why: "これ + を + ください. The four syllables that convert money into souvenirs." },
        { t: "build", en: "Excuse me, how much is this?", tokens: ["すみません", "これ", "は", "いくら", "です", "か"], extra: ["を", "どこ"],
          why: "すみません opens every transaction; これはいくらですか does the rest." },
        { t: "mc", q: "{{カードでお願いします}} at the till means…",
          choices: ["By card, please", "Please give me a card", "Where is my card?", "The card is broken"], a: 0,
          why: "That's the means-で from week 3, riding again: pay BY card. お願いします = please (formal request — more soon)." },
        { t: "mc", q: "540円 is read…",
          choices: ["ごひゃくよんじゅうえん", "ごひゃくしじゅうえん", "ごびゃくよんじゅうえん", "ごせんよんじゅうえん"], a: 0,
          why: "500 ごひゃく (no sound change after ご) + 40 よんじゅう + 円. Prices prefer よん over し for 4 — し sounds like 死 (death), bad for business." },
      ],
    },
    {
      id: "7.2",
      title: "Counters — 一匹、二匹、三匹のドラゴン",
      sub: "why Japanese can't just say “three dragons”, and the counters that matter",
      briefing: [
        ["h", "Numbers never fly solo"],
        ["p", "Japanese can't count a noun directly — every count needs a **counter word** matched to the noun's shape or kind. English does this occasionally (“three *sheets* of paper”); Japanese does it for everything. The pattern: {{noun + を/が + number-counter + verb}}: 猫が二匹います, りんごを三つください."],
        ["table", ["Counter", "Counts", "The irregulars to know"], [
          ["〜つ", "anything (1–10 only)", "ひとつ・ふたつ・みっつ・よっつ・いつつ・むっつ・ななつ・やっつ・ここのつ・とお"],
          ["〜人 にん", "people", "ひとり(1)・ふたり(2)・さんにん(3)…"],
          ["〜匹 ひき", "small animals & dragons", "いっぴき・にひき・さんびき・ろっぴき・はっぴき"],
          ["〜本 ほん", "long thin things", "いっぽん・さんぼん・ろっぽん"],
          ["〜枚 まい", "flat things", "regular! いちまい・にまい…"],
          ["〜台 だい", "machines, vehicles", "regular"],
          ["〜冊 さつ", "books", "いっさつ・はっさつ"],
        ]],
        ["h", "The universal fallback"],
        ["p", "Can't remember the right counter? {{〜つ}} counts almost any *thing* up to ten, and shopkeepers will forgive everything. りんごをみっつください works; so does ひとつ、これをください. Use the fallback proudly while the real counters bed in."],
        ["ex", [
          ["ドラゴンが三匹[さんびき]います！", "どらごんがさんびきいます", "There are three dragons!", "小さい dragons, presumably — big ones get 頭"],
          ["ビールを二本[にほん]ください。", "びーるをにほんください", "Two (bottles of) beer, please."],
          ["切符[きっぷ]を二枚[にまい]ください。", "きっぷをにまいください", "Two tickets, please.", "flat things → 枚"],
        ]],
        ["h", "Word order: the count floats"],
        ["p", "The number-counter drops in **after the particle, before the verb** — it floats free of the noun: 猫**が**二匹います, ビール**を**三本買いました. No の needed. (三匹の猫 also exists, fronting the count like an adjective — both are correct; the floating version is more natural in speech.)"],
        ["note", "匹 covers cats, dogs, fish, insects and — canonically — small dragons. Large animals get 頭 (とう): 象が一頭. A Spyro-sized dragon is a judgement call. Choose 匹 and the dragon will not correct you. Probably."],
      ],
      vocab: [
        ["一[ひと]つ", "ひとつ", "hitotsu", "one (thing)", "counter"],
        ["二[ふた]つ", "ふたつ", "futatsu", "two (things)", "counter"],
        ["三[みっ]つ", "みっつ", "mittsu", "three (things)", "counter"],
        ["一人[ひとり]", "ひとり", "hitori", "one person; alone", "counter"],
        ["二人[ふたり]", "ふたり", "futari", "two people", "counter"],
        ["何人[なんにん]", "なんにん", "nannin", "how many people", "question"],
        ["家族[かぞく]", "かぞく", "kazoku", "family", "noun"],
        ["兄弟[きょうだい]", "きょうだい", "kyoudai", "siblings", "noun"],
        ["鳥[とり]", "とり", "tori", "bird", "noun"],
        ["馬[うま]", "うま", "uma", "horse", "noun"],
        ["ビール", "びーる", "biiru", "beer", "noun"],
        ["紙[かみ]", "かみ", "kami", "paper", "noun"],
      ],
      exercises: [
        { t: "mc", q: "Count the dragons: ドラゴンが＿＿います。(there are THREE)",
          choices: ["三匹（さんびき）", "三匹（さんひき）", "三人（さんにん）", "三枚（さんまい）"], a: 0,
          why: "Small animals (and dragons) → 匹, and after さん the h voices: さん**び**き. 三人 would make them people; 三枚 would make them flat. 🐉" },
        { t: "mc", q: "“One person” is…", choices: ["ひとり", "いちにん", "ひとつ", "いちひと"], a: 0,
          why: "The two irregulars of 人-counting: ひとり(1), ふたり(2). From three it's regular: さんにん, よにん…" },
        { t: "build", en: "Three apples, please.", tokens: ["りんご", "を", "三つ", "ください"], extra: ["三匹", "が"],
          why: "The count floats after the particle: りんごを + 三つ + ください. No の, no fuss." },
        { t: "mc", q: "Two beers (bottles). Pick the counter.",
          choices: ["ビールを二本ください", "ビールを二枚ください", "ビールを二人ください", "ビールを二冊ください"], a: 0,
          why: "Bottles are long and thin → 本. 二枚 would order two beer-sheets; 二人 two beer-people. Counters paint pictures — make them the right pictures." },
        { t: "type", q: "Ask: “How many people (in your) family?”",
          accept: ["家族は何人ですか", "かぞくはなんにんですか"],
          show: "家族[かぞく]は何人[なんにん]ですか。",
          why: "何 + counter asks “how many of that kind”: 何人、何匹、何枚… The reply might be 四人です — or ひとりと猫二匹." },
        { t: "match", q: "Match each thing to its natural counter.", pairs: [
          ["猫", "匹"],
          ["切符", "枚"],
          ["傘 (umbrella)", "本"],
          ["車", "台"],
        ]},
        { t: "mc", q: "{{馬が一頭、鳥が二羽います}} — the notable thing about 鳥 (birds)?",
          choices: ["Birds get their own counter, 羽 (わ)", "Birds are counted as fish", "Birds can't be counted", "It's a typo for 匹"], a: 0,
          why: "羽 (“feather/wing”) counts birds — and, by ancient monastic loophole, rabbits. (Monks weren't allowed meat but were allowed birds… so rabbits “became” birds. Real story. Japanese counters contain history.)" },
      ],
    },
    {
      id: "7.3",
      title: "The Clock — 時・分・半",
      sub: "telling time, from よじ to the から〜まで span",
      briefing: [
        ["h", "Hours: 〜時"],
        ["p", "Number + {{時}} (じ) = o'clock. Three hours misbehave: **4時 = よじ** (never よんじ), **7時 = しちじ**, **9時 = くじ** (never きゅうじ). Everything else is regular. Morning/afternoon: {{午前}}9時 = 9 a.m., {{午後}}3時 = 3 p.m."],
        ["h", "Minutes: 〜分"],
        ["p", "{{分}} reads ふん or ぷん depending on what it follows: いっ**ぷん**(1)、に**ふん**(2)、さん**ぷん**(3)、よん**ぷん**(4)、ご**ふん**(5)、ろっ**ぷん**(6)、なな**ふん**(7)、はっ**ぷん**(8)、きゅう**ふん**(9)、じゅっ**ぷん**(10). Half past = {{半}}: 六時半 6:30. “About” = {{ごろ}}: 三時ごろ, around three."],
        ["ex", [
          ["今[いま]、何時[なんじ]ですか。", "いまなんじですか", "What time is it now?"],
          ["九時半[くじはん]です。", "くじはんです", "It's 9:30."],
          ["会議[かいぎ]は午後[ごご]二時[にじ]に始[はじ]まります。", "かいぎはごごにじにはじまります", "The meeting starts at 2 p.m."],
        ]],
        ["h", "Spans: から〜まで"],
        ["p", "{{から}} = from, {{まで}} = until — they clip onto times, places, anything: {{九時から五時まで働きます}} “I work 9 to 5”, {{京都から東京まで}} “from Kyoto to Tokyo”. They also work alone: 何時からですか — “from what time?”"],
        ["note", "始まります (begins) and 終わります (ends) are the *thing's own* actions: 映画が始まります — the film starts (itself). Japanese is strict about who does what; a whole family of these self/other verb pairs arrives in your future. For now: events 始まる, and you 始めます them. (Preview — week 8 vocab.)"],
      ],
      vocab: [
        ["〜時[じ]", "じ", "-ji", "o'clock", "counter"],
        ["〜分[ふん]", "ふん", "-fun", "minute (-fun reading)", "counter"],
        ["〜分[ぷん]", "ぷん", "-pun", "minute (-pun reading)", "counter"],
        ["半[はん]", "はん", "han", "half (past)", "noun"],
        ["午前[ごぜん]", "ごぜん", "gozen", "a.m.", "noun"],
        ["午後[ごご]", "ごご", "gogo", "p.m.", "noun"],
        ["何時[なんじ]", "なんじ", "nanji", "what time", "question"],
        ["から", "から", "kara", "from", "particle"],
        ["まで", "まで", "made", "until, to", "particle"],
        ["会議[かいぎ]", "かいぎ", "kaigi", "meeting", "noun"],
        ["始[はじ]まります", "はじまります", "hajimarimasu", "to begin (itself)", "verb・godan"],
        ["終[お]わります", "おわります", "owarimasu", "to end (itself)", "verb・godan"],
        ["ごろ", "ごろ", "goro", "around (a time)", "suffix"],
      ],
      exercises: [
        { t: "mc", q: "4 o'clock is read…", choices: ["よじ", "よんじ", "しじ", "よっつじ"], a: 0,
          why: "The big three irregular hours: 4時 よじ, 7時 しちじ, 9時 くじ. Everything else behaves." },
        { t: "mc", q: "9 o'clock is read…", choices: ["くじ", "きゅうじ", "ここのじ", "くにじ"], a: 0,
          why: "くじ. きゅうじ will be understood and gently never repeated back to you." },
        { t: "type", q: "Ask: “What time is it now?”",
          accept: ["今何時ですか", "いまなんじですか"],
          show: "今[いま]、何時[なんじ]ですか。",
          why: "今 + 何時ですか. The watch-free traveller's essential." },
        { t: "build", en: "The meeting is from 9 until 5.", tokens: ["会議", "は", "九時", "から", "五時", "まで", "です"], extra: ["に", "ごろ"],
          why: "から〜まで clips onto the times; です seals it. The full 9-to-5, in five particles' worth of work." },
        { t: "mc", q: "{{映画は七時ごろ始まります}} — the film starts…",
          choices: ["around 7", "exactly at 7", "before 7 sharp", "at 7 minutes past"], a: 0,
          why: "ごろ softens a clock time to “around”. しちじ, of course — one of the three rebel hours." },
        { t: "mc", q: "6:30 p.m., fully specified:",
          choices: ["午後六時半", "午前六時半", "六時三十半", "半六時午後"], a: 0,
          why: "午後 (p.m.) + hour + 半. Order is big-to-small, always — the same principle that runs dates, addresses, and names in Japanese." },
      ],
    },
    {
      id: "7.4",
      title: "The Calendar — Days, Months, Birthdays",
      sub: "月曜日 to 日曜日, the treacherous first ten days, and duration",
      briefing: [
        ["h", "The week: seven celestial bodies"],
        ["p", "Japanese weekdays are named for the classical elements-slash-planets — the same system as Latin! {{月曜日}} Moon-day (Monday!), {{火曜日}} fire/Mars (Tuesday), {{水曜日}} water/Mercury, {{木曜日}} wood/Jupiter, {{金曜日}} metal/Venus (gold-day = payday, easy to remember), {{土曜日}} earth/Saturn (Saturday!), {{日曜日}} Sun-day. Monday, moon-day; Sunday, sun-day — English and Japanese agree at both ends of the week."],
        ["h", "Months: gloriously simple"],
        ["p", "Number + {{月}} (がつ): 一月 January … 十二月 December. Watch three: **4月 しがつ**, **7月 しちがつ**, **9月 くがつ** — the same rebels as the clock, in mirror image (the clock wanted よじ; the calendar wants しがつ)."],
        ["h", "Days of the month: the treacherous ten"],
        ["p", "Days 1–10 use the old Japanese counting and must simply be learned: {{ついたち}}(1st)・ふつか(2)・みっか(3)・よっか(4)・いつか(5)・むいか(6)・なのか(7)・ようか(8)・ここのか(9)・とおか(10). Then regularity, except 14th じゅうよっか, 20th はつか, 24th にじゅうよっか. Yes, 8th ようか vs 4th よっか is cruel. Everyone confuses them once per lifetime; get yours done early."],
        ["ex", [
          ["誕生日[たんじょうび]はいつですか。", "たんじょうびはいつですか", "When's your birthday?"],
          ["十月[じゅうがつ]二十日[はつか]です。", "じゅうがつはつかです", "October 20th."],
        ]],
        ["h", "Duration vs points"],
        ["p", "A point in time takes に; a **duration** takes nothing but often ぐらい (about): {{三時間勉強しました}} “I studied for three hours”, {{一週間}} a week, {{二年間}} two years. {{ぐらい}} = about (amounts), {{ごろ}} = about (clock points). 三時ごろ (around 3:00) vs 三時間ぐらい (about 3 hours) — tiny words, entirely different claims."],
      ],
      vocab: [
        ["月曜日[げつようび]", "げつようび", "getsuyoubi", "Monday", "time"],
        ["火曜日[かようび]", "かようび", "kayoubi", "Tuesday", "time"],
        ["水曜日[すいようび]", "すいようび", "suiyoubi", "Wednesday", "time"],
        ["木曜日[もくようび]", "もくようび", "mokuyoubi", "Thursday", "time"],
        ["金曜日[きんようび]", "きんようび", "kin'youbi", "Friday", "time"],
        ["土曜日[どようび]", "どようび", "doyoubi", "Saturday", "time"],
        ["日曜日[にちようび]", "にちようび", "nichiyoubi", "Sunday", "time"],
        ["誕生日[たんじょうび]", "たんじょうび", "tanjoubi", "birthday", "noun"],
        ["〜月[がつ]", "がつ", "-gatsu", "month (of year)", "counter"],
        ["〜日[にち]", "にち", "-nichi", "day (of month)", "counter"],
        ["ぐらい", "ぐらい", "gurai", "about (amount)", "suffix"],
      ],
      exercises: [
        { t: "mc", q: "April is read…", choices: ["しがつ", "よんがつ", "よがつ", "しちがつ"], a: 0,
          why: "The calendar's rebels: 4月 しがつ, 7月 しちがつ, 9月 くがつ. (Mirror-world of the clock, which insisted on よじ.)" },
        { t: "mc", q: "The 1st of the month is…", choices: ["ついたち", "いちにち", "ひとか", "いちか"], a: 0,
          why: "ついたち — from 月立ち, “the moon rising”. The first ten days keep old Japanese alive; this one is pure poetry." },
        { t: "mc", q: "The 8th is ようか. The 4th is…", choices: ["よっか", "ようか", "よんか", "はちか"], a: 0,
          why: "4th よっか (small っ), 8th ようか (long お). The cruellest pair in the calendar — your once-per-lifetime confusion is hereby spent." },
        { t: "match", q: "Match the day to its celestial body.", pairs: [
          ["月曜日", "Moon — Monday"],
          ["金曜日", "gold/Venus — Friday"],
          ["土曜日", "earth/Saturn — Saturday"],
          ["日曜日", "Sun — Sunday"],
        ]},
        { t: "type", q: "Ask: “When is your birthday?”",
          accept: ["誕生日はいつですか", "たんじょうびはいつですか", "お誕生日はいつですか", "おたんじょうびはいつですか"],
          show: "誕生日[たんじょうび]はいつですか。",
          why: "いつ from week 1, now with a purpose. Follow-up gift logistics are your own responsibility." },
        { t: "mc", q: "{{三時間ぐらい日本語を勉強しました}} — the claim is…",
          choices: ["studied about 3 hours", "studied at about 3 o'clock", "will study at 3", "studied 3 times"], a: 0,
          why: "時間 = duration (hours of), ぐらい = about (amount). 三時ごろ would be the clock-point. Tiny suffix, different fact." },
        { t: "mc", q: "“I'll go to Japan on Friday” — pick the right particle use:",
          choices: ["金曜日に日本に行きます", "金曜日で日本に行きます", "金曜日を日本に行きます", "金曜日日本行きます"], a: 0,
          why: "Named days take に (English needs “on”, so Japanese needs に — the secret agreement from week 3 still holds)." },
      ],
    },
    {
      id: "7.5",
      review: true,
      title: "Mission Review 07",
      sub: "numbers, counters, clock, calendar — cartography complete",
      briefing: [
        ["h", "Debrief: the numeric sector is charted"],
        ["ul", [
          "**Numbers** stack big-to-small; think in 万; watch the joints (さんびゃく・はっせん).",
          "**Counters** always: つ (universal), 人 (ひとり・ふたり), 匹・本・枚・台・冊 — the count floats after the particle.",
          "**Clock**: よじ・しちじ・くじ; ふん/ぷん; から〜まで spans.",
          "**Calendar**: planet-days; しがつ・しちがつ・くがつ; the treacherous first ten (ついたち…とおか).",
          "**ごろ** ≈ clock point; **ぐらい** ≈ amount.",
        ]],
        ["p", "The computer notes with satisfaction that you can now buy two beers, three apples and a train ticket, and still make the 9:30 meeting. Simulation begins."],
      ],
      vocab: [],
      exercises: [
        { t: "mc", q: "¥3,600 is read…",
          choices: ["さんぜんろっぴゃくえん", "さんせんろくひゃくえん", "さんぜんろくびゃくえん", "みせんむひゃくえん"], a: 0,
          why: "3,000 さんぜん (voiced joint) + 600 ろっぴゃく (hardened joint) + 円. Both sound-changes in one price — the till approves." },
        { t: "build", en: "Two cats and one dog. (report the census)", tokens: ["猫", "が", "二匹", "と", "犬", "が", "一匹", "います"], extra: ["二人", "二枚"],
          why: "Animals → 匹: にひき, いっぴき. The counters float after their particles; と joins the two complete facts." },
        { t: "mc", q: "The train leaves at 7:30 p.m. That's…",
          choices: ["午後七時半", "午前七時半", "七時半分", "午後半七時"], a: 0,
          why: "午後 + しちじ (rebel hour) + 半. Big-to-small, as always." },
        { t: "type", q: "Say: “From Monday until Friday.” (the eternal span)",
          accept: ["月曜日から金曜日まで", "げつようびからきんようびまで"],
          show: "月曜日[げつようび]から金曜日[きんようび]まで。",
          why: "から〜まで — moon-day to gold-day. Some truths are interstellar." },
        { t: "mc", q: "Which is “around 4 o'clock” (not “about 4 hours”)?",
          choices: ["四時ごろ", "四時間ぐらい", "四時から", "四日ごろ"], a: 0,
          why: "よじ + ごろ = around 4:00. 四時間ぐらい measures duration; 四日 is the 4th (よっか — treachery survived)." },
      ],
    },
  ],
});

/* ================= WEEK 8 — SHORE LEAVE ================= */
DK.week({
  n: 8,
  name: "SHORE LEAVE",
  brief: "Stardate 79536.6. All work and no play violates Starfleet medical directives. This week: wanting things, inviting people, making plans, and going places just to do things there. Grammar for holidays — learned, appropriately, as one long imaginary trip to Japan.",
  lessons: [
    {
      id: "8.1",
      title: "〜たいです — Wanting",
      sub: "I want to soak in a hot spring — the grammar of desire",
      briefing: [
        ["h", "Verb stem + たい"],
        ["p", "Take the ます-form, drop ます, add {{たい}}: 行きます → {{行きたい}} “want to go”. The result behaves as an **い-adjective** — week 4's machinery bolts straight on: 行きたくない (don't want to), 行きたかった (wanted to), 行きたくなかった (didn't want to)."],
        ["ex", [
          ["温泉[おんせん]に入[はい]りたいです。", "おんせんにはいりたいです", "I want to get in a hot spring."],
          ["新幹線[しんかんせん]に乗[の]りたいです。", "しんかんせんにのりたいです", "I want to ride the bullet train.", "乗る takes に — you board ONTO it"],
          ["何[なに]も食[た]べたくないです。", "なにもたべたくないです", "I don't want to eat anything."],
        ]],
        ["p", "With たい, the object can take が or を — {{お茶が飲みたい}} and {{お茶を飲みたい}} are both fine. (The desire is adjective-like, so が sneaks in; both are heard daily.)"],
        ["h", "ほしい — wanting THINGS"],
        ["p", "For nouns, use {{ほしい}} (also an い-adjective): {{新しい財布がほしいです}} “I want a new wallet.” Verb-wants take たい, thing-wants take ほしい."],
        ["h", "The politeness asterisk"],
        ["p", "たい/ほしい state **your own** wants — natural among friends, a bit bare toward superiors (you don't tell the admiral 休みたいです; you hint). And for *third parties* Japanese uses 〜たがっている (“shows signs of wanting”) — you can't read minds, only behaviour. Japanese grammar is epistemically honest: you know your wants, you infer everyone else's."],
        ["note", "Asking 何が食べたいですか (what do you want to eat) among friends is fine and useful. The universal safe answer: 何でもいいです — “anything's fine” — which, as in English, means nothing of the sort."],
      ],
      vocab: [
        ["旅行[りょこう]", "りょこう", "ryokou", "trip, travel", "noun"],
        ["温泉[おんせん]", "おんせん", "onsen", "hot spring", "noun"],
        ["海[うみ]", "うみ", "umi", "sea", "noun"],
        ["泊[と]まります", "とまります", "tomarimasu", "to stay overnight", "verb・godan"],
        ["乗[の]ります", "のります", "norimasu", "to ride, board (に)", "verb・godan"],
        ["新幹線[しんかんせん]", "しんかんせん", "shinkansen", "bullet train", "noun"],
        ["富士山[ふじさん]", "ふじさん", "fujisan", "Mt Fuji", "noun"],
        ["城[しろ]", "しろ", "shiro", "castle", "noun"],
        ["桜[さくら]", "さくら", "sakura", "cherry blossom", "noun"],
        ["ほしい", "ほしい", "hoshii", "wanted (things)", "い-adj"],
        ["休[やす]みます", "やすみます", "yasumimasu", "to rest, take time off", "verb・godan"],
      ],
      exercises: [
        { t: "build", en: "I want to go to Japan.", tokens: ["日本", "に", "行き", "たい", "です"], extra: ["行く", "ほしい"],
          why: "ます-stem 行き + たい. The stem, not the dictionary form — 行くたい doesn't exist." },
        { t: "mc", q: "“I DON'T want to eat” is…",
          choices: ["食べたくないです", "食べたいないです", "食べないたいです", "食べたくありませんでした"], a: 0,
          why: "たい is an い-adjective, so week 4 applies: たい→たくない. (The last option is fine grammar but past tense — “didn't want to”.)" },
        { t: "mc", q: "You want a new wallet (a thing). Which pattern?",
          choices: ["新しい財布がほしいです", "新しい財布を買いたいほしいです", "新しい財布がたいです", "財布は新しかったです"], a: 0,
          why: "Nouns take ほしい; verbs take たい. (Wanting to BUY it would be 買いたい — the verb-want.)" },
        { t: "type", q: "Say: “I want to see the cherry blossoms.”",
          accept: ["桜が見たいです", "さくらがみたいです", "桜を見たいです", "さくらをみたいです"],
          show: "桜[さくら]が見[み]たいです。",
          why: "見ます → 見たい; が or を both welcome. Book late March–early April; the blossoms keep their own stardates." },
        { t: "mc", q: "Pick the particle: 新幹線＿乗りたいです。",
          choices: ["に", "を", "で", "が"], a: 0,
          why: "乗る boards ONTO its vehicle → に. (で would be riding it as mere transport to somewhere else — here the shinkansen IS the destination.)" },
        { t: "mc", q: "{{疲れたから、今日は何もしたくない}} means…",
          choices: ["I'm tired, so today I don't want to do anything", "I'm tired of doing everything today", "Today made me tired", "I can't do anything today"], a: 0,
          why: "何も + negative (week 3's polarity pact) meets したくない (する→し+たくない). A sentence for Sunday afternoons everywhere." },
      ],
    },
    {
      id: "8.2",
      title: "Invitations — ませんか・ましょう・ましょうか",
      sub: "the negative question that means yes — asking people out, Japanese style",
      briefing: [
        ["h", "ませんか — inviting with a negative"],
        ["p", "Japanese invites with a **negative question**: {{一緒に映画を見ませんか}} — literally “won't you watch a film together?” — exactly like English “won't you join us?”. The negative leaves graceful room to decline. Inviting with the bare affirmative (見ますか?) just asks whether they're going to; ませんか asks them to."],
        ["h", "ましょう — let's"],
        ["p", "{{ましょう}} = “let's”: 行きましょう, 食べましょう, 始めましょう. As a question, {{ましょうか}} offers: 手伝いましょうか “shall I help?”, 窓を開けましょうか “shall I open the window?”"],
        ["ex", [
          ["週末[しゅうまつ]、一緒[いっしょ]にお祭[まつ]りに行[い]きませんか。", "しゅうまつ、いっしょにおまつりにいきませんか", "Won't you come to the festival with me this weekend?"],
          ["いいですね。行[い]きましょう！", "いいですね。いきましょう", "Sounds great — let's go!"],
          ["荷物[にもつ]、持[も]ちましょうか。", "にもつ、もちましょうか", "Shall I carry your bag?"],
        ]],
        ["h", "Declining without saying no"],
        ["p", "Japan rarely says no outright. The standard soft decline: {{すみません、ちょっと都合が悪いです}} (“sorry, the timing's a bit…”), or simply {{ちょっと…}} with an apologetic tilt. Then soften the future: {{また今度}} “next time, maybe”. Everyone understands; nobody loses face. If someone answers your invitation with ちょっと…, do not ask what's wrong with the day. The ちょっと IS the answer."],
        ["note", "いいですね (falling, warm) = “sounds nice!” — acceptance. いいです (flat, clipped) can mean “no thanks”! Tone and ね carry the difference. When declining a shop's offer: 大丈夫です — “I'm fine (without)”. Yes, “it's good” means no. The translator would never have coped anyway."],
      ],
      vocab: [
        ["誘[さそ]います", "さそいます", "sasoimasu", "to invite", "verb・godan"],
        ["映画館[えいがかん]", "えいがかん", "eigakan", "cinema", "noun"],
        ["お祭[まつ]り", "おまつり", "omatsuri", "festival", "noun"],
        ["花火[はなび]", "はなび", "hanabi", "fireworks", "noun"],
        ["飲[の]み物[もの]", "のみもの", "nomimono", "a drink", "noun"],
        ["食[た]べ物[もの]", "たべもの", "tabemono", "food", "noun"],
        ["都合[つごう]", "つごう", "tsugou", "convenience, timing", "noun"],
        ["残念[ざんねん]", "ざんねん", "zannen", "a shame, unfortunate", "な-adj"],
        ["また今度[こんど]", "またこんど", "mata kondo", "next time (maybe)", "expression"],
        ["ぜひ", "ぜひ", "zehi", "by all means, definitely", "adverb"],
        ["荷物[にもつ]", "にもつ", "nimotsu", "luggage, bag", "noun"],
      ],
      exercises: [
        { t: "build", en: "Won't you watch a film together (with me)?", tokens: ["一緒に", "映画", "を", "見ませんか"], extra: ["見ますか", "が"],
          why: "The inviting negative: 見ませんか. 見ますか would be mere data collection about their plans." },
        { t: "mc", q: "Your friend says {{行きましょう！}}. They mean…",
          choices: ["Let's go!", "Please go away", "Shall I go alone?", "They went already"], a: 0,
          why: "ましょう = let's. Enthusiasm included at no extra charge." },
        { t: "mc", q: "{{手伝いましょうか}} means…",
          choices: ["Shall I help you?", "Help me!", "Did you help?", "We won't help"], a: 0,
          why: "ましょうか turns “let's” into an offer: shall I…? Say it to anyone wrestling a suitcase up station stairs; instant diplomacy." },
        { t: "mc", q: "You're invited but can't make it. The gracious decline:",
          choices: ["すみません、ちょっと都合が悪いです。また今度！", "いいえ、行きません。", "だめです。", "何も言わない"], a: 0,
          why: "Soft apology + vague reason + また今度. Direct refusals (行きません) land like photon torpedoes; save them for actual emergencies." },
        { t: "type", q: "Say: “Let's go!” (accept an invitation with gusto)",
          accept: ["行きましょう", "いきましょう"],
          show: "行[い]きましょう！",
          why: "ます-stem + ましょう. Optionally preceded by いいですね for full warmth: いいですね、行きましょう！" },
        { t: "mc", q: "A shop assistant offers a bag. {{大丈夫です}} from you means…",
          choices: ["No thanks, I'm fine", "Yes please", "The bag is excellent", "Is the bag OK?"], a: 0,
          why: "The famous polite-refusal 大丈夫です — “I'm fine (without)”. Context and a small wave of the hand complete the meaning. The UT would have shipped you a bag." },
        { t: "mc", q: "Which invitation is for FIREWORKS?",
          choices: ["花火を見に行きませんか", "花見に行きましたか", "火花を食べませんか", "花を買いましょうか"], a: 0,
          why: "花火 (flower-fire) = fireworks. 花見 is blossom-viewing, 火花 is “sparks”, and eating any of them is inadvisable. (見に行く — “go to see” — is tomorrow's grammar, arriving early.)" },
      ],
    },
    {
      id: "8.3",
      title: "Make It So — the Volitional and つもり",
      sub: "そうしよう — the captain's form: let's-do-it, and stating intentions",
      briefing: [
        ["h", "The volitional: ましょう out of uniform"],
        ["p", "The plain counterpart of ましょう — “let's / I shall” among friends or inside your own head:"],
        ["table", ["Class", "Rule", "Example"], [
          ["godan", "final -u → -ou", "行く→行こう、飲む→飲もう、頑張る→頑張ろう"],
          ["ichidan", "る → よう", "食べる→食べよう、見る→見よう"],
          ["irregular", "the usual two", "する→しよう、来る→来[こ]よう"],
        ]],
        ["ex", [
          ["そうしよう。", "そうしよう", "Let's do that. — or, on a starship: Make it so.", "そう (that way) + しよう (volitional of する)"],
          ["よし、行[い]こう！", "よし、いこう", "Right — let's go! (Engage!)"],
          ["今年[ことし]は日本語[にほんご]を頑張[がんば]ろう。", "ことしはにほんごをがんばろう", "This year I'll give Japanese my all.", "a resolution, spoken to oneself"],
        ]],
        ["p", "Yes: **{{そうしよう}} is literally “make it so”**. Jean-Luc Picard has been speaking textbook volitional Japanese all along. When the away team proposes a plan and you agree: そうしよう。 When the helm is ready: 行こう。 The bridge is yours."],
        ["h", "つもり — stated intention"],
        ["p", "Plain form + {{つもりです}} = “I intend to”: {{来年日本に行くつもりです}} “I plan to go to Japan next year.” Negative intentions negate the inner verb: {{買わないつもりです}} “I intend not to buy it.” Alongside: {{予定}} for scheduled plans — 出発の予定 (scheduled departure) is firmer than つもり (personal intention)."],
        ["note", "The volitional + と思っています (“I'm thinking I'll…”) softens an intention politely: 日本に行こうと思っています. That と思う machinery is next week's flagship — consider this a sensor echo of what's coming."],
      ],
      vocab: [
        ["予定[よてい]", "よてい", "yotei", "plan, schedule", "noun"],
        ["来週[らいしゅう]", "らいしゅう", "raishuu", "next week", "time"],
        ["来月[らいげつ]", "らいげつ", "raigetsu", "next month", "time"],
        ["来年[らいねん]", "らいねん", "rainen", "next year", "time"],
        ["今年[ことし]", "ことし", "kotoshi", "this year", "time"],
        ["始[はじ]めます", "はじめます", "hajimemasu", "to start (something)", "verb・ichidan"],
        ["続[つづ]けます", "つづけます", "tsuzukemasu", "to continue (something)", "verb・ichidan"],
        ["頑張[がんば]ります", "がんばります", "ganbarimasu", "to do one's best", "verb・godan"],
        ["決[き]めます", "きめます", "kimemasu", "to decide", "verb・ichidan"],
        ["夢[ゆめ]", "ゆめ", "yume", "dream", "noun"],
        ["よし", "よし", "yoshi", "right!, OK then!", "expression"],
      ],
      exercises: [
        { t: "mc", q: "Volitional of {{する}}:", choices: ["しよう", "すろう", "しましょう", "そう"], a: 0,
          why: "する→しよう. Combine with そう (that way) and you have the captain's sign-off: そうしよう — make it so." },
        { t: "mc", q: "Volitional of {{行く}}:", choices: ["行こう", "行きょう", "行くよう", "行かおう"], a: 0,
          why: "Godan: -u → -ou. 行く→行こう. よし、行こう — engage." },
        { t: "mc", q: "The away team proposes a plan. As acting captain, you approve with…",
          choices: ["そうしよう。", "そうですか。", "そうじゃない。", "どうしよう。"], a: 0,
          why: "そうしよう — “let's do that / make it so.” (どうしよう is its anxious cousin: “what'll I DO?!” — never confuse them on the bridge.) ☕🖖" },
        { t: "build", en: "I intend to go to Japan next year.", tokens: ["来年", "日本", "に", "行く", "つもり", "です"], extra: ["行きます", "予定"],
          why: "つもり takes the PLAIN form: 行くつもりです. One politeness uniform per sentence, worn at the end." },
        { t: "type", q: "Say to yourself, with resolve: “I'll do my best!” (casual volitional)",
          accept: ["頑張ろう", "がんばろう"],
          show: "頑張[がんば]ろう！",
          why: "頑張る→頑張ろう. The word Japan runs on. Say it before every drill session; the computer will pretend not to hear." },
        { t: "mc", q: "{{お茶を飲もう}} is…",
          choices: ["Let's have tea (casual)", "Please drink tea (request)", "I drank tea (past)", "Tea, Earl Grey, hot (order)"], a: 0,
          why: "飲む→飲もう, the volitional. The captain's actual beverage protocol arrives in week 12 — patience, Number One." },
        { t: "mc", q: "Which states a personal INTENTION (not a fixed schedule)?",
          choices: ["日本語を続けるつもりです", "出発は九時の予定です", "日本語を続けています", "続けてください"], a: 0,
          why: "つもり = what I mean to do; 予定 = what the timetable says. (Continuing your Japanese: strongly endorsed by this computer.)" },
      ],
    },
    {
      id: "8.4",
      title: "Going TO DO — 〜に行きます",
      sub: "purpose of movement: I'm going to Kyoto to see the festival",
      briefing: [
        ["h", "Stem + に + motion verb"],
        ["p", "To say you go somewhere **in order to do something**, take the ます-stem and add {{に}} + a motion verb: {{見に行きます}} “go to see”, {{食べに行きます}} “go to eat”, {{遊びに来てください}} “come round (to hang out)!”"],
        ["ex", [
          ["お祭[まつ]りを見[み]に行[い]きます。", "おまつりをみにいきます", "I'm going to see the festival."],
          ["京都[きょうと]へ友達[ともだち]に会[あ]いに行[い]きました。", "きょうとへともだちにあいにいきました", "I went to Kyoto to meet a friend."],
          ["うちに遊[あそ]びに来[き]ませんか。", "うちにあそびにきませんか", "Won't you come round to ours?", "遊ぶ = hang out, not just child's play"],
        ]],
        ["p", "する-verbs shorten to the noun: {{買い物に行きます}} “go shopping”, {{旅行に行きます}} “go travelling”. The noun IS the stem."],
        ["h", "会う takes に"],
        ["p", "Surprise particle: {{会います}} (meet) marks the person with **に**, not を: {{友達に会います}}. You meet *toward* someone in Japanese. File alongside 乗ります (board に) — a small club of verbs whose targets take に."],
        ["h", "Sentence assembly, full stack"],
        ["p", "All the pieces now snap together: {{明日、友達と新宿へ映画を見に行きます}} — tomorrow / with a friend / to Shinjuku / to see a film / go. Five particles, five jobs, zero ambiguity. This is the sentence-machine you've been building for eight weeks."],
        ["note", "うち (home/our place) is softer than 家 (いえ, the house-as-building). 遊びに来て uses うち: it's the home-as-hearth you invite people to, not the architecture."],
      ],
      vocab: [
        ["会[あ]います", "あいます", "aimasu", "to meet (person に)", "verb・godan"],
        ["美術館[びじゅつかん]", "びじゅつかん", "bijutsukan", "art museum", "noun"],
        ["花見[はなみ]", "はなみ", "hanami", "blossom viewing", "noun"],
        ["プール", "ぷーる", "puuru", "swimming pool", "noun"],
        ["空港[くうこう]", "くうこう", "kuukou", "airport", "noun"],
        ["うち", "うち", "uchi", "home, our place", "noun"],
        ["東京[とうきょう]", "とうきょう", "toukyou", "Tokyo", "noun"],
        ["新宿[しんじゅく]", "しんじゅく", "shinjuku", "Shinjuku (Tokyo district)", "noun"],
        ["絵[え]", "え", "e", "picture, painting", "noun"],
        ["泳[およ]ぎ", "およぎ", "oyogi", "swimming", "noun"],
      ],
      exercises: [
        { t: "build", en: "I'm going to see the festival.", tokens: ["お祭り", "を", "見", "に", "行きます"], extra: ["見る", "で"],
          why: "ます-STEM + に: 見(ます) + に行きます. The dictionary form 見る can't ride this pattern." },
        { t: "mc", q: "Pick the particle: 友達＿会いに行きます。",
          choices: ["に", "を", "と", "が"], a: 0,
          why: "会う meets *toward* its person: 友達に会う. The small に-club: 会う、乗る. Memorise the members, spare yourself the red ink." },
        { t: "mc", q: "“I'm going (out) shopping” — most natural:",
          choices: ["買い物に行きます", "買い物をしに行くします", "買い物で行きます", "買い物が行きたい"], a: 0,
          why: "する-verbs drop straight to the noun: 買い物に行きます. Compact, idiomatic, heard a thousand times a day nationwide." },
        { t: "type", q: "Say: “I'm going to the pool to swim.” (use 泳ぎに)",
          accept: ["プールに泳ぎに行きます", "ぷーるにおよぎにいきます", "プールへ泳ぎに行きます"],
          show: "プールに泳[およ]ぎに行[い]きます。",
          why: "Two に's, two jobs: destination (プールに) and purpose (泳ぎに). Particles never clash — each knows its lane." },
        { t: "mc", q: "{{うちに遊びに来ませんか}} is best rendered…",
          choices: ["Won't you come round to ours?", "Don't play at my house", "Are you coming home?", "Let's go to the playground"], a: 0,
          why: "遊ぶ between adults = hang out. Combined with the inviting negative: the warmest sentence in this course. Accept with ぜひ！" },
        { t: "build", en: "I went to the airport to meet a friend.", tokens: ["空港", "へ", "友達", "に", "会い", "に", "行きました"], extra: ["会う", "を"],
          why: "Destination へ + person に (会う's rule) + purpose-stem 会いに + past motion. Full stack, flawlessly assembled." },
      ],
    },
    {
      id: "8.5",
      review: true,
      title: "Mission Review 08",
      sub: "wants, invitations, intentions, purposes — shore leave debriefing",
      briefing: [
        ["h", "Debrief: R&R complete"],
        ["ul", [
          "**〜たい** (verb-wants) conjugates like an い-adjective; **ほしい** for thing-wants; both are yours-only.",
          "**ませんか** invites; **ましょう** rallies; **ましょうか** offers.",
          "**Volitional**: -ou / よう / しよう・来よう — そうしよう, make it so. **つもり** + plain form states intent.",
          "**Stem + に行く** = go in order to; 会う and 乗る take に.",
          "Declining: ちょっと…、また今度。 Accepting: いいですね！ぜひ！",
        ]],
        ["p", "The captain reviews your leave request and stamps it そうしよう. Simulation begins."],
      ],
      vocab: [],
      exercises: [
        { t: "mc", q: "“I wanted to see the fireworks (but…)” is…",
          choices: ["花火が見たかったです", "花火を見たいでした", "花火が見ましたかった", "花火は見たくです"], a: 0,
          why: "たい is an い-adjective: past = たかった. 見たいでした is the 高いでした error wearing a new hat." },
        { t: "build", en: "Won't you go to the art museum together?", tokens: ["一緒に", "美術館", "に", "行きませんか"], extra: ["行きますか", "を"],
          why: "Inviting negative + destination に. Culture, offered gracefully." },
        { t: "mc", q: "Volitional of {{食べる}}:", choices: ["食べよう", "食べろう", "食べおう", "食べましょうう"], a: 0,
          why: "Ichidan: る→よう. 何か食べよう — let's eat something." },
        { t: "type", q: "The crew awaits your order. Say: “Let's do that.” (the captain's phrase)",
          accept: ["そうしよう", "そうしましょう"],
          show: "そうしよう。",
          why: "そう + しよう. Somewhere, a bald captain in a red uniform nods approvingly." },
        { t: "mc", q: "“I'm going to Tokyo to buy souvenirs” — pick the correct assembly:",
          choices: ["東京へお土産を買いに行きます", "東京でお土産を買うに行きます", "東京にお土産が買いましょう", "お土産は東京を買いたい"], a: 0,
          why: "Destination へ + object を + stem 買い + に行きます. The pattern takes the STEM (買い), never the dictionary form (買う)." },
      ],
    },
  ],
});

/* ================= WEEK 9 — DIPLOMATIC CORPS ================= */
DK.week({
  n: 9,
  name: "DIPLOMATIC CORPS",
  brief: "Stardate 79539.2. Darmok and Jalad at Tanagra. Diplomacy means reporting what others said, saying what you think, and describing things by their stories — a person who speaks in metaphor is only using relative clauses with style. This week: opinions, quotation, and clauses. Temba, his arms wide.",
  lessons: [
    {
      id: "9.1",
      title: "と思います — In My Opinion",
      sub: "thinking out loud, politely — plain form + と思う",
      briefing: [
        ["h", "The opinion machine"],
        ["p", "Plain form + {{と思います}} = “I think that…”. The と is a quotation particle — you're quoting your own mind. And because the quoted thought is *inside* the sentence, it stays in **plain form**; the politeness uniform goes on 思います at the end. One uniform per sentence — the rule you learned in week 6, now running at full power."],
        ["ex", [
          ["日本語[にほんご]は面白[おもしろ]いと思[おも]います。", "にほんごはおもしろいとおもいます", "I think Japanese is interesting."],
          ["明日[あした]、雨[あめ]が降[ふ]ると思[おも]います。", "あした、あめがふるとおもいます", "I think it'll rain tomorrow."],
          ["ピカード艦長[かんちょう]は一番[いちばん]いい艦長[かんちょう]だと思[おも]います。", "ぴかーどかんちょうはいちばんいいかんちょうだとおもいます", "I think Captain Picard is the best captain.", "correct opinion, correct grammar"],
        ]],
        ["p", "Note the third example: nouns and な-adjectives need {{だ}} before と — {{いい艦長だと思います}}. い-adjectives and verbs connect bare. (だ is the plain です from week 6, reporting for duty.)"],
        ["h", "Negating: move the negative inside"],
        ["p", "“I don't think X” is usually said as “I think NOT-X”: {{高くないと思います}} “I think it's not expensive.” Japanese prefers to keep 思います positive and put the doubt in the thought itself."],
        ["h", "Asking opinions"],
        ["p", "{{どう思いますか}} — “what do you think?” (Yes, どう = how, not 何 = what: Japanese asks HOW you think about it. 何と思いますか is a rarer, more literal “what words do you think”.) To agree: {{私もそう思います}} — “I think so too.” Diplomacy in five syllables."],
        ["note", "と思っています (with ている) reports a *sustained* thought — a held intention or long-term belief: 日本に行こうと思っています “I've been thinking I'll go to Japan.” Last week's sensor echo, confirmed."],
      ],
      vocab: [
        ["思[おも]います", "おもいます", "omoimasu", "to think", "verb・godan"],
        ["正[ただ]しい", "ただしい", "tadashii", "correct, right", "い-adj"],
        ["違[ちが]います", "ちがいます", "chigaimasu", "to differ; be wrong", "verb・godan"],
        ["問題[もんだい]", "もんだい", "mondai", "problem, question", "noun"],
        ["答[こた]え", "こたえ", "kotae", "answer", "noun"],
        ["意味[いみ]", "いみ", "imi", "meaning", "noun"],
        ["言葉[ことば]", "ことば", "kotoba", "word; language", "noun"],
        ["文化[ぶんか]", "ぶんか", "bunka", "culture", "noun"],
        ["歴史[れきし]", "れきし", "rekishi", "history", "noun"],
        ["大切[たいせつ]", "たいせつ", "taisetsu", "important, precious", "な-adj"],
      ],
      exercises: [
        { t: "build", en: "I think Japanese is interesting.", tokens: ["日本語", "は", "面白い", "と", "思います"], extra: ["です", "だ"],
          why: "い-adjective connects bare to と. No です inside the thought — one uniform per sentence, worn at the end." },
        { t: "mc", q: "“I think he's a student” — pick the right connection:",
          choices: ["学生だと思います", "学生と思います", "学生ですと思います", "学生のと思います"], a: 0,
          why: "Nouns need だ before と: 学生**だ**と思います. (ですと is the classic error — the uniform snuck inside.)" },
        { t: "mc", q: "The natural way to say “I don't think it's expensive”:",
          choices: ["高くないと思います", "高いと思いません", "高いと思わない思います", "高くなかったです"], a: 0,
          why: "Move the negative INSIDE the thought: “I think it's not-expensive”. Japanese keeps 思います standing and lets the thought carry the doubt." },
        { t: "type", q: "Agree diplomatically: “I think so too.”",
          accept: ["私もそう思います", "わたしもそうおもいます"],
          show: "私[わたし]もそう思[おも]います。",
          why: "も (week 2) + そう + 思います. The five-syllable handshake of every meeting in Japan." },
        { t: "mc", q: "{{歴史は大切だと思います}} — why the だ?",
          choices: ["大切 is a な-adjective — it needs だ before と", "だ is decorative", "It's past tense", "It marks a question"], a: 0,
          why: "な-adjectives quote like nouns: 大切**だ**と思います. い-adjectives (面白いと) and verbs (降ると) go bare. Tribes, remembered." },
        { t: "mc", q: "Ask a colleague's opinion of the plan:",
          choices: ["この予定について、どう思いますか", "この予定は何と思いますか", "この予定を思いますか", "予定はどうですかと思います"], a: 0,
          why: "どう思いますか — HOW do you think about it. (について = “regarding”, a diplomatic freebie worth pocketing.)" },
      ],
    },
    {
      id: "9.2",
      title: "「…」と言いました — Reporting Speech",
      sub: "quoting people, naming things with という — nothing is true, everything is permitted",
      briefing: [
        ["h", "Direct quotes"],
        ["p", "The same quotation particle と carries speech: {{「ありがとう」と言いました}} — “(they) said ‘thanks’.” The corner brackets 「」 are Japanese quotation marks. Direct quotes preserve the original words, register and all."],
        ["h", "Indirect quotes: plain form again"],
        ["p", "Reporting the *content* rather than the exact words: plain form + と言いました. {{田中さんは明日来ると言いました}} — “Tanaka said he'll come tomorrow.” Same machinery as と思います — think of 言う and 思う as the two mouths of the same particle: one speaks out, one speaks in."],
        ["ex", [
          ["先生[せんせい]は「明日[あした]テストがあります」と言[い]いました。", "せんせいは「あしたてすとがあります」といいました", "The teacher said, “There's a test tomorrow.”"],
          ["アサシンは「何[なに]も真実[しんじつ]ではなく、全[すべ]てが許[ゆる]されている」と言[い]いました。", "あさしんは「なにもしんじつではなく、すべてがゆるされている」といいました", "The Assassin said: “Nothing is true; everything is permitted.”", "the Creed, in the language of quotation"],
        ]],
        ["h", "という — “called” / “known as”"],
        ["p", "{{という}} names and defines: {{「ダーモック」という言葉}} “the word called ‘Darmok’”, {{アルタイルという暗殺者}} “an assassin called Altaïr”, {{京都という町}} “the town of Kyoto”. When you don't know a word: {{「eagle」は日本語で何と言いますか}} — “how do you say ‘eagle’ in Japanese?” (Answer: 鷲, わし.) This one pattern turns every conversation into a vocabulary lesson."],
        ["note", "Darmok's people spoke entirely in {{伝説}} (legends) — “Darmok and Jalad at Tanagra” meaning cooperation against a common foe. Picard cracked it by trading stories, no translator required. That's this whole course in one episode: メタファーは文化の記憶だと思います — metaphor is a culture's memory, I think."],
      ],
      vocab: [
        ["真実[しんじつ]", "しんじつ", "shinjitsu", "truth", "noun"],
        ["全[すべ]て", "すべて", "subete", "everything, all", "noun"],
        ["許[ゆる]します", "ゆるします", "yurushimasu", "to permit, forgive", "verb・godan"],
        ["暗殺者[あんさつしゃ]", "あんさつしゃ", "ansatsusha", "assassin", "noun"],
        ["鷲[わし]", "わし", "washi", "eagle", "noun"],
        ["隠[かく]れます", "かくれます", "kakuremasu", "to hide (oneself)", "verb・ichidan"],
        ["信条[しんじょう]", "しんじょう", "shinjou", "creed, credo", "noun"],
        ["物語[ものがたり]", "ものがたり", "monogatari", "tale, story", "noun"],
        ["伝説[でんせつ]", "でんせつ", "densetsu", "legend", "noun"],
        ["歌[うた]います", "うたいます", "utaimasu", "to sing", "verb・godan"],
      ],
      exercises: [
        { t: "mc", q: "The Assassin's creed — {{「何も真実ではなく、全てが許されている」}} — translates as…",
          choices: ["“Nothing is true; everything is permitted.”", "“Everything is true; nothing is permitted.”", "“The truth permits everything.”", "“Hide in plain sight.”"], a: 0,
          why: "何も + negative (nothing), 真実ではなく (is not truth — ではない's formal linking form), 全てが許されている (all is permitted). Now you can read the Creed in three languages. 🦅" },
        { t: "build", en: "The teacher said, “please read the book.”", tokens: ["先生", "は", "「", "本を読んでください", "」", "と", "言いました"], extra: ["思います", "が"],
          why: "「quote」 + と + 言いました. The quoted request keeps its own internal grammar untouched." },
        { t: "mc", q: "{{アルタイルという暗殺者}} means…",
          choices: ["an assassin called Altaïr", "Altaïr says “assassin”", "the assassin who spoke", "Altaïr's assassin"], a: 0,
          why: "AというB = “a B called A”. The naming pattern — works for people, towns, words, and legendary hooded ancestors." },
        { t: "type", q: "Ask: “How do you say ‘eagle’ in Japanese?” (use 「eagle」は…)",
          accept: ["eagleは日本語で何と言いますか", "「eagle」は日本語で何と言いますか", "eagleはにほんごでなんといいますか"],
          show: "「eagle」は日本語[にほんご]で何[なん]と言[い]いますか。",
          why: "The self-refuelling question — each answer is a new word. (It's 鷲, わし. Leap of faith not included.)" },
        { t: "mc", q: "Tanaka told you he's coming tomorrow. Report it:",
          choices: ["田中さんは明日来ると言いました", "田中さんは明日来ますと言いました", "田中さんは明日来たと言います", "田中さんという明日"], a: 0,
          why: "Indirect quotes take PLAIN form: 来る, not 来ます. (来た would report he already came — different fact entirely.)" },
        { t: "mc", q: "{{「ダーモックとジャラッドはタナグラで」という伝説}} — what grammar is doing the work?",
          choices: ["という naming a legend by its words", "と言いました reporting past speech", "と思います giving an opinion", "たい expressing desire"], a: 0,
          why: "という wraps the phrase into a name: “the legend called ‘Darmok and Jalad at Tanagra’”. Shaka, when the walls fell — is when you forget this pattern." },
      ],
    },
    {
      id: "9.3",
      title: "Relative Clauses — The Tea the Captain Drinks",
      sub: "whole sentences as adjectives: 昨日買った本、先祖の記憶を探す機械",
      briefing: [
        ["h", "No “who”, no “that”, no “which”"],
        ["p", "English bolts clauses on after the noun with relative pronouns: “the book **that I bought** yesterday”. Japanese simply parks the whole clause (in plain form) **in front of** the noun, like a big adjective: {{昨日買った本}} — “the yesterday-bought book”. No pronoun, no glue, no mercy for word-order habits."],
        ["ex", [
          ["昨日[きのう]買[か]った本[ほん]を読[よ]みました。", "きのうかったほんをよみました", "I read the book I bought yesterday."],
          ["これは艦長[かんちょう]が飲[の]むお茶[ちゃ]です。", "これはかんちょうがのむおちゃです", "This is the tea the captain drinks.", "Earl Grey, one assumes"],
          ["日本語[にほんご]を話[はな]す友達[ともだち]がいます。", "にほんごをはなすともだちがいます", "I have a friend who speaks Japanese."],
        ]],
        ["h", "The subject inside takes が (or の)"],
        ["p", "Inside a relative clause, the doer is marked with {{が}} — never は: {{艦長**が**飲むお茶}}. は belongs to main sentences; clauses are too small to have topics. (In writing you'll also meet の doing が's job inside clauses: 艦長の飲むお茶 — same meaning, bookish flavour.)"],
        ["h", "Stack and nest freely"],
        ["p", "Any plain-form tense works: 行く人 (people who go), 行った人 (who went), 行かない人 (who don't), 行っていた人 (who were going). And clauses nest: {{先祖[せんぞ]の記憶[きおく]を探[さが]す機械[きかい]}} — “a machine that searches ancestors' memories.” (An Animus, by any other name.) Build from the inside out; read from the outside in."],
        ["note", "This is THE structure that makes spoken Japanese hard to parse at first — the noun arrives *after* its whole description, so you must hold the clause in buffer. Training regime: when you hear a plain-form verb mid-sentence, expect a noun to land on it. Two weeks of drills and your buffer upgrades itself."],
      ],
      vocab: [
        ["場所[ばしょ]", "ばしょ", "basho", "place", "noun"],
        ["世界[せかい]", "せかい", "sekai", "world", "noun"],
        ["未来[みらい]", "みらい", "mirai", "future", "noun"],
        ["過去[かこ]", "かこ", "kako", "the past", "noun"],
        ["記憶[きおく]", "きおく", "kioku", "memory", "noun"],
        ["先祖[せんぞ]", "せんぞ", "senzo", "ancestor", "noun"],
        ["秘密[ひみつ]", "ひみつ", "himitsu", "secret", "noun"],
        ["探[さが]します", "さがします", "sagashimasu", "to search for", "verb・godan"],
        ["見[み]つけます", "みつけます", "mitsukemasu", "to find", "verb・ichidan"],
        ["機械[きかい]", "きかい", "kikai", "machine", "noun"],
        ["塔[とう]", "とう", "tou", "tower", "noun"],
      ],
      exercises: [
        { t: "build", en: "I read the book I bought yesterday.", tokens: ["昨日", "買った", "本", "を", "読みました"], extra: ["買いました", "が"],
          why: "The clause 昨日買った (plain past!) parks in front of 本. 買いました can never live inside a clause — plain form only." },
        { t: "mc", q: "“The tea the captain drinks” — pick the correct clause:",
          choices: ["艦長が飲むお茶", "艦長は飲むお茶", "艦長を飲むお茶", "お茶が飲む艦長"], a: 0,
          why: "Inside a clause the subject takes が, never は. (The last option is a tea that drinks captains — grammar CAN build horrors.)" },
        { t: "mc", q: "{{先祖の記憶を探す機械}} describes…",
          choices: ["a machine that searches ancestral memories", "an ancestor who fixes machines", "a memory of searching machines", "a machine my ancestors built"], a: 0,
          why: "[先祖の記憶を探す] is the clause; 機械 is the noun it lands on. Abstergo would like to know your location. 🦅" },
        { t: "mc", q: "“I have a friend who lives in Tokyo”:",
          choices: ["東京に住んでいる友達がいます", "東京に住んでいます友達がいます", "友達は東京に住むがいます", "東京の住む友達います"], a: 0,
          why: "住んでいる (plain ている — the settled state) fronts 友達. The ます stays outside the clause, at the sentence's end… where there happens to be います already wearing it." },
        { t: "type", q: "Say: “a person who speaks Japanese” (just the phrase)",
          accept: ["日本語を話す人", "にほんごをはなすひと"],
          show: "日本語[にほんご]を話[はな]す人[ひと]。",
          why: "[日本語を話す] + 人. You are, at this point, describing yourself — と思います。" },
        { t: "mc", q: "{{高い塔から飛ぶ暗殺者を見ました}} means…",
          choices: ["I saw an assassin leaping from a tall tower", "A tall assassin saw the tower fly", "I flew from the tower the assassin built", "The tower watched us both"], a: 0,
          why: "[高い塔から飛ぶ] describes 暗殺者; 見ました is yours. Haystack cart sold separately. Leap of faith: grammatically confirmed." },
      ],
    },
    {
      id: "9.4",
      title: "Because and But — から・ので・けど",
      sub: "reasons, contrasts, and the connective tissue of real conversation",
      briefing: [
        ["h", "から — because (plain and simple)"],
        ["p", "Reason + {{から}} + result: {{頭が痛いから、薬を飲みます}} “my head hurts, so I'll take medicine.” から attaches to either polite or plain forms — in conversation, plain + から is the everyday default. Reason first, result second: Japanese explains *before* it concludes."],
        ["h", "ので — because (soft uniform)"],
        ["p", "{{ので}} is から's gentler sibling — more objective, less insistent, beloved of polite requests and excuses: {{熱があるので、休みたいです}} “since I have a fever, I'd like to take the day off.” Nouns and な-adjectives take な before it: 病気**な**ので. When asking favours of superiors, ので simply sounds better-brought-up than から."],
        ["h", "けど／が — but"],
        ["p", "{{けど}} (casual) and {{が}} (formal) glue contrasting sentences: {{高いけど、美味しいです}} “it's pricey, but delicious.” They also soft-open conversations without any contrast at all: {{すみませんが…}} “excuse me, but…” — a politeness airlock before the actual request."],
        ["ex", [
          ["寒[さむ]いから、窓[まど]を閉[し]めてください。", "さむいから、まどをしめてください", "It's cold, so please close the window."],
          ["日本語[にほんご]は難[むずか]しいけど、面白[おもしろ]いです。", "にほんごはむずかしいけど、おもしろいです", "Japanese is hard, but interesting.", "the learner's creed"],
          ["時間[じかん]がないので、タクシーで行[い]きます。", "じかんがないので、たくしーでいきます", "There's no time, so I'll take a taxi."],
        ]],
        ["h", "〜とき — when"],
        ["p", "{{とき}} (time) takes a clause in front, exactly like yesterday's relative clauses — because it IS one: {{日本に行くとき}} “when I go to Japan”, {{子供だったとき}} “when I was a child”. Tense inside is relative to the main event: 行く**とき** (before/while going) vs 行った**とき** (once there). The clause machinery, already paying dividends."],
      ],
      vocab: [
        ["頭[あたま]", "あたま", "atama", "head", "noun"],
        ["痛[いた]い", "いたい", "itai", "painful, sore", "い-adj"],
        ["風邪[かぜ]", "かぜ", "kaze", "a cold (illness)", "noun"],
        ["熱[ねつ]", "ねつ", "netsu", "fever", "noun"],
        ["薬[くすり]", "くすり", "kusuri", "medicine", "noun"],
        ["病院[びょういん]", "びょういん", "byouin", "hospital", "noun"],
        ["病気[びょうき]", "びょうき", "byouki", "illness", "noun"],
        ["だから", "だから", "dakara", "so, therefore", "conjunction"],
        ["でも", "でも", "demo", "but (sentence-initial)", "conjunction"],
        ["とき", "とき", "toki", "when, the time of", "noun"],
        ["タクシー", "たくしー", "takushii", "taxi", "noun"],
      ],
      exercises: [
        { t: "build", en: "My head hurts, so I'll take medicine.", tokens: ["頭", "が", "痛い", "から", "薬", "を", "飲みます"], extra: ["ので", "でも"],
          why: "Reason (頭が痛い) + から + result. Note 飲む does medicine as well as tea — Japanese “drinks” its pills." },
        { t: "mc", q: "Pick the connector.", jp: "寒[さむ]い＿＿、窓[まど]を閉[し]めてください。", speak: false,
          choices: ["から", "とき", "けど", "より"], a: 0,
          why: "A reason for the request → から. (けど would produce “it's cold BUT close the window” — chaotic-neutral thermostat energy.)" },
        { t: "mc", q: "Asking your boss for a day off, the smoother opener is…",
          choices: ["熱があるので、休みたいです", "熱があるから、休みます！", "熱がある。休む。", "休みますが熱です"], a: 0,
          why: "ので presents the reason as objective circumstance, and 休みたい keeps it a wish rather than an announcement. から+休みます reads as “I have a fever so I'm GONE.”" },
        { t: "mc", q: "{{日本語は難しいけど、面白いです}} — the けど is doing what?",
          choices: ["conceding a contrast: hard, BUT interesting", "giving a reason", "quoting someone", "marking a question"], a: 0,
          why: "けど joins the concession to the point. This sentence is also simply true, and you may now say it with feeling." },
        { t: "mc", q: "“When I went to Japan, I ate sushi” — pick the とき clause:",
          choices: ["日本に行ったとき、寿司を食べました", "日本に行くとき、寿司を食べました", "日本にとき行った、寿司を食べました", "日本は行きましたとき寿司です"], a: 0,
          why: "行った**とき** = once there (the going already done when the eating happens). 行くとき would put the sushi en route — airport sushi, a different and sadder story." },
        { t: "type", q: "Say: “I caught a cold, so I'll go to the hospital.” (use から)",
          accept: ["風邪だから病院に行きます", "かぜだからびょういんにいきます", "風邪ですから病院に行きます", "風邪だから、病院に行きます"],
          show: "風邪[かぜ]だから、病院[びょういん]に行[い]きます。",
          why: "Noun + だ + から. (Japan-culture note: people go to the hospital for colds — 病院 covers clinics too. Nobody is being dramatic.)" },
      ],
    },
    {
      id: "9.5",
      review: true,
      title: "Mission Review 09",
      sub: "opinions, quotes, clauses, reasons — Temba, his arms wide",
      briefing: [
        ["h", "Debrief: the metaphor decoded"],
        ["ul", [
          "**と思います** — plain form + と; nouns/な-adj bring だ. Negatives go inside the thought.",
          "**と言いました** — direct 「…」 or indirect plain form; **という** names things.",
          "**Relative clauses** park plain-form sentences in front of nouns; inner subjects take が.",
          "**から／ので** reason-first; **けど／が** concede; **とき** clauses tell relative time.",
        ]],
        ["p", "Darmok and Jalad, their sails unfurled: you and this language, on the open sea. Picard would be proud — he learned a language from stories too. Simulation begins."],
      ],
      vocab: [],
      exercises: [
        { t: "mc", q: "“I think this castle is old” — correct connection:",
          choices: ["この城は古いと思います", "この城は古いだと思います", "この城は古いですと思います", "この城が古かったと言います"], a: 0,
          why: "い-adjective connects BARE: 古いと. (だ after い-adjectives is the mirror-image of the noun error — the tribes strike again.)" },
        { t: "build", en: "The friend who lives in Kyoto came to Tokyo.", tokens: ["京都", "に", "住んでいる", "友達", "が", "東京", "に", "来ました"], extra: ["住んでいます", "は"],
          why: "Clause [京都に住んでいる] fronts 友達; the friend arrives as news → が." },
        { t: "mc", q: "{{「タナグラのダーモックとジャラッド」という物語は友情の話だと思います}} — parse the claim:",
          choices: ["I think the tale called “Darmok and Jalad at Tanagra” is a story of friendship", "Darmok told Jalad a story at Tanagra", "I said the legend was false", "Tanagra is where stories go"], a: 0,
          why: "という names the tale; 〜の話 = a story of; だと思います wraps it as opinion. Sokath, his eyes uncovered — you parsed it." },
        { t: "type", q: "Say: “It's raining, so let's watch a film at home.” (use から and ましょう)",
          accept: ["雨だから家で映画を見ましょう", "あめだからいえでえいがをみましょう", "雨だから、家で映画を見ましょう", "雨が降っているから家で映画を見ましょう", "あめがふっているからいえでえいがをみましょう"],
          show: "雨[あめ]だから、家[いえ]で映画[えいが]を見[み]ましょう。",
          why: "Reason + から, action-place で, invitation ましょう. Four weeks of grammar in one cosy evening." },
        { t: "mc", q: "Report it: your friend said “I'll come at 9.”",
          choices: ["友達は九時に来ると言いました", "友達は九時に来ますと言いました", "友達は九時に来たと思います", "友達という九時"], a: 0,
          why: "Indirect quote → plain 来る inside, 言いました outside. くじ, of course — the rebel hour, to the end." },
      ],
    },
  ],
});
