/* ============================================================
   DARMOK curriculum — Weeks 10–12
   ============================================================ */

/* ================= WEEK 10 — PRIME DIRECTIVE ================= */
DK.week({
  n: 10,
  name: "PRIME DIRECTIVE",
  brief: "Stardate 79541.8. Regulations week: what you CAN do, what you MUST do, what you'd BETTER do, and what you've done TOO MUCH of. The grammar of ability, obligation and advice — every regulation in the book, and how to bend them politely.",
  lessons: [
    {
      id: "10.1",
      title: "The Potential Form — 話せます",
      sub: "“can do” in one compact form — ことができます gets a promotion",
      briefing: [
        ["h", "Compressing ことができます"],
        ["p", "Week 6 gave you the scaffold: 話すことができます. Everyday Japanese compresses this into the **potential form** — one verb that means “can do”:"],
        ["table", ["Class", "Rule", "Example"], [
          ["godan", "final -u → -e + る", "話す→話せる、飲む→飲める、行く→行ける"],
          ["ichidan", "る → られる", "食べる→食べられる、見る→見られる"],
          ["irregular", "the usual suspects", "する→できる、来る→来[こ]られる"],
        ]],
        ["p", "The result is always an **ichidan** verb, so it conjugates the friendly way: 話せる→話せます→話せない→話せました. する's potential simply IS できる — the word you've been using all along."],
        ["h", "The object usually takes が"],
        ["ex", [
          ["日本語[にほんご]が話[はな]せます。", "にほんごがはなせます", "I can speak Japanese."],
          ["漢字[かんじ]が少[すこ]し読[よ]めます。", "かんじがすこしよめます", "I can read a little kanji."],
          ["今日[きょう]は来[こ]られません。", "きょうはこられません", "I can't come today."],
        ]],
        ["p", "Like 好き and 分かる, potential verbs prefer {{が}} on their target — ability, understanding and liking are all states that “arise” rather than acts you perform. (を survives in casual speech; が is the polished choice.)"],
        ["h", "見える・聞こえる — the involuntary pair"],
        ["p", "Two special verbs outrank the potential: {{見えます}} “is visible” and {{聞こえます}} “is audible” — for what reaches your senses *unbidden*: {{窓から富士山が見えます}} “you can see Fuji from the window.” 見られます would mean you're *able to (go and) watch* something. The mountain simply appears; no effort, no potential form needed."],
        ["note", "In speech you'll increasingly hear ichidan potentials without ら: 食べれる, 見れる — “ra-nuki” Japanese. Understand it everywhere; write the full られる in anything formal. Living languages molt; textbooks lag." ],
      ],
      vocab: [
        ["外国[がいこく]", "がいこく", "gaikoku", "foreign country", "noun"],
        ["外国語[がいこくご]", "がいこくご", "gaikokugo", "foreign language", "noun"],
        ["中国語[ちゅうごくご]", "ちゅうごくご", "chuugokugo", "Chinese (language)", "noun"],
        ["フランス語[ご]", "ふらんすご", "furansugo", "French (language)", "noun"],
        ["全部[ぜんぶ]", "ぜんぶ", "zenbu", "all, everything", "noun"],
        ["半分[はんぶん]", "はんぶん", "hanbun", "half", "noun"],
        ["声[こえ]", "こえ", "koe", "voice", "noun"],
        ["音[おと]", "おと", "oto", "sound", "noun"],
        ["字[じ]", "じ", "ji", "character, letter", "noun"],
        ["見[み]えます", "みえます", "miemasu", "to be visible", "verb・ichidan"],
        ["聞[き]こえます", "きこえます", "kikoemasu", "to be audible", "verb・ichidan"],
      ],
      exercises: [
        { t: "mc", q: "Potential of {{飲む}}:", choices: ["飲める", "飲まれる", "飲みえる", "飲むできる"], a: 0,
          why: "Godan: -u → -e + る. 飲む→飲める. お酒が飲めますか is Japan's favourite dinner-party question." },
        { t: "mc", q: "Potential of {{食べる}}:", choices: ["食べられる", "食べれる", "食べえる", "食べける"], a: 0,
          why: "Ichidan: る→られる. (食べれる is the ra-nuki street version — understood everywhere, written nowhere formal.)" },
        { t: "mc", q: "Potential of {{する}}:", choices: ["できる", "しられる", "せる", "すれる"], a: 0,
          why: "する's potential IS できる — the ことができます pattern was the potential form hiding in plain sight all along." },
        { t: "build", en: "I can read a little kanji.", tokens: ["漢字", "が", "少し", "読めます"], extra: ["を", "読みます"],
          why: "Potential target takes が; 読む→読める→読めます. Modest and true — and truer every week." },
        { t: "type", q: "Say: “I can speak Japanese.” (own it)",
          accept: ["日本語が話せます", "にほんごがはなせます", "日本語を話せます"],
          show: "日本語[にほんご]が話[はな]せます。",
          why: "話す→話せる. Ten weeks ago this sentence was aspirational; now it's just accurate reporting." },
        { t: "mc", q: "“You can see Mt Fuji from this window” — the natural verb:",
          choices: ["見えます", "見られます", "見ます", "見せます"], a: 0,
          why: "The mountain reaches your eyes unbidden → 見えます. 見られます would be about your ability/permission to watch — wrong tool for scenery." },
        { t: "mc", q: "{{すみません、声が聞こえません}} on a comm channel means…",
          choices: ["Sorry, I can't hear you", "Please lower your voice", "I refuse to listen", "The sound is beautiful"], a: 0,
          why: "聞こえる = reaches the ear (or doesn't). The 24th-century “you're on mute”, fully operational in the 21st." },
      ],
    },
    {
      id: "10.2",
      title: "Must and Needn't — なければなりません",
      sub: "obligation: the double-negative that runs Japanese society",
      briefing: [
        ["h", "“Must” is a double negative"],
        ["p", "Japanese has no word for “must”. It builds obligation from **two negatives**: {{行かなければなりません}} — literally “if (I) don't go, (it) won't become” → “I must go.” Take the ない-form, swap ない for {{なければ}}, add {{なりません}}:"],
        ["table", ["Verb", "ない-form", "must"], [
          ["行く", "行かない", "行かなければなりません"],
          ["払う", "払わない", "払わなければなりません"],
          ["起きる", "起きない", "起きなければなりません"],
          ["する", "しない", "しなければなりません"],
        ]],
        ["p", "In speech this monster shrinks: {{なきゃ}} or {{ないと}} — 行かなきゃ！ “gotta go!” Both leave the “…won't become” unsaid; everyone hears it anyway."],
        ["h", "“Needn't” — permission NOT to"],
        ["p", "The mirror image: ない-form, swap ない for {{なくても}}, add {{いいです}} (the てもいい you know, running on a negative): {{明日は来なくてもいいです}} — “you needn't come tomorrow.” Literally: “even not-coming is fine.”"],
        ["ex", [
          ["パスポートを見[み]せなければなりません。", "ぱすぽーとをみせなければなりません", "You must show your passport."],
          ["早[はや]く起[お]きなければなりません。", "はやくおきなければなりません", "I have to get up early."],
          ["靴[くつ]を脱[ぬ]がなくてもいいです。", "くつをぬがなくてもいいです", "You don't need to take your shoes off.", "rare words in Japan — treasure them"],
        ]],
        ["table", ["Pattern", "Meaning"], [
          ["〜なければなりません", "must (if not-X, won't do)"],
          ["〜なくてもいいです", "needn't (even not-X is fine)"],
          ["〜てもいいです", "may (even X is fine)"],
          ["〜てはいけません", "must not (X won't do)"],
        ]],
        ["p", "Behold the full regulation matrix — all four corners of permission and obligation, all built from parts you own: te-form, ない-form, いい, いけません."],
        ["note", "なりません vs いけません at the end are interchangeable in this pattern; なければいけません is a shade more conversational, なければなりません more official. Choose by how much uniform the sentence is wearing."],
      ],
      vocab: [
        ["払[はら]います", "はらいます", "haraimasu", "to pay", "verb・godan"],
        ["パスポート", "ぱすぽーと", "pasupooto", "passport", "noun"],
        ["予約[よやく]", "よやく", "yoyaku", "reservation", "noun"],
        ["準備[じゅんび]", "じゅんび", "junbi", "preparation", "noun"],
        ["出発[しゅっぱつ]", "しゅっぱつ", "shuppatsu", "departure", "noun"],
        ["到着[とうちゃく]", "とうちゃく", "touchaku", "arrival", "noun"],
        ["忘[わす]れます", "わすれます", "wasuremasu", "to forget", "verb・ichidan"],
        ["見[み]せます", "みせます", "misemasu", "to show", "verb・ichidan"],
        ["早[はや]く", "はやく", "hayaku", "early, quickly", "adverb"],
        ["急[いそ]ぎます", "いそぎます", "isogimasu", "to hurry", "verb・godan"],
      ],
      exercises: [
        { t: "mc", q: "“I must pay” is…",
          choices: ["払わなければなりません", "払えばなりません", "払ってなりません", "払うなければいいです"], a: 0,
          why: "払う→払わない→払わ**なければなりません**. The -う verb goes to -わ (week 6's fossil rule), then the double negative stacks on." },
        { t: "mc", q: "{{明日は早く起きなくてもいいです}} means…",
          choices: ["You needn't get up early tomorrow", "You must get up early tomorrow", "Don't get up tomorrow", "Getting up early is banned"], a: 0,
          why: "なくてもいい = even not-doing is fine → needn't. The holiday-morning pattern. Savour it." },
        { t: "build", en: "I must go to the airport.", tokens: ["空港", "に", "行かなければ", "なりません"], extra: ["行っても", "いいです"],
          why: "行かない → 行かなければ + なりません. If-not-go, won't-become: the full ceremonial double negative." },
        { t: "mc", q: "Your friend, sprinting past: {{もう行かなきゃ！}}. That's…",
          choices: ["“Gotta go!” — casual なければなりません", "“Don't go!”", "“I already went”", "“Shall we go?”"], a: 0,
          why: "なきゃ = なければ(なりません) with the ending swallowed. The obligation is so obvious it needn't be finished." },
        { t: "mc", q: "Which sign means you do NOT have to remove your shoes?",
          choices: ["靴を脱がなくてもいいです", "靴を脱がなければなりません", "靴を脱いではいけません", "靴を脱いでください"], a: 0,
          why: "なくてもいい = needn't. (Option 3 FORBIDS removing them — a sign that exists somewhere, surely, guarding a very cold floor.)" },
        { t: "type", q: "Say: “I must study Japanese.” (the app regrets nothing)",
          accept: ["日本語を勉強しなければなりません", "にほんごをべんきょうしなければなりません"],
          show: "日本語[にほんご]を勉強[べんきょう]しなければなりません。",
          why: "する→しない→しなければなりません. Longest word-train in the course — and you just drove it." },
      ],
    },
    {
      id: "10.3",
      title: "Advice — 〜た方がいいです and すぎる",
      sub: "you'd better rest; you've eaten too much — the gentle art of counsel",
      briefing: [
        ["h", "た方がいいです — you'd better"],
        ["p", "Advice runs on the comparison machinery from week 4: {{方}} (side) says one side is better. Affirmative advice takes the **た-form**: {{休んだ方がいいですよ}} “you'd better rest.” Negative advice takes **ない**: {{行かない方がいいです}} “better not go.”"],
        ["table", ["Advice", "Form", "Example"], [
          ["do it", "た + 方がいい", "薬を飲んだ方がいいです"],
          ["don't", "ない + 方がいい", "飲みすぎない方がいいです"],
        ]],
        ["p", "Why た for something not yet done? The advice presents the action *as if accomplished* — “the having-rested side is better.” Grammar with a bedside manner. The final よ (week 1's assertion particle) is almost mandatory: advice without よ sounds like a weather report."],
        ["h", "すぎる — too much"],
        ["p", "{{すぎる}} (to exceed) bolts onto stems: verbs at the ます-stem ({{食べすぎる}} overeat), adjectives minus the い ({{高すぎる}} too expensive), な-adjectives bare ({{静かすぎる}} TOO quiet). The result is an ichidan verb: 食べすぎました “I overate” — announced across Japan every New Year."],
        ["ex", [
          ["風邪[かぜ]のときは、寝[ね]た方[ほう]がいいですよ。", "かぜのときは、ねたほうがいいですよ", "When you have a cold, you'd better sleep."],
          ["この城[しろ]は人[ひと]が多[おお]すぎます。", "このしろはひとがおおすぎます", "This castle is way too crowded."],
          ["ゲームをしすぎない方[ほう]がいいですよ。", "げーむをしすぎないほうがいいですよ", "Better not game too much.", "the computer says, hypocritically"],
        ]],
        ["note", "Advice hierarchy, weakest to strongest: 〜たらどうですか (how about…?) < 〜た方がいいです (you'd better) < 〜なければなりません (you must). Prescribing upward — advising your captain — softens further: お休みになった方が… and then trails off entirely. The trailing-off IS the politeness."],
      ],
      vocab: [
        ["塩[しお]", "しお", "shio", "salt", "noun"],
        ["砂糖[さとう]", "さとう", "satou", "sugar", "noun"],
        ["甘[あま]い", "あまい", "amai", "sweet", "い-adj"],
        ["辛[から]い", "からい", "karai", "spicy, hot", "い-adj"],
        ["健康[けんこう]", "けんこう", "kenkou", "health", "noun"],
        ["野菜[やさい]", "やさい", "yasai", "vegetables", "noun"],
        ["果物[くだもの]", "くだもの", "kudamono", "fruit", "noun"],
        ["体[からだ]", "からだ", "karada", "body", "noun"],
        ["運動[うんどう]", "うんどう", "undou", "exercise", "noun"],
        ["多[おお]い", "おおい", "ooi", "many, numerous", "い-adj"],
      ],
      exercises: [
        { t: "build", en: "You'd better eat vegetables. (advice, with よ)", tokens: ["野菜", "を", "食べた", "方", "が", "いい", "です", "よ"], extra: ["食べる", "ない"],
          why: "Advice-to-do takes た: 食べた方がいいですよ. The よ delivers it warmly instead of meteorologically." },
        { t: "mc", q: "“You'd better NOT drink too much” is…",
          choices: ["飲みすぎない方がいいですよ", "飲みすぎた方がいいですよ", "飲まない方がすぎます", "飲みすぎてもいいです"], a: 0,
          why: "すぎる stacks on the stem (飲み+すぎる), then negative advice takes ない: 飲みすぎない方がいい. (Option 2 recommends overdrinking. Do not take option 2 to parties.)" },
        { t: "mc", q: "{{このカレーは辛すぎます！}} means…",
          choices: ["This curry is TOO spicy!", "This curry is nicely spicy", "This curry lacks spice", "I want more curry"], a: 0,
          why: "辛い minus い + すぎる: beyond the acceptable spice frontier. 美味しいけど辛すぎる — a complete restaurant review." },
        { t: "mc", q: "Why does advice use the PAST form (寝た方がいい) for something not yet done?",
          choices: ["It presents the action as accomplished — “the having-slept side is better”", "It's a typo everyone repeats", "Advice is always about the past", "た marks politeness"], a: 0,
          why: "The た here is aspect, not time: the recommended world is the one where it's already done. Grammar with a bedside manner." },
        { t: "type", q: "Advise a sniffling friend: “You'd better rest.” (休む, with よ)",
          accept: ["休んだ方がいいですよ", "やすんだほうがいいですよ", "休んだほうがいいですよ"],
          show: "休[やす]んだ方[ほう]がいいですよ。",
          why: "休む→休んだ (む→んだ, the song again) + 方がいいですよ. Medical-grade grammar." },
        { t: "mc", q: "{{食べすぎました…}} groaned after dinner is…",
          choices: ["I ate too much…", "I didn't eat enough", "The food was excellent", "I'll eat later"], a: 0,
          why: "ます-stem + すぎる, past. The national announcement of every 忘年会 (year-end party) season." },
      ],
    },
    {
      id: "10.4",
      title: "Becoming — なる, and やすい・にくい",
      sub: "the sky grows dark; kanji become easy to read — the grammar of change",
      briefing: [
        ["h", "なる — to become"],
        ["p", "{{なります}} turns states into stories. What comes before it changes shape by tribe:"],
        ["table", ["Type", "Rule", "Example"], [
          ["い-adjective", "い → く + なる", "暗い→暗くなります (grows dark)"],
          ["な-adjective", "+ に + なる", "静か→静かになります (becomes quiet)"],
          ["noun", "+ に + なる", "医者になります (becomes a doctor)"],
        ]],
        ["ex", [
          ["空[そら]が暗[くら]くなりました。", "そらがくらくなりました", "The sky grew dark."],
          ["日本語[にほんご]が上手[じょうず]になりましたね！", "にほんごがじょうずになりましたね", "Your Japanese has gotten good!", "the compliment you're now earning legitimately"],
          ["暖[あたた]かくなりましたね。", "あたたかくなりましたね", "It's warmed up, hasn't it.", "small talk, level 2 — change over time"],
        ]],
        ["p", "That く is the **adverb form** of い-adjectives, and it works beyond なる: {{早く起きます}} get up early, {{よく分かります}} understand well. な-adjectives adverb with に: {{静かに話してください}} speak quietly. Two tribes, two adverb badges — the same split, one last time."],
        ["h", "やすい・にくい — easy/hard to"],
        ["p", "ます-stem + {{やすい}} (easy to) or {{にくい}} (hard to), and the result is an い-adjective with the full week-4 toolkit: {{読みやすい}} easy to read, {{歩きにくい靴}} shoes that are hard to walk in, {{この漢字は覚えやすくなりました}} — this kanji became easy to remember. Stack the machines; they were built to interlock."],
        ["note", "The seasons run on なる: 春になりました (spring has come), 寒くなりましたね (it's gotten cold, hasn't it). Japanese small talk is a weather-and-change protocol, and なる is its verb. Master it and every lift ride in Japan is yours."],
      ],
      vocab: [
        ["なります", "なります", "narimasu", "to become", "verb・godan"],
        ["空[そら]", "そら", "sora", "sky", "noun"],
        ["星[ほし]", "ほし", "hoshi", "star", "noun"],
        ["月[つき]", "つき", "tsuki", "the moon", "noun"],
        ["地球[ちきゅう]", "ちきゅう", "chikyuu", "the Earth", "noun"],
        ["宇宙[うちゅう]", "うちゅう", "uchuu", "space, the universe", "noun"],
        ["明[あか]るい", "あかるい", "akarui", "bright", "い-adj"],
        ["暗[くら]い", "くらい", "kurai", "dark", "い-adj"],
        ["暖[あたた]かい", "あたたかい", "atatakai", "warm", "い-adj"],
        ["涼[すず]しい", "すずしい", "suzushii", "cool (weather)", "い-adj"],
        ["覚[おぼ]えます", "おぼえます", "oboemasu", "to memorise, learn", "verb・ichidan"],
      ],
      exercises: [
        { t: "build", en: "The sky grew dark.", tokens: ["空", "が", "暗く", "なりました"], extra: ["暗い", "に"],
          why: "い-adjective drops い, takes く, meets なる: 暗くなりました. Cue the stars." },
        { t: "mc", q: "“become quiet” is…",
          choices: ["静かになる", "静かくなる", "静かなる", "静いになる"], a: 0,
          why: "な-tribe takes に before なる: 静かに. (静かく is the い-tribe rule knocking on the wrong door.)" },
        { t: "mc", q: "“I will become a doctor” is…",
          choices: ["医者になります", "医者くなります", "医者をなります", "医者がなりました"], a: 0,
          why: "Nouns follow the な-road: 医者**に**なります. Destination-に for a career — you travel to what you become." },
        { t: "mc", q: "{{この本は読みやすいです}} means…",
          choices: ["This book is easy to read", "This book is worth reading", "I read this book quickly", "This book must be read"], a: 0,
          why: "読み (stem) + やすい = easy-to-read, itself now an い-adjective: 読みやすかった, 読みやすくない — the whole toolkit applies." },
        { t: "type", q: "Say: “It's gotten warm, hasn't it.” (seasonal small talk, level 2)",
          accept: ["暖かくなりましたね", "あたたかくなりましたね"],
          show: "暖[あたた]かくなりましたね。",
          why: "暖かい→暖かく + なりました + ね (inviting agreement). You are now fully armed for Japanese lift rides." },
        { t: "mc", q: "{{宇宙から地球が見えて、星がきれいでした}} — the astronaut reports…",
          choices: ["Earth was visible from space, and the stars were beautiful", "Earth became a star", "Space grew dark and cold", "The moon blocked the view"], a: 0,
          why: "見えて (visible — te-form linking) + きれいでした (な-adj past). Ten weeks of grammar, one orbital postcard. 🌍" },
        { t: "mc", q: "“Kanji have become easy to memorise” — the full stack:",
          choices: ["漢字が覚えやすくなりました", "漢字を覚えるやすいなりました", "漢字が覚えにくくなりました", "漢字は覚えますやすいです"], a: 0,
          why: "覚え (stem) + やすい (→ い-adj) + くなりました (change). Three machines interlocked — and, with this app's drill deck, an accurate statement." },
      ],
    },
    {
      id: "10.5",
      review: true,
      title: "Mission Review 10",
      sub: "can, must, should, become — regulations internalised",
      briefing: [
        ["h", "Debrief: the rulebook, absorbed"],
        ["ul", [
          "**Potential**: -eる / られる / できる・来られる; target takes が. 見える・聞こえる for the unbidden senses.",
          "**Must**: ない→なければなりません (casual: なきゃ). **Needn't**: なくてもいいです.",
          "**Advice**: た方がいいですよ / ない方がいいですよ. **Too much**: stem+すぎる.",
          "**Change**: 〜くなる (い-tribe) / 〜になる (な-tribe & nouns); stems take やすい・にくい.",
        ]],
        ["p", "The Prime Directive of language learning: interference in your own progress is mandatory. Simulation begins."],
      ],
      vocab: [],
      exercises: [
        { t: "mc", q: "“I can't come tomorrow” is…",
          choices: ["明日は来られません", "明日は来ません", "明日は来なくてもいいです", "明日は来てはいけません"], a: 0,
          why: "Potential negative: 来られません — unable. (来ません just declines; the potential explains.)" },
        { t: "build", en: "You must show your ticket.", tokens: ["切符", "を", "見せなければ", "なりません"], extra: ["見せても", "見せない"],
          why: "見せる→見せない→見せなければなりません. The gate agent's grammar." },
        { t: "mc", q: "Pick the correct change: “The station has become convenient.”",
          choices: ["駅は便利になりました", "駅は便利くなりました", "駅は便利をなりました", "駅が便利だなりました"], a: 0,
          why: "便利 is な-tribe → 便利に + なりました. The く road belongs to the い-tribe." },
        { t: "type", q: "Say: “I can write kanji.” (a boast eleven weeks in the making)",
          accept: ["漢字が書けます", "かんじがかけます", "漢字を書けます"],
          show: "漢字[かんじ]が書[か]けます。",
          why: "書く→書ける, target takes が. Modesty optional; accuracy guaranteed." },
        { t: "mc", q: "Your friend has a fever AND wants to go hiking. Correct counsel:",
          choices: ["行かない方がいいですよ", "行った方がいいですよ", "行かなければなりません", "行きすぎます"], a: 0,
          why: "Negative advice: ない方がいいですよ. Prescribe rest, cite week 9: 熱があるから、寝た方がいいですよ." },
      ],
    },
  ],
});

/* ================= WEEK 11 — FIRST OFFICER'S EXCHANGE ================= */
DK.week({
  n: 11,
  name: "FIRST OFFICER'S EXCHANGE",
  brief: "Stardate 79544.3. Gift-giving is diplomacy at its most concentrated — and Japanese grammar tracks every favour's direction like a sensor log. This week: giving, receiving, favours, experience, and the art of “already” and “not yet”.",
  lessons: [
    {
      id: "11.1",
      title: "あげる・くれる・もらう — The Vector of Giving",
      sub: "three verbs for “give” — because direction matters",
      briefing: [
        ["h", "One English verb, three Japanese vectors"],
        ["p", "English “give” ignores direction; Japanese refuses to. The three verbs form a targeting system centred on **you**:"],
        ["table", ["Verb", "Vector", "Example"], [
          ["あげます", "outward: I/we → others (or A → B, neither is me)", "私は友達に花をあげました"],
          ["くれます", "inward: others → me/my circle", "友達が私に花をくれました"],
          ["もらいます", "receiving: I get FROM someone", "私は友達に（から）花をもらいました"],
        ]],
        ["p", "The giver of くれる takes が (they're the news); the receiver of もらう is the topic and the source takes に or から. One event, two camera angles: {{友達がくれました}} = {{友達にもらいました}} — “my friend gave me / I received from my friend.”"],
        ["ex", [
          ["母[はは]にチョコレートをあげました。", "ははにちょこれーとをあげました", "I gave my mother chocolate."],
          ["田中[たなか]さんが切符[きっぷ]をくれました。", "たなかさんがきっぷをくれました", "Tanaka gave me a ticket."],
          ["父[ちち]に古[ふる]い時計[とけい]をもらいました。", "ちちにふるいとけいをもらいました", "I got an old watch from my father."],
        ]],
        ["h", "Why bother? Because gratitude is grammar"],
        ["p", "くれる doesn't just report a transfer — it encodes **that you benefited**. 田中さんが切符をくれました quietly says “and wasn't that kind.” Using あげる for someone giving TO you sounds bizarrely self-absent, like narrating your life from orbit. The vectors are the feeling."],
        ["note", "Family terms: 母・父 for YOUR OWN mother/father when talking to others; お母さん・お父さん for someone ELSE's (or addressing your own at home). Humble inward, honorific outward — the same instinct as 上手/得意 from week 4, now organising the family album."],
      ],
      vocab: [
        ["あげます", "あげます", "agemasu", "to give (outward)", "verb・ichidan"],
        ["くれます", "くれます", "kuremasu", "to give (to me)", "verb・ichidan"],
        ["もらいます", "もらいます", "moraimasu", "to receive", "verb・godan"],
        ["プレゼント", "ぷれぜんと", "purezento", "present, gift", "noun"],
        ["花[はな]", "はな", "hana", "flower", "noun"],
        ["チョコレート", "ちょこれーと", "chokoreeto", "chocolate", "noun"],
        ["時計[とけい]", "とけい", "tokei", "watch, clock", "noun"],
        ["母[はは]", "はは", "haha", "(my) mother", "noun"],
        ["父[ちち]", "ちち", "chichi", "(my) father", "noun"],
        ["両親[りょうしん]", "りょうしん", "ryoushin", "parents", "noun"],
        ["彼[かれ]", "かれ", "kare", "he; boyfriend", "pronoun"],
        ["彼女[かのじょ]", "かのじょ", "kanojo", "she; girlfriend", "pronoun"],
      ],
      exercises: [
        { t: "mc", q: "Pick the verb.", jp: "友達[ともだち]が私[わたし]にプレゼントを＿＿。", speak: false,
          choices: ["くれました", "あげました", "もらいました", "なりました"], a: 0,
          why: "Friend → me is the inward vector: くれる. (あげました here would narrate your own gift-receiving from space.)" },
        { t: "mc", q: "Pick the verb.", jp: "私[わたし]は母[はは]に花[はな]を＿＿。", speak: false,
          choices: ["あげました", "くれました", "もらいました", "見せました"], a: 0,
          why: "Me → mother is outward: あげる. Mother's Day, grammatically secured." },
        { t: "build", en: "I received chocolate from my father.", tokens: ["父", "に", "チョコレート", "を", "もらいました"], extra: ["が", "あげました"],
          why: "Receiver is topic (dropped); source takes に (or から); もらいました. Sweet, and correctly vectored." },
        { t: "mc", q: "{{田中さんが手伝ってくれました}} vs {{私は田中さんに手伝ってもらいました}} — the difference is…",
          choices: ["Camera angle only — same helpful event", "Different people helped", "One is past, one is future", "One is rude"], a: 0,
          why: "Giver-cam (くれる, Tanaka が) vs receiver-cam (もらう, source に). One kindness, two shots. (て-forms of these — tomorrow's episode.)" },
        { t: "mc", q: "Talking to a colleague about their mum, you say…",
          choices: ["お母さんはお元気ですか", "母はお元気ですか", "母さんは元気か", "あなたの母は元気"], a: 0,
          why: "Someone ELSE's mother gets the honorific お母さん. Your own, to outsiders, is plain 母. Humble inward, honorific outward." },
        { t: "type", q: "Say: “My boyfriend gave me flowers.” (use 彼 and くれる)",
          accept: ["彼が花をくれました", "かれがはなをくれました", "彼は花をくれました"],
          show: "彼[かれ]が花[はな]をくれました。",
          why: "Inward vector with built-in warmth: くれました says “gave me — kindly.” The grammar blushes so you don't have to." },
      ],
    },
    {
      id: "11.2",
      title: "Favours — 〜てくれる・〜てあげる・〜てもらう",
      sub: "the giving verbs strapped to te-forms: actions as gifts",
      briefing: [
        ["h", "Actions travel the same vectors"],
        ["p", "Strap the giving verbs onto a te-form and *actions* become gifts with direction:"],
        ["table", ["Pattern", "Meaning", "Example"], [
          ["〜てくれる", "someone kindly does for ME", "友達が道を教えてくれました"],
          ["〜てあげる", "I do for someone", "地図を見せてあげました"],
          ["〜てもらう", "I get someone to do / benefit from", "先生に説明してもらいました"],
        ]],
        ["ex", [
          ["友達[ともだち]が駅[えき]まで案内[あんない]してくれました。", "ともだちがえきまであんないしてくれました", "My friend kindly showed me the way to the station."],
          ["兄[あに]が自転車[じてんしゃ]を直[なお]してくれました。", "あにがじてんしゃをなおしてくれました", "My big brother fixed my bike (for me)."],
          ["田中[たなか]さんに漢字[かんじ]を教[おし]えてもらいました。", "たなかさんにかんじをおしえてもらいました", "I had Tanaka teach me kanji."],
        ]],
        ["h", "The gratitude engine"],
        ["p", "This is how Japanese says thank-you *inside the sentence*. 教えてくれました isn't “taught me” — it's “taught me, bless them.” Plain 教えました states data; てくれました states debt. Omitting the vector when a favour happened sounds coldly transactional — the verb IS the thank-you note."],
        ["h", "てあげる: handle with care"],
        ["p", "{{てあげる}} announces your own generosity — fine for equals and littles ({{手伝ってあげるよ}} “I'll help you out!”), patronising toward superiors (you don't “bestow favours” on the captain). Polite offer instead: {{手伝いましょうか}} — week 8's ましょうか, which is why you learned it first."],
        ["note", "Requesting: 〜てもらえますか / 〜てくれますか — “could you…for me?” Even softer as negatives: 〜てもらえませんか. Politeness in Japanese is a ladder of indirection, and you now stand on its middle rungs comfortably."],
      ],
      vocab: [
        ["貸[か]します", "かします", "kashimasu", "to lend", "verb・godan"],
        ["借[か]ります", "かります", "karimasu", "to borrow", "verb・ichidan"],
        ["教[おし]えます", "おしえます", "oshiemasu", "to teach, tell", "verb・ichidan"],
        ["送[おく]ります", "おくります", "okurimasu", "to send; see off", "verb・godan"],
        ["案内[あんない]", "あんない", "annai", "guidance, showing around", "noun"],
        ["直[なお]します", "なおします", "naoshimasu", "to fix, repair", "verb・godan"],
        ["説明[せつめい]", "せつめい", "setsumei", "explanation", "noun"],
        ["道[みち]", "みち", "michi", "road, way", "noun"],
        ["地図[ちず]", "ちず", "chizu", "map", "noun"],
        ["兄[あに]", "あに", "ani", "(my) older brother", "noun"],
        ["姉[あね]", "あね", "ane", "(my) older sister", "noun"],
      ],
      exercises: [
        { t: "build", en: "My friend kindly told me the way.", tokens: ["友達", "が", "道", "を", "教えて", "くれました"], extra: ["あげました", "に"],
          why: "Favour inbound → てくれました, giver が. The thank-you lives inside the verb." },
        { t: "mc", q: "{{先生に説明してもらいました}} means…",
          choices: ["I had the teacher explain (and benefited)", "I explained to the teacher", "The teacher demanded an explanation", "I will explain tomorrow"], a: 0,
          why: "Receiver-cam: I got the explaining FROM 先生 (に). The benefit flows to the speaker; the gratitude is built in." },
        { t: "mc", q: "Offering help to your boss, choose wisely:",
          choices: ["手伝いましょうか", "手伝ってあげましょうか", "手伝ってもらいます", "手伝え"], a: 0,
          why: "てあげる to a superior announces charity from below — awkward. ましょうか offers without bestowing. (Option 4 is a drill sergeant.)" },
        { t: "mc", q: "“Could you lend me the map?” — the soft request:",
          choices: ["地図を貸してもらえませんか", "地図を貸します", "地図を借りてあげます", "地図はどこですか"], a: 0,
          why: "てもらえませんか — “couldn't I receive the lending?” — maximum softness. 貸す = lend out, 借りる = borrow in: another vector pair, same compass." },
        { t: "type", q: "Report gratefully: “My older sister fixed my bike (for me).”",
          accept: ["姉が自転車を直してくれました", "あねがじてんしゃをなおしてくれました"],
          show: "姉[あね]が自転車[じてんしゃ]を直[なお]してくれました。",
          why: "姉 (my own big sister — humble form) + が + 直して + くれました. Debt recorded; sibling appreciated." },
        { t: "mc", q: "Which sentence *thanks* the friend grammatically?",
          choices: ["友達が空港まで送ってくれました", "友達が空港まで送りました", "友達を空港まで送りました", "空港は友達を送りました"], a: 0,
          why: "てくれました encodes the kindness. Option 2 reports logistics; option 3 has YOU driving THEM; option 4 has the airport doing the driving." },
      ],
    },
    {
      id: "11.3",
      title: "Ever Done It? — 〜たことがあります・〜たり",
      sub: "experience, and the art of listing a weekend loosely",
      briefing: [
        ["h", "た + ことがあります — “I have (at some point)”"],
        ["p", "The た-form + {{ことがあります}} = “the thing-of-having-done exists” → “I've done it (at least once)”: {{日本に行ったことがあります}} “I've been to Japan.” It's the *experience* perfect — not what you did yesterday (plain ました does that), but what your life-log contains."],
        ["ex", [
          ["着物[きもの]を着[き]たことがありますか。", "きものをきたことがありますか", "Have you ever worn a kimono?"],
          ["馬[うま]に乗[の]ったことがあります。", "うまにのったことがあります", "I've ridden a horse.", "乗る takes に, as ever"],
          ["富士山[ふじさん]に登[のぼ]ったことがありません。", "ふじさんにのぼったことがありません", "I've never climbed Mt Fuji."],
        ]],
        ["p", "Answers: {{はい、あります}} / {{いいえ、ありません}} — the こと exists or it doesn't. Add {{一度}} (once) or {{何度も}} (many times) for precision: 一度だけあります — just the once."],
        ["h", "〜たり〜たりする — the open sample"],
        ["p", "Listing actions exhaustively with te-forms (食べて、飲んで、寝ました) implies that was the whole itinerary. For a *sample* — “things like…” — use た-form + り, close with する: {{週末は映画を見たり、本を読んだりします}} “weekends, I watch films, read books, that sort of thing.” It's や (week 2) for verbs — same shrug, different part of speech."],
        ["ex", [
          ["京都[きょうと]でお寺[てら]を見[み]たり、抹茶[まっちゃ]を飲[の]んだりしました。", "きょうとでおてらをみたり、まっちゃをのんだりしました", "In Kyoto I saw temples, drank matcha, that sort of thing."],
        ]],
        ["note", "The final する carries all tense: 〜たりします (habit), 〜たりしました (that trip), 〜たりしたいです (the dream). One conjugation to rule the whole loose list."],
      ],
      vocab: [
        ["一度[いちど]", "いちど", "ichido", "once, one time", "adverb"],
        ["何度[なんど]も", "なんども", "nandomo", "many times", "adverb"],
        ["経験[けいけん]", "けいけん", "keiken", "experience", "noun"],
        ["登[のぼ]ります", "のぼります", "noborimasu", "to climb", "verb・godan"],
        ["着物[きもの]", "きもの", "kimono", "kimono", "noun"],
        ["着[き]ます", "きます", "kimasu", "to wear, put on", "verb・ichidan"],
        ["抹茶[まっちゃ]", "まっちゃ", "matcha", "matcha, powdered green tea", "noun"],
        ["スキー", "すきー", "sukii", "skiing", "noun"],
        ["温泉[おんせん]旅館[りょかん]", "おんせんりょかん", "onsen ryokan", "hot-spring inn", "noun"],
        ["外国人[がいこくじん]", "がいこくじん", "gaikokujin", "foreigner", "noun"],
      ],
      exercises: [
        { t: "build", en: "I have been to Japan.", tokens: ["日本", "に", "行った", "こと", "が", "あります"], extra: ["行きました", "を"],
          why: "た-form + ことがあります: the experience exists in your life-log. 行きました alone would just report a specific past trip." },
        { t: "mc", q: "“Have you ever eaten sushi?” is…",
          choices: ["寿司を食べたことがありますか", "寿司を食べましたか", "寿司を食べることができますか", "寿司はありますか"], a: 0,
          why: "Experience-perfect → 食べたことがありますか. (Option 2 asks about a specific occasion — “did you eat the sushi?” Who ate the sushi? An investigation.)" },
        { t: "mc", q: "{{一度だけ着物を着たことがあります}} means…",
          choices: ["I've worn a kimono just once", "I always wear kimono", "I wore a kimono yesterday", "I want to wear a kimono"], a: 0,
          why: "一度だけ (only once) + experience pattern. 着る (wear) is ichidan — and yes, it sounds exactly like 来る's ます-stem; kanji and context referee." },
        { t: "build", en: "On weekends I read books, listen to music, that sort of thing.",
          tokens: ["週末", "は", "本", "を", "読んだり", "音楽", "を", "聞いたり", "します"], extra: ["読んで", "聞きます"],
          why: "たり…たり + final する carrying the habit tense. The loose weekend, loosely listed." },
        { t: "mc", q: "Pick the correct close for: 京都でお寺を見たり、抹茶を飲んだり＿＿。(that trip, last spring)",
          choices: ["しました", "します", "です", "ありました"], a: 0,
          why: "The final する carries ALL the tense — past trip → しました. The たり's stay timeless; the する time-stamps." },
        { t: "type", q: "Confess: “I have never climbed Mt Fuji.” (登る)",
          accept: ["富士山に登ったことがありません", "ふじさんにのぼったことがありません", "富士山に登ったことはありません"],
          show: "富士山[ふじさん]に登[のぼ]ったことがありません。",
          why: "Negative experience: ことがありません. Japanese proverb: climb it once, wise; twice, a fool. Zero, so far: efficient." },
      ],
    },
    {
      id: "11.4",
      title: "Already and Not Yet — もう・まだ",
      sub: "the trap answer 「まだ食べていません」, and durations with 〜間",
      briefing: [
        ["h", "もう — already / anymore"],
        ["p", "{{もう}} + past = already done: {{もう昼ご飯を食べました}} “I've already had lunch.” {{もう}} + negative = not anymore: {{もう飲みません}} “I don't drink anymore.” The word itself just marks the threshold crossed."],
        ["h", "まだ — still / not yet, and THE trap"],
        ["p", "{{まだ}} + affirmative = still: {{まだ働いています}} “still working.” Not-yet is where English speakers crash: “I haven't eaten yet” is {{まだ食べていません}} — the **ていません** form, NOT 食べませんでした. Why: ませんでした closes the case (“I didn't eat, the end”); ていません keeps it open (“the eating hasn't happened *so far*”). まだ demands the open case."],
        ["ex", [
          ["もう宿題[しゅくだい]をしましたか。", "もうしゅくだいをしましたか", "Have you done the homework already?"],
          ["いいえ、まだしていません。", "いいえ、まだしていません", "No, not yet.", "open case — the homework's fate undecided"],
          ["まだ雨[あめ]が降[ふ]っていますか。", "まだあめがふっていますか", "Is it still raining?"],
        ]],
        ["h", "Durations: 〜間 and どのぐらい"],
        ["p", "{{間}} (かん) turns units into spans: 一時間 an hour, 三日間 three days, 二週間 two weeks, 一年間 a year. Ask with {{どのぐらい}}: {{どのぐらい日本語を勉強していますか}} — “how long have you been studying Japanese?” And the answer deploys the continuing-state ています:"],
        ["ex", [
          ["一年間[いちねんかん]、日本語[にほんご]を勉強[べんきょう]しています。", "いちねんかん、にほんごをべんきょうしています", "I've been studying Japanese for a year.", "sound familiar? keep going."],
        ]],
        ["note", "まだまだです — “still still” — is the modest reply to compliments on your Japanese (week 4's protocol, upgraded). It means “long way to go”, said while being objectively further along than last month. Use it; earn it; secretly disagree with it."],
      ],
      vocab: [
        ["もう", "もう", "mou", "already; anymore", "adverb"],
        ["まだ", "まだ", "mada", "still; not yet", "adverb"],
        ["〜年間[ねんかん]", "ねんかん", "-nenkan", "(span of) years", "counter"],
        ["〜週間[しゅうかん]", "しゅうかん", "-shuukan", "(span of) weeks", "counter"],
        ["どのぐらい", "どのぐらい", "dono gurai", "how long, how much", "question"],
        ["ずっと", "ずっと", "zutto", "the whole time, all along", "adverb"],
        ["最近[さいきん]", "さいきん", "saikin", "recently", "adverb"],
        ["昔[むかし]", "むかし", "mukashi", "long ago, old times", "noun"],
        ["初[はじ]めて", "はじめて", "hajimete", "for the first time", "adverb"],
        ["久[ひさ]しぶり", "ひさしぶり", "hisashiburi", "(it's been) a long time", "expression"],
        ["宿題[しゅくだい]", "しゅくだい", "shukudai", "homework", "noun"],
      ],
      exercises: [
        { t: "mc", q: "「もう昼ご飯を食べましたか」— you haven't. THE correct reply:",
          choices: ["いいえ、まだ食べていません", "いいえ、まだ食べませんでした", "いいえ、食べたことがありません", "いいえ、もう食べました"], a: 0,
          why: "Not-yet keeps the case OPEN: ていません. ませんでした closes it (“lunch: cancelled”). This is the week's crown-jewel correction — Duolingo marks it, never explains it." },
        { t: "mc", q: "{{もうビールを飲みません}} means…",
          choices: ["I don't drink beer anymore", "I haven't drunk beer yet", "I already drank beer", "More beer, please"], a: 0,
          why: "もう + negative = not anymore; a threshold crossed in the other direction. (One January in every drinker's life.)" },
        { t: "build", en: "I have been studying Japanese for one year.",
          tokens: ["一年間", "日本語", "を", "勉強して", "います"], extra: ["勉強しました", "まだ"],
          why: "Duration 一年間 (no particle) + continuing-state ています. This sentence is biographically yours — say it in the mirror." },
        { t: "mc", q: "{{まだ働いています}} means…",
          choices: ["(I'm) still working", "(I) haven't worked yet", "(I) don't work anymore", "(I) just started working"], a: 0,
          why: "まだ + affirmative = still. The salaryman's 10 p.m. text message." },
        { t: "type", q: "Greet a friend you haven't seen in months:",
          accept: ["久しぶり", "ひさしぶり", "お久しぶりです", "おひさしぶりです", "久しぶりです"],
          show: "久[ひさ]しぶり！",
          why: "久しぶり — “it's been ages!” Add お…です for politeness. Standard reply: 久しぶり！元気だった？" },
        { t: "mc", q: "Ask how long they've lived in Edinburgh:",
          choices: ["どのぐらいエディンバラに住んでいますか", "いつエディンバラに住みますか", "エディンバラはどこですか", "何時にエディンバラですか"], a: 0,
          why: "どのぐらい + continuing-state 住んでいます. Answer shape: 五年間住んでいます — duration + ています, the pattern of settled lives." },
      ],
    },
    {
      id: "11.5",
      review: true,
      title: "Mission Review 11",
      sub: "vectors of giving, favours, experience, already/not-yet — exchange complete",
      briefing: [
        ["h", "Debrief: the diplomatic pouch, sealed"],
        ["ul", [
          "**あげる／くれる／もらう** — outward / inward / receiving; the vector IS the feeling.",
          "**〜てくれる・てもらう** put gratitude inside the verb; **てあげる** punches down politely — offer with ましょうか instead.",
          "**〜たことがあります** — the life-log perfect; answers はい、あります／いいえ、ありません.",
          "**〜たり〜たりする** — loose lists; final する carries tense.",
          "**もう／まだ** — and the crown jewel: まだ〜ていません, the open case.",
        ]],
        ["p", "One mission remains. The computer has begun rationing its remaining commendations. Simulation begins."],
      ],
      vocab: [],
      exercises: [
        { t: "mc", q: "Pick the verb: 姉が漢字を教えて＿＿。(my sister kindly taught me)",
          choices: ["くれました", "あげました", "もらいました", "しまいました"], a: 0,
          why: "Inward favour, giver が → てくれました. The gratitude is grammatical." },
        { t: "build", en: "Have you ever ridden the bullet train?", tokens: ["新幹線", "に", "乗った", "こと", "が", "あります", "か"], extra: ["乗りました", "を"],
          why: "乗る takes に; experience takes たことがあります. Answer, ideally: はい、何度もあります." },
        { t: "mc", q: "「もう予約しましたか」— not yet! Reply:",
          choices: ["まだしていません", "まだしませんでした", "もうしません", "したことがありません"], a: 0,
          why: "Open case: まだ + ていません. The booking's fate remains undecided — closing it with ませんでした would cancel the trip." },
        { t: "type", q: "Say: “I received a present from a friend.” (もらう)",
          accept: ["友達にプレゼントをもらいました", "ともだちにぷれぜんとをもらいました", "友達からプレゼントをもらいました", "ともだちからぷれぜんとをもらいました"],
          show: "友達[ともだち]にプレゼントをもらいました。",
          why: "Receiver-cam: source に/から + もらいました. Warmth vectored correctly." },
        { t: "mc", q: "Describe a loose Kyoto day: temples, matcha, that sort of thing.",
          choices: ["お寺を見たり、抹茶を飲んだりしました", "お寺を見て、抹茶を飲みました", "お寺と抹茶がありました", "お寺は抹茶より好きです"], a: 0,
          why: "たり…たりしました = a sample of the day. (Option 2 is fine Japanese but implies the complete itinerary — と vs や, for verbs.)" },
      ],
    },
  ],
});

/* ================= WEEK 12 — THE KOBAYASHI PROTOCOL ================= */
DK.week({
  n: 12,
  name: "THE KOBAYASHI PROTOCOL",
  brief: "Stardate 79546.9. The final mission: conditionals — Japanese has four ways to say “if” — a survival kit of honorific language, and a diplomatic reception in Kyoto where everything you've learned gets used at once. There are always possibilities. Engage.",
  lessons: [
    {
      id: "12.1",
      title: "If and When — たら and と",
      sub: "the workhorse conditional, and the one for laws of nature",
      briefing: [
        ["h", "たら — the universal “if/when”"],
        ["p", "Take the plain past た, add {{ら}}: 行った→{{行ったら}}, 安い→{{安かったら}}, 雨だ→{{雨だったら}}. Meaning: “if/once X happens, then…”. It's the **workhorse** — when in doubt, たら is almost never wrong:"],
        ["ex", [
          ["京都[きょうと]に着[つ]いたら、連絡[れんらく]してください。", "きょうとについたら、れんらくしてください", "When you arrive in Kyoto, please get in touch."],
          ["雨[あめ]が降[ふ]ったら、家[いえ]で映画[えいが]を見[み]ましょう。", "あめがふったら、いえでえいがをみましょう", "If it rains, let's watch a film at home."],
          ["安[やす]かったら、買[か]います。", "やすかったら、かいます", "If it's cheap, I'll buy it."],
        ]],
        ["p", "The た inside is the same “as-if-done” aspect from week 10's advice: the condition is *imagined complete*, then the consequence follows. {{もし}} at the front flags a hypothetical early — もし雨が降ったら… — useful in long sentences, never required."],
        ["h", "と — the law of nature"],
        ["p", "Dictionary form + {{と}} = “whenever X, inevitably Y”. It's for machinery, nature, and directions — things with no free will involved:"],
        ["ex", [
          ["ボタンを押[お]すと、ドアが開[あ]きます。", "ぼたんをおすと、どあがあきます", "Press the button and the door opens.", "starship-approved"],
          ["春[はる]になると、桜[さくら]が咲[さ]きます。", "はるになると、さくらがさきます", "When spring comes, the cherries bloom."],
        ]],
        ["p", "Because と states inevitability, the result **can't be a request, command or invitation** — no ください, ましょう, or たい after it. Laws of nature don't take suggestions. For those, たら."],
        ["note", "開きます above is あきます — the door opens (itself). You met the self/other pairs in week 7: 開く/開ける, 始まる/始める. The starship doors of Japan あきます automatically and say nothing; the ones on the Enterprise add a shhhk. Progress is debatable."],
      ],
      vocab: [
        ["もし", "もし", "moshi", "if (hypothetical flag)", "adverb"],
        ["押[お]します", "おします", "oshimasu", "to push, press", "verb・godan"],
        ["ボタン", "ぼたん", "botan", "button", "noun"],
        ["開[あ]きます", "あきます", "akimasu", "to open (itself)", "verb・godan"],
        ["着[つ]きます", "つきます", "tsukimasu", "to arrive", "verb・godan"],
        ["咲[さ]きます", "さきます", "sakimasu", "to bloom", "verb・godan"],
        ["困[こま]ります", "こまります", "komarimasu", "to be in trouble", "verb・godan"],
        ["遅[おく]れます", "おくれます", "okuremasu", "to be late", "verb・ichidan"],
        ["連絡[れんらく]", "れんらく", "renraku", "contact, getting in touch", "noun"],
        ["問[と]題[だい]ありません", "もんだいありません", "mondai arimasen", "no problem", "expression"],
      ],
      exercises: [
        { t: "build", en: "When you arrive in Kyoto, please contact me.", tokens: ["京都", "に", "着いたら", "連絡", "して", "ください"], extra: ["着くと", "着いて"],
          why: "Request in the result → must be たら, never と. 着いた + ら: the arrival imagined complete, the favour following." },
        { t: "mc", q: "Pick the conditional: ボタンを＿＿、ドアが開きます。(mechanism)",
          choices: ["押すと", "押したら", "押せば", "押して"], a: 0,
          why: "Machinery = inevitability = と. (押したら isn't wrong, but と is the native voice of buttons, seasons and timetables.)" },
        { t: "mc", q: "Which sentence is BROKEN?",
          choices: ["春になると、花見をしましょう", "春になったら、花見をしましょう", "春になると、桜が咲きます", "もし雨が降ったら、行きません"], a: 0,
          why: "と cannot end in an invitation — laws of nature don't take suggestions. Swap to たら and the hanami is back on." },
        { t: "mc", q: "{{電車に遅れたら、困ります}} means…",
          choices: ["If I miss the train, I'm in trouble", "The train is often late", "I was late, so trouble came", "Slow trains bother me"], a: 0,
          why: "遅れたら (if late-for) + 困ります (be stuck/troubled) — the traveller's conditional. Preventive medicine: 早く出発しましょう." },
        { t: "type", q: "Say: “If it's cheap, I'll buy it.” (bargain-hunter's creed)",
          accept: ["安かったら買います", "やすかったらかいます", "安かったら、買います"],
          show: "安[やす]かったら、買[か]います。",
          why: "い-adjective conditional: 安い→安かった→安かったら. The adjective machinery's final form." },
        { t: "mc", q: "{{もし}} at the start of a conditional…",
          choices: ["flags “hypothetical incoming” early — optional but kind to listeners", "is required by law", "makes it past tense", "negates the sentence"], a: 0,
          why: "もし is a courtesy beacon for long sentences — the listener buffers correctly from word one. Japanese syntax, ever considerate of its audience." },
      ],
    },
    {
      id: "12.2",
      title: "ば and なら — The Full Conditional Chart",
      sub: "four ifs, one table — and which one to actually use",
      briefing: [
        ["h", "ば — the logical if"],
        ["p", "The classic textbook conditional: godan -u → -e + ば ({{行けば}}), ichidan る → れば ({{食べれば}}), い-adjectives い → ければ ({{安ければ}}), and negatives ない → なければ — which you already own from なければなりません! It states pure logic: “if X holds, Y follows”, with a scholarly flavour: {{練習すれば、上手になります}} — practise and you'll improve."],
        ["h", "なら — the “in that case” conditional"],
        ["p", "{{なら}} takes a **topic someone raised** and runs with it: 「日本に行きます」「日本に行く{{なら}}、京都がいいですよ」 — “If it's Japan you're going to, Kyoto's the place.” なら doesn't wait for the condition to happen — it responds to *information on the table*. It's the conditional of advice and retorts."],
        ["h", "The chart"],
        ["table", ["Form", "Flavour", "At home in…"], [
          ["たら", "if/once, sequential", "everything — the workhorse"],
          ["と", "inevitably, whenever", "machines, nature, directions"],
          ["ば", "pure logic, proverbs", "advice, general truths"],
          ["なら", "“in that case…”", "responding to what was said"],
        ]],
        ["ex", [
          ["質問[しつもん]があれば、聞[き]いてください。", "しつもんがあれば、きいてください", "If you have questions, please ask."],
          ["時間[じかん]がなければ、明日[あした]でもいいですよ。", "じかんがなければ、あしたでもいいですよ", "If you haven't time, tomorrow's fine too."],
          ["スカイリムなら、300時間[じかん]遊[あそ]んだことがあります。", "すかいりむなら、さんびゃくじかんあそんだことがあります", "If we're talking Skyrim — I have 300 hours in it.", "なら, the gamer's conditional"],
        ]],
        ["p", "Overlap is real: many sentences accept two or three of the four. The exam-grade distinctions matter less than the reflexes: **workhorse たら, machine と, proverb ば, retort なら.** Say them in that order three times and the chart is yours."],
        ["note", "頑張れば、できます。 — if you keep at it, you can do it. Grammar and pep talk, one sentence. The ば-conditional of this entire course."],
      ],
      vocab: [
        ["質問[しつもん]", "しつもん", "shitsumon", "question", "noun"],
        ["相談[そうだん]", "そうだん", "soudan", "consultation, advice-seeking", "noun"],
        ["練習[れんしゅう]", "れんしゅう", "renshuu", "practice", "noun"],
        ["試験[しけん]", "しけん", "shiken", "exam, test", "noun"],
        ["合格[ごうかく]", "ごうかく", "goukaku", "passing (an exam)", "noun"],
        ["失敗[しっぱい]", "しっぱい", "shippai", "failure, mistake", "noun"],
        ["心配[しんぱい]", "しんぱい", "shinpai", "worry", "noun"],
        ["気[き]をつけます", "きをつけます", "ki o tsukemasu", "to be careful", "expression"],
        ["無理[むり]", "むり", "muri", "impossible, overdoing it", "な-adj"],
        ["大丈夫[だいじょうぶ]", "だいじょうぶ", "daijoubu", "OK, fine", "な-adj"],
      ],
      exercises: [
        { t: "mc", q: "ば-form of {{行く}}:", choices: ["行けば", "行くば", "行かば", "行けれど"], a: 0,
          why: "Godan: -u → -e + ば. 行けば分かります — go and you'll see." },
        { t: "mc", q: "ば-form of {{安い}}:", choices: ["安ければ", "安いば", "安ずれば", "安かろうば"], a: 0,
          why: "い-adjectives: い → ければ. 安ければ買います — the bargain-hunter's creed, now in scholarly register." },
        { t: "mc", q: "「京都に行きます！」 — respond with advice. Which conditional?",
          choices: ["京都に行くなら、秋がいいですよ", "京都に行くと、秋がいいですよ", "京都に行けば、秋でした", "京都に行ったら、秋です"], a: 0,
          why: "Information on the table → なら, the “in that case” conditional. You're not waiting for the trip to happen; you're riffing on the news." },
        { t: "build", en: "If you have questions, please ask.", tokens: ["質問", "が", "あれば", "聞いて", "ください"], extra: ["あると", "ある"],
          why: "ある→あれば. (あったら also fine — workhorse forever — but today's drill rides the scholarly ば.)" },
        { t: "type", q: "Deliver the course's pep talk: “If you keep at it, you can do it.” (頑張れば…)",
          accept: ["頑張ればできます", "がんばればできます", "頑張れば、できます"],
          show: "頑張[がんば]れば、できます。",
          why: "頑張る→頑張れば + できる (する's potential). Twelve weeks of evidence say the sentence is true." },
        { t: "mc", q: "Match the reflex: workhorse / machine / proverb / retort =",
          choices: ["たら・と・ば・なら", "と・たら・なら・ば", "ば・なら・たら・と", "なら・ば・と・たら"], a: 0,
          why: "たら (workhorse), と (machine), ば (proverb), なら (retort). The four ifs, filed for life." },
      ],
    },
    {
      id: "12.3",
      title: "Tea. Earl Grey. Hot. — Keigo Survival Kit",
      sub: "the politeness stack: ordering, thanking, and the captain's beverage protocol",
      briefing: [
        ["h", "The three levels, from orbit"],
        ["p", "Japanese politeness has three broad bands: **casual** (plain forms, week 6), **polite** (です/ます — your home base), and **keigo** — the honorific system that lifts *others* up ({{尊敬語}}) and lowers *yourself* ({{謙譲語}}). Full keigo takes years; the survival kit takes one lesson, and it's this one."],
        ["h", "The phrases that run every shop in Japan"],
        ["table", ["You'll hear", "It means", "You say back"], [
          ["いらっしゃいませ！", "welcome! (honorific)", "(nothing — a nod suffices)"],
          ["〜でございます", "super-polite です", "(just parse it)"],
          ["少々お待ちください", "please wait a moment", "はい"],
          ["ありがとうございました", "thank you (completed favour)", "どうも / a nod"],
        ]],
        ["h", "お願いします — the diplomatic を+ください"],
        ["p", "{{〜をお願いします}} (“I request…”) outranks 〜をください in polish: {{紅茶をお願いします}}. Specify with で: {{ホットでお願いします}} “hot, please” (iced coffee culture makes this a REAL daily question in Japan). Which assembles the captain's order:"],
        ["ex", [
          ["紅茶[こうちゃ]をお願[ねが]いします。アールグレイを。ホットで。", "こうちゃをおねがいします。あーるぐれいを。ほっとで。", "Tea, please. Earl Grey. Hot.", "Picard-protocol, Kyoto-certified ☕"],
        ]],
        ["p", "Fragmented follow-ups (アールグレイを。ホットで。) are perfectly natural spoken Japanese — the particles carry the grammar even without full sentences. The replicator — that is, the barista — will comply."],
        ["h", "The meal frame"],
        ["p", "{{いただきます}} before eating (humbly-receive — grace, gratitude and physics in one word) and {{ごちそうさまでした}} after (it-was-a-feast). Bracket every meal with them; they are the two most reliably appreciated words a visitor says."],
        ["note", "すみません is the Swiss Army knife: excuse-me, sorry, AND thank-you-for-troubling-yourself. Waving a server over: すみません！ Receiving a favour: すみません (= thanks, you shouldn't have). When in doubt in Japan, すみません — the diplomatic universal solvent."],
      ],
      vocab: [
        ["お願[ねが]いします", "おねがいします", "onegai shimasu", "please (I request)", "expression"],
        ["いらっしゃいませ", "いらっしゃいませ", "irasshaimase", "welcome (to the shop)", "expression"],
        ["いただきます", "いただきます", "itadakimasu", "(said before eating)", "expression"],
        ["ごちそうさまでした", "ごちそうさまでした", "gochisousama deshita", "(said after eating)", "expression"],
        ["すみません", "すみません", "sumimasen", "excuse me; sorry; thanks", "expression"],
        ["失礼[しつれい]します", "しつれいします", "shitsurei shimasu", "pardon the intrusion", "expression"],
        ["お客様[きゃくさま]", "おきゃくさま", "okyakusama", "customer, guest (honorific)", "noun"],
        ["店員[てんいん]", "てんいん", "ten'in", "shop staff", "noun"],
        ["注文[ちゅうもん]", "ちゅうもん", "chuumon", "order (food/goods)", "noun"],
        ["ホット", "ほっと", "hotto", "hot (drink)", "noun"],
        ["アールグレイ", "あーるぐれい", "aaru gurei", "Earl Grey", "noun"],
      ],
      exercises: [
        { t: "build", en: "Tea, please. (the diplomatic order)", tokens: ["紅茶", "を", "お願いします"], extra: ["ください", "が"],
          why: "をお願いします — ください's polished sibling. The foundation of the captain's protocol." },
        { t: "mc", q: "Now complete the protocol. “Hot, please” is…",
          choices: ["ホットでお願いします", "ホットをお願いします", "ホットはお願いします", "ホットにください"], a: 0,
          why: "The specification rides で (means/manner — week 3's particle, final cameo): served-as-hot. 紅茶を。アールグレイを。ホットで。 Make it so. ☕🖖" },
        { t: "mc", q: "You step into a shop. {{いらっしゃいませ！}} rings out. You…",
          choices: ["nod, or say nothing — it needs no reply", "shout いらっしゃいませ back", "apologise and leave", "order immediately"], a: 0,
          why: "It's a ritual welcome, not a question. Returning it would startle the staff into legend. A nod is fluent." },
        { t: "type", q: "Before eating, say the word:",
          accept: ["いただきます"],
          show: "いただきます。",
          why: "Humbly-I-receive: grace, thanks to the cook, the farmer, and the fish. Hands together optional; sincerity standard." },
        { t: "mc", q: "The server clears your plates. The closing formula:",
          choices: ["ごちそうさまでした", "いただきます", "いらっしゃいませ", "お腹が空いた"], a: 0,
          why: "ごちそうさまでした — “that was a feast.” Bracket closed. (Option 4 would restart the entire meal.)" },
        { t: "mc", q: "すみません can mean…",
          choices: ["excuse me, sorry, AND thank you — all three", "only sorry", "only excuse me", "goodbye"], a: 0,
          why: "The universal solvent. Called across a restaurant: excuse me. After treading on a foot: sorry. Receiving held-open doors: thanks-for-the-trouble. One word, whole toolkit." },
        { t: "mc", q: "{{少々お待ちください}} from a shop assistant means…",
          choices: ["Please wait a moment (very politely)", "Please leave", "We're closed", "Pay here"], a: 0,
          why: "少々 (a little) + お待ちください (honorific 待ってください). They're fetching your Earl Grey. Diplomacy holds." },
      ],
    },
    {
      id: "12.4",
      title: "Final Mission — The Kyoto Reception",
      sub: "a diplomatic evening, conducted entirely in what you now know",
      briefing: [
        ["h", "Mission briefing"],
        ["p", "A Federation delegation attends a reception at a Kyoto teahouse. You are the interpreter — the universal translator stays off. Read the scene; every line is built from your twelve weeks. The simulation will then debrief you on it."],
        ["h", "Scene one: arrival"],
        ["ex", [
          ["いらっしゃいませ。お名前[なまえ]をお願[ねが]いします。", "", "Welcome. Your name, please."],
          ["ピカードです。七時[しちじ]に予約[よやく]しました。", "", "Picard. I reserved for seven o'clock."],
          ["ピカード様[さま]ですね。少々[しょうしょう]お待[ま]ちください。", "", "Mr Picard, yes. One moment, please."],
        ]],
        ["h", "Scene two: the toast"],
        ["ex", [
          ["今日[きょう]は来[き]てくれて、ありがとうございます。", "", "Thank you for coming today.", "てくれて — the favour vector, in the wild"],
          ["平和[へいわ]と友情[ゆうじょう]のために、乾杯[かんぱい]しましょう！", "", "To peace and friendship — a toast!"],
          ["乾杯[かんぱい]！", "", "Cheers!"],
        ]],
        ["h", "Scene three: the conversation"],
        ["ex", [
          ["日本語[にほんご]が上手[じょうず]ですね。どのぐらい勉強[べんきょう]していますか。", "", "Your Japanese is good! How long have you been studying?"],
          ["三[さん]か月[げつ]ぐらいです。でも、まだまだです。", "", "About three months. But I've a long way to go.", "the modesty protocol, executed flawlessly"],
          ["三[さん]か月[げつ]！すごいですね。どうやって勉強[べんきょう]しましたか。", "", "Three months?! Amazing. How did you study?"],
          ["宇宙船[うちゅうせん]のコンピューターで勉強[べんきょう]しました。毎日[まいにち]練習[れんしゅう]すれば、できますよ。", "", "I studied on a starship's computer. Practise every day and you can do it."],
        ]],
        ["h", "Scene four: departure"],
        ["ex", [
          ["もう遅[おそ]いので、失礼[しつれい]します。今日[きょう]は本当[ほんとう]にありがとうございました。", "", "It's late, so I'll take my leave. Thank you so much for today."],
          ["こちらこそ。また京都[きょうと]に来[き]たら、ぜひ連絡[れんらく]してください。", "", "The pleasure was ours. When you're next in Kyoto, do get in touch."],
        ]],
        ["p", "Read it twice. Speak the lines aloud with the ▶ buttons. Then enter the simulation — the debriefing questions all point back at this scene."],
      ],
      vocab: [
        ["平和[へいわ]", "へいわ", "heiwa", "peace", "noun"],
        ["友情[ゆうじょう]", "ゆうじょう", "yuujou", "friendship", "noun"],
        ["乾杯[かんぱい]", "かんぱい", "kanpai", "a toast; cheers!", "noun"],
        ["挨拶[あいさつ]", "あいさつ", "aisatsu", "greeting", "noun"],
        ["通訳[つうやく]", "つうやく", "tsuuyaku", "interpreter", "noun"],
        ["大使[たいし]", "たいし", "taishi", "ambassador", "noun"],
        ["成功[せいこう]", "せいこう", "seikou", "success", "noun"],
        ["〜か月[げつ]", "かげつ", "-kagetsu", "(span of) months", "counter"],
        ["どうやって", "どうやって", "dou yatte", "how, by what means", "question"],
        ["こちらこそ", "こちらこそ", "kochira koso", "likewise; the pleasure's mine", "expression"],
      ],
      exercises: [
        { t: "mc", q: "The receptionist says {{少々お待ちください}}. Picard should…",
          choices: ["wait a moment", "follow her immediately", "repeat his name", "remove his shoes"], a: 0,
          why: "Honorific “please wait” — as decoded in the survival kit. (Shoes may ALSO come off shortly; this is a teahouse.)" },
        { t: "mc", q: "{{今日は来てくれて、ありがとうございます}} — why てくれて?",
          choices: ["The guests' coming was a favour TO the host — inward vector, gratitude encoded", "It marks past tense", "It's a conditional", "It's the potential form"], a: 0,
          why: "Week 11 in the wild: 来てくれる = came-for-my-benefit. Stacked with ありがとう it's the standard warm thanks-for-coming." },
        { t: "build", en: "Let's toast to peace and friendship!", tokens: ["平和", "と", "友情", "の", "ため", "に", "乾杯", "しましょう"], extra: ["を", "たら"],
          why: "〜のために = for the sake of (a parting gift of a pattern); 乾杯しましょう from the invitation engine of week 8." },
        { t: "mc", q: "Asked どのぐらい勉強していますか, the interpreter replies 三か月ぐらいです。でも、まだまだです。 The まだまだ is…",
          choices: ["the modesty protocol — “long way to go” (while being excellent)", "a complaint about the food", "a request to leave", "the name of a tea"], a: 0,
          why: "Week 11's まだまだです, deployed at the perfect moment. The reception audibly approves. すごいですね follows on cue." },
        { t: "mc", q: "{{毎日練習すれば、できますよ}} — the grammar and the message:",
          choices: ["ば-conditional: practise daily and you can do it — the course's thesis", "と-conditional: nature's law of tea", "たら: once you practised, you could", "volitional: let's practise"], a: 0,
          why: "練習すれば (する→すれば) + できます (potential). The proverb conditional carrying the truest sentence in this app." },
        { t: "type", q: "Return the host's warmth: “Likewise!” (one word)",
          accept: ["こちらこそ"],
          show: "こちらこそ。",
          why: "“It is THIS side (that should thank you)” — gratitude, reflected with a bow. The conversation closes in balance." },
        { t: "mc", q: "{{また京都に来たら、ぜひ連絡してください}} — parse the send-off:",
          choices: ["When you next come to Kyoto, do please get in touch", "Don't come back to Kyoto without permission", "Kyoto will contact you", "If you call, Kyoto comes"], a: 0,
          why: "来たら (workhorse conditional) + ぜひ (by all means, week 8) + 連絡してください (week 12.1). Three missions, one warm goodbye." },
      ],
    },
    {
      id: "12.5",
      review: true,
      title: "Graduation — The Kobayashi Protocol",
      sub: "the no-win scenario was learning a language from an owl. you changed the conditions.",
      briefing: [
        ["h", "Final debrief"],
        ["ul", [
          "**Conditionals**: workhorse たら, machine と, proverb ば, retort なら.",
          "**Keigo survival kit**: お願いします、いらっしゃいませ、いただきます、ごちそうさまでした、すみません — and the captain's beverage protocol.",
          "**The Kyoto reception**: every week of this course, live-fired in one evening.",
        ]],
        ["h", "Twelve weeks, logged"],
        ["p", "You can now: build any polite or plain verb form; wield twenty particles with intent; conjugate two tribes of adjectives; count dragons; tell time; want, invite, intend, and purpose; think and quote; hang whole clauses off nouns; reason with から and ので; enable with the potential; obligate with double negatives; advise with bedside manner; vector gifts and favours; log experience; and order tea with the precision of a starship captain."],
        ["p", "**認[みと]めよう。君[きみ]はもう初心者[しょしんしゃ]ではない。** — Face it: you're not a beginner anymore."],
        ["p", "Your drill deck keeps every word on rotation — the tour ends; the reviews continue. And somewhere past this course lie the JLPT N4, ten thousand kanji stories, and every episode of Star Trek dubbed into Japanese, where 「そうしよう」 awaits your trained ear."],
        ["tip", "The final simulation samples the whole course. No pressure: rank is earned, never lost. There are always possibilities. — 参[まい]りましょう。Engage."],
      ],
      vocab: [],
      exercises: [
        { t: "mc", q: "Week 1, forever: 誰＿艦長ですか。",
          choices: ["が", "は", "を", "の"], a: 0,
          why: "Question words never take は. The first reflex of the course — still true at the end of it." },
        { t: "mc", q: "Week 5's machine: {{飲む}} → te-form →",
          choices: ["飲んで", "飲みて", "飲って", "飲て"], a: 0,
          why: "む→んで. The warp core still hums." },
        { t: "build", en: "I think I want to go to Japan next year.", tokens: ["来年", "日本", "に", "行きたい", "と", "思います"], extra: ["行きます", "だ"],
          why: "たい (い-adjective, connects bare) + と思います. Wanting, thinking, and planning — weeks 8 and 9, holding hands." },
        { t: "type", q: "One last time, with feeling — the captain's order:",
          accept: ["紅茶をお願いします", "こうちゃをおねがいします", "紅茶をください"],
          show: "紅茶[こうちゃ]をお願[ねが]いします。アールグレイを。ホットで。",
          why: "Tea. Earl Grey. Hot. Course complete, Captain. ☕🖖" },
        { t: "mc", q: "{{毎日練習すれば、できます}} — do you believe it now?",
          choices: ["はい、そう思います", "いいえ、無理です", "まだ食べていません", "ドラゴンが三匹います"], a: 0,
          why: "そう思います — and the evidence agrees. (The other options are, respectively: defeatism, an unfinished lunch, and three dragons. All grammatical. One correct.) 🖖" },
      ],
    },
  ],
});
