/* ============================================================
   DARMOK curriculum — Weeks 4–6
   ============================================================ */

/* ================= WEEK 4 — SENSOR CALIBRATION ================= */
DK.week({
  n: 4,
  name: "SENSOR CALIBRATION",
  brief: "Stardate 79526.2. A report that says only “there is a planet” is useless — is it big, hot, beautiful, dangerous? This week the sensors come online: Japanese adjectives, their two tribes, comparisons, and how to declare what you like (and what you're brilliant at).",
  lessons: [
    {
      id: "4.1",
      title: "い-Adjectives — Words That Conjugate",
      sub: "adjectives with an engine inside: 高い・高くない・高かった・高くなかった",
      briefing: [
        ["h", "Japanese adjectives DO things"],
        ["p", "The strangest, most wonderful fact in this course: Japanese adjectives **conjugate like verbs**. An い-adjective carries its own tense and polarity. 高い doesn't just mean “expensive” — it means “IS expensive”, a complete predicate."],
        ["table", ["Form", "高い (expensive)", "Meaning"], [
          ["present", "高いです", "is expensive"],
          ["negative", "高くないです", "isn't expensive"],
          ["past", "高かったです", "was expensive"],
          ["past negative", "高くなかったです", "wasn't expensive"],
        ]],
        ["p", "The machine: chop the final {{い}}, attach {{くない}} / {{かった}} / {{くなかった}}. **です here is only politeness polish — the adjective itself carries the tense.** That's why it's 高かったです and never 高いでした. Duolingo corrects that mistake silently; now you know the reason: the past already happened inside the adjective."],
        ["ex", [
          ["この店[みせ]は高[たか]いです。", "このみせはたかいです", "This shop is expensive."],
          ["昨日[きのう]の映画[えいが]は面白[おもしろ]かったです。", "きのうのえいがはおもしろかったです", "Yesterday's film was interesting."],
          ["テストは難[むずか]しくなかったです。", "てすとはむずかしくなかったです", "The test wasn't hard."],
        ]],
        ["h", "Before a noun: no glue needed"],
        ["p", "い-adjectives sit straight in front of nouns: {{高い店}} “an expensive shop”, {{面白い本}} “an interesting book”. No particle, no の — they were born to do this."],
        ["h", "The いい rebellion"],
        ["p", "{{いい}} (good) is the one troublemaker: it conjugates from its older form {{よい}}. Good → よくない → よかった → よくなかった. {{よかった！}} on its own means “thank goodness!” — one of the most-heard words in Japan."],
        ["note", "Not everything ending in い is an い-adjective: きれい (pretty) and 有名 (famous) are な-adjectives wearing disguises. Tomorrow's lesson unmasks them."],
      ],
      vocab: [
        ["高[たか]い", "たかい", "takai", "expensive; tall", "い-adj"],
        ["安[やす]い", "やすい", "yasui", "cheap", "い-adj"],
        ["大[おお]きい", "おおきい", "ookii", "big", "い-adj"],
        ["小[ちい]さい", "ちいさい", "chiisai", "small", "い-adj"],
        ["新[あたら]しい", "あたらしい", "atarashii", "new", "い-adj"],
        ["古[ふる]い", "ふるい", "furui", "old (things)", "い-adj"],
        ["面白[おもしろ]い", "おもしろい", "omoshiroi", "interesting, funny", "い-adj"],
        ["難[むずか]しい", "むずかしい", "muzukashii", "difficult", "い-adj"],
        ["楽[たの]しい", "たのしい", "tanoshii", "fun, enjoyable", "い-adj"],
        ["速[はや]い", "はやい", "hayai", "fast", "い-adj"],
        ["いい", "いい", "ii", "good", "い-adj (irregular)"],
      ],
      exercises: [
        { t: "mc", q: "Make {{高い}} negative:",
          choices: ["高くないです", "高いじゃないです", "高くありました", "高いないです"], a: 0,
          why: "Chop い, add くない: 高くないです. じゃない belongs to nouns and な-adjectives — い-adjectives have their own machinery." },
        { t: "mc", q: "“The film WAS interesting” is…",
          choices: ["面白かったです", "面白いでした", "面白いだったです", "面白くです"], a: 0,
          why: "The adjective itself takes the past: 面白かった + polish です. 面白いでした is the classic error — you're now vaccinated." },
        { t: "mc", q: "Past tense of {{いい}} (good):",
          choices: ["よかった", "いかった", "いいでした", "よいです"], a: 0,
          why: "いい conjugates from よい: よかった. Alone, よかった！ = “thank goodness!” — say it when your luggage appears." },
        { t: "build", en: "This book is interesting.", tokens: ["この", "本", "は", "面白い", "です"], extra: ["これ", "が"],
          why: "この + noun (from week 1!), topic は, adjective + polish です." },
        { t: "type", q: "Say: “Japanese isn't difficult.” (manifest it)",
          accept: ["日本語は難しくないです", "にほんごはむずかしくないです"],
          show: "日本語[にほんご]は難[むずか]しくないです。",
          why: "難しい → 難しくない + です. Also accepted by the universe as an affirmation." },
        { t: "mc", q: "Which phrase is correct?",
          choices: ["新しい宇宙船", "新しいの宇宙船", "新しいな宇宙船", "宇宙船新しい"], a: 0,
          why: "い-adjectives connect straight to nouns — no glue: 新しい宇宙船, “a new starship”." },
        { t: "mc", q: "{{昨日は楽しかったです}} means…",
          choices: ["Yesterday was fun", "Yesterday will be fun", "Yesterday wasn't fun", "Make yesterday fun"], a: 0,
          why: "楽しい → 楽しかった (past inside the adjective) + です. A lovely text to send after seeing a friend." },
      ],
    },
    {
      id: "4.2",
      title: "な-Adjectives — The Other Tribe",
      sub: "静かな部屋 — adjectives that behave like nouns, plus the きれい trap",
      briefing: [
        ["h", "The second tribe"],
        ["p", "な-adjectives don't conjugate themselves — they borrow です's forms, exactly like nouns do. Where い-adjectives have an engine inside, な-adjectives ride the copula:"],
        ["table", ["Form", "静か (quiet)", "compare: noun 学生"], [
          ["present", "静かです", "学生です"],
          ["negative", "静かじゃないです", "学生じゃないです"],
          ["past", "静かでした", "学生でした"],
          ["past negative", "静かじゃなかったです", "学生じゃなかったです"],
        ]],
        ["h", "The な appears before nouns"],
        ["p", "The tribe's namesake: before a noun they need {{な}}. {{静かな部屋}} “a quiet room”, {{有名な人}} “a famous person”. Predicate position drops it: {{部屋は静かです}}. That's the entire grammar of the tribe."],
        ["ex", [
          ["京都[きょうと]は静[しず]かな町[まち]です。", "きょうとはしずかなまちです", "Kyoto is a quiet town."],
          ["この駅[えき]は便利[べんり]です。", "このえきはべんりです", "This station is convenient."],
          ["昨日[きのう]は暇[ひま]じゃなかったです。", "きのうはひまじゃなかったです", "I wasn't free yesterday."],
        ]],
        ["h", "The three famous impostors"],
        ["p", "{{きれい}} (pretty/clean), {{有名}} (famous — ゆうめ**い**), and {{嫌い}} (disliked) all *end in the sound い* but are **な-adjectives**. So: きれい**じゃない**です, never きれくない. If you learn one trap in all of Japanese, learn きれい — everyone falls in it exactly once. This is your once."],
        ["tip", "How to file new adjectives: if the dictionary shows it with な or it ends in something other than い, it's な-tribe. If it ends in い *in hiragana* (not just sound), it's usually い-tribe. きれい is written 綺麗 — the い is inside kanji, a clue it was never a real い-adjective."],
      ],
      vocab: [
        ["静[しず]か", "しずか", "shizuka", "quiet", "な-adj"],
        ["有名[ゆうめい]", "ゆうめい", "yuumei", "famous", "な-adj"],
        ["便利[べんり]", "べんり", "benri", "convenient", "な-adj"],
        ["きれい", "きれい", "kirei", "pretty; clean", "な-adj (trap!)"],
        ["元気[げんき]", "げんき", "genki", "healthy, energetic", "な-adj"],
        ["簡単[かんたん]", "かんたん", "kantan", "simple, easy", "な-adj"],
        ["大変[たいへん]", "たいへん", "taihen", "tough, awful; very", "な-adj"],
        ["親切[しんせつ]", "しんせつ", "shinsetsu", "kind", "な-adj"],
        ["暇[ひま]", "ひま", "hima", "free (time)", "な-adj"],
        ["賑[にぎ]やか", "にぎやか", "nigiyaka", "lively, bustling", "な-adj"],
        ["町[まち]", "まち", "machi", "town", "noun"],
      ],
      exercises: [
        { t: "mc", q: "“The room is NOT clean” is…",
          choices: ["きれいじゃないです", "きれくないです", "きれいくないです", "きれいないです"], a: 0,
          why: "きれい is a な-adjective in disguise — it borrows noun grammar: きれいじゃない. きれくない is THE classic learner error; you are now immune." },
        { t: "mc", q: "Pick the correct phrase for “a quiet room”:",
          choices: ["静かな部屋", "静かい部屋", "静か部屋", "静かの部屋"], a: 0,
          why: "な-adjective + noun needs な: 静かな部屋. (Predicate drops it: 部屋は静かです.)" },
        { t: "mc", q: "“Kyoto WAS lively” is…",
          choices: ["賑やかでした", "賑やかったです", "賑やくなかったです", "賑やかいでした"], a: 0,
          why: "な-tribe borrows です's past: 賑やかでした — exactly like a noun (学生でした)." },
        { t: "build", en: "This station is convenient.", tokens: ["この", "駅", "は", "便利", "です"], extra: ["な", "が"],
          why: "Predicate position — no な needed. The な only appears directly before a noun." },
        { t: "build", en: "Kyoto is a famous town.", tokens: ["京都", "は", "有名", "な", "町", "です"], extra: ["の", "い"],
          why: "Before the noun 町, the な reports for duty: 有名な町." },
        { t: "type", q: "Ask “How are you?” — literally “are you well?”",
          accept: ["元気ですか", "げんきですか", "お元気ですか", "おげんきですか"],
          show: "元気[げんき]ですか。",
          why: "元気ですか — the standard “how are you”. Answer: はい、元気です。" },
        { t: "mc", q: "Which of these is an い-adjective — the odd one out?",
          choices: ["面白い", "きれい", "有名", "嫌い"], a: 0,
          why: "面白い is genuine い-tribe (面白くない). きれい・有名・嫌い all *sound* like い but conjugate with じゃない — the three famous impostors." },
      ],
    },
    {
      id: "4.3",
      title: "Comparisons — より・の方が・一番",
      sub: "faster than, the fastest, and which do you prefer",
      briefing: [
        ["h", "Adjectives never change for comparison"],
        ["p", "No -er, no -est, no more/most: Japanese compares by arranging **particles** around an unchanging adjective. Three patterns cover everything:"],
        ["h", "AはBより — A beats B"],
        ["ex", [
          ["新幹線[しんかんせん]は車[くるま]より速[はや]いです。", "しんかんせんはくるまよりはやいです", "The bullet train is faster than a car.", "than-car — より pins the loser"],
        ]],
        ["p", "{{より}} marks the thing being out-done. Mnemonic: より = “compared to” — whatever wears より loses the contest."],
        ["h", "の方が — the winner's badge"],
        ["p", "Flip the emphasis with {{〜の方が}} (のほうが): {{冬より夏の方が好きです}} — “I like summer MORE than winter.” 方 (ほう) literally means “side/direction”: “the summer side is preferred”. Asking which of two: {{どちらが}} — and the answer must use の方が:"],
        ["ex", [
          ["紅茶[こうちゃ]とコーヒーと、どちらが好[す]きですか。", "こうちゃとこーひーとどちらがすきですか", "Tea or coffee — which do you prefer?"],
          ["紅茶[こうちゃ]の方[ほう]が好[す]きです。", "こうちゃのほうがすきです", "I prefer tea.", "obviously"],
        ]],
        ["h", "一番 — the superlative"],
        ["p", "{{一番}} (いちばん, “number one”) before an adjective makes the superlative: {{一番速い}} fastest, {{一番有名な山}} the most famous mountain. Scope it with {{〜の中で}} (among) or a place: {{日本で一番高い山は富士山です}}."],
        ["note", "好き appears above ahead of schedule — it's tomorrow's star. For today just absorb the pattern: XがYより好き / どちらが好きですか." ],
      ],
      vocab: [
        ["〜より", "より", "yori", "than, compared to", "particle"],
        ["方[ほう]", "ほう", "hou", "side, direction (の方が)", "noun"],
        ["一番[いちばん]", "いちばん", "ichiban", "most, number one", "adverb"],
        ["どちら", "どちら", "dochira", "which (of two)", "question"],
        ["天気[てんき]", "てんき", "tenki", "weather", "noun"],
        ["夏[なつ]", "なつ", "natsu", "summer", "noun"],
        ["冬[ふゆ]", "ふゆ", "fuyu", "winter", "noun"],
        ["春[はる]", "はる", "haru", "spring", "noun"],
        ["秋[あき]", "あき", "aki", "autumn", "noun"],
        ["暑[あつ]い", "あつい", "atsui", "hot (weather)", "い-adj"],
        ["寒[さむ]い", "さむい", "samui", "cold (weather)", "い-adj"],
      ],
      exercises: [
        { t: "build", en: "Winter is colder than summer.", tokens: ["冬", "は", "夏", "より", "寒い", "です"], extra: ["方", "一番"],
          why: "A は B より + adjective. 夏 wears より, so summer loses the cold contest." },
        { t: "mc", q: "{{日本で一番有名な山は富士山です}} means…",
          choices: ["Japan's most famous mountain is Mt Fuji", "Mt Fuji is one mountain in Japan", "Fuji is Japan's tallest station", "The first mountain in Japan was Fuji"], a: 0,
          why: "で scopes the contest (in Japan), 一番 crowns it, 有名な (な-adjective!) modifies 山." },
        { t: "mc", q: "Someone asks {{紅茶とコーヒーと、どちらが好きですか}}. The grammatical reply is…",
          choices: ["紅茶の方が好きです", "紅茶は好きです", "紅茶が一番より好きです", "どちらが紅茶です"], a: 0,
          why: "A どちら question contractually requires の方が in the answer: “the tea side is preferred”." },
        { t: "mc", q: "Pick the missing word.", jp: "バスより電車[でんしゃ]の＿＿が速[はや]いです。", speak: false,
          choices: ["方", "中", "一番", "より"], a: 0,
          why: "の方が — the winner's badge. The train side is faster." },
        { t: "type", q: "Say: “Today is hot.” (weather small talk = 50% of Japanese conversation)",
          accept: ["今日は暑いです", "きょうはあついです"],
          show: "今日[きょう]は暑[あつ]いです。",
          why: "Master 今日は暑いですね / 寒いですね and you can sustain conversation with any taxi driver in Japan." },
        { t: "mc", q: "Which sentence says autumn is the BEST season (of the four)?",
          choices: ["季節の中で秋が一番好きです", "秋は冬より好きです", "秋の方が好きです", "秋はいい天気です"], a: 0,
          why: "〜の中で + 一番 = superlative among a set. The others only compare two things or state a fact. (季節 = season.)" },
      ],
    },
    {
      id: "4.4",
      title: "Likes, Skills, and が — 好き・嫌い・上手・下手",
      sub: "why “I like tea” takes が, not を — and how to praise like a local",
      briefing: [
        ["h", "好き is an adjective, not a verb"],
        ["p", "English “like” is a verb, so you expect を. But {{好き}} is a **な-adjective** — literally “X is pleasing”. The pleasing thing takes {{が}}: {{私は紅茶が好きです}} — “as for me, tea is pleasing.” This one fact explains the particle Duolingo never justified."],
        ["table", ["Pattern", "Meaning"], [
          ["Xが好きです", "I like X"],
          ["Xが大好きです", "I love X"],
          ["Xが嫌いです", "I dislike X"],
          ["Xが上手です", "(someone is) good at X"],
          ["Xが下手です", "(someone is) bad at X"],
          ["Xが分かります", "I understand X (分かる also takes が!)"],
        ]],
        ["ex", [
          ["私[わたし]はゲームが好[す]きです。", "わたしはげーむがすきです", "I like games."],
          ["妹[いもうと]は料理[りょうり]が上手[じょうず]です。", "いもうとはりょうりがじょうずです", "My little sister is good at cooking."],
          ["日本語[にほんご]が少[すこ]し分[わ]かります。", "にほんごがすこしわかります", "I understand a little Japanese.", "the humble truth, particle-perfect"],
        ]],
        ["h", "The modesty protocol"],
        ["p", "{{上手}} praises **others**: 日本語が上手ですね！ (you'll hear this constantly — Japan awards it for saying こんにちは). For your own skills use {{得意}} (とくい, my strong suit) or just facts. Calling yourself 上手 sounds like polishing your own medals. Self-deprecation runs the other way too: 下手ですが… “I'm bad at this, but…” before doing something perfectly well."],
        ["note", "嫌い (dislike) is strong — closer to “hate”. For polite decline: {{あまり好きじゃないです}} “I don't much care for it.” Japan's favourite way to say no without saying no."],
      ],
      vocab: [
        ["好[す]き", "すき", "suki", "liked, pleasing", "な-adj"],
        ["大好[だいす]き", "だいすき", "daisuki", "loved, adored", "な-adj"],
        ["嫌[きら]い", "きらい", "kirai", "disliked", "な-adj (trap!)"],
        ["上手[じょうず]", "じょうず", "jouzu", "good at", "な-adj"],
        ["下手[へた]", "へた", "heta", "bad at", "な-adj"],
        ["分[わ]かります", "わかります", "wakarimasu", "to understand", "verb・godan"],
        ["ゲーム", "げーむ", "geemu", "game", "noun"],
        ["スポーツ", "すぽーつ", "supootsu", "sport", "noun"],
        ["歌[うた]", "うた", "uta", "song", "noun"],
        ["料理[りょうり]", "りょうり", "ryouri", "cooking; dish", "noun"],
        ["ドラゴン", "どらごん", "doragon", "dragon", "noun"],
        ["冒険[ぼうけん]", "ぼうけん", "bouken", "adventure", "noun"],
      ],
      exercises: [
        { t: "mc", q: "Pick the particle.", jp: "私[わたし]は紅茶[こうちゃ]＿＿好[す]きです。", speak: false,
          choices: ["が", "を", "に", "は"], a: 0,
          why: "好き is an adjective — “tea is pleasing (to me)” — so the liked thing takes が. This is the answer to a hundred silent Duolingo corrections." },
        { t: "type", q: "Say: “I like dragons.” (a certain purple one, perhaps)",
          accept: ["ドラゴンが好きです", "どらごんがすきです", "私はドラゴンが好きです"],
          show: "ドラゴンが好[す]きです。",
          why: "Xが好きです. Works for dragons, gems, and gliding through portals. 🐲" },
        { t: "mc", q: "A local says {{日本語が上手ですね！}} after you say one word. They mean…",
          choices: ["“Your Japanese is good!” — the standard encouragement", "Your Japanese is bad", "Please stop speaking", "They're asking a question"], a: 0,
          why: "上手 praises others' skill, and Japan hands it out generously. The protocol reply: いえいえ、まだまだです (“oh no, not yet at all”)." },
        { t: "build", en: "My friend is good at cooking.", tokens: ["友達", "は", "料理", "が", "上手", "です"], extra: ["を", "下手"],
          why: "Person は + skill が + 上手です. The skill takes が, same as 好き." },
        { t: "mc", q: "The polite way to say you don't care for natto:",
          choices: ["あまり好きじゃないです", "嫌いです！", "全然好きです", "下手です"], a: 0,
          why: "嫌い is strong (“hate”). あまり好きじゃない — “don't much like it” — declines the fermented beans while preserving the peace." },
        { t: "mc", q: "Pick the particle.", jp: "日本語[にほんご]＿＿分[わ]かりますか。", speak: false,
          choices: ["が", "を", "で", "も"], a: 0,
          why: "分かる joins the が-club: understanding “arises” from the thing. 日本語が分かります — say it and mean it a little more each week." },
        { t: "build", en: "I love adventure. (nothing is true…)", tokens: ["冒険", "が", "大好き", "です"], extra: ["を", "嫌い"],
          why: "大好き = 大 (big) + 好き. Creed-appropriate enthusiasm, correct particle." },
      ],
    },
    {
      id: "4.5",
      review: true,
      title: "Mission Review 04",
      sub: "two adjective tribes, comparisons, and the が-club — sensors calibrated",
      briefing: [
        ["h", "Debrief: sensors online"],
        ["ul", [
          "**い-adjectives** conjugate themselves: 高くない・高かった・高くなかった. いい goes via よ〜: よかった.",
          "**な-adjectives** borrow です like nouns: 静かじゃない・静かでした — and need な before a noun: 静かな部屋.",
          "**The impostors**: きれい・有名・嫌い sound like い but are な-tribe. きれいじゃない, never きれくない.",
          "**Comparisons**: AはBより〜 / Bの方が〜 / 一番〜. Adjectives never change shape.",
          "**The が-club**: 好き・嫌い・上手・下手・分かる all mark their target with が.",
        ]],
        ["p", "Simulation begins — mixed drills ahead. わからないことがあったら、もう一度ブリーフィングを読んでください。(If something's unclear, reread the briefing — yes, you can nearly parse that sentence now.)"],
      ],
      vocab: [],
      exercises: [
        { t: "mc", q: "“The film wasn't interesting” is…",
          choices: ["面白くなかったです", "面白いじゃなかったです", "面白かったないです", "面白いでしたない"], a: 0,
          why: "い-tribe: 面白い → 面白くない → past 面白くなかった + です polish." },
        { t: "mc", q: "“a kind person” is…",
          choices: ["親切な人", "親切人", "親切い人", "親切の人"], a: 0,
          why: "親切 is な-tribe: before a noun the な reports for duty." },
        { t: "build", en: "I like summer more than winter.", tokens: ["冬", "より", "夏", "の", "方", "が", "好き", "です"], extra: ["を", "一番"],
          why: "Loser wears より, winner wears の方が, and 好き takes が." },
        { t: "type", q: "Say: “I understand a little Japanese.”",
          accept: ["日本語が少し分かります", "にほんごがすこしわかります", "日本語が少しわかります"],
          show: "日本語[にほんご]が少[すこ]し分[わ]かります。",
          why: "The honest, particle-perfect sentence for every conversation in Japan. It opens doors." },
        { t: "mc", q: "Spot the broken sentence:",
          choices: ["きれくないです", "きれいじゃないです", "静かじゃないです", "高くないです"], a: 0,
          why: "きれい is な-tribe — it can't take くない. The trap claims everyone once; not you, not today." },
      ],
    },
  ],
});

/* ================= WEEK 5 — THE TE-FORM DIRECTIVE ================= */
DK.week({
  n: 5,
  name: "THE TE-FORM DIRECTIVE",
  brief: "Stardate 79528.8. Engineering reports the te-form is the warp core of Japanese: requests, ongoing actions, permission, prohibition, and chaining sentences all run through it. Learn to build it once, correctly, and half the language's grammar comes free. Directive: master it this week.",
  lessons: [
    {
      id: "5.1",
      title: "Building the Te-Form",
      sub: "て・って・んで・いて — the five rules that unlock fifty grammar points",
      briefing: [
        ["h", "Why the te-form matters"],
        ["p", "The te-form is a verb's connector shape — it doesn't carry tense, it carries **linkage**: “do X and…”, “please do X”, “X-ing”, “may I X?”. At least a dozen essential patterns are just te-form + something. Build it right and they all come free."],
        ["h", "Ichidan and irregular: trivial"],
        ["p", "Ichidan: る → て. {{食べる → 食べて}}, {{見る → 見て}}. The rebels: {{する → して}}, {{来る → 来[き]て}}. Done."],
        ["h", "Godan: group by the final sound"],
        ["table", ["Ends in", "Becomes", "Examples"], [
          ["う・つ・る", "って", "買う→買って、待つ→待って、帰る→帰って"],
          ["む・ぶ・ぬ", "んで", "飲む→飲んで、遊ぶ→遊んで"],
          ["く", "いて", "書く→書いて　(exception: 行く→行って！)"],
          ["ぐ", "いで", "泳ぐ→泳いで"],
          ["す", "して", "話す→話して"],
        ]],
        ["p", "Learners chant this to the tune of “Twinkle Twinkle”: *u-tsu-ru → tte / mu-bu-nu → nde / ku → ite, gu → ide / su → shite*. Sing it in the shower twice and it's yours for life."],
        ["ex", [
          ["ちょっと待[ま]って！", "ちょっとまって", "Wait a sec!", "待つ → 待って — you already knew this one from anime"],
          ["行[い]って来[き]ます！", "いってきます", "I'm off! (lit. going and coming)", "行く's rebel te-form + 来る's — said leaving home every day in Japan"],
        ]],
        ["h", "The one exception in the whole system"],
        ["p", "{{行く}} should give 行いて by the く rule; instead it's {{行って}}. That is the **only** te-form exception in the entire language. One. Savour how tidy this machine is."],
        ["tip", "First uses today, as a warm-up: te-form + から = “after doing”; te-form joins actions like “and”: 朝ご飯を食べて、学校に行きます — “I eat breakfast and go to school.” The tense lives only on the final verb."],
      ],
      vocab: [
        ["待[ま]ちます", "まちます", "machimasu", "to wait", "verb・godan"],
        ["立[た]ちます", "たちます", "tachimasu", "to stand", "verb・godan"],
        ["座[すわ]ります", "すわります", "suwarimasu", "to sit", "verb・godan"],
        ["遊[あそ]びます", "あそびます", "asobimasu", "to play, hang out", "verb・godan"],
        ["泳[およ]ぎます", "およぎます", "oyogimasu", "to swim", "verb・godan"],
        ["手伝[てつだ]います", "てつだいます", "tetsudaimasu", "to help", "verb・godan"],
        ["開[あ]けます", "あけます", "akemasu", "to open (something)", "verb・ichidan"],
        ["閉[し]めます", "しめます", "shimemasu", "to close (something)", "verb・ichidan"],
        ["使[つか]います", "つかいます", "tsukaimasu", "to use", "verb・godan"],
        ["作[つく]ります", "つくります", "tsukurimasu", "to make", "verb・godan"],
      ],
      exercises: [
        { t: "mc", q: "{{買う}} (buy) → te-form:",
          choices: ["買って", "買いて", "買んで", "買て"], a: 0,
          why: "う・つ・る → って. 買う→買って. First line of the song." },
        { t: "mc", q: "{{飲む}} (drink) → te-form:",
          choices: ["飲んで", "飲みて", "飲って", "飲いで"], a: 0,
          why: "む・ぶ・ぬ → んで. 飲む→飲んで. Second line of the song." },
        { t: "mc", q: "{{食べる}} (eat) → te-form:",
          choices: ["食べて", "食べって", "食べんで", "食びて"], a: 0,
          why: "Ichidan verbs just swap る for て. No song required — the friendly class stays friendly." },
        { t: "mc", q: "{{行く}} (go) → te-form:",
          choices: ["行って", "行いて", "行んで", "行きて"], a: 0,
          why: "THE exception. By the く-rule it'd be 行いて; reality says 行って. The only te-form outlaw in the language." },
        { t: "mc", q: "{{話す}} (speak) → te-form:",
          choices: ["話して", "話って", "話んで", "話いて"], a: 0,
          why: "す → して. Fourth line of the song. You now hold all five rules." },
        { t: "match", q: "Match verb to te-form.", pairs: [
          ["待つ", "待って"],
          ["泳ぐ", "泳いで"],
          ["書く", "書いて"],
          ["する", "して"],
        ]},
        { t: "build", en: "I eat breakfast and go to school.", tokens: ["朝ご飯", "を", "食べて", "学校", "に", "行きます"], extra: ["食べます", "で"],
          why: "Te-form chains actions; only the final verb carries the tense. 食べて…行きます." },
        { t: "mc", q: "{{行って来ます}} — said while leaving home — literally means…",
          choices: ["I'll go and come (back)", "Please go away", "I have arrived", "Let's go together"], a: 0,
          why: "行って (go) + 来ます (come): “I'm off — and I'll return.” The reply from inside the house: 行ってらっしゃい." },
      ],
    },
    {
      id: "5.2",
      title: "〜てください — Making Requests",
      sub: "please do, please don't, and the magic of ちょっと",
      briefing: [
        ["h", "Te-form + ください = please"],
        ["p", "The politest everyday way to ask someone to do something: te-form + {{ください}}. {{待ってください}} “please wait”, {{もう一度言ってください}} “please say it again” — the sentence that will carry your entire first trip to Japan."],
        ["ex", [
          ["ちょっと待[ま]ってください。", "ちょっとまってください", "Please wait a moment."],
          ["もう一度[いちど]言[い]ってください。", "もういちどいってください", "Please say that again."],
          ["ゆっくり話[はな]してください。", "ゆっくりはなしてください", "Please speak slowly.", "the learner's shield-generator"],
        ]],
        ["h", "Please DON'T: 〜ないでください"],
        ["p", "The negative request uses the plain negative (preview of next week) + でください: {{写真を撮らないでください}} “please don't take photos”. You'll see it on signs at every shrine — now you can read them."],
        ["h", "Softeners"],
        ["p", "{{ちょっと}} (“a little”) softens anything: ちょっと待ってください is friendlier than the bare command. {{すみません}} in front adds lubrication: すみません、ドアを閉めてください. Politeness in Japanese is mostly about padding, and now you have padding."],
        ["note", "Dropping ください leaves the bare te-form — a casual command between friends: 待って！ “wait!”. Fine for friends and dogs; keep ください for everyone else until week 6's casual-speech briefing."],
      ],
      vocab: [
        ["ドア", "どあ", "doa", "door", "noun"],
        ["窓[まど]", "まど", "mado", "window", "noun"],
        ["電気[でんき]", "でんき", "denki", "electricity; the lights", "noun"],
        ["ゆっくり", "ゆっくり", "yukkuri", "slowly", "adverb"],
        ["もう一度[いちど]", "もういちど", "mou ichido", "once more", "expression"],
        ["写真[しゃしん]", "しゃしん", "shashin", "photo", "noun"],
        ["撮[と]ります", "とります", "torimasu", "to take (a photo)", "verb・godan"],
        ["言[い]います", "いいます", "iimasu", "to say", "verb・godan"],
        ["消[け]します", "けします", "keshimasu", "to turn off, erase", "verb・godan"],
        ["つけます", "つけます", "tsukemasu", "to turn on", "verb・ichidan"],
      ],
      exercises: [
        { t: "build", en: "Please wait a moment.", tokens: ["ちょっと", "待って", "ください"], extra: ["待ちます", "を"],
          why: "ちょっと (softener) + te-form + ください. The politeness sandwich." },
        { t: "type", q: "Ask: “Please say it once more.” (your best friend in every conversation)",
          accept: ["もう一度言ってください", "もういちどいってください"],
          show: "もう一度[いちど]言[い]ってください。",
          why: "もう一度 + 言って (言う→言って, う→って) + ください. Deploy without shame — natives appreciate the effort." },
        { t: "mc", q: "A shrine sign reads {{写真を撮らないでください}}. It says…",
          choices: ["Please don't take photos", "Please take photos", "Photos cost money", "Camera repairs here"], a: 0,
          why: "ないでください = please don't. 撮らない is the plain negative of 撮る — the full machinery arrives next week; the sign's meaning arrives now." },
        { t: "build", en: "Please speak slowly.", tokens: ["ゆっくり", "話して", "ください"], extra: ["話しません", "が"],
          why: "話す→話して (す→して) + ください. Say it early, say it often." },
        { t: "mc", q: "Pick the correct request: “Please close the window.”",
          choices: ["窓を閉めてください", "窓を閉めますください", "窓を閉めるください", "窓が閉めてください"], a: 0,
          why: "ください attaches to the TE-FORM only — never ます or dictionary form. Object still takes を." },
        { t: "mc", q: "Your friend (casual register) says {{電気つけて}}. They want you to…",
          choices: ["turn the lights on", "turn the lights off", "pay the electricity bill", "look at the light"], a: 0,
          why: "Bare te-form = casual command. つける = turn on (消す = turn off). Friends drop ください and particles; the te-form carries everything." },
      ],
    },
    {
      id: "5.3",
      title: "〜ています — Now, and States That Stick",
      sub: "I am eating / I live in Edinburgh / I know — one pattern, three faces",
      briefing: [
        ["h", "Face one: happening right now"],
        ["p", "Te-form + {{います}} = the progressive, “is …ing”: {{今、食べています}} “I'm eating right now.” Yes — that's the existence verb います moonlighting as an auxiliary: the action *exists* in progress."],
        ["ex", [
          ["今[いま]、雨[あめ]が降[ふ]っています。", "いまあめがふっています", "It's raining right now."],
          ["艦長[かんちょう]はお茶[ちゃ]を飲[の]んでいます。", "かんちょうはおちゃをのんでいます", "The captain is drinking tea.", "as is right and proper"],
        ]],
        ["h", "Face two: ongoing states"],
        ["p", "Some verbs describe an instant change whose **result persists**. For those, ています means the resulting state, not an action in progress:"],
        ["table", ["Japanese", "NOT", "But rather"], [
          ["住んでいます", "is in the act of living", "lives (somewhere)"],
          ["知っています", "is learning", "knows"],
          ["持っています", "is grabbing", "owns / has"],
          ["結婚しています", "is mid-wedding", "is married"],
        ]],
        ["ex", [
          ["エディンバラに住[す]んでいます。", "えでぃんばらにすんでいます", "I live in Edinburgh."],
          ["田中[たなか]さんを知[し]っていますか。", "たなかさんをしっていますか", "Do you know Tanaka?"],
        ]],
        ["h", "Face three: habits"],
        ["p", "{{毎日日本語を勉強しています}} — “I've been studying Japanese every day.” English uses present simple; Japanese frames a habit as one long ongoing action. Sound familiar? It should — it's your life right now."],
        ["note", "One asymmetry to memorise: “do you know?” is 知って**います**か, but “I DON'T know” is plain {{知りません}} — never 知っていません. Nobody knows why. Even the linguists shrug politely."],
      ],
      vocab: [
        ["住[す]みます", "すみます", "sumimasu", "to live (reside)", "verb・godan"],
        ["知[し]ります", "しります", "shirimasu", "to (get to) know", "verb・godan"],
        ["持[も]ちます", "もちます", "mochimasu", "to hold, own", "verb・godan"],
        ["働[はたら]きます", "はたらきます", "hatarakimasu", "to work", "verb・godan"],
        ["雨[あめ]", "あめ", "ame", "rain", "noun"],
        ["雪[ゆき]", "ゆき", "yuki", "snow", "noun"],
        ["降[ふ]ります", "ふります", "furimasu", "to fall (rain/snow)", "verb・godan"],
        ["電話[でんわ]", "でんわ", "denwa", "telephone; phone call", "noun"],
        ["エディンバラ", "えでぃんばら", "edinbara", "Edinburgh", "noun"],
        ["会社[かいしゃ]", "かいしゃ", "kaisha", "company, office", "noun"],
      ],
      exercises: [
        { t: "build", en: "It is raining now.", tokens: ["今", "雨", "が", "降って", "います"], extra: ["を", "あります"],
          why: "降る→降って + います. New phenomenon in the sky → が." },
        { t: "mc", q: "{{京都に住んでいます}} means…",
          choices: ["I live in Kyoto", "I am currently moving to Kyoto", "I lived in Kyoto once", "I will live in Kyoto"], a: 0,
          why: "住む is a result-state verb: ています = the settled state, “lives”. Not an action caught mid-happening." },
        { t: "mc", q: "“I DON'T know” is…",
          choices: ["知りません", "知っていません", "知らないでいます", "知りませんでした"], a: 0,
          why: "The famous asymmetry: 知っています (know) but 知りません (don't know). 知っていません doesn't exist. File under “Japanese keeps one mystery per week”." },
        { t: "type", q: "Say: “I'm studying Japanese.” (meta, but true)",
          accept: ["日本語を勉強しています", "にほんごをべんきょうしています"],
          show: "日本語[にほんご]を勉強[べんきょう]しています。",
          why: "Habit-face ています: an ongoing project, like a five-year mission. Which this literally is — welcome to week 5 of 12." },
        { t: "mc", q: "Pick the natural translation: “The captain is drinking tea.”",
          choices: ["艦長はお茶を飲んでいます", "艦長はお茶を飲みます", "艦長はお茶が飲みました", "艦長はお茶でいます"], a: 0,
          why: "Right now, in progress → 飲んでいます. Bare 飲みます would state habit/future (“the captain drinks tea — generally, as policy”). Also true, but not the scene." },
        { t: "build", en: "I work at a company in Edinburgh.", tokens: ["エディンバラ", "の", "会社", "で", "働いて", "います"], extra: ["に", "働きます"],
          why: "エディンバラの会社 (chained nouns) + action-place で + 働いて + います (ongoing state: employed)." },
      ],
    },
    {
      id: "5.4",
      title: "May I? — 〜てもいいです・〜てはいけません",
      sub: "permission, prohibition, and surviving temple etiquette",
      briefing: [
        ["h", "Asking permission"],
        ["p", "Te-form + {{もいいですか}} = “is it OK if I…?” Literally: “even doing X — is it good?” The answer comes back in the same shape:"],
        ["ex", [
          ["ここで写真[しゃしん]を撮[と]ってもいいですか。", "ここでしゃしんをとってもいいですか", "May I take photos here?"],
          ["はい、いいですよ。", "はいいいですよ", "Sure, go ahead."],
          ["入[はい]ってもいいですか。", "はいってもいいですか", "May I come in?"],
        ]],
        ["h", "Prohibition: てはいけません"],
        ["p", "Te-form + {{はいけません}} = “must not”. It's firm — rules, signs, safety: {{ここに入ってはいけません}} “you must not enter here.” In speech, the て**は** contracts to ちゃ: 入っちゃだめ — you'll hear parents say it to children (and children to dragons)."],
        ["table", ["Pattern", "Force", "Example"], [
          ["〜てもいいです", "permission", "座ってもいいです — you may sit"],
          ["〜てもいいですか", "asking", "座ってもいいですか — may I sit?"],
          ["〜てはいけません", "prohibition", "座ってはいけません — no sitting"],
          ["〜ないでください", "polite request-not", "座らないでください — please don't sit"],
        ]],
        ["h", "Field guide: temples and shrines"],
        ["p", "Where this grammar lives in the wild: {{靴を脱いでください}} (please remove your shoes — you WILL meet this sign), 写真を撮ってはいけません inside many temple halls, and 触ってはいけません next to anything ancient. One week of te-form and suddenly Japan's signage is subtitles."],
        ["note", "Refusing permission directly (“no you may not”) is avoided. You'll hear {{ちょっと…}} with a pained expression instead. If a Japanese person says ちょっと and inhales through their teeth, the answer was no."],
      ],
      vocab: [
        ["入[はい]ります", "はいります", "hairimasu", "to enter", "verb・godan (impostor)"],
        ["出[で]ます", "でます", "demasu", "to exit, leave", "verb・ichidan"],
        ["触[さわ]ります", "さわります", "sawarimasu", "to touch", "verb・godan"],
        ["脱[ぬ]ぎます", "ぬぎます", "nugimasu", "to take off (clothes/shoes)", "verb・godan"],
        ["靴[くつ]", "くつ", "kutsu", "shoes", "noun"],
        ["博物館[はくぶつかん]", "はくぶつかん", "hakubutsukan", "museum", "noun"],
        ["神社[じんじゃ]", "じんじゃ", "jinja", "(Shinto) shrine", "noun"],
        ["たばこ", "たばこ", "tabako", "cigarette, smoking", "noun"],
        ["吸[す]います", "すいます", "suimasu", "to smoke, inhale", "verb・godan"],
        ["だめ", "だめ", "dame", "no good, not allowed", "な-adj"],
      ],
      exercises: [
        { t: "build", en: "May I take a photo here?", tokens: ["ここ", "で", "写真", "を", "撮って", "も", "いい", "です", "か"], extra: ["に", "撮ります"],
          why: "Action-place で + object を + 撮って + もいいですか. The politest camera in the sector." },
        { t: "mc", q: "The museum sign {{触ってはいけません}} means…",
          choices: ["Do not touch", "Please touch gently", "Touching costs extra", "Wash your hands"], a: 0,
          why: "てはいけません = must not. 触る (touch) → 触って. The 500-year-old teabowl thanks you." },
        { t: "type", q: "Ask: “May I enter?”", accept: ["入ってもいいですか", "はいってもいいですか"],
          show: "入[はい]ってもいいですか。",
          why: "入る is a godan impostor (-iru but godan): 入って. Knock, ask, receive どうぞ." },
        { t: "mc", q: "At a ryokan entrance you'll be told {{靴を脱いでください}}. Do what?",
          choices: ["Take your shoes off", "Put your shoes on", "Buy new shoes", "Clean your shoes"], a: 0,
          why: "脱ぐ→脱いで (ぐ→いで, third line of the song) + ください. Genkan protocol: shoes off, slippers on, tatami in socks only." },
        { t: "mc", q: "Which reply GRANTS permission?",
          choices: ["はい、いいですよ", "いいえ、いけません", "ちょっと…", "だめです"], a: 0,
          why: "いいですよ = go ahead (よ adds friendly assurance). ちょっと… + wince = no, in its natural habitat." },
        { t: "mc", q: "Pick the sign for a no-smoking area:",
          choices: ["ここでたばこを吸ってはいけません", "ここでたばこを吸ってもいいです", "たばこを吸ってください", "たばこがあります"], a: 0,
          why: "Prohibition → 吸ってはいけません. The second sign would make it a smoking lounge; the third would be actively encouraging. Particles and patterns matter." },
      ],
    },
    {
      id: "5.5",
      review: true,
      title: "Mission Review 05",
      sub: "the warp core is online — te-form in all four applications",
      briefing: [
        ["h", "Debrief: warp core stable"],
        ["ul", [
          "**Building it**: う・つ・る→って / む・ぶ・ぬ→んで / く→いて・ぐ→いで / す→して; ichidan る→て; して・来て; and the lone outlaw 行って.",
          "**〜てください** please do / **〜ないでください** please don't.",
          "**〜ています** now-progressive, stuck-states (住んでいます・知っています), and habits.",
          "**〜てもいいですか** may I / **〜てはいけません** must not.",
          "Chaining: 食べて、行きます — tense rides only the last verb.",
        ]],
        ["p", "Complete this simulation and the Chief Engineer signs your commendation. The te-form now works for you for life — every future grammar point that starts 〜て just plugs in."],
      ],
      vocab: [],
      exercises: [
        { t: "mc", q: "{{待つ}} → te-form:", choices: ["待って", "待んで", "待いて", "待て"], a: 0,
          why: "つ → って. ちょっと待ってください — now you can build it from parts." },
        { t: "mc", q: "{{泳ぐ}} → te-form:", choices: ["泳いで", "泳って", "泳んで", "泳して"], a: 0,
          why: "ぐ → いで (the voiced twin of く→いて). 泳ぐ→泳いで." },
        { t: "build", en: "Please open the window.", tokens: ["窓", "を", "開けて", "ください"], extra: ["開けます", "に"],
          why: "開ける is ichidan: る→て. Object を + te-form + ください." },
        { t: "mc", q: "{{持っています}} means…",
          choices: ["I have / own (it)", "I am lifting weights", "I will hold it", "Hold this please"], a: 0,
          why: "持つ is a result-state verb: ています = the persisting state of possession. ペンを持っていますか — got a pen?" },
        { t: "type", q: "Say: “It's snowing.”", accept: ["雪が降っています", "ゆきがふっています"],
          show: "雪[ゆき]が降[ふ]っています。",
          why: "Same build as the rain sentence — swap 雨 for 雪. Grammar patterns are transporters: same coordinates, new cargo." },
        { t: "mc", q: "You want to ask to sit down. Which is it?",
          choices: ["座ってもいいですか", "座ってはいけませんか", "座らないでください", "座りましたか"], a: 0,
          why: "Permission request = てもいいですか. The second asks “am I forbidden?”, the third begs someone else not to sit, the fourth asks about sitting history." },
      ],
    },
  ],
});

/* ================= WEEK 6 — UNIVERSAL TRANSLATOR OFFLINE ================= */
DK.week({
  n: 6,
  name: "UNIVERSAL TRANSLATOR OFFLINE",
  brief: "Stardate 79531.5. Intercepted comms are never in textbook polite form. This week you learn how Japanese actually talks: the plain forms — dictionary form, ない, た — casual speech, and the machinery for “can do” and “before/after”. The translator stays off; you won't need it.",
  lessons: [
    {
      id: "6.1",
      title: "The Dictionary Form and ない",
      sub: "plain speech, part one — what verbs look like off duty",
      briefing: [
        ["h", "Politeness is a setting, not a tense"],
        ["p", "Everything you've said so far ran in polite mode (です/ます). Japanese also has **plain mode** — same meanings, different endings — used between friends and family, inside your own head, in books, and (crucially) as the raw material for tons of grammar. The dictionary form IS the plain non-past: {{飲む}} = 飲みます, off duty."],
        ["h", "Plain negative: 〜ない"],
        ["table", ["Class", "Rule", "Example"], [
          ["godan", "final -u → -a + ない", "飲む→飲まない、書く→書かない"],
          ["godan in -う", "-u → -わ + ない", "買う→買わない (not 買あない!)"],
          ["ichidan", "drop る + ない", "食べる→食べない"],
          ["irregular", "just two to learn", "する→しない、来る→来[こ]ない"],
        ]],
        ["p", "ない then conjugates **like an い-adjective**: 飲まない → 飲まなかった (didn't drink). The systems interlock — everything you learned in week 4 applies."],
        ["ex", [
          ["明日[あした]、行[い]く？", "あしたいく", "Going tomorrow? (casual)", "rising tone does the か's job"],
          ["ううん、行[い]かない。", "ううんいかない", "Nah, not going."],
        ]],
        ["h", "Where you've already met ない"],
        ["p", "{{写真を撮らないでください}} — that ないでください from week 5? Plain negative + でください. And you'll hear {{分かんない}} (“dunno”) constantly in anime — it's 分からない with the ら swallowed. The plain forms have been around you all along."],
        ["note", "Casual isn't rude — it's intimate. Using ます with your best friend after a year sounds like keeping them at arm's length; using plain form with a shopkeeper you just met is overfamiliar. The setting to match is the relationship, and when unsure, polite never offends."],
      ],
      vocab: [
        ["漫画[まんが]", "まんが", "manga", "manga, comics", "noun"],
        ["アニメ", "あにめ", "anime", "anime", "noun"],
        ["一緒[いっしょ]に", "いっしょに", "issho ni", "together", "adverb"],
        ["大丈夫[だいじょうぶ]", "だいじょうぶ", "daijoubu", "OK, fine, no problem", "な-adj"],
        ["本当[ほんとう]", "ほんとう", "hontou", "true, really", "noun"],
        ["多分[たぶん]", "たぶん", "tabun", "probably", "adverb"],
        ["ちょっと", "ちょっと", "chotto", "a little; um…", "adverb"],
        ["うん", "うん", "un", "yeah (casual はい)", "expression"],
        ["ううん", "ううん", "uun", "nah (casual いいえ)", "expression"],
        ["いつも", "いつも", "itsumo", "always", "adverb"],
      ],
      exercises: [
        { t: "mc", q: "Plain (dictionary) form of {{飲みます}}:",
          choices: ["飲む", "飲みる", "飲ま", "飲めて"], a: 0,
          why: "Reverse the week-3 rule: stem 飲み + む-row. The dictionary form is where verbs live when nobody's being polite." },
        { t: "mc", q: "Plain negative of {{買う}}:",
          choices: ["買わない", "買あない", "買らない", "買ない"], a: 0,
          why: "-う verbs go to -わ: 買わない. The wa is a fossil of old Japanese — and the reason it's not the unpronounceable 買あない." },
        { t: "mc", q: "Plain negative of {{来る}}:",
          choices: ["来[こ]ない", "来[き]ない", "来[く]ない", "来ません"], a: 0,
          why: "The rebel changes its own reading: 来る(くる)→来ない(こない). It's the only verb that shape-shifts its stem — even its ます form was 来(き)ます." },
        { t: "mc", q: "Your friend texts {{明日、来る？}}. You're not coming. The natural reply:",
          choices: ["ううん、行かない", "いいえ、来ませんでした", "ううん、来る", "はい、行きます"], a: 0,
          why: "Casual register (ううん) + plain negative — and perspective flips 来る to 行かない: from YOUR phone, you're not GOING." },
        { t: "mc", q: "“I didn't eat” in plain form:",
          choices: ["食べなかった", "食べないでした", "食べませんかった", "食べなくた"], a: 0,
          why: "ない conjugates like an い-adjective: ない→なかった. Week 4's machinery, reused — the systems interlock." },
        { t: "build", en: "I probably won't watch TV. (casual)", tokens: ["多分", "テレビ", "は", "見ない"], extra: ["見ます", "か"],
          why: "多分 + plain negative. That は adds week-1 contrast: TV, at least, isn't happening." },
        { t: "mc", q: "Which register pairing is natural?",
          choices: ["Best friend: 一緒に行く？ / Shop staff: 袋はいりますか", "Best friend: ご一緒しますか / Shop staff: 行く？", "Everyone: plain form", "Everyone: ます form including your cat"], a: 0,
          why: "Match the setting to the relationship: plain with intimates, polite with strangers. (Your cat outranks you; address it however it prefers.)" },
      ],
    },
    {
      id: "6.2",
      title: "た — The Plain Past",
      sub: "plain speech, part two — and a free gift from the te-form",
      briefing: [
        ["h", "You already know this lesson"],
        ["p", "The plain past た-form is built **exactly like the te-form**, with た instead of て: 買って→買った, 飲んで→飲んだ, 食べて→食べた, して→した, 行って→行った. If you sang the song last week, you already own the past tense. This is the te-form paying its first dividend."],
        ["table", ["Verb", "te-form", "plain past"], [
          ["買う", "買って", "買った"],
          ["飲む", "飲んで", "飲んだ"],
          ["書く", "書いて", "書いた"],
          ["食べる", "食べて", "食べた"],
          ["する", "して", "した"],
        ]],
        ["ex", [
          ["昨日[きのう]、何[なに]した？", "きのうなにした", "What'd you do yesterday? (casual)"],
          ["映画[えいが]を見[み]た。すごく面白[おもしろ]かった！", "えいがをみた。すごくおもしろかった", "Watched a film. It was really good!"],
        ]],
        ["h", "だ — です off duty"],
        ["p", "Plain です is {{だ}}: 学生だ (am a student), 本当だ！ (it's true!). Nouns and な-adjectives take it; い-adjectives refuse it (面白い is already complete). In casual questions だ usually vanishes: 学生？ 大丈夫？ — tone does the work."],
        ["h", "The full plain-form set"],
        ["table", ["", "non-past", "past"], [
          ["affirmative", "飲む", "飲んだ"],
          ["negative", "飲まない", "飲まなかった"],
        ]],
        ["p", "Four cells. That's the entire plain conjugation — and with it you can now read manga, follow anime dialogue, and text like a human being. Next week these forms start powering advanced grammar."],
        ["tip", "お腹が空いた (I'm hungry — lit. “stomach emptied”) and 疲れた (I'm tired) are plain-past **states**: the emptying/tiring already happened, the result is now. Japanese announces the event; English describes the aftermath. Both are said a million times a day."],
      ],
      vocab: [
        ["すごい", "すごい", "sugoi", "amazing, incredible", "い-adj"],
        ["まあまあ", "まあまあ", "maamaa", "so-so", "adverb"],
        ["疲[つか]れた", "つかれた", "tsukareta", "(I'm) tired", "expression"],
        ["お腹[なか]", "おなか", "onaka", "stomach, belly", "noun"],
        ["お腹[なか]が空[す]いた", "おなかがすいた", "onaka ga suita", "(I'm) hungry", "expression"],
        ["眠[ねむ]い", "ねむい", "nemui", "sleepy", "い-adj"],
        ["忙[いそが]しい", "いそがしい", "isogashii", "busy", "い-adj"],
        ["昼[ひる]ご飯[はん]", "ひるごはん", "hirugohan", "lunch", "noun"],
        ["カレー", "かれー", "karee", "curry", "noun"],
        ["美味[おい]しい", "おいしい", "oishii", "delicious", "い-adj"],
      ],
      exercises: [
        { t: "mc", q: "Plain past of {{飲む}}:",
          choices: ["飲んだ", "飲みた", "飲うた", "飲だ"], a: 0,
          why: "Te-form 飲んで with だ swapped in: 飲んだ. The song works twice." },
        { t: "mc", q: "Plain past of {{する}}:",
          choices: ["した", "すった", "するた", "しました"], a: 0,
          why: "して→した. (しました is the same thing back in uniform.)" },
        { t: "build", en: "— What did you do yesterday? — I watched anime. (casual)",
          tokens: ["昨日", "何", "した", "？", "アニメ", "を", "見た"], extra: ["しました", "見ました"],
          why: "Plain past both ways: 何した？ … 見た。Casual Japanese drops every unneeded syllable." },
        { t: "mc", q: "{{お腹が空いた}} literally announces “the stomach emptied”. When do you say it?",
          choices: ["When you're hungry NOW", "After a big meal", "During surgery", "When the fridge is empty"], a: 0,
          why: "Plain-past state: the emptying happened, the hunger is the aftermath. English says “I'm hungry”; Japanese reports the event log." },
        { t: "mc", q: "Pick the correct casual sentence for “It's true!”",
          choices: ["本当だ！", "本当です だ！", "本当いだ！", "だ本当！"], a: 0,
          why: "Noun + だ. (An い-adjective would refuse the だ: すごい！ stands alone, never すごいだ — that's the giveaway of the two tribes.)" },
        { t: "type", q: "Say casually: “The curry was delicious.”",
          accept: ["カレーは美味しかった", "かれーはおいしかった", "カレーはおいしかった", "カレー美味しかった", "かれーおいしかった"],
          show: "カレーは美味[おい]しかった。",
          why: "い-adjective plain past: 美味しい→美味しかった, no です in casual mode. Compliment every curry; it's policy." },
        { t: "mc", q: "{{疲れた…}} sighed at day's end means…",
          choices: ["I'm exhausted", "I will get tired", "You look tired", "Tiredness is impossible"], a: 0,
          why: "Another plain-past state: the tiring happened, the flop onto the sofa is the result. Universal salaryman vocabulary." },
      ],
    },
    {
      id: "6.3",
      title: "Nominalizers — の・こと and “Can Do”",
      sub: "turning verbs into things: 泳ぐのが好きです・話すことができます",
      briefing: [
        ["h", "Verbs pretending to be nouns"],
        ["p", "“I like *swimming*” — English turns the verb into a noun with -ing. Japanese does it by parking {{の}} or {{こと}} after the plain form: {{泳ぐの}} / {{泳ぐこと}} = “swimming (as a thing)”. Now it can take noun particles — like the が that 好き demands:"],
        ["ex", [
          ["泳[およ]ぐのが好[す]きです。", "およぐのがすきです", "I like swimming."],
          ["漢字[かんじ]を書[か]くのは難[むずか]しいです。", "かんじをかくのはむずかしいです", "Writing kanji is difficult."],
          ["歌[うた]うことが好[す]きです。", "うたうことがすきです", "I like singing."],
        ]],
        ["p", "の feels concrete and personal; こと feels abstract and formal. For 好き/上手/下手 either works — の is more conversational. Some patterns insist on one (next paragraph insists on こと)."],
        ["h", "Ability: 〜ことができます"],
        ["p", "Plain form + {{ことができます}} = “can do”: {{日本語を話すことができます}} — “I can speak Japanese” (literally “the thing of speaking Japanese is possible” — できます is that が-club verb “to be possible/able”). Week 10 teaches the compact potential form (話せます); this longer scaffold works on every verb TODAY and is beautifully unambiguous."],
        ["ex", [
          ["ピアノを弾[ひ]くことができます。", "ぴあのをひくことができます", "I can play the piano."],
          ["ここで泳[およ]ぐことができますか。", "ここでおよぐことができますか", "Can one swim here?"],
        ]],
        ["note", "Why plain form? Nominalizers freeze the verb into a noun-phrase, and only the final verb of a sentence wears the politeness uniform. Inside the phrase, verbs stay plain: 話す**こと**ができます, never 話します**こと**. One uniform per sentence — the rule that organises all complex Japanese."],
      ],
      vocab: [
        ["こと", "こと", "koto", "thing (abstract)", "noun"],
        ["できます", "できます", "dekimasu", "to be able, be possible", "verb・ichidan"],
        ["走[はし]ります", "はしります", "hashirimasu", "to run", "verb・godan (impostor)"],
        ["歌[うた]います", "うたいます", "utaimasu", "to sing", "verb・godan"],
        ["踊[おど]ります", "おどります", "odorimasu", "to dance", "verb・godan"],
        ["運転[うんてん]", "うんてん", "unten", "driving", "noun"],
        ["漢字[かんじ]", "かんじ", "kanji", "kanji, Chinese characters", "noun"],
        ["掃除[そうじ]", "そうじ", "souji", "cleaning", "noun"],
        ["弾[ひ]きます", "ひきます", "hikimasu", "to play (an instrument)", "verb・godan"],
        ["ピアノ", "ぴあの", "piano", "piano", "noun"],
        ["ギター", "ぎたー", "gitaa", "guitar", "noun"],
      ],
      exercises: [
        { t: "build", en: "I like swimming.", tokens: ["泳ぐ", "の", "が", "好き", "です"], extra: ["泳ぎます", "を"],
          why: "Plain form + の makes “swimming” a noun; 好き then demands its が. 泳ぎますの is impossible — one uniform per sentence." },
        { t: "mc", q: "“I can speak Japanese” with this week's scaffold:",
          choices: ["日本語を話すことができます", "日本語を話しますことができます", "日本語を話すのがです", "日本語で話せことです"], a: 0,
          why: "PLAIN form + ことができます. The inner verb never wears ます — the politeness uniform goes on the final verb only." },
        { t: "mc", q: "Pick the missing piece.", jp: "漢字[かんじ]を書[か]く＿＿は難[むずか]しいです。", speak: false,
          choices: ["の", "を", "が", "です"], a: 0,
          why: "書くの = “the writing (of kanji)”, now a noun and a fine topic: writing-kanji は difficult です." },
        { t: "type", q: "Say: “I like singing.” (use 歌うの)",
          accept: ["歌うのが好きです", "うたうのがすきです"],
          show: "歌[うた]うのが好[す]きです。",
          why: "歌う (plain) + の + が好きです. Karaoke qualification, stage one." },
        { t: "mc", q: "{{運転することができません}} means…",
          choices: ["I can't drive", "I don't have a car", "Driving is forbidden here", "I won't drive today"], a: 0,
          why: "できません = negative of できます: the ability itself is absent. (Prohibition was 運転してはいけません — different beast, week 5.)" },
        { t: "build", en: "Can you play the guitar?", tokens: ["ギター", "を", "弾く", "こと", "が", "できます", "か"], extra: ["弾きます", "の"],
          why: "を belongs to 弾く inside the phrase; ことができますか wraps the ability question around it." },
      ],
    },
    {
      id: "6.4",
      title: "Before and After — 前に・てから・た後で",
      sub: "sequencing actions like a duty roster",
      briefing: [
        ["h", "Three sequencing tools"],
        ["table", ["Pattern", "Attach to", "Meaning"], [
          ["〜前[まえ]に", "dictionary form", "before doing"],
          ["〜てから", "te-form", "after doing / once done"],
          ["〜た後[あと]で", "plain past", "after doing"],
        ]],
        ["p", "Note the elegance: **前に always takes the dictionary form** (the act hasn't happened yet — it stays un-conjugated), while **後で takes た** (by the time we're “after”, it HAS happened). The grammar mirrors time itself. Nobody tells you this; it makes the whole thing memorable."],
        ["ex", [
          ["寝[ね]る前[まえ]に、歯[は]を磨[みが]きます。", "ねるまえにはをみがきます", "Before sleeping, I brush my teeth."],
          ["シャワーを浴[あ]びてから、朝[あさ]ご飯[はん]を食[た]べます。", "しゃわーをあびてからあさごはんをたべます", "After showering, I eat breakfast."],
          ["仕事[しごと]が終[お]わった後[あと]で、買[か]い物[もの]をしました。", "しごとがおわったあとでかいものをしました", "After work ended, I went shopping."],
        ]],
        ["h", "てから vs た後で"],
        ["p", "Both mean “after”, but {{てから}} implies **and then, in direct sequence** — the first action enables or leads to the second (shower → breakfast). {{た後で}} just timestamps: at some point afterwards. For morning routines and recipes, てから; for loose chronology, た後で."],
        ["p", "Bonus: 前に and 後で also take plain nouns with の: {{仕事の前に}} before work, {{晩ご飯の後で}} after dinner. The duty roster writes itself."],
        ["note", "The Japanese day is bracketed by set phrases you now can parse: 行ってきます (off I go), ただいま (I'm back), お風呂に入る (get in the bath — enters, not washes; the washing happens BEFORE the tub, a genuinely important cultural datum)."],
      ],
      vocab: [
        ["寝[ね]ます", "ねます", "nemasu", "to sleep, go to bed", "verb・ichidan"],
        ["起[お]きます", "おきます", "okimasu", "to wake up, get up", "verb・ichidan"],
        ["シャワー", "しゃわー", "shawaa", "shower", "noun"],
        ["浴[あ]びます", "あびます", "abimasu", "to take (a shower)", "verb・ichidan"],
        ["歯[は]", "は", "ha", "tooth, teeth", "noun"],
        ["磨[みが]きます", "みがきます", "migakimasu", "to brush, polish", "verb・godan"],
        ["顔[かお]", "かお", "kao", "face", "noun"],
        ["洗[あら]います", "あらいます", "araimasu", "to wash", "verb・godan"],
        ["お風呂[ふろ]", "おふろ", "ofuro", "bath", "noun"],
        ["終[お]わります", "おわります", "owarimasu", "to end, finish", "verb・godan"],
      ],
      exercises: [
        { t: "build", en: "Before sleeping, I brush my teeth.", tokens: ["寝る", "前", "に", "歯", "を", "磨きます"], extra: ["寝た", "後"],
          why: "前に takes the DICTIONARY form — the sleeping hasn't happened yet, so the verb stays unconjugated. Grammar mirroring time." },
        { t: "mc", q: "Pick the correct form.", jp: "ご飯[はん]を＿＿から、テレビを見[み]ます。", speak: false,
          choices: ["食べて", "食べる", "食べた", "食べます"], a: 0,
          why: "〜てから rides the te-form: 食べてから = “once I've eaten, then…”. Direct sequence, like a recipe step." },
        { t: "mc", q: "And this one.", jp: "映画[えいが]を＿＿後[あと]で、レストランに行[い]きました。", speak: false,
          choices: ["見た", "見る", "見て", "見ます"], a: 0,
          why: "後で takes the plain PAST — by the time we're “after”, the watching has happened. 前に=dictionary, 後で=た: time itself, encoded." },
        { t: "mc", q: "{{仕事の前にコーヒーを飲みます}} uses 前に with a noun. It means…",
          choices: ["I drink coffee before work", "I drink coffee at the front of the office", "Work comes before coffee", "I used to drink coffee"], a: 0,
          why: "Noun + の前に = “before (the noun)”. Same slot the dictionary-form verb uses. One pattern, two fuels." },
        { t: "type", q: "Say: “I wash my face.” (a modest but essential report)",
          accept: ["顔を洗います", "かおをあらいます"],
          show: "顔[かお]を洗[あら]います。",
          why: "洗う → 洗います. Slot it into today's patterns: 顔を洗ってから… / 寝る前に顔を洗います." },
        { t: "build", en: "After showering, I eat breakfast.", tokens: ["シャワー", "を", "浴びて", "から", "朝ご飯", "を", "食べます"], extra: ["浴びる", "前"],
          why: "浴びる (ichidan) → 浴びて + から: shower first, breakfast follows, in enabling sequence." },
      ],
    },
    {
      id: "6.5",
      review: true,
      title: "Mission Review 06",
      sub: "plain forms, casual talk, nominalizers, sequencing — the translator stays off",
      briefing: [
        ["h", "Debrief: fluent in off-duty Japanese"],
        ["ul", [
          "**Plain set**: 飲む・飲まない・飲んだ・飲まなかった (+だ for nouns/な-adj). ない conjugates like an い-adjective.",
          "**た-form** = te-form with た swapped in. The song pays dividends.",
          "**Register**: plain with intimates, polite with strangers; one politeness uniform per sentence, worn by the final verb.",
          "**の／こと** turn verbs into nouns; **〜ことができます** = can do.",
          "**Sequence**: 前に + dictionary (not yet happened) / てから + te / た後で + past (already happened).",
        ]],
        ["p", "Half-way through the tour. From here, plain forms start powering everything: opinions, clauses, conditionals. The foundation is laid — simulation begins."],
      ],
      vocab: [],
      exercises: [
        { t: "mc", q: "Complete the plain set for 行く: 行く・行かない・＿＿・行かなかった",
          choices: ["行った", "行いた", "行くた", "行きました"], a: 0,
          why: "The outlaw strikes twice: 行って→行った. Same irregularity, same spot." },
        { t: "mc", q: "Your friend asks {{昼ご飯、食べた？}} — you haven't. Reply casually:",
          choices: ["ううん、まだ", "いいえ、食べませんでした", "うん、食べない", "はい、食べます"], a: 0,
          why: "Casual no (ううん) + まだ (not yet). Full uniform (option 2) with a best friend sounds like resigning from the friendship." },
        { t: "build", en: "I like reading books.", tokens: ["本", "を", "読む", "の", "が", "好き", "です"], extra: ["読みます", "こと を"],
          why: "を stays with 読む inside the phrase; の nominalizes; 好き collects its が." },
        { t: "type", q: "Say: “I can speak a little Japanese.” (use ことができます)",
          accept: ["日本語を少し話すことができます", "にほんごをすこしはなすことができます", "少し日本語を話すことができます", "すこしにほんごをはなすことができます"],
          show: "日本語[にほんご]を少[すこ]し話[はな]すことができます。",
          why: "Plain 話す + ことができます, with 少し for honest modesty. Six weeks in, this sentence is simply true." },
        { t: "mc", q: "Pick the correctly-mirrored pair:",
          choices: ["寝る前に／起きた後で", "寝た前に／起きる後で", "寝て前に／起きて後で", "寝ます前に／起きます後で"], a: 0,
          why: "前に + dictionary (not yet), 後で + た (already done). If you remember one image from this week: grammar flowing the same direction as time." },
      ],
    },
  ],
});
