// lessons-extra-a.js — units 7–16 (+ new characters) for ¡Vamos!
export const EXTRA_CHARACTERS = {
  pablo:    { name: 'Pablo',    city: 'Barcelona',      country: 'España',    lang: 'es-ES', skin: '#eab387', hair: '#2e2018', hairH: 19, lip: '#b04a30', chip: '#2f6f8f' },
  sofia:    { name: 'Sofía',    city: 'Medellín',       country: 'Colombia',  lang: 'es-CO', skin: '#e2a06e', hair: '#181008', hairH: 25, lip: '#a4442a', chip: '#c75b39' },
  andres:   { name: 'Andrés',   city: 'Quito',          country: 'Ecuador',   lang: 'es-EC', skin: '#cf9058', hair: '#100a05', hairH: 18, lip: '#8f3c24', chip: '#20635b' },
  marta:    { name: 'Marta',    city: 'Granada',        country: 'España',    lang: 'es-ES', skin: '#f1bd8e', hair: '#6b4423', hairH: 25, lip: '#c2452d', chip: '#b0812c' },
  javier:   { name: 'Javier',   city: 'Cusco',          country: 'Perú',      lang: 'es-PE', skin: '#c98a52', hair: '#0d0803', hairH: 17, lip: '#8f3c24', chip: '#7d5296' },
  elena:    { name: 'Elena',    city: 'Montevideo',     country: 'Uruguay',   lang: 'es-UY', skin: '#f2c294', hair: '#8a5a2b', hairH: 26, lip: '#c2452d', chip: '#3f6f9e' },
  nico:     { name: 'Nico',     city: 'Valparaíso',     country: 'Chile',     lang: 'es-CL', skin: '#e6ad7d', hair: '#241811', hairH: 20, lip: '#a4442a', chip: '#bb4444' },
  tomas:    { name: 'Tomás',    city: 'Córdoba',        country: 'Argentina', lang: 'es-AR', skin: '#edb488', hair: '#3f2b1a', hairH: 18, lip: '#b04a30', chip: '#2f6f8f' },
  paula:    { name: 'Paula',    city: 'La Paz',         country: 'Bolivia',   lang: 'es-BO', skin: '#cd8f57', hair: '#120c06', hairH: 26, lip: '#8f3c24', chip: '#c75b39' },
  isabela:  { name: 'Isabela',  city: 'Caracas',        country: 'Venezuela', lang: 'es-VE', skin: '#dda071', hair: '#1c1209', hairH: 24, lip: '#a4442a', chip: '#20635b' },
  iker:     { name: 'Iker',     city: 'Bilbao',         country: 'España',    lang: 'es-ES', skin: '#efc39a', hair: '#171310', hairH: 18, lip: '#b04a30', chip: '#b0812c' },
  valeria:  { name: 'Valeria',  city: 'Cartagena',      country: 'Colombia',  lang: 'es-CO', skin: '#c98a5b', hair: '#100a06', hairH: 25, lip: '#8f3c24', chip: '#3f6f9e' },
  martin:   { name: 'Martín',   city: 'Mendoza',        country: 'Argentina', lang: 'es-AR', skin: '#e9b184', hair: '#33231a', hairH: 19, lip: '#b04a30', chip: '#7d5296' },
  ines:     { name: 'Inés',     city: 'Salamanca',      country: 'España',    lang: 'es-ES', skin: '#f3c497', hair: '#4a3018', hairH: 25, lip: '#c2452d', chip: '#bb4444' },
  franco:   { name: 'Franco',   city: 'Bariloche',      country: 'Argentina', lang: 'es-AR', skin: '#e5aa78', hair: '#26170d', hairH: 18, lip: '#a4442a', chip: '#2f6f8f' },
  daniela:  { name: 'Daniela',  city: 'Guayaquil',      country: 'Ecuador',   lang: 'es-EC', skin: '#d59a63', hair: '#140d07', hairH: 24, lip: '#8f3c24', chip: '#c75b39' },
  aitana:   { name: 'Aitana',   city: 'Valencia',       country: 'España',    lang: 'es-ES', skin: '#f0bd90', hair: '#5f3d1e', hairH: 26, lip: '#c2452d', chip: '#20635b' },
  rosa:     { name: 'Rosa',     city: 'Arequipa',       country: 'Perú',      lang: 'es-PE', skin: '#cc8d55', hair: '#0f0904', hairH: 25, lip: '#8f3c24', chip: '#b0812c' },
  agustina: { name: 'Agustina', city: 'Punta del Este', country: 'Uruguay',   lang: 'es-UY', skin: '#eeb98c', hair: '#7a4a21', hairH: 25, lip: '#c2452d', chip: '#7d5296' },
};

export const EXTRA_UNITS_A = [
  {
    id: 'u7', city: 'Barcelona', country: 'España', char: 'pablo', color: '#2f6f8f',
    title: 'Los colores y la ropa',
    lessons: [
      { id: 'u7l1', t: 'Los colores',
        intro: '¡Hola! Soy Pablo, de Barcelona. Aquí Gaudí pintó la ciudad de mil colores. Empecemos por ellos.',
        tip: ['Color agreement', 'Colors are adjectives and agree: el coche rojo, la casa roja. Azul and verde don’t change for gender.'],
        v: [['rojo', 'red'], ['azul', 'blue'], ['verde', 'green'], ['amarillo', 'yellow'], ['negro', 'black'], ['blanco', 'white']],
        s: [['El vestido es azul', 'The dress is blue'], ['Me gusta el color rojo', 'I like the color red']],
        f: [
          { q: 'La casa es ___.', o: ['blanca', 'blanco', 'blancos'], a: 'blanca', h: 'The house is white.' },
          { q: 'El gato es ___.', o: ['negro', 'negra', 'negras'], a: 'negro', h: 'The cat is black.' },
        ] },
      { id: 'u7l2', t: 'La ropa',
        intro: 'El Barrio Gótico está lleno de tiendas pequeñas. Hoy: las palabras de la ropa.',
        tip: ['Plural clothes', 'Some clothes are always plural in Spanish: los pantalones, los vaqueros (jeans).'],
        v: [['la camisa', 'the shirt'], ['los pantalones', 'the pants'], ['el vestido', 'the dress'], ['los zapatos', 'the shoes'], ['la chaqueta', 'the jacket'], ['el sombrero', 'the hat']],
        s: [['Llevo una camisa verde', 'I wear a green shirt'], ['Los zapatos son nuevos', 'The shoes are new']],
        f: [
          { q: 'Los ___ son negros.', o: ['pantalones', 'pantalón', 'vestido'], a: 'pantalones', h: 'The pants are black.' },
          { q: 'Me gusta tu ___ roja.', o: ['chaqueta', 'sombrero', 'zapatos'], a: 'chaqueta', h: 'I like your red jacket.' },
        ] },
      { id: 'u7l3', t: '¿Qué llevas?',
        intro: '“Llevar” sirve para la ropa: llevo, llevas, lleva. ¿Qué llevas tú hoy?',
        tip: ['Llevar', '“Llevar” means to wear (and to carry): llevo gafas = I wear glasses / I’m carrying glasses.'],
        v: [['llevar', 'to wear'], ['llevo', 'I wear'], ['bonito', 'pretty'], ['feo', 'ugly'], ['cómodo', 'comfortable'], ['la talla', 'the size']],
        s: [['Llevo un sombrero bonito', 'I wear a pretty hat'], ['¿Qué talla llevas?', 'What size do you wear?']],
        f: [
          { q: 'Este vestido es muy ___.', o: ['bonito', 'bonita', 'bonitos'], a: 'bonito', h: 'This dress is very pretty.' },
          { q: 'Estos zapatos son muy ___.', o: ['cómodos', 'cómodo', 'cómoda'], a: 'cómodos', h: 'These shoes are very comfortable.' },
        ] },
      { id: 'u7l4', t: 'El estilo',
        intro: 'En el Passeig de Gràcia, la moda es arte. Hablemos de estilos.',
        tip: ['Muy + adjective', '“Muy” never changes: muy moderno, muy moderna, muy modernos. Easy!'],
        v: [['la moda', 'the fashion'], ['moderno', 'modern'], ['elegante', 'elegant'], ['sencillo', 'simple'], ['el estilo', 'the style'], ['favorito', 'favorite']],
        s: [['Mi color favorito es el verde', 'My favorite color is green'], ['El estilo de Pablo es moderno', 'The style of Pablo is modern']],
        f: [
          { q: 'La moda de Barcelona es muy ___.', o: ['moderna', 'moderno', 'modernos'], a: 'moderna', h: 'Barcelona fashion is very modern.' },
          { q: 'Mi ___ favorito es sencillo.', o: ['estilo', 'moda', 'talla'], a: 'estilo', h: 'My favorite style is simple.' },
        ] },
      { id: 'u7l5', t: 'Comprar ropa',
        intro: 'Última parada: el probador. Frases para comprar ropa sin miedo.',
        tip: ['Quedar bien', '“Me queda bien” = it fits me well. “Te queda genial” = it looks great on you.'],
        v: [['el probador', 'the fitting room'], ['quedar bien', 'to fit well'], ['demasiado', 'too (much)'], ['otro', 'another'], ['el descuento', 'the discount'], ['el color', 'the color']],
        s: [['¿Tiene otro color?', 'Do you have another color?'], ['La chaqueta queda bien', 'The jacket fits well']],
        f: [
          { q: 'Es ___ caro para mí.', o: ['demasiado', 'demasiada', 'muchos'], a: 'demasiado', h: 'It is too expensive for me.' },
          { q: 'Hay un ___ del veinte por ciento.', o: ['descuento', 'probador', 'precio'], a: 'descuento', h: 'There is a twenty percent discount.' },
        ] },
    ],
  },
  {
    id: 'u8', city: 'Medellín', country: 'Colombia', char: 'sofia', color: '#c75b39',
    title: 'El cuerpo y la salud',
    lessons: [
      { id: 'u8l1', t: 'El cuerpo',
        intro: '¡Hola! Soy Sofía, de Medellín, la ciudad de la eterna primavera. Hoy: el cuerpo humano.',
        tip: ['Body + article', 'Spanish uses the article with body parts: me duele la cabeza (not “mi cabeza”).'],
        v: [['la cabeza', 'the head'], ['la mano', 'the hand'], ['el pie', 'the foot'], ['el brazo', 'the arm'], ['la pierna', 'the leg'], ['el ojo', 'the eye']],
        s: [['Me duele la cabeza', 'My head hurts'], ['Tengo dos manos', 'I have two hands']],
        f: [
          { q: 'Me duele ___ cabeza.', o: ['la', 'mi', 'el'], a: 'la', h: 'My head hurts.' },
          { q: 'La ___ es parte del cuerpo.', o: ['mano', 'casa', 'silla'], a: 'mano', h: 'The hand is part of the body.' },
        ] },
      { id: 'u8l2', t: '¿Cómo te sientes?',
        intro: '¿Estás bien? Hoy aprendes a decir cómo te sientes de verdad.',
        tip: ['Me duele(n)', 'One thing hurts: me duele la mano. Several: me duelen los pies. Like “gustar”.'],
        v: [['me duele', 'it hurts me'], ['enfermo', 'sick'], ['sano', 'healthy'], ['el dolor', 'the pain'], ['la fiebre', 'the fever'], ['mareado', 'dizzy']],
        s: [['Estoy enfermo hoy', 'I am sick today'], ['Me duelen los pies', 'My feet hurt']],
        f: [
          { q: 'Me ___ los brazos.', o: ['duelen', 'duele', 'dolor'], a: 'duelen', h: 'My arms hurt.' },
          { q: 'Tengo ___ y dolor de cabeza.', o: ['fiebre', 'sano', 'pie'], a: 'fiebre', h: 'I have a fever and a headache.' },
        ] },
      { id: 'u8l3', t: 'En la farmacia',
        intro: 'Si algo te duele, vamos a la farmacia de la esquina. Yo te acompaño.',
        tip: ['Necesitar', '“Necesito” + noun or verb: necesito medicina, necesito descansar. No preposition needed.'],
        v: [['la farmacia', 'the pharmacy'], ['la medicina', 'the medicine'], ['la pastilla', 'the pill'], ['la receta', 'the prescription'], ['necesitar', 'to need'], ['ayudar', 'to help']],
        s: [['Necesito una pastilla, por favor', 'I need a pill, please'], ['La farmacia está cerca', 'The pharmacy is near']],
        f: [
          { q: '___ una medicina para el dolor.', o: ['Necesito', 'Necesitas', 'Necesitar'], a: 'Necesito', h: 'I need a medicine for the pain.' },
          { q: '¿Me puede ___, por favor?', o: ['ayudar', 'ayudo', 'ayuda'], a: 'ayudar', h: 'Can you help me, please?' },
        ] },
      { id: 'u8l4', t: 'El médico',
        intro: 'Una cita con el médico no da miedo si sabes qué decir. Practiquemos.',
        tip: ['Mejor', '“Mejor” = better (irregular): me siento mejor. “Mucho mejor” = much better.'],
        v: [['la cita', 'the appointment'], ['la salud', 'the health'], ['el hospital', 'the hospital'], ['la enfermera', 'the nurse'], ['descansar', 'to rest'], ['mejor', 'better']],
        s: [['Tengo una cita con el médico', 'I have an appointment with the doctor'], ['Necesitas descansar más', 'You need to rest more']],
        f: [
          { q: 'Hoy me siento ___.', o: ['mejor', 'mejora', 'bueno'], a: 'mejor', h: 'Today I feel better.' },
          { q: 'La ___ trabaja en el hospital.', o: ['enfermera', 'cita', 'salud'], a: 'enfermera', h: 'The nurse works at the hospital.' },
        ] },
      { id: 'u8l5', t: 'Vida sana',
        intro: 'En Medellín subimos el cerro los domingos. Ejercicio, aire y buena energía.',
        tip: ['Hacer ejercicio', 'Spanish “does” exercise: hago ejercicio. Also: hacer yoga, hacer deporte.'],
        v: [['hacer ejercicio', 'to exercise'], ['el ejercicio', 'the exercise'], ['fuerte', 'strong'], ['débil', 'weak'], ['la energía', 'the energy'], ['respirar', 'to breathe']],
        s: [['Hago ejercicio todos los días', 'I exercise every day'], ['Tengo mucha energía hoy', 'I have a lot of energy today']],
        f: [
          { q: 'Mis piernas son muy ___.', o: ['fuertes', 'fuerte', 'fuertas'], a: 'fuertes', h: 'My legs are very strong.' },
          { q: '___ ejercicio por la mañana.', o: ['Hago', 'Hace', 'Hacer'], a: 'Hago', h: 'I exercise in the morning.' },
        ] },
    ],
  },
  {
    id: 'u9', city: 'Quito', country: 'Ecuador', char: 'andres', color: '#20635b',
    title: 'La naturaleza y los animales',
    lessons: [
      { id: 'u9l1', t: 'Los animales',
        intro: '¡Hola! Soy Andrés, de Quito, en la mitad del mundo. Ecuador es pura naturaleza.',
        tip: ['Animal genders', 'El perro / la perra, el gato / la gata — but el pez and el pájaro don’t change.'],
        v: [['el perro', 'the dog'], ['el gato', 'the cat'], ['el pájaro', 'the bird'], ['el pez', 'the fish'], ['el caballo', 'the horse'], ['la vaca', 'the cow']],
        s: [['Mi perro es muy grande', 'My dog is very big'], ['El pájaro canta por la mañana', 'The bird sings in the morning']],
        f: [
          { q: 'El ___ vive en el agua.', o: ['pez', 'perro', 'caballo'], a: 'pez', h: 'The fish lives in the water.' },
          { q: 'La ___ da leche.', o: ['vaca', 'gata', 'pájara'], a: 'vaca', h: 'The cow gives milk.' },
        ] },
      { id: 'u9l2', t: 'La selva',
        intro: 'A pocas horas de Quito empieza la Amazonía. Árboles, ríos y vida por todas partes.',
        tip: ['Hay', '“Hay” = there is AND there are: hay un río, hay muchos árboles. One word, both meanings.'],
        v: [['la selva', 'the jungle'], ['el árbol', 'the tree'], ['la flor', 'the flower'], ['el río', 'the river'], ['la montaña', 'the mountain'], ['el volcán', 'the volcano']],
        s: [['Hay muchos árboles en la selva', 'There are many trees in the jungle'], ['El volcán está cerca de Quito', 'The volcano is near Quito']],
        f: [
          { q: '___ muchas flores en el jardín.', o: ['Hay', 'Es', 'Está'], a: 'Hay', h: 'There are many flowers in the garden.' },
          { q: 'El ___ Amazonas es muy largo.', o: ['río', 'árbol', 'volcán'], a: 'río', h: 'The Amazon river is very long.' },
        ] },
      { id: 'u9l3', t: 'El cielo andino',
        intro: 'De noche, desde el teleférico, se ven todas las estrellas. Mira arriba.',
        tip: ['El sol, la luna', 'Sun is masculine, moon is feminine — poets love this pair: el sol y la luna.'],
        v: [['el cielo', 'the sky'], ['la estrella', 'the star'], ['la luna', 'the moon'], ['el sol', 'the sun'], ['la nube', 'the cloud'], ['la altura', 'the altitude']],
        s: [['La luna está en el cielo', 'The moon is in the sky'], ['Quito está a mucha altura', 'Quito is at high altitude']],
        f: [
          { q: 'De noche veo las ___.', o: ['estrellas', 'nubes', 'soles'], a: 'estrellas', h: 'At night I see the stars.' },
          { q: 'El ___ sale por la mañana.', o: ['sol', 'luna', 'cielo'], a: 'sol', h: 'The sun rises in the morning.' },
        ] },
      { id: 'u9l4', t: 'Animales andinos',
        intro: 'El cóndor, la llama, el mono… Aquí viven animales únicos en el mundo.',
        tip: ['La llama', 'Llama (animal), llama (he/she calls) and flame (una llama) — context is everything!'],
        v: [['la llama', 'the llama'], ['el cóndor', 'the condor'], ['la tortuga', 'the turtle'], ['el mono', 'the monkey'], ['la rana', 'the frog'], ['la mariposa', 'the butterfly']],
        s: [['El cóndor vuela sobre los Andes', 'The condor flies over the Andes'], ['La tortuga vive muchos años', 'The turtle lives many years']],
        f: [
          { q: 'La ___ es un animal de los Andes.', o: ['llama', 'rana', 'mariposa'], a: 'llama', h: 'The llama is an animal of the Andes.' },
          { q: 'El ___ vive en los árboles.', o: ['mono', 'pez', 'cóndor'], a: 'mono', h: 'The monkey lives in the trees.' },
        ] },
      { id: 'u9l5', t: 'Cuidar la tierra',
        intro: 'La naturaleza nos da todo. Última lección de Quito: cómo cuidarla.',
        tip: ['Cuidar', '“Cuidar” = to take care of. No extra preposition: cuido el jardín, cuido a mi perro (a for beings).'],
        v: [['la tierra', 'the earth'], ['el aire', 'the air'], ['limpio', 'clean'], ['sucio', 'dirty'], ['cuidar', 'to take care of'], ['proteger', 'to protect']],
        s: [['Debemos proteger la selva', 'We must protect the jungle'], ['El aire de la montaña es limpio', 'The mountain air is clean']],
        f: [
          { q: 'El río está ___.', o: ['sucio', 'sucia', 'sucios'], a: 'sucio', h: 'The river is dirty.' },
          { q: 'Hay que ___ los animales.', o: ['proteger', 'protege', 'protejo'], a: 'proteger', h: 'We must protect the animals.' },
        ] },
    ],
  },
  {
    id: 'u10', city: 'Granada', country: 'España', char: 'marta', color: '#b0812c',
    title: 'La casa',
    lessons: [
      { id: 'u10l1', t: 'Las habitaciones',
        intro: '¡Hola! Soy Marta, de Granada. Mi casa del Albaicín tiene vistas a la Alhambra. Pasa, pasa.',
        tip: ['La habitación', 'Room in general = la habitación; bedroom = el dormitorio (or el cuarto in Latin America).'],
        v: [['la casa', 'the house'], ['la cocina', 'the kitchen'], ['el baño', 'the bathroom'], ['el dormitorio', 'the bedroom'], ['la sala', 'the living room'], ['la puerta', 'the door']],
        s: [['La cocina está al lado del baño', 'The kitchen is next to the bathroom'], ['Mi casa tiene tres dormitorios', 'My house has three bedrooms']],
        f: [
          { q: 'Cocino en la ___.', o: ['cocina', 'sala', 'puerta'], a: 'cocina', h: 'I cook in the kitchen.' },
          { q: 'El ___ está arriba.', o: ['dormitorio', 'dormitoria', 'puerta'], a: 'dormitorio', h: 'The bedroom is upstairs.' },
        ] },
      { id: 'u10l2', t: 'Los muebles',
        intro: 'Cama, sofá, espejo… Los muebles de una casa andaluza, con sus patios llenos de luz.',
        tip: ['En', '“En” covers in/on/at: el libro está en la mesa, estoy en casa, vivo en Granada.'],
        v: [['la cama', 'the bed'], ['la silla', 'the chair'], ['el sofá', 'the sofa'], ['la lámpara', 'the lamp'], ['el espejo', 'the mirror'], ['la ventana', 'the window']],
        s: [['El sofá está en la sala', 'The sofa is in the living room'], ['Hay un espejo en el baño', 'There is a mirror in the bathroom']],
        f: [
          { q: 'Duermo en la ___.', o: ['cama', 'silla', 'lámpara'], a: 'cama', h: 'I sleep in the bed.' },
          { q: 'La ___ da mucha luz.', o: ['ventana', 'cama', 'silla'], a: 'ventana', h: 'The window gives a lot of light.' },
        ] },
      { id: 'u10l3', t: 'Las tareas',
        intro: 'En mi casa todos ayudamos: uno cocina, otro limpia. Las tareas del hogar.',
        tip: ['Hay que', '“Hay que” + infinitive = one must / you have to (impersonal): hay que limpiar.'],
        v: [['limpiar', 'to clean'], ['cocinar', 'to cook'], ['lavar', 'to wash'], ['ordenar', 'to tidy'], ['el plato', 'the dish'], ['la basura', 'the trash']],
        s: [['Hay que lavar los platos', 'The dishes must be washed'], ['Limpio la cocina los sábados', 'I clean the kitchen on Saturdays']],
        f: [
          { q: 'Voy a ___ mi dormitorio.', o: ['ordenar', 'ordeno', 'ordenas'], a: 'ordenar', h: 'I am going to tidy my bedroom.' },
          { q: 'Saca la ___, por favor.', o: ['basura', 'plato', 'cocina'], a: 'basura', h: 'Take out the trash, please.' },
        ] },
      { id: 'u10l4', t: 'Mi barrio',
        intro: 'El Albaicín es un barrio de calles estrechas y jardines secretos. Te lo enseño.',
        tip: ['El piso', 'In Spain, “el piso” = apartment. In Latin America it usually means the floor!'],
        v: [['el barrio', 'the neighborhood'], ['el jardín', 'the garden'], ['el piso', 'the apartment'], ['la terraza', 'the terrace'], ['el garaje', 'the garage'], ['el ascensor', 'the elevator']],
        s: [['Mi barrio tiene muchos jardines', 'My neighborhood has many gardens'], ['El piso no tiene ascensor', 'The apartment has no elevator']],
        f: [
          { q: 'Tomo café en la ___.', o: ['terraza', 'garaje', 'ascensor'], a: 'terraza', h: 'I have coffee on the terrace.' },
          { q: 'El coche está en el ___.', o: ['garaje', 'jardín', 'barrio'], a: 'garaje', h: 'The car is in the garage.' },
        ] },
      { id: 'u10l5', t: 'Buscar casa',
        intro: '¿Buscas piso en Granada? Aprende las palabras de los anuncios.',
        tip: ['Adjective order', 'Adjectives usually go AFTER the noun in Spanish: un piso luminoso, una casa tranquila.'],
        v: [['el alquiler', 'the rent'], ['amueblado', 'furnished'], ['luminoso', 'bright'], ['tranquilo', 'quiet'], ['céntrico', 'central'], ['hay', 'there is']],
        s: [['El piso es luminoso y céntrico', 'The apartment is bright and central'], ['El alquiler es muy caro', 'The rent is very expensive']],
        f: [
          { q: 'Busco un piso ___.', o: ['amueblado', 'amueblada', 'amueblados'], a: 'amueblado', h: 'I am looking for a furnished apartment.' },
          { q: 'El barrio es muy ___.', o: ['tranquilo', 'tranquila', 'tranquilos'], a: 'tranquilo', h: 'The neighborhood is very quiet.' },
        ] },
    ],
  },
  {
    id: 'u11', city: 'Cusco', country: 'Perú', char: 'javier', color: '#7d5296',
    title: 'La hora y los números',
    lessons: [
      { id: 'u11l1', t: 'Números 11–20',
        intro: '¡Hola! Soy Javier, de Cusco, la antigua capital inca. Los incas eran maestros de los números.',
        tip: ['11–15 are special', 'Once, doce, trece, catorce, quince. From 16: dieciséis (diez y seis together).'],
        v: [['once', 'eleven'], ['doce', 'twelve'], ['trece', 'thirteen'], ['quince', 'fifteen'], ['dieciocho', 'eighteen'], ['veinte', 'twenty']],
        s: [['Tengo quince soles', 'I have fifteen soles'], ['El tren sale en veinte minutos', 'The train leaves in twenty minutes']],
        f: [
          { q: 'Diez más cinco son ___.', o: ['quince', 'doce', 'veinte'], a: 'quince', h: 'Ten plus five is fifteen.' },
          { q: 'Diez más diez son ___.', o: ['veinte', 'once', 'trece'], a: 'veinte', h: 'Ten plus ten is twenty.' },
        ] },
      { id: 'u11l2', t: 'Cientos y miles',
        intro: 'Machu Picchu está a más de dos mil metros. Números grandes para lugares grandes.',
        tip: ['Cien vs. ciento', 'Exactly 100 = cien. 101+ = ciento uno, ciento dos… 500 is irregular: quinientos.'],
        v: [['treinta', 'thirty'], ['cuarenta', 'forty'], ['cincuenta', 'fifty'], ['cien', 'one hundred'], ['quinientos', 'five hundred'], ['mil', 'one thousand']],
        s: [['La entrada cuesta cincuenta soles', 'The ticket costs fifty soles'], ['Hay mil turistas hoy', 'There are a thousand tourists today']],
        f: [
          { q: 'Cincuenta más cincuenta son ___.', o: ['cien', 'mil', 'quinientos'], a: 'cien', h: 'Fifty plus fifty is one hundred.' },
          { q: 'Hay más de ___ personas.', o: ['mil', 'miles', 'milo'], a: 'mil', h: 'There are more than a thousand people.' },
        ] },
      { id: 'u11l3', t: '¿Qué hora es?',
        intro: 'El tren a Machu Picchu no espera. ¡Aprende a decir la hora!',
        tip: ['Telling time', 'Es la una (1:00), son las dos (2:00+). Half past = y media; quarter past = y cuarto.'],
        v: [['la hora', 'the time'], ['el reloj', 'the clock'], ['en punto', 'o’clock'], ['y media', 'half past'], ['y cuarto', 'quarter past'], ['el minuto', 'the minute']],
        s: [['Son las tres y media', 'It is half past three'], ['El tren sale a las ocho en punto', 'The train leaves at eight o’clock']],
        f: [
          { q: '___ las cinco y cuarto.', o: ['Son', 'Es', 'Está'], a: 'Son', h: 'It is quarter past five.' },
          { q: 'Es la una ___.', o: ['en punto', 'en puntos', 'y punto'], a: 'en punto', h: 'It is one o’clock.' },
        ] },
      { id: 'u11l4', t: 'El calendario',
        intro: 'Junio en Cusco es el mes del Inti Raymi, la fiesta del sol. ¿Qué fecha es hoy?',
        tip: ['Dates', 'Spanish says day-month: el quince de junio. Months are lowercase, like days.'],
        v: [['el mes', 'the month'], ['enero', 'January'], ['junio', 'June'], ['diciembre', 'December'], ['la fecha', 'the date'], ['el cumpleaños', 'the birthday']],
        s: [['Mi cumpleaños es en diciembre', 'My birthday is in December'], ['Junio es un mes frío en Cusco', 'June is a cold month in Cusco']],
        f: [
          { q: 'El año empieza en ___.', o: ['enero', 'junio', 'diciembre'], a: 'enero', h: 'The year begins in January.' },
          { q: '¿Cuál es la ___ de hoy?', o: ['fecha', 'mes', 'hora'], a: 'fecha', h: 'What is today’s date?' },
        ] },
      { id: 'u11l5', t: 'Las estaciones',
        intro: 'Cuando en España es verano, aquí es invierno. ¡El hemisferio sur al revés!',
        tip: ['Reversed seasons', 'South of the equator the seasons flip: Christmas in Argentina is summer!'],
        v: [['la primavera', 'the spring'], ['el invierno', 'the winter'], ['el otoño', 'the autumn'], ['la estación', 'the season'], ['empezar', 'to begin'], ['terminar', 'to end']],
        s: [['El invierno empieza en junio aquí', 'Winter begins in June here'], ['Me gusta la primavera', 'I like spring']],
        f: [
          { q: 'Las clases ___ en marzo.', o: ['empiezan', 'empieza', 'empezar'], a: 'empiezan', h: 'Classes begin in March.' },
          { q: 'El verano ___ en marzo aquí.', o: ['termina', 'terminan', 'terminar'], a: 'termina', h: 'Summer ends in March here.' },
        ] },
    ],
  },
  {
    id: 'u12', city: 'Montevideo', country: 'Uruguay', char: 'elena', color: '#3f6f9e',
    title: 'Los sentimientos',
    lessons: [
      { id: 'u12l1', t: 'Emociones',
        intro: '¡Hola! Soy Elena, de Montevideo. Con un mate en la rambla, hablemos de emociones.',
        tip: ['Estar + emotion', 'Emotions are states → estar: estoy feliz, está triste. They change, like the weather.'],
        v: [['feliz', 'happy'], ['triste', 'sad'], ['enojado', 'angry'], ['nervioso', 'nervous'], ['contento', 'glad'], ['preocupado', 'worried']],
        s: [['Estoy muy feliz hoy', 'I am very happy today'], ['¿Por qué estás triste?', 'Why are you sad?']],
        f: [
          { q: 'Ella está ___ por el examen.', o: ['nerviosa', 'nervioso', 'nerviosos'], a: 'nerviosa', h: 'She is nervous about the exam.' },
          { q: 'Estamos muy ___ con la noticia.', o: ['contentos', 'contento', 'contenta'], a: 'contentos', h: 'We are very glad about the news.' },
        ] },
      { id: 'u12l2', t: 'Tener hambre, tener sueño',
        intro: 'En español no “estás” hambriento: “tienes” hambre. Un truco muy útil.',
        tip: ['Tener expressions', 'Spanish “has” feelings: tengo hambre (hunger), tengo sed (thirst), tengo miedo (fear).'],
        v: [['tener hambre', 'to be hungry'], ['tener sed', 'to be thirsty'], ['tener sueño', 'to be sleepy'], ['tener miedo', 'to be afraid'], ['tener frío', 'to be cold'], ['tener razón', 'to be right']],
        s: [['Tengo hambre y sed', 'I am hungry and thirsty'], ['El niño tiene sueño', 'The boy is sleepy']],
        f: [
          { q: '___ mucha hambre.', o: ['Tengo', 'Estoy', 'Soy'], a: 'Tengo', h: 'I am very hungry.' },
          { q: 'Tú siempre tienes ___.', o: ['razón', 'razones', 'razona'], a: 'razón', h: 'You are always right.' },
        ] },
      { id: 'u12l3', t: 'El amor y la amistad',
        intro: 'El tango nació en este río. Hablemos de amor, abrazos y amistad.',
        tip: ['Querer', '“Querer” = to want AND to love: quiero un café / te quiero (I love you).'],
        v: [['el amor', 'the love'], ['querer', 'to love'], ['el corazón', 'the heart'], ['el beso', 'the kiss'], ['el abrazo', 'the hug'], ['extrañar', 'to miss (someone)']],
        s: [['Te quiero con todo el corazón', 'I love you with all my heart'], ['Extraño a mi familia', 'I miss my family']],
        f: [
          { q: 'Un ___ fuerte para ti.', o: ['abrazo', 'abraza', 'brazo'], a: 'abrazo', h: 'A big hug for you.' },
          { q: '___ mucho a mis amigos.', o: ['Extraño', 'Extraña', 'Extrañar'], a: 'Extraño', h: 'I miss my friends a lot.' },
        ] },
      { id: 'u12l4', t: 'Dar opiniones',
        intro: 'Los uruguayos discutimos de fútbol con pasión pero con respeto. “Creo que…”, “me parece…”',
        tip: ['Creo que', 'Start opinions with “creo que” or “me parece que” + normal sentence. Easy and natural.'],
        v: [['creo que', 'I think that'], ['pienso', 'I think'], ['me parece', 'it seems to me'], ['estar de acuerdo', 'to agree'], ['quizás', 'maybe'], ['claro', 'of course']],
        s: [['Creo que tienes razón', 'I think you are right'], ['Estoy de acuerdo contigo', 'I agree with you']],
        f: [
          { q: '___ que el mate es delicioso.', o: ['Creo', 'Creer', 'Cree'], a: 'Creo', h: 'I think mate is delicious.' },
          { q: 'Me ___ una buena idea.', o: ['parece', 'parezco', 'parecer'], a: 'parece', h: 'It seems like a good idea to me.' },
        ] },
      { id: 'u12l5', t: '¿Por qué?',
        intro: 'La palabra favorita de los niños: ¿por qué? Y su respuesta: porque.',
        tip: ['Por qué vs. porque', 'Question: ¿por qué? (two words + accent). Answer: porque (one word): ¿Por qué estudias? Porque me gusta.'],
        v: [['¿por qué?', 'why?'], ['porque', 'because'], ['la razón', 'the reason'], ['sentir', 'to feel'], ['peor', 'worse'], ['igual', 'the same']],
        s: [['Estudio porque me gusta', 'I study because I like it'], ['¿Por qué estás preocupado?', 'Why are you worried?']],
        f: [
          { q: '¿___ estás feliz?', o: ['Por qué', 'Porque', 'Para qué'], a: 'Por qué', h: 'Why are you happy?' },
          { q: 'No voy ___ tengo sueño.', o: ['porque', 'por qué', 'para'], a: 'porque', h: 'I am not going because I am sleepy.' },
        ] },
    ],
  },
  {
    id: 'u13', city: 'Valparaíso', country: 'Chile', char: 'nico', color: '#bb4444',
    title: 'El arte y la música',
    lessons: [
      { id: 'u13l1', t: 'La música',
        intro: '¡Hola! Soy Nico, de Valparaíso, la ciudad de los cerros pintados. Aquí todo suena a música.',
        tip: ['Tocar vs. jugar', 'Instruments use “tocar”: toco la guitarra. Games and sports use “jugar”.'],
        v: [['la canción', 'the song'], ['la guitarra', 'the guitar'], ['el ritmo', 'the rhythm'], ['la voz', 'the voice'], ['tocar', 'to play (music)'], ['escuchar', 'to listen']],
        s: [['Toco la guitarra por la noche', 'I play the guitar at night'], ['Me gusta escuchar canciones', 'I like to listen to songs']],
        f: [
          { q: 'Ella ___ el piano muy bien.', o: ['toca', 'juega', 'toco'], a: 'toca', h: 'She plays the piano very well.' },
          { q: 'Esa canción tiene buen ___.', o: ['ritmo', 'voz', 'guitarra'], a: 'ritmo', h: 'That song has a good rhythm.' },
        ] },
      { id: 'u13l2', t: 'El baile',
        intro: 'Rápido o lento, el que baila gana. ¿Bailamos?',
        tip: ['Adverbs of manner', 'Bailar rápido, hablar lento — many adjectives work as adverbs in speech.'],
        v: [['el baile', 'the dance'], ['bailar', 'to dance'], ['el paso', 'the step'], ['rápido', 'fast'], ['lento', 'slow'], ['mover', 'to move']],
        s: [['Me gusta bailar contigo', 'I like to dance with you'], ['Este baile es muy rápido', 'This dance is very fast']],
        f: [
          { q: 'El tango es un baile ___.', o: ['lento', 'lenta', 'lentos'], a: 'lento', h: 'Tango is a slow dance.' },
          { q: 'Aprendo un ___ nuevo.', o: ['paso', 'pasa', 'pie'], a: 'paso', h: 'I am learning a new step.' },
        ] },
      { id: 'u13l3', t: 'Los murales',
        intro: 'En Valparaíso las paredes hablan: cada cerro es un museo al aire libre.',
        tip: ['Pintar / pintor / pintura', 'One family: pintar (verb), el pintor (person), la pintura (painting/paint).'],
        v: [['el arte', 'the art'], ['el mural', 'the mural'], ['la pintura', 'the painting'], ['el pintor', 'the painter'], ['pintar', 'to paint'], ['la pared', 'the wall']],
        s: [['El pintor pinta un mural', 'The painter paints a mural'], ['Las paredes tienen mucho arte', 'The walls have a lot of art']],
        f: [
          { q: 'Ella ___ un mural enorme.', o: ['pinta', 'pinto', 'pintar'], a: 'pinta', h: 'She paints a huge mural.' },
          { q: 'La ___ está llena de colores.', o: ['pared', 'pintor', 'arte'], a: 'pared', h: 'The wall is full of colors.' },
        ] },
      { id: 'u13l4', t: 'El cine y el teatro',
        intro: 'Los viernes vamos al cine del puerto. ¿Película o teatro?',
        tip: ['La entrada', 'Ticket for events = la entrada. Transport ticket = el boleto / el billete.'],
        v: [['la película', 'the movie'], ['el actor', 'the actor'], ['el teatro', 'the theater'], ['la entrada', 'the ticket (event)'], ['famoso', 'famous'], ['actuar', 'to act']],
        s: [['La película empieza a las nueve', 'The movie starts at nine'], ['El actor es muy famoso', 'The actor is very famous']],
        f: [
          { q: 'Compro dos ___ para el teatro.', o: ['entradas', 'entrada', 'boletos'], a: 'entradas', h: 'I buy two tickets for the theater.' },
          { q: 'Ella ___ en una película chilena.', o: ['actúa', 'actuar', 'actúo'], a: 'actúa', h: 'She acts in a Chilean movie.' },
        ] },
      { id: 'u13l5', t: 'La poesía',
        intro: 'Neruda vivió aquí, mirando el mar. Palabras, poemas y libros para terminar.',
        tip: ['Leer y escribir', 'Two essential irregulars: leo (I read), escribo (I write). Practice them together.'],
        v: [['el poema', 'the poem'], ['el poeta', 'the poet'], ['la palabra', 'the word'], ['leer', 'to read'], ['escribir', 'to write'], ['el libro', 'the book']],
        s: [['El poeta escribe sobre el mar', 'The poet writes about the sea'], ['Leo un libro de poemas', 'I read a book of poems']],
        f: [
          { q: 'Me gusta ___ poesía.', o: ['leer', 'leo', 'lee'], a: 'leer', h: 'I like to read poetry.' },
          { q: 'Ella ___ una palabra nueva.', o: ['escribe', 'escribir', 'escribo'], a: 'escribe', h: 'She writes a new word.' },
        ] },
    ],
  },
  {
    id: 'u14', city: 'Córdoba', country: 'Argentina', char: 'tomas', color: '#2f6f8f',
    title: 'La escuela y el trabajo',
    lessons: [
      { id: 'u14l1', t: 'La escuela',
        intro: '¡Che, hola! Soy Tomás, de Córdoba, ciudad universitaria desde 1613. Hoy: la escuela.',
        tip: ['Pregunta / respuesta', 'Hacer una pregunta = to ask a question. Dar una respuesta = to give an answer.'],
        v: [['la clase', 'the class'], ['el maestro', 'the teacher'], ['la tarea', 'the homework'], ['el examen', 'the exam'], ['la pregunta', 'the question'], ['la respuesta', 'the answer']],
        s: [['El maestro hace una pregunta', 'The teacher asks a question'], ['Tengo mucha tarea hoy', 'I have a lot of homework today']],
        f: [
          { q: 'No sé la ___ correcta.', o: ['respuesta', 'pregunta', 'tarea'], a: 'respuesta', h: 'I do not know the correct answer.' },
          { q: 'El ___ de español es mañana.', o: ['examen', 'clase', 'maestro'], a: 'examen', h: 'The Spanish exam is tomorrow.' },
        ] },
      { id: 'u14l2', t: 'La universidad',
        intro: 'La universidad de Córdoba es la más antigua del país. Vocabulario de estudiante.',
        tip: ['Aprobar', '“Aprobar un examen” = to pass an exam. To fail (colloquially in Argentina): desaprobar.'],
        v: [['la universidad', 'the university'], ['la carrera', 'the degree'], ['la biblioteca', 'the library'], ['aprobar', 'to pass (exam)'], ['el curso', 'the course'], ['la nota', 'the grade']],
        s: [['Estudio mi carrera en Córdoba', 'I study my degree in Córdoba'], ['La biblioteca abre temprano', 'The library opens early']],
        f: [
          { q: 'Quiero ___ el examen final.', o: ['aprobar', 'apruebo', 'aprueba'], a: 'aprobar', h: 'I want to pass the final exam.' },
          { q: 'Saqué una buena ___.', o: ['nota', 'carrera', 'biblioteca'], a: 'nota', h: 'I got a good grade.' },
        ] },
      { id: 'u14l3', t: 'La oficina',
        intro: 'Del aula a la oficina: reuniones, correos y proyectos. El español del trabajo.',
        tip: ['El correo', '“El correo” = mail AND email. Also common: el mail, el correo electrónico.'],
        v: [['la oficina', 'the office'], ['la reunión', 'the meeting'], ['el jefe', 'the boss'], ['el correo', 'the email'], ['el proyecto', 'the project'], ['la empresa', 'the company']],
        s: [['La reunión es a las diez', 'The meeting is at ten'], ['El jefe lee mi correo', 'The boss reads my email']],
        f: [
          { q: 'Trabajo en una ___ grande.', o: ['empresa', 'empleo', 'reunión'], a: 'empresa', h: 'I work at a big company.' },
          { q: 'Te envío el ___ del proyecto.', o: ['correo', 'jefe', 'oficina'], a: 'correo', h: 'I am sending you the project email.' },
        ] },
      { id: 'u14l4', t: 'Buscar trabajo',
        intro: 'Tu primera entrevista en español no da miedo si practicás antes. ¡Dale!',
        tip: ['Buscar', 'No preposition after buscar: busco trabajo (not “busco por trabajo”).'],
        v: [['el trabajo', 'the job'], ['buscar', 'to look for'], ['la entrevista', 'the interview'], ['el sueldo', 'the salary'], ['contratar', 'to hire'], ['la experiencia', 'the experience']],
        s: [['Busco trabajo en una empresa', 'I am looking for a job at a company'], ['Tengo una entrevista el lunes', 'I have an interview on Monday']],
        f: [
          { q: '___ trabajo de profesor.', o: ['Busco', 'Busco por', 'Buscar'], a: 'Busco', h: 'I am looking for a job as a teacher.' },
          { q: 'La empresa va a ___ diez personas.', o: ['contratar', 'contrata', 'contrato'], a: 'contratar', h: 'The company is going to hire ten people.' },
        ] },
      { id: 'u14l5', t: 'Poder y deber',
        intro: '“Puedo” abre puertas; “debo” marca el camino. Dos verbos para negociar tu vida.',
        tip: ['Poder / deber / tener que', 'Puedo = I can. Debo = I must (duty). Tengo que = I have to (need). All + infinitive.'],
        v: [['poder', 'to be able to'], ['puedo', 'I can'], ['deber', 'must'], ['debo', 'I must'], ['tener que', 'to have to'], ['la responsabilidad', 'the responsibility']],
        s: [['Puedo trabajar desde casa', 'I can work from home'], ['Tengo que estudiar esta noche', 'I have to study tonight']],
        f: [
          { q: '___ terminar el proyecto hoy.', o: ['Debo', 'Deber', 'Debe'], a: 'Debo', h: 'I must finish the project today.' },
          { q: '¿___ ayudarme con la tarea?', o: ['Puedes', 'Puedo', 'Poder'], a: 'Puedes', h: 'Can you help me with the homework?' },
        ] },
    ],
  },
  {
    id: 'u15', city: 'La Paz', country: 'Bolivia', char: 'paula', color: '#c75b39',
    title: 'Fiestas y tradiciones',
    lessons: [
      { id: 'u15l1', t: 'Las fiestas',
        intro: '¡Hola! Soy Paula, de La Paz. Nuestro carnaval llena las calles de música y color.',
        tip: ['Celebrar', 'Celebrar una fiesta, celebrar un cumpleaños — also “festejar” in much of Latin America.'],
        v: [['la fiesta', 'the party'], ['el carnaval', 'the carnival'], ['el desfile', 'the parade'], ['el disfraz', 'the costume'], ['celebrar', 'to celebrate'], ['el regalo', 'the gift']],
        s: [['El desfile pasa por mi calle', 'The parade goes down my street'], ['Celebramos el carnaval en febrero', 'We celebrate carnival in February']],
        f: [
          { q: 'Llevo un ___ de cóndor.', o: ['disfraz', 'desfile', 'regalo'], a: 'disfraz', h: 'I wear a condor costume.' },
          { q: '___ mi cumpleaños con una fiesta.', o: ['Celebro', 'Celebra', 'Celebrar'], a: 'Celebro', h: 'I celebrate my birthday with a party.' },
        ] },
      { id: 'u15l2', t: 'Fin de año',
        intro: 'En diciembre, la familia se junta: cena, brindis y doce uvas a medianoche.',
        tip: ['Feliz Navidad', 'Learn the pair: ¡Feliz Navidad! (Merry Christmas) and ¡Feliz Año Nuevo! (Happy New Year).'],
        v: [['la Navidad', 'Christmas'], ['el Año Nuevo', 'New Year'], ['la cena', 'the dinner'], ['el brindis', 'the toast'], ['la medianoche', 'midnight'], ['desear', 'to wish']],
        s: [['La cena de Navidad es en familia', 'Christmas dinner is with family'], ['Te deseo un feliz Año Nuevo', 'I wish you a happy New Year']],
        f: [
          { q: 'Hacemos un ___ a medianoche.', o: ['brindis', 'cena', 'regalo'], a: 'brindis', h: 'We make a toast at midnight.' },
          { q: 'Te ___ mucha suerte.', o: ['deseo', 'desea', 'desear'], a: 'deseo', h: 'I wish you good luck.' },
        ] },
      { id: 'u15l3', t: 'Tradiciones andinas',
        intro: 'Aquí honramos a la Pachamama, la madre tierra, con ofrendas y tejidos de colores.',
        tip: ['Antiguo', '“Antiguo” before the noun = former; after = ancient: mi antigua casa vs. una casa antigua.'],
        v: [['la tradición', 'the tradition'], ['la Pachamama', 'Mother Earth'], ['la ofrenda', 'the offering'], ['el tejido', 'the weaving'], ['la costumbre', 'the custom'], ['antiguo', 'ancient']],
        s: [['La ofrenda es para la Pachamama', 'The offering is for Mother Earth'], ['Es una tradición muy antigua', 'It is a very ancient tradition']],
        f: [
          { q: 'Los ___ tienen muchos colores.', o: ['tejidos', 'tejido', 'tejidas'], a: 'tejidos', h: 'The weavings have many colors.' },
          { q: 'Es una ___ de mi familia.', o: ['costumbre', 'costumbres', 'ofrenda'], a: 'costumbre', h: 'It is a custom of my family.' },
        ] },
      { id: 'u15l4', t: 'Invitaciones',
        intro: '¿Te invito a la fiesta? Aprende a invitar, aceptar y brindar. ¡Salud!',
        tip: ['Venir vs. ir', 'Venir = come (toward the speaker); ir = go (away). ¿Vienes a mi fiesta? — ¡Voy!'],
        v: [['invitar', 'to invite'], ['la invitación', 'the invitation'], ['venir', 'to come'], ['traer', 'to bring'], ['el invitado', 'the guest'], ['¡salud!', 'cheers!']],
        s: [['Te invito a mi fiesta', 'I invite you to my party'], ['¿Puedes traer un postre?', 'Can you bring a dessert?']],
        f: [
          { q: '¿___ a la fiesta el sábado?', o: ['Vienes', 'Vas', 'Traes'], a: 'Vienes', h: 'Are you coming to the party on Saturday?' },
          { q: 'Los ___ llegan a las nueve.', o: ['invitados', 'invitado', 'invitaciones'], a: 'invitados', h: 'The guests arrive at nine.' },
        ] },
      { id: 'u15l5', t: 'El cumpleaños',
        intro: 'Torta, velas y una sorpresa. Así festejamos los cumpleaños en Bolivia.',
        tip: ['Cumplir años', '¿Cuántos años cumples? = What age are you turning? Cumplo veinte = I’m turning twenty.'],
        v: [['cumplir años', 'to turn (an age)'], ['la torta', 'the cake'], ['la vela', 'the candle'], ['soplar', 'to blow'], ['la sorpresa', 'the surprise'], ['festejar', 'to celebrate']],
        s: [['Mi hermana cumple quince años', 'My sister turns fifteen'], ['La torta tiene muchas velas', 'The cake has many candles']],
        f: [
          { q: 'Voy a ___ las velas.', o: ['soplar', 'soplo', 'sopla'], a: 'soplar', h: 'I am going to blow out the candles.' },
          { q: '¡Qué ___ tan linda!', o: ['sorpresa', 'sorpreso', 'soplar'], a: 'sorpresa', h: 'What a lovely surprise!' },
        ] },
    ],
  },
  {
    id: 'u16', city: 'Caracas', country: 'Venezuela', char: 'isabela', color: '#20635b',
    title: 'La tecnología',
    lessons: [
      { id: 'u16l1', t: 'El teléfono',
        intro: '¡Hola! Soy Isabela, de Caracas. Hoy el español también vive en las pantallas.',
        tip: ['Llamar', 'Llamar = to call: te llamo mañana. “Me llamo” (my name is) is the same verb, reflexive!'],
        v: [['el teléfono', 'the phone'], ['el mensaje', 'the message'], ['llamar', 'to call'], ['enviar', 'to send'], ['la aplicación', 'the app'], ['la pantalla', 'the screen']],
        s: [['Te envío un mensaje ahora', 'I am sending you a message now'], ['La pantalla de mi teléfono es grande', 'My phone screen is big']],
        f: [
          { q: 'Te ___ esta noche.', o: ['llamo', 'llama', 'llamar'], a: 'llamo', h: 'I will call you tonight.' },
          { q: 'Uso una ___ para aprender español.', o: ['aplicación', 'pantalla', 'mensaje'], a: 'aplicación', h: 'I use an app to learn Spanish.' },
        ] },
      { id: 'u16l2', t: 'El internet',
        intro: 'Contraseñas, descargas, videos… El vocabulario de la red, en español.',
        tip: ['Descargar / subir', 'Download = descargar (or bajar); upload = subir. Subo una foto = I upload a photo.'],
        v: [['el internet', 'the internet'], ['la red', 'the network'], ['la contraseña', 'the password'], ['descargar', 'to download'], ['subir', 'to upload'], ['el video', 'the video']],
        s: [['Necesito la contraseña del wifi', 'I need the wifi password'], ['Subo un video a la red', 'I upload a video to the network']],
        f: [
          { q: 'Voy a ___ la aplicación.', o: ['descargar', 'descargo', 'descarga'], a: 'descargar', h: 'I am going to download the app.' },
          { q: 'Olvidé mi ___.', o: ['contraseña', 'red', 'video'], a: 'contraseña', h: 'I forgot my password.' },
        ] },
      { id: 'u16l3', t: 'Las redes sociales',
        intro: 'Compartir fotos, seguir amigos, comentar. Así hablamos en las redes.',
        tip: ['Compartir', 'Compartir = to share (photos AND food!): comparto la foto / compartimos una arepa.'],
        v: [['la foto', 'the photo'], ['compartir', 'to share'], ['seguir', 'to follow'], ['publicar', 'to post'], ['el comentario', 'the comment'], ['el perfil', 'the profile']],
        s: [['Comparto una foto de Caracas', 'I share a photo of Caracas'], ['Ella publica un comentario', 'She posts a comment']],
        f: [
          { q: 'Te ___ en la red social.', o: ['sigo', 'sigue', 'seguir'], a: 'sigo', h: 'I follow you on the social network.' },
          { q: 'Mi ___ tiene una foto nueva.', o: ['perfil', 'comentario', 'foto'], a: 'perfil', h: 'My profile has a new photo.' },
        ] },
      { id: 'u16l4', t: 'La computadora',
        intro: 'En Venezuela decimos “computadora”; en España, “ordenador”. ¡Dos palabras, una máquina!',
        tip: ['Guardar', 'Guardar = to save (a file) and to keep: guardo el archivo / guardo un secreto.'],
        v: [['la computadora', 'the computer'], ['el teclado', 'the keyboard'], ['el ratón', 'the mouse'], ['el archivo', 'the file'], ['guardar', 'to save'], ['borrar', 'to delete']],
        s: [['Guardo el archivo importante', 'I save the important file'], ['El teclado no funciona', 'The keyboard does not work']],
        f: [
          { q: 'No quiero ___ ese archivo.', o: ['borrar', 'borro', 'borra'], a: 'borrar', h: 'I do not want to delete that file.' },
          { q: 'El ___ está al lado del teclado.', o: ['ratón', 'archivo', 'teclado'], a: 'ratón', h: 'The mouse is next to the keyboard.' },
        ] },
      { id: 'u16l5', t: 'El futuro digital',
        intro: 'Robots, inteligencia artificial… El futuro habla español también.',
        tip: ['El cambio', 'Cambiar (verb) → el cambio (noun): el mundo cambia; el cambio es rápido.'],
        v: [['el robot', 'the robot'], ['la inteligencia', 'the intelligence'], ['la máquina', 'the machine'], ['inventar', 'to invent'], ['el cambio', 'the change'], ['el avance', 'the advance']],
        s: [['La máquina aprende rápido', 'The machine learns fast'], ['Quiero inventar un robot', 'I want to invent a robot']],
        f: [
          { q: 'La ___ artificial es un gran avance.', o: ['inteligencia', 'máquina', 'cambio'], a: 'inteligencia', h: 'Artificial intelligence is a great advance.' },
          { q: 'Los ___ son cada vez más rápidos.', o: ['cambios', 'cambio', 'cambia'], a: 'cambios', h: 'The changes are faster and faster.' },
        ] },
    ],
  },
];
