// lessons-extra-b.js — units 17–26 for ¡Vamos!
export const EXTRA_UNITS_B = [
  {
    id: 'u17', city: 'Bilbao', country: 'España', char: 'iker', color: '#b0812c',
    title: 'El mercado y las comparaciones',
    lessons: [
      { id: 'u17l1', t: 'En el mercado',
        intro: '¡Kaixo! Soy Iker, de Bilbao. En el mercado de la Ribera se come el mejor pescado del norte.',
        tip: ['El pescado', 'In the water it’s “el pez”; on your plate it’s “el pescado”. Same fish, new name!'],
        v: [['el mercado', 'the market'], ['el pescado', 'the fish (food)'], ['la carne', 'the meat'], ['el queso', 'the cheese'], ['fresco', 'fresh'], ['el kilo', 'the kilo']],
        s: [['El pescado está muy fresco', 'The fish is very fresh'], ['Un kilo de queso, por favor', 'A kilo of cheese, please']],
        f: [
          { q: 'La ___ está en oferta hoy.', o: ['carne', 'carno', 'kilos'], a: 'carne', h: 'The meat is on sale today.' },
          { q: 'Las verduras están muy ___.', o: ['frescas', 'fresca', 'fresco'], a: 'frescas', h: 'The vegetables are very fresh.' },
        ] },
      { id: 'u17l2', t: 'Comparar',
        intro: '¿Más caro o más barato? Comparar es la clave para comprar bien.',
        tip: ['Más / menos que', 'más + adjective + que: el queso es más caro que el pan. Equal: tan caro como.'],
        v: [['más que', 'more than'], ['menos que', 'less than'], ['tan como', 'as… as'], ['mejor que', 'better than'], ['el mismo', 'the same'], ['diferente', 'different']],
        s: [['El pescado es más caro que la carne', 'Fish is more expensive than meat'], ['Este queso es mejor que ese', 'This cheese is better than that one']],
        f: [
          { q: 'El tren es ___ rápido que el bus.', o: ['más', 'muy', 'tan'], a: 'más', h: 'The train is faster than the bus.' },
          { q: 'Mi casa es tan grande ___ la tuya.', o: ['como', 'que', 'de'], a: 'como', h: 'My house is as big as yours.' },
        ] },
      { id: 'u17l3', t: 'Los pintxos',
        intro: 'En el País Vasco, los pintxos son arte en miniatura. ¡Vamos de bar en bar!',
        tip: ['Probar', 'Probar = to try/taste: ¿quieres probar? Also “to try on” clothes: me pruebo la chaqueta.'],
        v: [['el pintxo', 'the pintxo (Basque tapa)'], ['la tapa', 'the tapa'], ['probar', 'to try (food)'], ['la barra', 'the bar counter'], ['típico', 'typical'], ['rico', 'tasty']],
        s: [['Quiero probar ese pintxo', 'I want to try that pintxo'], ['La tortilla está muy rica', 'The tortilla is very tasty']],
        f: [
          { q: 'Los pintxos están en la ___.', o: ['barra', 'puerta', 'mesa'], a: 'barra', h: 'The pintxos are on the bar counter.' },
          { q: 'Es un plato muy ___ del norte.', o: ['típico', 'típica', 'típicos'], a: 'típico', h: 'It is a very typical northern dish.' },
        ] },
      { id: 'u17l4', t: 'Cantidades',
        intro: '¿Mucho, poco, nada? Las palabras de cantidad valen para todo.',
        tip: ['Nada / algo', 'Double negative is correct Spanish: no quiero nada = I don’t want anything.'],
        v: [['mucho', 'a lot'], ['poco', 'little (amount)'], ['algo', 'something'], ['nada', 'nothing'], ['todo', 'everything'], ['suficiente', 'enough']],
        s: [['No quiero nada, gracias', 'I do not want anything, thank you'], ['Hay suficiente comida para todos', 'There is enough food for everyone']],
        f: [
          { q: '¿Quieres ___ de comer?', o: ['algo', 'nada', 'alguien'], a: 'algo', h: 'Do you want something to eat?' },
          { q: 'No hay ___ en la nevera.', o: ['nada', 'algo', 'todo'], a: 'nada', h: 'There is nothing in the fridge.' },
        ] },
      { id: 'u17l5', t: 'El superlativo',
        intro: 'El mejor pintxo, el mercado más antiguo… Para exagerar con estilo, el superlativo.',
        tip: ['-ísimo', 'Add -ísimo for “very very”: bueno → buenísimo, grande → grandísimo. ¡Riquísimo!'],
        v: [['el más', 'the most'], ['el menos', 'the least'], ['grandísimo', 'very big'], ['buenísimo', 'very good'], ['el mejor', 'the best'], ['el peor', 'the worst']],
        s: [['Este es el mejor bar de Bilbao', 'This is the best bar in Bilbao'], ['La cena estuvo buenísima', 'The dinner was really good']],
        f: [
          { q: 'Es el mercado ___ antiguo de la ciudad.', o: ['más', 'muy', 'mucho'], a: 'más', h: 'It is the oldest market in the city.' },
          { q: 'El pintxo está ___.', o: ['riquísimo', 'riquísima', 'más rico que'], a: 'riquísimo', h: 'The pintxo is delicious (very tasty).' },
        ] },
    ],
  },
  {
    id: 'u18', city: 'Cartagena', country: 'Colombia', char: 'valeria', color: '#3f6f9e',
    title: 'La playa y el mar',
    lessons: [
      { id: 'u18l1', t: 'En la playa',
        intro: '¡Hola! Soy Valeria, de Cartagena de Indias. Sol, arena y mar Caribe: bienvenido.',
        tip: ['Tomar el sol', 'Spanish “takes” the sun: tomar el sol = to sunbathe. Also: tomar un café, tomar el bus.'],
        v: [['la arena', 'the sand'], ['la ola', 'the wave'], ['el mar', 'the sea'], ['el traje de baño', 'the swimsuit'], ['la sombrilla', 'the beach umbrella'], ['tomar el sol', 'to sunbathe']],
        s: [['La arena está muy caliente', 'The sand is very hot'], ['Me gusta tomar el sol', 'I like to sunbathe']],
        f: [
          { q: 'Las ___ son grandes hoy.', o: ['olas', 'ola', 'arenas'], a: 'olas', h: 'The waves are big today.' },
          { q: 'Necesito mi ___ de baño.', o: ['traje', 'sombrilla', 'arena'], a: 'traje', h: 'I need my swimsuit.' },
        ] },
      { id: 'u18l2', t: 'El Caribe',
        intro: 'Islas, barcos y brisa con olor a coco. Así es mi Caribe.',
        tip: ['En barco', 'Transport uses “en”: en barco, en avión, en bus. Exception: a pie (on foot).'],
        v: [['la isla', 'the island'], ['el barco', 'the boat'], ['la brisa', 'the breeze'], ['el coco', 'the coconut'], ['tropical', 'tropical'], ['el paraíso', 'the paradise']],
        s: [['Vamos a la isla en barco', 'We go to the island by boat'], ['La brisa del mar es rica', 'The sea breeze is lovely']],
        f: [
          { q: 'Viajamos ___ barco a las islas.', o: ['en', 'a', 'por'], a: 'en', h: 'We travel by boat to the islands.' },
          { q: 'El clima ___ es caliente.', o: ['tropical', 'tropicales', 'trópico'], a: 'tropical', h: 'The tropical climate is hot.' },
        ] },
      { id: 'u18l3', t: 'Deportes acuáticos',
        intro: '¿Bucear entre corales o surfear las olas? El mar es nuestro gimnasio.',
        tip: ['Saber + infinitive', '“Saber” + verb = to know how: sé nadar = I know how to swim. No “cómo” needed.'],
        v: [['bucear', 'to dive'], ['el surf', 'the surf'], ['la tabla', 'the board'], ['flotar', 'to float'], ['profundo', 'deep'], ['la piscina', 'the pool']],
        s: [['Sé nadar muy bien', 'I know how to swim very well'], ['El mar es muy profundo aquí', 'The sea is very deep here']],
        f: [
          { q: 'Quiero aprender a ___.', o: ['bucear', 'buceo', 'bucea'], a: 'bucear', h: 'I want to learn to dive.' },
          { q: 'La ___ de surf es nueva.', o: ['tabla', 'ola', 'piscina'], a: 'tabla', h: 'The surfboard is new.' },
        ] },
      { id: 'u18l4', t: 'La ciudad amurallada',
        intro: 'Cartagena guarda quinientos años de historia detrás de sus murallas.',
        tip: ['El siglo', 'Centuries use Roman numerals in Spanish: el siglo XVI (dieciséis) = the 16th century.'],
        v: [['la muralla', 'the city wall'], ['el castillo', 'the castle'], ['la historia', 'the history'], ['colonial', 'colonial'], ['la piedra', 'the stone'], ['el siglo', 'the century']],
        s: [['La muralla es del siglo XVII', 'The wall is from the 17th century'], ['El castillo está hecho de piedra', 'The castle is made of stone']],
        f: [
          { q: 'La ciudad ___ es hermosa.', o: ['colonial', 'coloniales', 'colonia'], a: 'colonial', h: 'The colonial city is beautiful.' },
          { q: 'Me encanta la ___ de Cartagena.', o: ['historia', 'histórico', 'piedra'], a: 'historia', h: 'I love the history of Cartagena.' },
        ] },
      { id: 'u18l5', t: 'Vacaciones perfectas',
        intro: 'Hotel con vista al mar, una hamaca y nada que hacer. ¿Reservamos?',
        tip: ['Relajarse', 'Reflexive: me relajo, te relajas, se relaja. Nos relajamos en la playa = we relax at the beach.'],
        v: [['el hotel', 'the hotel'], ['la reserva', 'the reservation'], ['la habitación', 'the room'], ['la vista', 'the view'], ['relajarse', 'to relax'], ['inolvidable', 'unforgettable']],
        s: [['La habitación tiene vista al mar', 'The room has a sea view'], ['Fue un viaje inolvidable', 'It was an unforgettable trip']],
        f: [
          { q: 'Tengo una ___ para dos noches.', o: ['reserva', 'vista', 'habitación'], a: 'reserva', h: 'I have a reservation for two nights.' },
          { q: 'Me ___ en la playa.', o: ['relajo', 'relaja', 'relajar'], a: 'relajo', h: 'I relax at the beach.' },
        ] },
    ],
  },
  {
    id: 'u19', city: 'Mendoza', country: 'Argentina', char: 'martin', color: '#7d5296',
    title: 'La cocina',
    lessons: [
      { id: 'u19l1', t: 'En la cocina',
        intro: '¡Hola! Soy Martín, de Mendoza, tierra de sol y buena mesa. Hoy cocinamos juntos.',
        tip: ['La receta', 'Remember: la receta = recipe AND prescription. In the kitchen, it’s always the tasty one.'],
        v: [['la receta', 'the recipe'], ['el ingrediente', 'the ingredient'], ['la sartén', 'the frying pan'], ['la olla', 'the pot'], ['el horno', 'the oven'], ['el fuego', 'the fire']],
        s: [['La receta tiene cinco ingredientes', 'The recipe has five ingredients'], ['El pan está en el horno', 'The bread is in the oven']],
        f: [
          { q: 'Cocino la sopa en la ___.', o: ['olla', 'sartén', 'horno'], a: 'olla', h: 'I cook the soup in the pot.' },
          { q: 'Baja el ___, por favor.', o: ['fuego', 'horno', 'ingrediente'], a: 'fuego', h: 'Lower the heat, please.' },
        ] },
      { id: 'u19l2', t: 'Preparar',
        intro: 'Cortar, mezclar, servir: los verbos que convierten ingredientes en cena.',
        tip: ['Primero, luego', 'Order your recipe: primero (first), luego (then), después (after), al final (finally).'],
        v: [['cortar', 'to cut'], ['mezclar', 'to mix'], ['freír', 'to fry'], ['hervir', 'to boil'], ['añadir', 'to add'], ['servir', 'to serve']],
        s: [['Primero corto la cebolla', 'First I cut the onion'], ['Luego añado la sal', 'Then I add the salt']],
        f: [
          { q: 'Hay que ___ el agua.', o: ['hervir', 'hiervo', 'hierve'], a: 'hervir', h: 'The water must be boiled.' },
          { q: '___ los ingredientes en la olla.', o: ['Mezclo', 'Mezclar', 'Mezclas'], a: 'Mezclo', h: 'I mix the ingredients in the pot.' },
        ] },
      { id: 'u19l3', t: 'El asado',
        intro: 'El domingo en Argentina huele a asado. Parrilla, chimichurri y amigos.',
        tip: ['El asado', 'More than barbecue: el asado is a social ritual. “Hacer un asado” = to host one.'],
        v: [['el asado', 'the barbecue'], ['la parrilla', 'the grill'], ['el chimichurri', 'the chimichurri'], ['la sal', 'the salt'], ['la pimienta', 'the pepper'], ['jugoso', 'juicy']],
        s: [['Hacemos un asado el domingo', 'We are having a barbecue on Sunday'], ['La carne está muy jugosa', 'The meat is very juicy']],
        f: [
          { q: 'La carne está en la ___.', o: ['parrilla', 'pimienta', 'sal'], a: 'parrilla', h: 'The meat is on the grill.' },
          { q: 'Le falta un poco de ___.', o: ['sal', 'salado', 'sala'], a: 'sal', h: 'It needs a bit of salt.' },
        ] },
      { id: 'u19l4', t: 'Sabores',
        intro: 'Dulce, salado, picante… Describe lo que comes como un crítico gastronómico.',
        tip: ['Picante', 'In Spain “picante”; in some countries also “picoso”. Spicy-hot ≠ caliente (temperature hot)!'],
        v: [['dulce', 'sweet'], ['salado', 'salty'], ['amargo', 'bitter'], ['ácido', 'sour'], ['picante', 'spicy'], ['el sabor', 'the flavor']],
        s: [['El postre está muy dulce', 'The dessert is very sweet'], ['No me gusta la comida picante', 'I do not like spicy food']],
        f: [
          { q: 'El limón es ___.', o: ['ácido', 'ácida', 'dulce'], a: 'ácido', h: 'The lemon is sour.' },
          { q: 'Este café tiene un ___ amargo.', o: ['sabor', 'sal', 'saber'], a: 'sabor', h: 'This coffee has a bitter flavor.' },
        ] },
      { id: 'u19l5', t: 'El imperativo',
        intro: 'Las recetas mandan: corta, mezcla, sirve. El imperativo, tu chef interior.',
        tip: ['Commands (tú)', 'For -ar verbs, the tú command = él/ella form: corta, mezcla, prueba. ¡Cocina!'],
        v: [['corta', 'cut! (command)'], ['mezcla', 'mix! (command)'], ['prueba', 'try! (command)'], ['sirve', 'serve! (command)'], ['no olvides', 'don’t forget'], ['la instrucción', 'the instruction']],
        s: [['Corta el pan y sirve la sopa', 'Cut the bread and serve the soup'], ['No olvides la pimienta', 'Don’t forget the pepper']],
        f: [
          { q: '___ la salsa antes de servir.', o: ['Prueba', 'Probar', 'Pruebo'], a: 'Prueba', h: 'Taste the sauce before serving.' },
          { q: 'Sigue las ___ de la receta.', o: ['instrucciones', 'instrucción', 'ingredientes'], a: 'instrucciones', h: 'Follow the recipe’s instructions.' },
        ] },
    ],
  },
  {
    id: 'u20', city: 'Salamanca', country: 'España', char: 'ines', color: '#bb4444',
    title: 'El imperfecto',
    lessons: [
      { id: 'u20l1', t: 'Cuando era niña',
        intro: '¡Hola! Soy Inés, de Salamanca, ciudad de estudiantes desde hace 800 años. Hablemos de recuerdos.',
        tip: ['The imperfect', 'For ongoing past states: era (I was), tenía (I had), vivía (I lived). No fixed endpoint.'],
        v: [['era', 'I was (used to be)'], ['tenía', 'I had (used to have)'], ['vivía', 'I lived (used to live)'], ['jugaba', 'I played (used to play)'], ['la infancia', 'the childhood'], ['el recuerdo', 'the memory']],
        s: [['Cuando era niña vivía aquí', 'When I was a girl I lived here'], ['Jugaba en la Plaza Mayor', 'I used to play in the Plaza Mayor']],
        f: [
          { q: 'Cuando ___ niño, jugaba mucho.', o: ['era', 'fui', 'soy'], a: 'era', h: 'When I was a boy, I played a lot.' },
          { q: '___ un perro pequeño.', o: ['Tenía', 'Tuve', 'Tengo'], a: 'Tenía', h: 'I used to have a small dog.' },
        ] },
      { id: 'u20l2', t: 'Antes y ahora',
        intro: 'Antes estudiaba latín; ahora estudias español. Todo cambia.',
        tip: ['Ya no', '“Ya no” = not anymore: ya no vivo allí. “Todavía” = still: todavía estudio.'],
        v: [['antes', 'before'], ['todavía', 'still'], ['ya no', 'no longer'], ['entonces', 'back then'], ['la época', 'the era'], ['el pasado', 'the past']],
        s: [['Antes vivía con mis padres', 'Before, I lived with my parents'], ['Ya no tengo miedo de hablar', 'I am no longer afraid of speaking']],
        f: [
          { q: '___ no como carne.', o: ['Ya', 'Todavía', 'Antes'], a: 'Ya', h: 'I no longer eat meat.' },
          { q: '¿___ estudias español?', o: ['Todavía', 'Ya no', 'Entonces'], a: 'Todavía', h: 'Are you still studying Spanish?' },
        ] },
      { id: 'u20l3', t: 'Costumbres pasadas',
        intro: 'Iba a clase, veía a mis amigos, hacía la tarea… Rutinas del pasado.',
        tip: ['Iba / hacía / veía', 'Only 3 irregular imperfects exist: ser (era), ir (iba), ver (veía). ¡Solo tres!'],
        v: [['iba', 'I used to go'], ['hacía', 'I used to do'], ['veía', 'I used to see'], ['cada', 'each'], ['mientras', 'while'], ['a menudo', 'often']],
        s: [['Iba a la biblioteca cada día', 'I used to go to the library each day'], ['Veía a mis abuelos a menudo', 'I used to see my grandparents often']],
        f: [
          { q: '___ al cine los viernes.', o: ['Iba', 'Fui', 'Voy'], a: 'Iba', h: 'I used to go to the movies on Fridays.' },
          { q: 'Estudiaba ___ escuchaba música.', o: ['mientras', 'cada', 'a menudo'], a: 'mientras', h: 'I studied while I listened to music.' },
        ] },
      { id: 'u20l4', t: 'Describir el pasado',
        intro: 'La plaza estaba llena, había música, todo parecía mágico. Pintar escenas con palabras.',
        tip: ['Había', '“Había” = there was/were (imperfect of hay). Same word for singular and plural.'],
        v: [['había', 'there was/were'], ['estaba', 'was (state)'], ['parecía', 'seemed'], ['hermoso', 'beautiful'], ['el lugar', 'the place'], ['la vida', 'the life']],
        s: [['Había mucha gente en la plaza', 'There were many people in the square'], ['El lugar parecía un sueño', 'The place seemed like a dream']],
        f: [
          { q: '___ flores en todas las ventanas.', o: ['Había', 'Habían', 'Hay'], a: 'Había', h: 'There were flowers in all the windows.' },
          { q: 'La ciudad ___ tranquila.', o: ['estaba', 'era', 'estuvo'], a: 'estaba', h: 'The city was calm (at that moment).' },
        ] },
      { id: 'u20l5', t: '¿Pretérito o imperfecto?',
        intro: 'La gran pregunta del español: ¿qué pasó (pretérito) o cómo era (imperfecto)?',
        tip: ['Scene vs. event', 'Imperfect paints the scene (llovía…); preterite is the event (…y de repente llegó).'],
        v: [['de repente', 'suddenly'], ['una vez', 'once'], ['normalmente', 'normally'], ['aquel día', 'that day'], ['el momento', 'the moment'], ['el cuento', 'the story']],
        s: [['De repente empezó a llover', 'Suddenly it started to rain'], ['Normalmente estudiaba en casa', 'I normally studied at home']],
        f: [
          { q: 'Dormía cuando, ___, sonó el teléfono.', o: ['de repente', 'normalmente', 'cada día'], a: 'de repente', h: 'I was sleeping when, suddenly, the phone rang.' },
          { q: '___ fui a Madrid en tren.', o: ['Una vez', 'Mientras', 'Todavía'], a: 'Una vez', h: 'Once I went to Madrid by train.' },
        ] },
    ],
  },
  {
    id: 'u21', city: 'Bariloche', country: 'Argentina', char: 'franco', color: '#2f6f8f',
    title: 'Viajes de aventura',
    lessons: [
      { id: 'u21l1', t: 'La montaña',
        intro: '¡Hola! Soy Franco, de Bariloche, entre lagos y montañas de la Patagonia. ¿Listo para la aventura?',
        tip: ['El lago', 'Watch the gender: el lago (lake) is masculine, but el agua takes “el” yet stays feminine.'],
        v: [['el lago', 'the lake'], ['el bosque', 'the forest'], ['la cabaña', 'the cabin'], ['el sendero', 'the trail'], ['escalar', 'to climb'], ['la aventura', 'the adventure']],
        s: [['La cabaña está cerca del lago', 'The cabin is near the lake'], ['El sendero cruza el bosque', 'The trail crosses the forest']],
        f: [
          { q: 'Quiero ___ esa montaña.', o: ['escalar', 'escalo', 'escala'], a: 'escalar', h: 'I want to climb that mountain.' },
          { q: 'El ___ es largo y hermoso.', o: ['sendero', 'senda', 'lago'], a: 'sendero', h: 'The trail is long and beautiful.' },
        ] },
      { id: 'u21l2', t: 'El equipaje',
        intro: 'Mochila, mapa y linterna: lo esencial antes de salir a la montaña.',
        tip: ['Hacer la maleta', '“Hacer la maleta” = to pack: hago la maleta esta noche. Also “empacar” in Latin America.'],
        v: [['la mochila', 'the backpack'], ['la maleta', 'the suitcase'], ['el mapa', 'the map'], ['la brújula', 'the compass'], ['la linterna', 'the flashlight'], ['empacar', 'to pack']],
        s: [['Llevo el mapa en la mochila', 'I carry the map in the backpack'], ['No olvides la linterna', 'Don’t forget the flashlight']],
        f: [
          { q: 'El ___ es masculino: el mapa.', o: ['mapa', 'mapo', 'mape'], a: 'mapa', h: '“Mapa” is masculine: el mapa.' },
          { q: 'Voy a ___ esta noche.', o: ['empacar', 'empaco', 'empaca'], a: 'empacar', h: 'I am going to pack tonight.' },
        ] },
      { id: 'u21l3', t: 'Esquiar',
        intro: 'En invierno, el cerro Catedral se llena de nieve. Guantes, bufanda ¡y a esquiar!',
        tip: ['Ropa de invierno', 'El abrigo (coat), los guantes (gloves), la bufanda (scarf) — always with hace frío!'],
        v: [['esquiar', 'to ski'], ['el esquí', 'the ski'], ['la pista', 'the slope'], ['el guante', 'the glove'], ['la bufanda', 'the scarf'], ['el abrigo', 'the coat']],
        s: [['Esquiamos en la pista todo el día', 'We ski on the slope all day'], ['Llevo guantes y bufanda', 'I wear gloves and a scarf']],
        f: [
          { q: 'Hace frío: ponte el ___.', o: ['abrigo', 'traje de baño', 'esquí'], a: 'abrigo', h: 'It’s cold: put on your coat.' },
          { q: 'Me gusta ___ en invierno.', o: ['esquiar', 'esquío', 'esquía'], a: 'esquiar', h: 'I like to ski in winter.' },
        ] },
      { id: 'u21l4', t: 'Acampar',
        intro: 'Una carpa junto al lago, una fogata y mil estrellas. Acampar en la Patagonia.',
        tip: ['Al aire libre', '“Al aire libre” = outdoors, in the open air: comer al aire libre, dormir al aire libre.'],
        v: [['la carpa', 'the tent'], ['la fogata', 'the campfire'], ['el saco de dormir', 'the sleeping bag'], ['al aire libre', 'outdoors'], ['el paisaje', 'the landscape'], ['explorar', 'to explore']],
        s: [['Dormimos en la carpa junto al lago', 'We sleep in the tent by the lake'], ['El paisaje es increíble', 'The landscape is incredible']],
        f: [
          { q: 'Hacemos una ___ por la noche.', o: ['fogata', 'carpa', 'linterna'], a: 'fogata', h: 'We make a campfire at night.' },
          { q: 'Me encanta comer ___ aire libre.', o: ['al', 'en', 'por'], a: 'al', h: 'I love eating outdoors.' },
        ] },
      { id: 'u21l5', t: 'Contar el viaje',
        intro: 'Volviste con historias. Ahora, cuéntalas en español: fue increíble…',
        tip: ['Fue + adjective', 'Sum up past experiences with “fue”: fue increíble, fue peligroso, fue inolvidable.'],
        v: [['el viaje', 'the trip'], ['increíble', 'incredible'], ['peligroso', 'dangerous'], ['seguro', 'safe'], ['recordar', 'to remember'], ['la anécdota', 'the anecdote']],
        s: [['El viaje fue increíble', 'The trip was incredible'], ['Siempre voy a recordar ese lago', 'I will always remember that lake']],
        f: [
          { q: 'El sendero no es ___; es seguro.', o: ['peligroso', 'peligrosa', 'peligro'], a: 'peligroso', h: 'The trail is not dangerous; it is safe.' },
          { q: 'Te cuento una ___ del viaje.', o: ['anécdota', 'anecdota', 'aventuras'], a: 'anécdota', h: 'I’ll tell you an anecdote from the trip.' },
        ] },
    ],
  },
  {
    id: 'u22', city: 'Guayaquil', country: 'Ecuador', char: 'daniela', color: '#c75b39',
    title: 'Negocios y dinero',
    lessons: [
      { id: 'u22l1', t: 'El dinero',
        intro: '¡Hola! Soy Daniela, de Guayaquil, el gran puerto del Pacífico. Hablemos de plata — digo, de dinero.',
        tip: ['La plata', 'In much of South America, “la plata” (silver) is slang for money. ¡No tengo plata!'],
        v: [['la moneda', 'the coin'], ['el billete', 'the banknote'], ['ahorrar', 'to save (money)'], ['gastar', 'to spend'], ['la cuenta bancaria', 'the bank account'], ['el cajero', 'the ATM']],
        s: [['Quiero ahorrar más dinero', 'I want to save more money'], ['El cajero está en la esquina', 'The ATM is on the corner']],
        f: [
          { q: 'No debes ___ tanto.', o: ['gastar', 'gasto', 'gasta'], a: 'gastar', h: 'You shouldn’t spend so much.' },
          { q: 'Saco dinero del ___.', o: ['cajero', 'billete', 'moneda'], a: 'cajero', h: 'I withdraw money from the ATM.' },
        ] },
      { id: 'u22l2', t: 'Comprar y vender',
        intro: 'Cliente, negocio, trato: el lenguaje del comercio, sin miedo.',
        tip: ['Vender / vendedor', 'Vender (to sell) → el vendedor (seller). Comprar (to buy) → el comprador.'],
        v: [['vender', 'to sell'], ['el cliente', 'the customer'], ['el negocio', 'the business'], ['la ganancia', 'the profit'], ['ofrecer', 'to offer'], ['el trato', 'the deal']],
        s: [['El cliente siempre tiene razón', 'The customer is always right'], ['Es un buen trato para todos', 'It is a good deal for everyone']],
        f: [
          { q: 'Mi tía ___ frutas en el mercado.', o: ['vende', 'vender', 'vendo'], a: 'vende', h: 'My aunt sells fruit at the market.' },
          { q: 'El ___ va muy bien este año.', o: ['negocio', 'cliente', 'trato'], a: 'negocio', h: 'The business is going very well this year.' },
        ] },
      { id: 'u22l3', t: 'El puerto',
        intro: 'De aquí salen barcos con cacao y camarón para el mundo entero.',
        tip: ['Exportar / importar', 'Ex- goes out, im- comes in — same as English: exportamos cacao, importamos autos.'],
        v: [['el puerto', 'the port'], ['exportar', 'to export'], ['importar', 'to import'], ['el producto', 'the product'], ['el cacao', 'the cacao'], ['el camarón', 'the shrimp']],
        s: [['Ecuador exporta cacao al mundo', 'Ecuador exports cacao to the world'], ['El puerto está lleno de barcos', 'The port is full of ships']],
        f: [
          { q: 'El país ___ muchos productos.', o: ['exporta', 'exportar', 'exporto'], a: 'exporta', h: 'The country exports many products.' },
          { q: 'El ___ ecuatoriano es famoso.', o: ['cacao', 'cacaos', 'caco'], a: 'cacao', h: 'Ecuadorian cacao is famous.' },
        ] },
      { id: 'u22l4', t: 'Emprender',
        intro: '¿Tienes una idea? Aquí las ideas se convierten en negocios. ¡Arriésgate!',
        tip: ['Tener éxito', 'Success is “had” in Spanish: tener éxito = to be successful. ¡Éxito! = good luck!'],
        v: [['el emprendedor', 'the entrepreneur'], ['la idea', 'the idea'], ['crear', 'to create'], ['crecer', 'to grow'], ['el éxito', 'the success'], ['arriesgar', 'to risk']],
        s: [['Quiero crear mi propio negocio', 'I want to create my own business'], ['La empresa crece cada año', 'The company grows every year']],
        f: [
          { q: 'Ella tiene mucho ___.', o: ['éxito', 'éxita', 'exitoso'], a: 'éxito', h: 'She is very successful.' },
          { q: 'Hay que ___ para ganar.', o: ['arriesgar', 'arriesgo', 'arriesga'], a: 'arriesgar', h: 'You have to take risks to win.' },
        ] },
      { id: 'u22l5', t: 'Números en acción',
        intro: 'Mitades, dobles y porcentajes: matemáticas de bolsillo en español.',
        tip: ['Por ciento', '50% = el cincuenta por ciento. “La mitad” = half; “el doble” = double.'],
        v: [['el porcentaje', 'the percentage'], ['la mitad', 'the half'], ['el doble', 'the double'], ['sumar', 'to add (math)'], ['restar', 'to subtract'], ['el total', 'the total']],
        s: [['La mitad de cien es cincuenta', 'Half of one hundred is fifty'], ['El total es doscientos dólares', 'The total is two hundred dollars']],
        f: [
          { q: 'Veinte es el ___ de diez.', o: ['doble', 'mitad', 'total'], a: 'doble', h: 'Twenty is double ten.' },
          { q: 'Hay que ___ los gastos.', o: ['sumar', 'sumo', 'suma'], a: 'sumar', h: 'The expenses must be added up.' },
        ] },
    ],
  },
  {
    id: 'u23', city: 'Valencia', country: 'España', char: 'aitana', color: '#20635b',
    title: 'Salir con amigos',
    lessons: [
      { id: 'u23l1', t: '¿Salimos?',
        intro: '¡Hola! Soy Aitana, de Valencia. Aquí la vida pasa en la calle. ¿Te apetece salir?',
        tip: ['Apetecer', 'Spain’s favorite verb: ¿te apetece un café? = do you feel like a coffee? Works like gustar.'],
        v: [['salir', 'to go out'], ['quedar', 'to meet up'], ['proponer', 'to suggest'], ['apetecer', 'to feel like'], ['genial', 'great'], ['¿te apetece?', 'do you feel like it?']],
        s: [['¿Te apetece salir esta noche?', 'Do you feel like going out tonight?'], ['Quedamos en la plaza a las ocho', 'We meet at the square at eight']],
        f: [
          { q: '¿Te ___ un helado?', o: ['apetece', 'apeteces', 'apetecer'], a: 'apetece', h: 'Do you feel like an ice cream?' },
          { q: '___ con mis amigos el viernes.', o: ['Quedo', 'Quedas', 'Quedar'], a: 'Quedo', h: 'I am meeting up with my friends on Friday.' },
        ] },
      { id: 'u23l2', t: 'En la terraza',
        intro: 'Una horchata fresquita, buena charla y ninguna prisa. Así es Valencia.',
        tip: ['El zumo', 'In Spain juice is “el zumo”; in Latin America, “el jugo”. Horchata is pure Valencia!'],
        v: [['el zumo', 'the juice (Spain)'], ['la horchata', 'the horchata'], ['charlar', 'to chat'], ['reír', 'to laugh'], ['el rato', 'the while'], ['disfrutar', 'to enjoy']],
        s: [['Charlamos un rato en la terraza', 'We chat for a while on the terrace'], ['Disfruto mucho con vosotros', 'I really enjoy being with you all']],
        f: [
          { q: 'Nos gusta ___ de todo.', o: ['charlar', 'charlo', 'charla'], a: 'charlar', h: 'We like to chat about everything.' },
          { q: 'Un ___ de naranja, por favor.', o: ['zumo', 'jugo', 'rato'], a: 'zumo', h: 'An orange juice, please. (in Spain)' },
        ] },
      { id: 'u23l3', t: 'Las Fallas',
        intro: 'En marzo, Valencia arde: figuras gigantes, pólvora y fiesta. ¡Las Fallas!',
        tip: ['Impresionante', 'A word for wonders: ¡es impresionante! Works for fireworks, food, and your Spanish progress.'],
        v: [['el festival', 'the festival'], ['la figura', 'the figure'], ['quemar', 'to burn'], ['el fuego artificial', 'the firework'], ['marzo', 'March'], ['impresionante', 'impressive']],
        s: [['Las figuras se queman en marzo', 'The figures are burned in March'], ['Los fuegos artificiales son impresionantes', 'The fireworks are impressive']],
        f: [
          { q: 'El festival es en ___.', o: ['marzo', 'Marzo', 'marzos'], a: 'marzo', h: 'The festival is in March. (months are lowercase)' },
          { q: 'Las ___ son gigantes.', o: ['figuras', 'figura', 'fuegos'], a: 'figuras', h: 'The figures are gigantic.' },
        ] },
      { id: 'u23l4', t: 'Hacer planes',
        intro: '¿Libre u ocupado? Confirma, avisa y no dejes a nadie esperando.',
        tip: ['¿Quedamos?', 'The one-word invitation: ¿quedamos? = shall we meet up? Answer: ¡venga! (ok, let’s!).'],
        v: [['¿quedamos?', 'shall we meet?'], ['el sábado', 'Saturday'], ['libre', 'free (available)'], ['ocupado', 'busy'], ['confirmar', 'to confirm'], ['avisar', 'to let know']],
        s: [['¿Estás libre el sábado?', 'Are you free on Saturday?'], ['Te aviso esta tarde', 'I will let you know this afternoon']],
        f: [
          { q: 'Estoy ___ toda la semana.', o: ['ocupada', 'ocupado', 'ocupadas'], a: 'ocupada', h: 'I (a woman) am busy all week.' },
          { q: '¿Me puedes ___ mañana?', o: ['confirmar', 'confirmo', 'confirma'], a: 'confirmar', h: 'Can you confirm for me tomorrow?' },
        ] },
      { id: 'u23l5', t: 'Después de salir',
        intro: '¿Lo pasaste bien? Cuenta cómo fue la noche y despídete como un valenciano.',
        tip: ['Pasarlo bien', 'Spain: lo pasamos genial = we had a great time. Latin America: la pasamos bien.'],
        v: [['pasarlo bien', 'to have a good time'], ['divertido', 'fun'], ['aburrido', 'boring'], ['volver', 'to return'], ['la próxima vez', 'the next time'], ['despedirse', 'to say goodbye']],
        s: [['Lo pasamos genial anoche', 'We had a great time last night'], ['La próxima vez vamos a la playa', 'Next time we go to the beach']],
        f: [
          { q: 'La fiesta fue muy ___.', o: ['divertida', 'divertido', 'divertidas'], a: 'divertida', h: 'The party was a lot of fun.' },
          { q: '¿A qué hora ___ a casa?', o: ['vuelves', 'vuelvo', 'volver'], a: 'vuelves', h: 'What time are you returning home?' },
        ] },
    ],
  },
  {
    id: 'u24', city: 'Arequipa', country: 'Perú', char: 'rosa', color: '#b0812c',
    title: 'Opiniones y consejos',
    lessons: [
      { id: 'u24l1', t: '¿Verdad o falso?',
        intro: '¡Hola! Soy Rosa, de Arequipa, la ciudad blanca. Aquí debatimos con café y vista al volcán.',
        tip: ['Cierto', '“Es cierto” = it’s true. “No es cierto” = it’s not true. “¿De verdad?” = really?'],
        v: [['la opinión', 'the opinion'], ['opinar', 'to give an opinion'], ['la verdad', 'the truth'], ['falso', 'false'], ['dudar', 'to doubt'], ['cierto', 'true']],
        s: [['En mi opinión, es cierto', 'In my opinion, it is true'], ['Dudo que sea verdad', 'I doubt it is true']],
        f: [
          { q: 'Eso no es ___; es falso.', o: ['cierto', 'cierta', 'ciertos'], a: 'cierto', h: 'That is not true; it is false.' },
          { q: '¿Qué ___ tú del tema?', o: ['opinas', 'opino', 'opinar'], a: 'opinas', h: 'What is your opinion on the subject?' },
        ] },
      { id: 'u24l2', t: 'El debate',
        intro: 'Argumentar no es pelear: es explicar tu punto de vista con calma.',
        tip: ['Discutir', 'Careful: “discutir” often means to argue/quarrel, not just discuss. “Debatir” is neutral.'],
        v: [['el debate', 'the debate'], ['el argumento', 'the argument (reasoning)'], ['convencer', 'to convince'], ['explicar', 'to explain'], ['discutir', 'to argue'], ['el punto de vista', 'the point of view']],
        s: [['Tu argumento me convence', 'Your argument convinces me'], ['Explica tu punto de vista', 'Explain your point of view']],
        f: [
          { q: '¿Me puedes ___ tu idea?', o: ['explicar', 'explico', 'explica'], a: 'explicar', h: 'Can you explain your idea to me?' },
          { q: 'No quiero ___ contigo.', o: ['discutir', 'discuto', 'discute'], a: 'discutir', h: 'I don’t want to argue with you.' },
        ] },
      { id: 'u24l3', t: 'Me interesa',
        intro: '¿Qué te interesa? ¿Qué te aburre? Elegir es opinar.',
        tip: ['Interesar', 'Like gustar: me interesa la historia, me interesan los idiomas. The thing does the verb!'],
        v: [['interesante', 'interesting'], ['aburrir', 'to bore'], ['importar', 'to matter'], ['preferir', 'to prefer'], ['elegir', 'to choose'], ['la opción', 'the option']],
        s: [['Me interesan los idiomas', 'Languages interest me'], ['Prefiero la primera opción', 'I prefer the first option']],
        f: [
          { q: 'Ese libro es muy ___.', o: ['interesante', 'interesado', 'interesantes'], a: 'interesante', h: 'That book is very interesting.' },
          { q: '___ el café al té.', o: ['Prefiero', 'Preferir', 'Prefiere'], a: 'Prefiero', h: 'I prefer coffee over tea.' },
        ] },
      { id: 'u24l4', t: 'Consejos',
        intro: '“Deberías descansar más.” Dar consejos: el deporte nacional de las abuelas.',
        tip: ['Deberías', '“Deberías” + infinitive = you should: deberías practicar cada día. Soft and friendly.'],
        v: [['el consejo', 'the advice'], ['aconsejar', 'to advise'], ['recomendar', 'to recommend'], ['deberías', 'you should'], ['evitar', 'to avoid'], ['intentar', 'to try (attempt)']],
        s: [['Deberías visitar Arequipa', 'You should visit Arequipa'], ['Te recomiendo este restaurante', 'I recommend this restaurant to you']],
        f: [
          { q: '___ dormir ocho horas.', o: ['Deberías', 'Debes que', 'Deber'], a: 'Deberías', h: 'You should sleep eight hours.' },
          { q: 'Intenta ___ el azúcar.', o: ['evitar', 'evito', 'evita'], a: 'evitar', h: 'Try to avoid sugar.' },
        ] },
      { id: 'u24l5', t: 'Expresarse',
        intro: 'Sin embargo, además, por eso… Las palabras que unen tus ideas.',
        tip: ['Connectors', 'Level up: sin embargo (however), además (besides), por eso (that’s why). Use one per sentence!'],
        v: [['expresar', 'to express'], ['la manera', 'the way (manner)'], ['en mi opinión', 'in my opinion'], ['sin embargo', 'however'], ['además', 'besides'], ['por eso', 'that is why']],
        s: [['Me gusta; sin embargo, es caro', 'I like it; however, it is expensive'], ['Por eso estudio español', 'That is why I study Spanish']],
        f: [
          { q: 'Es tarde; ___, voy a la fiesta.', o: ['sin embargo', 'además', 'por eso'], a: 'sin embargo', h: 'It’s late; however, I’m going to the party.' },
          { q: 'Llueve; ___ llevo paraguas.', o: ['por eso', 'sin embargo', 'en mi opinión'], a: 'por eso', h: 'It’s raining; that’s why I carry an umbrella.' },
        ] },
    ],
  },
  {
    id: 'u25', city: 'Punta del Este', country: 'Uruguay', char: 'agustina', color: '#7d5296',
    title: 'El futuro simple',
    lessons: [
      { id: 'u25l1', t: 'Hablaré',
        intro: '¡Hola! Soy Agustina, de Punta del Este. Frente al mar se piensa bien en el futuro.',
        tip: ['Future endings', 'Add to the WHOLE infinitive: hablar-é, comer-ás, vivir-á. Same endings for all verbs!'],
        v: [['hablaré', 'I will speak'], ['comeré', 'I will eat'], ['viviré', 'I will live'], ['iré', 'I will go'], ['seré', 'I will be'], ['el futuro', 'the future']],
        s: [['Hablaré español perfectamente', 'I will speak Spanish perfectly'], ['Iré a Uruguay el año próximo', 'I will go to Uruguay next year']],
        f: [
          { q: 'Mañana ___ a la playa.', o: ['iré', 'iría', 'iba'], a: 'iré', h: 'Tomorrow I will go to the beach.' },
          { q: 'Algún día ___ famosa.', o: ['seré', 'soy', 'era'], a: 'seré', h: 'Someday I will be famous.' },
        ] },
      { id: 'u25l2', t: 'Predicciones',
        intro: '¿Lloverá mañana? ¿Habrá olas? El futuro también sirve para adivinar.',
        tip: ['Habrá', '“Habrá” = there will be. Hay → había → habrá: one little verb through time.'],
        v: [['será', 'it will be'], ['habrá', 'there will be'], ['lloverá', 'it will rain'], ['probablemente', 'probably'], ['algún día', 'someday'], ['predecir', 'to predict']],
        s: [['Mañana habrá sol todo el día', 'Tomorrow there will be sun all day'], ['Probablemente lloverá el jueves', 'It will probably rain on Thursday']],
        f: [
          { q: '___ mucha gente en la playa.', o: ['Habrá', 'Habrán', 'Hay'], a: 'Habrá', h: 'There will be many people at the beach.' },
          { q: 'El verano ___ muy caliente.', o: ['será', 'estará', 'es'], a: 'será', h: 'The summer will be very hot.' },
        ] },
      { id: 'u25l3', t: 'Promesas',
        intro: 'Prometer es fácil; cumplir, no tanto. Nunca jamás olvides esta lección.',
        tip: ['Nunca / jamás', 'Both mean never. Together = emphatic: nunca jamás = never ever.'],
        v: [['prometer', 'to promise'], ['la promesa', 'the promise'], ['nunca', 'never'], ['jamás', 'never (emphatic)'], ['cumplir', 'to fulfill'], ['jurar', 'to swear']],
        s: [['Prometo practicar cada día', 'I promise to practice every day'], ['Nunca olvidaré este verano', 'I will never forget this summer']],
        f: [
          { q: 'Siempre cumplo mis ___.', o: ['promesas', 'promesa', 'promete'], a: 'promesas', h: 'I always keep my promises.' },
          { q: '___ diré tu secreto.', o: ['Jamás', 'Siempre', 'Ya'], a: 'Jamás', h: 'I will never tell your secret.' },
        ] },
      { id: 'u25l4', t: 'Sueños y metas',
        intro: '¿Cuál es tu meta? Dilo en voz alta, en español, y estará más cerca.',
        tip: ['Lograr / conseguir', 'Both mean to achieve/get: lograré mi meta = conseguiré mi meta. Pick your favorite.'],
        v: [['el sueño', 'the dream'], ['la meta', 'the goal'], ['lograr', 'to achieve'], ['conseguir', 'to get (achieve)'], ['esforzarse', 'to make an effort'], ['el objetivo', 'the objective']],
        s: [['Mi meta es hablar español', 'My goal is to speak Spanish'], ['Lograré todos mis sueños', 'I will achieve all my dreams']],
        f: [
          { q: 'Voy a ___ mi objetivo.', o: ['lograr', 'logro', 'logra'], a: 'lograr', h: 'I am going to achieve my objective.' },
          { q: 'Hay que ___ para mejorar.', o: ['esforzarse', 'esfuerzo', 'esforzar'], a: 'esforzarse', h: 'One must make an effort to improve.' },
        ] },
      { id: 'u25l5', t: 'El año que viene',
        intro: 'Dentro de un año, ¿dónde estarás? Imagina tu futuro en español.',
        tip: ['Dentro de', '“Dentro de” + time = in/within: dentro de un año = a year from now.'],
        v: [['el año que viene', 'next year'], ['dentro de', 'within'], ['la década', 'the decade'], ['mejorar', 'to improve'], ['imaginar', 'to imagine'], ['el destino', 'the destiny']],
        s: [['El año que viene viviré aquí', 'Next year I will live here'], ['Mi español mejorará mucho', 'My Spanish will improve a lot']],
        f: [
          { q: 'Vuelvo ___ de dos horas.', o: ['dentro', 'fuera', 'después de que'], a: 'dentro', h: 'I’ll be back in two hours.' },
          { q: '___ un mundo mejor.', o: ['Imagina', 'Imaginar', 'Imagino que tú'], a: 'Imagina', h: 'Imagine a better world.' },
        ] },
    ],
  },
  {
    id: 'u26', city: 'Madrid', country: 'España', char: 'lucia', color: '#c75b39',
    title: 'El gran repaso',
    lessons: [
      { id: 'u26l1', t: 'De vuelta en Madrid',
        intro: '¡Hola otra vez! Soy Lucía. Empezaste aquí con “hola” — mira todo lo que sabes ahora.',
        tip: ['Regresar / volver', 'Both mean to return: regreso a Madrid = vuelvo a Madrid. “Volver a” + verb = to do again!'],
        v: [['regresar', 'to return'], ['la capital', 'the capital'], ['el reencuentro', 'the reunion'], ['contar', 'to tell'], ['el progreso', 'the progress'], ['orgulloso', 'proud']],
        s: [['Regreso a Madrid con amigos nuevos', 'I return to Madrid with new friends'], ['Estoy orgullosa de tu progreso', 'I am proud of your progress']],
        f: [
          { q: 'Madrid es la ___ de España.', o: ['capital', 'capitala', 'ciudad grande'], a: 'capital', h: 'Madrid is the capital of Spain.' },
          { q: 'Cuéntame, ¿qué ___ en tu viaje?', o: ['aprendiste', 'aprendes', 'aprenderás'], a: 'aprendiste', h: 'Tell me, what did you learn on your trip?' },
        ] },
      { id: 'u26l2', t: 'Conversaciones reales',
        intro: 'Ya no traduces palabra por palabra: ahora suenas natural. Pulamos tu acento.',
        tip: ['Sonar natural', 'Fluency isn’t speed — it’s rhythm. Short sentences, common words, and confidence.'],
        v: [['la conversación', 'the conversation'], ['fluido', 'fluent'], ['la frase', 'the sentence'], ['el acento', 'the accent'], ['sonar', 'to sound'], ['natural', 'natural']],
        s: [['Tu español suena muy natural', 'Your Spanish sounds very natural'], ['Tenemos una conversación fluida', 'We have a fluent conversation']],
        f: [
          { q: 'Tu acento ___ muy bien.', o: ['suena', 'sonar', 'sueno'], a: 'suena', h: 'Your accent sounds very good.' },
          { q: 'Hablas de manera muy ___.', o: ['fluida', 'fluido', 'fluidos'], a: 'fluida', h: 'You speak very fluently.' },
        ] },
      { id: 'u26l3', t: 'Todos los tiempos',
        intro: 'Presente, pasado, futuro: hoy los mezclamos todos. Reglas y excepciones.',
        tip: ['One rule to rule', 'Every tense you know: hablo (now), hablé (done), hablaba (used to), voy a hablar / hablaré (will).'],
        v: [['el presente', 'the present'], ['el pretérito', 'the preterite'], ['el verbo', 'the verb'], ['conjugar', 'to conjugate'], ['la regla', 'the rule'], ['la excepción', 'the exception']],
        s: [['Ayer estudié y mañana practicaré', 'Yesterday I studied and tomorrow I will practice'], ['Cada regla tiene una excepción', 'Every rule has an exception']],
        f: [
          { q: 'Sé ___ los verbos en -ar.', o: ['conjugar', 'conjugo', 'conjuga'], a: 'conjugar', h: 'I know how to conjugate -ar verbs.' },
          { q: 'Ayer ___ paella; mañana comeré tortilla.', o: ['comí', 'como', 'comeré'], a: 'comí', h: 'Yesterday I ate paella; tomorrow I will eat tortilla.' },
        ] },
      { id: 'u26l4', t: 'El mundo hispano',
        intro: 'Veintiún países, un idioma, mil acentos. El español te une a 500 millones de personas.',
        tip: ['One language, many voices', 'Vos (Argentina), vosotros (Spain), ustedes (everywhere) — all correct, all Spanish.'],
        v: [['hispanohablante', 'Spanish speaker'], ['el continente', 'the continent'], ['la cultura', 'the culture'], ['la variedad', 'the variety'], ['la frontera', 'the border'], ['unir', 'to unite']],
        s: [['El español une dos continentes', 'Spanish unites two continents'], ['Cada país tiene su variedad', 'Each country has its variety']],
        f: [
          { q: 'Hay 500 millones de ___.', o: ['hispanohablantes', 'hispanohablante', 'hablar'], a: 'hispanohablantes', h: 'There are 500 million Spanish speakers.' },
          { q: 'El idioma no tiene ___.', o: ['fronteras', 'frontera', 'fronterizo'], a: 'fronteras', h: 'The language has no borders.' },
        ] },
      { id: 'u26l5', t: 'Tu graduación',
        intro: 'Ciento treinta lecciones, doce ciudades, dos continentes. Hoy te gradúas. ¡Enhorabuena!',
        tip: ['¡Enhorabuena!', 'Spain says ¡enhorabuena!; Latin America prefers ¡felicidades! You’ve earned both.'],
        v: [['graduarse', 'to graduate'], ['el diploma', 'the diploma'], ['el logro', 'the achievement'], ['el esfuerzo', 'the effort'], ['el orgullo', 'the pride'], ['¡enhorabuena!', 'congratulations! (Spain)']],
        s: [['Hoy me gradúo del curso', 'Today I graduate from the course'], ['Tu esfuerzo es un gran logro', 'Your effort is a great achievement']],
        f: [
          { q: 'Recibo mi ___ hoy.', o: ['diploma', 'diplomo', 'graduado'], a: 'diploma', h: 'I receive my diploma today.' },
          { q: '¡___ por tu español!', o: ['Enhorabuena', 'Enhorabuenas', 'Buenhora'], a: 'Enhorabuena', h: 'Congratulations on your Spanish!' },
        ] },
    ],
  },
];
